### ISSUE TITLE
Adding K8s support for Sky

### ISSUE THREAD

**Issue by gilv** [skypilot-org/skypilot#1008]
Enable Sky to deploy workloads over K8s backend. 
Support also various K8s deployments: local on-premise, cloud offerings that offer K8s services or APIs

**Comment by Jeffwan** [comment]
I notice kubernetes support is part of v0.3 release. I am one maintainer of kuberay and I would like to help and evaluate  whether that could be an option for skypilot k8s backend.

**Comment by Michaelvll** [comment]
This is in progress. We should keep this open. cc @romilbhardwaj

**Comment by romilbhardwaj** [comment]
Closed with #2096.
