### ISSUE TITLE
Adding IBM Gen2 support for Sky

### ISSUE THREAD

**Issue by gilv** [skypilot-org/skypilot#1009]
Gen2 are very fast provisioning VMs in the IBM Cloud, where it possible to provision 100 of VMs with GPUs within a minute or so. Billing is done on the seconds level, so start VM, deploy workload, shut down VM will be very fast and cost effective.
We have similar PR as WIP to Ray to enable it to be deployed over Gen2 [20969](https://github.com/ray-project/ray/pull/20969)
It's a bit old blog [Gen2](https://www.ibm.com/cloud/blog/announcements/next-gen-virtual-servers-vpc) but still gives a bit details on those kind of VMs

**Comment by concretevitamin** [comment]
Merged as part of IBM support.
