### ISSUE TITLE
UX: handle GCP APIs "not been used" messages gracefully

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#1019]
```
Error: Error reading Project Service foo/cloudbuild.googleapis.com: googleapi: Error 403: Cloud Resource Manager API has not been used in project 123456789 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=123456789 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry....
```
We saw the above error embedded in HttpError details for two first-time TPU VM users.  The string is quite long and the users had trouble digging through it.

Can we look into 
1. Pre-checking this requirement on our end, rather than let it go into failover.  (We already pre-checked gcloud SDK version for TPU VMs, as the last screenshot shows.)

2. Or, on seeing this error, print a nicer + easier-to-read message so users don't have to dig through this long HttpError.  Also, block the entire cloud without going into region failover.

3. Automatically running 
```
# Requires `roles/serviceusage.serviceUsageAdmin` on $SEED_PROJECT
gcloud services enable cloudresourcemanager.googleapis.com
  --project "$SEED_PROJECT"
```
as suggested [here](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/docs/TROUBLESHOOTING.md#missing-api-cloudresourcemanagergoogleapiscom).

**Comment by concretevitamin** [comment]
Daniel on a new project ID that's never been used before observed 3 "APIs not been used errors". One of which is:
```
```

**Comment by concretevitamin** [comment]
Daniel on a new project ID that's never been used before observed 3 "APIs not been used errors". 
- Compute Engine API
- Cloud Resource Manager API
- IAM API

One such message
```
W 08-12 15:35:45 common_utils.py:178] Caught <HttpError 403 when requesting https://compute.googleapis.com/compute/v1/projects/ml?alt=json returned "Compute Engine API has not been used in project 1234 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=1234 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.". Details: "[{'message': 'Compute Engine API has not been used in project 1234 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=1234 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.', 'domain': 'usageLimits', 'reason': 'accessNotConfigured', 'extendedHelp': 'https://console.developers.google.com'}]">. Retrying.
```

Actions
- [ ] As part of `sky check` - require running these lines (best to check if these APIs are enabled; or, at least we should print the 3 URLs)
- [ ] Parse http errors of this form, and surface URLs in an easier-to-read way 

These errors seem to have been encountered by several first-time GCP users. So I think we should bump the priority of this.

**Comment by infwinston** [comment]
This is important. Will work on this during bug squash tomorrow.

**Comment by concretevitamin** [comment]
Repro:
* Create a new project on GCP console
* Run `gcloud init` to choose the new project
* Run `gcloud auth application-default login`
* `sky cpunode --cloud gcp` would trigger these errors
