### ISSUE TITLE
Failed to ssh into a cluster launched by SkyPilot

### ISSUE THREAD

**Issue by infwinston** [skypilot-org/skypilot#1022]
We met the issue during the onboarding session with Wilson. This is due to the ssh config added by SkyPilot was overwritten by a global rule set by user by `Host *`. For example, our username will be replaced to `weichiang` from `gcpuser`.
```
Host *
  User weichiang

Host mycluster
  User gcpuser
...
```
To avoid such silent failure, possible solutions include:
1. raise error if we find such `Host *` rule in `~/.ssh/config`
2. introduce a new command `sky ssh` to avoid dependency on ssh config

**Comment by Michaelvll** [comment]
Another problem is found: when the `~/.ssh/` has the wrong permission, sky launch will stuck in `launching` for a very long time. We may need to fail early for that as well.
