### ISSUE TITLE
[Spot] Exposing a way to specify the max number of simultaneous spot jobs

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#1078]
Currently, we will launch 16 spot jobs in parallel and let the remaining jobs pending in a queue. This becomes a problem when the quota of the user does not satisfy the requirement of 16 spot clusters, as the launching of the jobs will fail due to resource unavailability. There are several things we can do to solve the problem (ordered by the simplicity of implementation and can be done in the same order)
- [ ] Let the user specify the max number of simultaneous spot jobs, so that the user can make sure the jobs are within their quota.
- [ ] Whenever we met quota exceeds, we place the spot job back to the job queue and wait for a while.

PS, the problem comes from setting up the spot job for salk, and our current workaround is to let them modify the following line directly to match their quota.
https://github.com/skypilot-org/skypilot/blob/44b923572a143a6dbc7ea62618feff95af21fbcb/sky/backends/backend_utils.py#L102

**Comment by concretevitamin** [comment]
Seems like this can affect non-spot jobs as well?

 The 2nd option, placing the job back to the queue with some backoff, seems better because the user doesn't need to know/check their quota of a particular instance type.  We can also change the default recovery to "wait and retry forever".
