### ISSUE TITLE
[Spot] Ray dashboard hangs making `ray job` commands not responding

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#1088]
Although not much CPU and memory are used, the `sky-spot-controller` can still fail to take new `ray job` commands, due to a lot of `ray job` commands running and the jobs are stuck in INIT mode. That causes the `sky spot launch` to hang after setup is completed.

One possible reason for that is our skylet will try to update the status of the INIT jobs by querying ray with `ray job`, causing a lot of connection to the ray dashboard, `http://127.0.0.1:8265`.

It happens in the situation `In progress jobs: 14 PENDING, 4 RUNNING, 4 STARTING`, but I failed to reproduce the problem when `In progress jobs: 29 PENDING, 8 RUNNING` with the following code:
import subprocess

```
for i in range(200):
    for j in range(5):
        # retry
        try:
            subprocess.run(f'sky spot launch -y -d -n test-{i} job.yaml', shell=True, check=True)
        except subprocess.CalledProcessError:
            continue
        break
```

```
# job.yaml
resources:
  cloud: gcp
  region: us-west1

run: echo hi; sleep 800; echo bye

```

**Comment by concretevitamin** [comment]
We can try to directly query against redis. It's a hack as it assumes ray job internals (redis key formats, etc.).

Is this also related to the check interval being too short here?:

https://github.com/skypilot-org/skypilot/blob/78ce9adb5354b6a14d0ebe734747ead5839d0ad7/sky/skylet/subprocess_daemon.py#L55

**Comment by Michaelvll** [comment]
> We can try to directly query against redis. It's a hack as it assumes ray job internals (redis key formats, etc.).

Good point! I am thinking that we can use `ray job list` offered in `ray==1.13` to query all the job status in one call, instead of our previous parallel job status fetching. 

> Is this also related to the check interval being too short here?

The line seems only to be used in the on-prem situation, i.e. the ray job related commands won't be called in the spot case.

**Comment by Michaelvll** [comment]
I asked them to remove the `JobUpdateEvent` from the skylet and restart the controller, and it seems that it is now able to run for about 2 hours and is still running (Previously, it would hang after half an hour). 
https://github.com/skypilot-org/skypilot/blob/619655258e7b1479e5144d5a364257ac5dba5e4d/sky/skylet/skylet.py#L12

**Comment by Michaelvll** [comment]
It seems that the ray's job_manager is buggy. Even though they call `ray.actor.exit_actor()` for the `JobSupervisor.run` and actor will not be able to find using `ray.get_actor` with ValueError. The actor already got by `ray.get_actor` will still be available for calling remote functions, i.e. `await job_supervisor.ping.remote()` will always be available and the `_monitor_job` function will be in an infinite loop.
https://github.com/ray-project/ray/blob/e4ce38d001dbbe09cd21c497fedd03d692b2be3e/dashboard/modules/job/job_manager.py#L332-L335

**Comment by Michaelvll** [comment]
Just found another easier way to reproduce the error:
```
for i in {1..1000}; do ray job submit --job-id $i-gcpuser-2 --address http://127.0.0.1:8265 --no-wait 'echo hi; sleep 800; echo bye'; sleep 1; done
```

After several hundreds of jobs, `ray job list --address=http://127.0.0.1:8265` will fail to connect to the dashboard.
