### ISSUE TITLE
Error message when `sudo -H pip3 install skypilot`

### ISSUE THREAD

**Issue by WoosukKwon** [skypilot-org/skypilot#1091]
I found this red error message
```bash
ERROR: awscli 1.25.53 has requirement rsa<4.8,>=3.1.2, but you'll have rsa 4.9 which is incompatible.
```
when I ran `sudo -H pip3 install skypilot` to set up a local cluster on an AWS VM. Maybe this is related to the recent PR #1055. While this did not cause any problem to me, it'd be nice to remove those errors for better UX. (I can't see this error when I `pip install skypilot` in my local conda env. I guess this is only a problem in on-prem deployment).

**Comment by michaelzhiluo** [comment]
@WoosukKwon Can't seem to replicate on most recent master (i.e. `sky launch --cloud aws` , ssh into node and run `sudo -H pip3 install skypilot`)

Also, this issue will not be relevant anymore after #1114 is merged, so I'll close it for now.
