### ISSUE TITLE
[Spot] More simultaneous spot jobs

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#1094]
A pilot user requested for more simultaneous spot jobs than the current 16 jobs due to our settings for each job taking 0.5 CPU on spot controller. We can start testing launching more jobs on the spot controller and stress test it.

**Comment by romilbhardwaj** [comment]
Related to #1078?

**Comment by Michaelvll** [comment]
We can have similar logic for the spot controller as  serve controller to automatically scale up when the number of jobs exceeds the threshold.

**Comment by Michaelvll** [comment]
This has been fixed by #3191
