### ISSUE TITLE
[Permission] running `sky launch` on a machine without `~/.ssh/config` will have the file in wrong permission

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#1123]
We should set the `~/.ssh/config` permission with `chmod 644 ~/.ssh/config` if it is newly created by sky. Otherwise, the `ray up` will fail, due to failing to ssh into the cluster for the permission issue.

**Comment by ewzeng** [comment]
Hi @Michaelvll 
I'm new to SkyPilot, and I think this is a good issue to get me started. Could you assign it to me?
Thanks!

**Comment by Michaelvll** [comment]
Hey @ewzeng, thanks for taking this! Just assigned this to you. : )
