### ISSUE TITLE
Switch TPU implementation to ray up yaml

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#114]
According to [here](https://docs.ray.io/en/latest/cluster/config.html?highlight=tpu#tpu-configuration), `ray up` supports the tpu configuration in the `cluster_yaml`. Should we consider switching our implementation to the yaml file for clarity and simplicity? Also, with the `cluster_yaml` we can make the TPU preemptible, as mentioned in #113. @infwinston

**Comment by infwinston** [comment]
Closing this issue as we already use `ray up` to launch TPU VMs. For TPU nodes, `ray up` still doesn't support it.
