### ISSUE TITLE
[On-prem] machine with no credentials errors out in first `sky launch`

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#1140]
Repro:
```
docker run -it --rm python /bin/bash
# inside:
pip install skypilot
sky launch '' -y
```
This will default to `Local` cloud being chosen, then some file not found error from `~/.sky/local/<name>.yml`. Found when debugging #1138.

**Comment by Michaelvll** [comment]
This problem is fixed already.
