### ISSUE TITLE
[Mount] `sky start` will not mount the file_mounts

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#1157]
From our pilot user @lhqing: when he stop the VM for the jupyter lab task and start the VM again with `sky start`, the file_mounts with MOUNT mode will disappear in the target dir. Even though he could run the `sky launch` again, he has to remove the setup commands to avoid overhead for setting up the environment again.

We can have three design choices here:
1. mount the files after `sky start` automatically.
2. Add a `--no-setup` option for `sky launch`.
3. Automatically detect whether the setup was completed before.

I feel like the option 2 is the easiest way. Also, I personally experienced some cases that I want to update the file_mounts, but don't want to run the setup again.

**Comment by concretevitamin** [comment]
+1 to option 2. This issue has been raised by another user before, IIRC.

**Comment by concretevitamin** [comment]
Fixed by #1184.
