### ISSUE TITLE
Invalid cluster name is generated if username has uppercase or invalid characters 

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#1161]
If the user does not specify a cluster name, we randomly generate a name appended with the username appended to it. E.g.,
```
$ sky launch example.yaml
...
Launching a new cluster 'sky-7ccb-romilb'. Proceed? [Y/n]:
```

If the username has underscores or capital letters then it generates an invalid cluster name which fails our regex check:

https://github.com/skypilot-org/skypilot/blob/10967e6c17bee50827dfc6d1ea5cdd7fff2d6c8c/sky/backends/backend_utils.py#L1809-L1826

```
ValueError: Cluster name "sky-6948-rOmILB" is invalid; ensure it is fully matched by regex: [a-z]([-a-z0-9]{0,61}[a-z0-9])?
```

We should maybe run .lower() on the username and remove any invalid characters from it when generating cluster name.

**Comment by Akshat977** [comment]
Hi @romilbhardwaj ,
This issue seems to be a good initiation of my journey towards contribution to FOSS projects.
Can you please assign this to me?

**Comment by romilbhardwaj** [comment]
Thanks for taking this up @Akshat977!

**Comment by michaelzhiluo** [comment]
Any updates on this Git issue @Akshat977 ?

**Comment by Michaelvll** [comment]
Hey @Akshat977, since we did not hear back from you for a long time, we will reassign the issue soon. Please tell us your progress, if you are working on it. : )

**Comment by Akshat977** [comment]
Hey @Michaelvll, I will be working on and completing the issue within this week, so please reassign me.

**Comment by Akshat977** [comment]
Hey @Michaelvll , can you please review my pull request?
