### ISSUE TITLE
Should `sky down mycluster` terminate `mycluster`'s spot controller too?

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#1172]
Quick note for investigation.  I used laptop to launch a bunch of clusters, from which a bunch of spot jobs were spawned. On laptop, I `sky down` those clusters, but I'm surprised to see the spot controller VMs are not down'd. This is expected behavior, but unintuitive.

**Comment by Michaelvll** [comment]
I think this could lead to a deep recursive detection finding all the clusters launched on the clusters in local cluster table. Probably, a better solution is to share the `~/.sky` folder accross the clusters?
