### ISSUE TITLE
`sky stop` not working for Azure and create multiple VMs with the same name

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#1173]
I did `sky launch -c vision-azure 'some commands'`, `sky launch -c vision-azure 'some commands'` and later `sky stop vision-azure` without error. The dashboard shows there are two `vision-azure` running.

**Comment by leonHeee** [comment]
Azure API to launch VM is not idempotent. Check if the two `vision-azure` running with same zone. 
Feel like something wrong around https://github.com/skypilot-org/skypilot/blob/master/sky/clouds/azure.py#L178 need to check the generated parameters.

**Comment by amcw7777** [comment]
Azure API to launch VM is not idempotent. Check if the two `vision-azure` running with same zone. 
Feel like something wrong around https://github.com/skypilot-org/skypilot/blob/master/sky/clouds/azure.py#L178 need to check the generated parameters.
