### ISSUE TITLE
Support for multiple GCP configurations and remove `default` requirement

### ISSUE THREAD

**Issue by gmittal** [skypilot-org/skypilot#1193]
I have multiple GCP accounts/configurations (TPU research cloud, personal account, various organization accounts, etc.) and would like to be able to switch between them and have SkyPilot automatically use the currently active configuration (or have some way to hardcode which configuration SkyPilot should always use). 

I also would like to name my configurations something other than `default` and have SkyPilot work (currently fails because it looks for a `default` credential file).

https://github.com/skypilot-org/skypilot/blob/master/sky/clouds/gcp.py#L21

**Comment by concretevitamin** [comment]
Hey @gmittal a few questions:

- By "the currently active configuration", do you mean whatever is currently encoded in `~/.config/gcloud/active_config`?  This file contains a string that identifies a file in `~/.config/gcloud/configurations/`.
- For switching, you could run `gcloud init` to choose the new project and then `gcloud auth application-default login`. This will switch the config files correctly. We can then make SkyPilot always pick up the config pointed to by `active_config`. Would this manual switching suffice for your use case?

**Comment by infwinston** [comment]
Closed by https://github.com/skypilot-org/skypilot/pull/1539. 
SkyPilot uses the config activated by `gcloud config configurations activate CONFIG_NAME`
@gmittal let us know if it still doesn't work, thanks!

**Comment by concretevitamin** [comment]
Reopening, as we may want to pick up the config pointed to by `active_config`, rather than relying on config_default.

Related discussion in #1535.
