### ISSUE TITLE
[bug] `skypilot down` stuck for TPU VM nodes

### ISSUE THREAD

**Issue by parasj** [skypilot-org/skypilot#1202]
Skypilot is stuck deprovisioning a set of TPU VM nodes.

```
$ sky status
NAME    LAUNCHED  RESOURCES                                                                  STATUS  AUTOSTOP  COMMAND
tpu2  1 hr ago  1x GCP(TPU-VM, {'tpu-v3-8': 1}, accelerator_args={'runtime_version': '...  INIT    -         sky tpunode -c tpu2 --tpus...
tpu1  1 hr ago  1x GCP(TPU-VM, {'tpu-v3-8': 1}, accelerator_args={'runtime_version': '...  INIT    -         sky tpunode -c tpu1 --tpus...
tpu   1 hr ago  1x GCP(TPU-VM, {'tpu-v3-8': 1}, accelerator_args={'runtime_version': '...  INIT    -         sky tpunode -c tpu --tpus...
$ sky down "tpu*"
Terminating 3 clusters: tpu1, tpu2, tpu. Proceed? [Y/n]:
Terminating 3 clusters ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--
```

I had to manually clean up resources but skypilot is still stuck.

**Comment by Michaelvll** [comment]
Wondering if you have `sky launch -c tpu` running in parallel? Our `sky launch` will hold the lock for the cluster and `sky down` may stuck waiting for the lock to be released. Could you try to `rm ~/.sky/.tpu.lock ~/.sky/.tpu1.lock ~/.sky/.tpu2.lock` and do `sky down "tpu*"` again?

**Comment by parasj** [comment]
I'm not seeing any lock files:

**Comment by concretevitamin** [comment]
How long was it stuck for before you cleaned it up? I've found many gcloud commands to take quite a while,  sometimes nondeterministically, which may be what happened. 

cc @infwinston

**Comment by parasj** [comment]
About 3 hours

**Comment by parasj** [comment]
After further investigation, it seems like one cluster hit a provisioning issue and didn't actually start any TPU VMs.

**Comment by infwinston** [comment]
@parasj would you mind sharing the YAML you used? I haven't encountered this issue before and would like to try reproducing it.

**Comment by parasj** [comment]
I haven't encountered the issue after reinstalling Skypilot, so it may have been a transient issue.
