### ISSUE TITLE
Interactive node CLIs should have feature parity with YAML specification

### ISSUE THREAD

**Issue by parasj** [skypilot-org/skypilot#1205]
The interactive node CLIs (gpunode, tpunode) are missing key functionality I'd like to use:
* specification of a single region and zone to use for provisioning
* `--retry-until-up`

Overriding the Skypilot optimizer with a single region is helpful since it doesn't consider factors such as bucket locations. I'd prefer to have Skypilot wait until it can allocate a VM in a single region until successful. Currently, it will search all regions for a VM and then fail as there is zero on-demand A100 capacity across supported Skypilot AWS regions (US only).

**Comment by ewzeng** [comment]
Working on it :)
