### ISSUE TITLE
Sharing `~/.sky` across machines

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#1211]
@lhqing  mentioned sharing the `~/.sky` across multiple machine is very useful, and he has successfully done that with placing it on the Google Drive. It works well for all stopped clusters, but it has problems logging into the UP cluster from another machine.

TODO:
- [ ] Add all the ssh config information into an external file under `~/.sky` and import it in the `~/.ssh/config`, instead of directly adding them in the `~/.ssh/config`.

**Comment by Michaelvll** [comment]
> Add all the ssh config information into an external file under ~/.sky and import it in the ~/.ssh/config, instead of directly adding them in the ~/.ssh/config

Hey @michaelzhiluo, do you want to work on this TODO, as you created `~/.ssh/config` for multi-node?

**Comment by concretevitamin** [comment]
Related to/duplicates #177.
