### ISSUE TITLE
[Filemounts] Uploading a file creates symlinks, breaking docker volume mounts

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#1222]
SkyPilot has different behavior when files are mounted vs when directories are mounted.

E.g., consider this file mount:

```
file_mounts:
  /inputs: ./echo_app    # Case 1
  /inputs/README.md: ./echo_app/README.md    # Case 2 
```

When directories are mounted (case 1), it copies the file contents to the destination path. This is expected behavior. 
```
ubuntu@ip-172-31-46-159:/inputs$ ls -la
total 20
drwxrwxrwx 2 ubuntu ubuntu 4096 Oct 11 16:53 .
drwxrwxr-x 4 ubuntu ubuntu 4096 Oct 11 17:13 ..
-rwxrwxrwx 1 ubuntu ubuntu   86 Oct 11 16:53 Dockerfile
-rwxrwxrwx 1 ubuntu ubuntu   89 Oct 11 16:53 README.md
-rwxrwxrwx 1 ubuntu ubuntu  657 Oct 11 16:53 echo.py
```

When files are mounted (case 2), it creates a symlink to the file.
```
ubuntu@ip-172-31-46-198:/inputs$ ls -la
total 8
drwxr-xr-x  2 ubuntu root 4096 Oct 11 17:01 .
drwxr-xr-x 21 root   root 4096 Oct 11 17:01 ..
lrwxrwxrwx  1 ubuntu root   46 Oct 11 17:01 README.md -> /home/ubuntu/.sky/file_mounts/inputs/README.md
```

Case 2 breaks docker support when apps try to volume mount `/inputs/` with `--volume="/inputs:/inputs:ro"`. Symlinks inside a docker volume mount are not resolved when mounting ([see this](https://stackoverflow.com/a/40322275/11025009)). Can we copy files to their destination instead of symlinking them?

**Comment by Michaelvll** [comment]
I think the main reason for the symlink was to prevent some permission issues. Maybe @concretevitamin can say more about it.
Can we use hard links instead? I think the hard link should work with the mounting.

**Comment by concretevitamin** [comment]
Sorry, I don't remember the exact reasons why we chose to do soft symlinks rather than hard links / copying. Had something to do with permissions.

Here's what I dig up:

https://github.com/skypilot-org/skypilot/blob/c4fd2b13b3121da82abb59064fc389bee574c52e/sky/backends/backend_utils.py#L270-L282

#108
