### ISSUE TITLE
[Optimizer] Add disk price to the optimizer

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#1228]
We are using the default disk type for all the clouds, and the price should be fixed for all the regions in each cloud. We can have a dict for the disk price and add it to the cost used in the optimizer.

Also, we need to have the price in the `sky status`, since the STOPPED cluster will still cost money for the disk.

Some references:
AWS: gp3 with IOPs 3000 costs: disk_size * 0.08 / 30 /24 per hour.

**Comment by Sachin1939** [comment]
Hey @Michaelvll , I would like to work on this issue so could you please assign this issue to me since I want to start my open source contribution journey.
Thanks!

**Comment by concretevitamin** [comment]
Hey @Sachin1939 - feel free to send a PR on this.

**Comment by Michaelvll** [comment]
This is in progress and should leave open.
