### ISSUE TITLE
[Provisioner] sky launch hangs forever when ssh connection is banned

### ISSUE THREAD

**Issue by infwinston** [skypilot-org/skypilot#1232]
During Lily's onboarding session, `sky launch` hangs due to our campus wifi not supporting SSH connection. To reduce friction, we should immediately error out if SSH connection is not allowed.

**Comment by concretevitamin** [comment]
According to this https://berkeley.service-now.com/kb_view.do?sysparm_article=KB0010499 ssh is enabled. We need to debug this.

**Comment by ewzeng** [comment]
I'll be happy to look into this!

**Comment by ewzeng** [comment]
Contrary to what [servicenow](https://berkeley.service-now.com/kb_view.do?sysparm_article=KB0010499) says, CalVisitor does block port 22. You can see this by going on CalVisitor and running the follow commands:
```
time echo 'exit' | telnet portquiz.net 443 # Doesn't hang
time echo 'exit' | telnet portquiz.net 22  # Hangs
```

**Comment by Michaelvll** [comment]
Great findings @ewzeng! Thank you for investigating the problem. Do you add a network check in the following function to reduce the friction caused by the hanging?
https://github.com/skypilot-org/skypilot/blob/f49ed5aed4d180c18d7feddcb2733c61d9170441/sky/backends/backend_utils.py#L1342-L1343

**Comment by ewzeng** [comment]
Yes @Michaelvll! I was planning to :)
