### ISSUE TITLE
sky launch failed due to pip install permission and dependency conflicts

### ISSUE THREAD

**Issue by infwinston** [skypilot-org/skypilot#1234]
This error happened in Lily's onboarding session when she `sky launch` with her own AMI. The `pip3` on her server referred to a system one which requires root permission to install packages. and a couple package conflicts were triggered even with root permission.

Detailed log: https://gist.github.com/LiuXiaoxuanPKU/beec04d33af9c0688c34ba98e867f23c

Temporary workaround: we changed `pip3 install` to `pip3 --user install` in `aws-ray.yml.j2` to avoid using system pip. However, further discussion may be needed on whether to make this change permanent. Potential dependency conflicts may still happen if users install some packages with `pip --user`.

**Comment by concretevitamin** [comment]
Related: we can consider highlighting any stderr output from `ray up` (provisioning) in red.
