### ISSUE TITLE
[Examples] Examples are missing description and usage instructions

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#1241]
One thing I notice throughout our examples is a lack of opening comments at the top of the YAML. It makes it really hard to understand for new users what each example does and how to use it (the how to use it is particularly hard to understand for non-typical examples, such as those in `examples/benchmark` and `examples/spot`).

We should try to add a few line description and a usage guide for each example we add. `minimal.yaml` sets a good standard:

```
# A minimal example.
#
# Runs a task that simply lists the default conda environments.
#
# Usage:
#   sky launch -c min minimal.yaml
#   sky down min
```

**Comment by concretevitamin** [comment]
+1. In fact, this structure of "One-line description -> Some more detailed descriptions -> Usage example" is from Google's style guides.  We should apply them to all examples, as well as modules/classes.  Ref: https://google.github.io/styleguide/pyguide.html#382-modules
