### ISSUE TITLE
[Provisioner] Add support for opening ports on VMs

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#1255]
I want to host a publicly accessible jupyter notebook using SkyPilot, where I distribute IP and port number and my customers can simply type `http://IP:PORT/` in their browser to access the notebook. I can fetch the IPs of the machines provisioned by SkyPilot by inspecting `~/.sky/state.db`, but only port 22 is open on the VMs. Security is handled at the application layer (I distribute jupyter auth credentials).

It would be great to have functionality to open specific ports on VMs so users can host services with SkyPilot and expose them externally.

Note that this is about opening ports in the VM's security group, which is different from port-forwarding (supported by sky cpunode).

**Comment by romilbhardwaj** [comment]
Update for AWS - it appears ray reuses the same security group for all VMs provisioned by the autoscaler. 

As a workaround, one can configure the ports needed on that security group once, and all future VMs will have that port open. I opened port 8888 and then I could access jupyter on all ips.

Worked for my usecase, but may not work for people who may need different ports on different clusters.

**Comment by Michaelvll** [comment]
Note: in our ray-up YAML file, we specified the security_group used for the cluster to be `sky-sg-<userhash>`, so any update to that security group will be applied to all launched VMs. We may be able to support the opening ports by automatically generating a new security group if the user specifies a port in the configuration.

**Comment by romilbhardwaj** [comment]
@parasj also faced this issue:

> SSH forwarding is the only supported way to expose a port to the world in Skypilot [today](https://skypilot.readthedocs.io/en/latest/examples/gpu-jupyter.html). However, I need public access to the VM without SSH forwarding.
> 
> The task YAML should support a ports field:
> ```
> ports:
>   - 8080
> ```
> 
> I currently must manually add the port via the AWS EC2 console.

**Comment by romilbhardwaj** [comment]
From @michaelzhiluo in #1546:

> This might be an important feature needed to enable model serving. Reasons being,
> 
> There is no documentation on what ports are "open" for sky launch'ed VMs.
> User might need a very specific port.
> Reach feature parity with sky cpu/gpu/tpunode which as --port-forward

**Comment by romilbhardwaj** [comment]
Also raised in #1887. Draft PR with GCP support in #1850.

**Comment by romilbhardwaj** [comment]
Raised on slack:
> Is it possible to configure ports on skypilot so that they are accessible through a public url? 

> for serving a streamlit app to share results with colleagues

> I was able to do it by configuring the  VM to allow HTTP traffic (enables tcp port 80), installing nginx and configuring the webserver to expose the streamlit app using a reverse proxy [...] this also required stopping and relaunching the cluster.

> I was wondering whether this could be done  more straightforwardly through skypilot

**Comment by concretevitamin** [comment]
Related 
- Docker-compose has `ports`: https://github.com/TabbyML/tabby/blob/main/experimental/deploy/docker-compose.yaml#L8-L9
- Docker has `EXPOSE`: https://github.com/GoogleCloudPlatform/llm-pipeline-examples/blob/main/docker/train.Dockerfile#L57-L59

**Comment by concretevitamin** [comment]
cc @cblmemo

**Comment by cblmemo** [comment]
I'm wondering if putting `ports` section in `task.yaml` is a good idea, since in #1850 and AWS's proposed implementation in #1487 , the ports will open for all VMs launched by skypilot and it is not limited to VMs provisioned for one task. Maybe we could consider adding a `ports` / `exposed_ports` section in `~/.sky/config.yaml`?
