### ISSUE TITLE
[Provisioner][Feature Request] Use quotas to guide region/cloud fail over

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#1268]
Current failover logic iterates over a series of regions/cloud. However, often the reason for provisioning failures is the lack of quotas. User may have quota in just one region, but they must wait for failover to happen across many other regions first. (Of course they could specify the region in the yaml, but that's only if the user knows where they have quotas)

Can we obtain user's quotas from cloud APIs and use that to guide our failover logic?

**Comment by WoosukKwon** [comment]
I agree that it'd be super useful. Especially, when provisioning multiple nodes, the failover time can be very long.

I've discussed this with @infwinston a while ago. If I remember correctly, one challenge was to understand the GCP's complex quota logic.

**Comment by Michaelvll** [comment]
This is being added in #1953 and future PRs. We should keep this open.

**Comment by romilbhardwaj** [comment]
Duplicate of #664, closing.
