### ISSUE TITLE
UX: spot and non-spot versions use different names to see existing jobs: `sky queue` vs `sky spot status`

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#1277]
A comment from a new user:

 I found it strange that the spot and non-spot versions use different names for similar tasks.
* to see existing jobs: `sky queue` vs `sky spot status`

-----

We can consider renaming options.

**Comment by michaelzhiluo** [comment]
What is the final decision regarding this? I saw that `sky spot queue` and `sky queue` is the best option.

**Comment by concretevitamin** [comment]
Yes, according to the vote we should rename `spot status` to `spot queue`
everywhere.
