### ISSUE TITLE
[UX] Show cost on `sky down`

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#1278]
One of the sky camp attendee mentioned they were expecting to see a dollar estimate of how much you spent on the cluster on running `sky down`. Could also show it in `sky status` (est. cost of clusters till now).

I think this would be a nice UX feature to have. Of course, will have to think about how to handle stopped clusters and autostopped instances...

**Comment by SakshiT25** [comment]
Is this issue still open? @romilbhardwaj

**Comment by Michaelvll** [comment]
We have merged a `sky cost-report` feature in #1301  (thanks to @sumanthgenz) and decided to not have the print at the end of `sky down`. Closing this for now. : )
