### ISSUE TITLE
[UX] Launching on an existing cluster sets the state to INIT causing confusion

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#1282]
One of our users is confused by the status of `sky launch -c existing_cluster` being INIT. It is confusing why the cluster will be re-initialized again and whether it creates another cluster. It would be good to clarify that. Here are 2 options:
1. Change the INIT state to SETUP, which will be easier to understand. (we can keep the internal status, but distinguish the display for launch a new cluster and launch on an existing cluster).
2. Re-design the logic of the `sky launch` so that it can skip the code path that sets the cluster status UP->INIT->UP. (This may require modifying many places, as internally we use INIT for many checks).

**Comment by concretevitamin** [comment]
cc @gilv: would you say "It is confusing why the cluster will be re-initialized again and whether it creates another cluster." is accurate? Which option of the two proposed by @Michaelvll sounds better to you?

**Comment by Michaelvll** [comment]
> Which option of the two proposed by @Michaelvll sounds better to you?
I feel like the second one should be done ultimately, but to mitigate the problem, we can do the first one as the first step. Wdyt?
