### ISSUE TITLE
[custom image] pip install fail in some custom image

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#1289]
During the onboarding of a user, we found this issue. Installing ray/skypilot with the default pip3 can fail in some custom images due to the `permission denied` for writing to the default python package location. Adding `--user` in the ray yaml config to every `pip3 install` fixes her issue.

We need to re-consider where we install the dependencies of skypilot on the remote VM.

**Comment by concretevitamin** [comment]
Have we investigated always using `--user`?

**Comment by Michaelvll** [comment]
cc. @infwinston

**Comment by infwinston** [comment]
I think `--user` is better than without it. Though it's not guaranteed to solve potential dependency issue if user installed some packages with `--user` that conflict with `skypilot`.

btw, is this issue the same as https://github.com/skypilot-org/skypilot/issues/1234?

**Comment by Michaelvll** [comment]
Duplicate with #1234. Closing.
