### ISSUE TITLE
Down Stage in `execution.py` is never called

### ISSUE THREAD

**Issue by michaelzhiluo** [skypilot-org/skypilot#1295]
In the code here,
https://github.com/skypilot-org/skypilot/blob/deb089dabf46485793f35992ed33999dc64cd6b8/sky/execution.py#L251-L254

`backend.teardown` is never called since when `down=True`, `idle_minutes_to_autostop` is set to 1 here:

https://github.com/skypilot-org/skypilot/blob/deb089dabf46485793f35992ed33999dc64cd6b8/sky/execution.py#L165-L182

In that case what is the purpose of `stages.DOWN`?

**Comment by Michaelvll** [comment]
Currently, it is only for other backends, since the `DOWN` stage does not make sense for the serverful `CloudVMRayBackend` design. Otherwise, when the logging is detached during the job is running, the cluster will be terminated immediately in the `DOWN` block.

**Comment by michaelzhiluo** [comment]
Ah ic, why would `LocalDockerBackend` need this? (I'm guessing we can remove `stage.DOWN` all together if it is not needed)
