### ISSUE TITLE
[Onprem] workdir fail to be found in multinode case

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#1298]
When `sky admin deploy` on two newly launched cluster, and `sky launch` on the worker node. The following issue appears during the execution
```
bash: cd: /home/myuser/sky_workdir: No such file or directory
```
[notes](https://docs.google.com/document/d/11yBU42ko8ujCmEOvAXS-PJtnupIwUDHzMXlesp-9gAE/edit?usp=sharing)

**Comment by michaelzhiluo** [comment]
Thanks for finding bug! On it...
