### ISSUE TITLE
[Feature Request] Logs of Setup

### ISSUE THREAD

**Issue by michaelzhiluo** [skypilot-org/skypilot#1307]
It'd be nice to be `setup.log` in `~/sky_logs/timestamp/...`. In that case, I can happily debug environment from past iterations of debugging.

Edit: It is actually a bug instead.

**Comment by Michaelvll** [comment]
The `setup-{ip}.log` should appear in the `~/sky_logs/timestamp/...`.

https://github.com/skypilot-org/skypilot/blob/f49ed5aed4d180c18d7feddcb2733c61d9170441/sky/backends/cloud_vm_ray_backend.py#L1982-L1986

Just tested with the following yaml, and the `setup-ip.log` correctly shows up.
```

```

**Comment by michaelzhiluo** [comment]
Should be a bug then @Michaelvll I dont see it after setting up resnet environment.
<img width="853" alt="Screen Shot 2022-10-31 at 2 48 17 AM" src="https://user-images.githubusercontent.com/20640975/198979861-e0c905b4-68de-4e65-b284-dba9cba8adda.png">

**Comment by Michaelvll** [comment]
The logs should be on your local machine, not on the remote VM.

**Comment by michaelzhiluo** [comment]
Was this originally intended to have different `local` and `remote` log directories? It was surprising that the directory contents on my laptop does not match remote and I would have never known otherwise.

Suggested fixes:
1) Match `setup.log` for both remote and local.
2) Have documentation that `setup.log` is only on local, etc.

**Comment by michaelzhiluo** [comment]
@Michaelvll If there is detach setup, is this fixed?

**Comment by Michaelvll** [comment]
We now have a `--detach-setup` option now. The problem should be fixed. : )
