### ISSUE TITLE
[Onprem] `sky cancel [JOB_ID]` is broken

### ISSUE THREAD

**Issue by michaelzhiluo** [skypilot-org/skypilot#1309]
Sky cancel no longer fully cancels the job (it still runs post cancelation). This is most likely to do with switching the Ray to be launched by admin instead of root.

**Comment by concretevitamin** [comment]
Side note -- Can we check why that PR didn't trigger a test that catches this issue?  Was it because there's no test on the cancel behavior?

**Comment by michaelzhiluo** [comment]
There is a test, but it is a smoke test...

**Comment by concretevitamin** [comment]
That's ok. Let's institute the policy that on-prem smoke tests should be run for on-prem changes that may change behavior (just like we've been running regular smoke tests for core system changes).
