### ISSUE TITLE
[Storage] Unexpected behavior when adding a file mount with a relative path

### ISSUE THREAD

**Issue by pschafhalter** [skypilot-org/skypilot#1314]
Hi,

I'm trying to mount an S3 bucket within my workdir. I used the following config, expecting `./data` to be a location within my workdir; however, it mounts to `~/data`. This is inconsistent with the behavior in `setup` and `run`, where `.` points to the workdir.
```
file_mounts:
  ./data:
    name: $BUCKET_NAME
```
My current workaround is to mount the bucket in the workdir explicitly; however, it would be nice to use relative paths for file mounts.
```
file_mounts:
  ~/sky_workdir/data:
    name: $BUCKET_NAME
```

**Comment by romilbhardwaj** [comment]
Thanks for reporting this bug! I'll investigate and push a fix.

**Comment by romilbhardwaj** [comment]
Thinking more about this - if we change `.` to point to workdir for `file_mounts`, we run the small risk of the file_mount overwriting contents of the workdir OR workdir sync (e.g., with `sky exec`) overwriting `file_mounts`. While this can happen today too if any file_mount writes in `~/sky_workdir/`, but having `.` would make it easier for users to shoot themselves in the foot.

However, as peter mentioned, making this change has a big usability pro - consistency across setup, run and file_mounts. Overall, I feel the pros outweigh the risks and we should add this. Will let others chime in too.

**Comment by concretevitamin** [comment]
Thanks for the report @pschafhalter !

@romilbhardwaj This analysis makes sense to me.
