### ISSUE TITLE
`unattended-upgrade` process upon starting VM made `launch` get stuck

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#1341]
User reported:
> A couple issues I encountered while trying to use an AMI for ubuntu 18.04: Upon starting the instance, an unattended-upgrade process runs in the background and blocks the initialization process (it holds the lock needed by apt-get). It might be good to allow doing sudo systemctl stop unattended-upgrades while preparing SkyPilot runtime.

Specifically it got stuck after
```
Successfully installed MarkupSafe-2.1.1 PrettyTable-3.5.0 awscli-1.26.4 boto3-1.25.4 botocore-1.28.4 colorama-0.4.4 commonmark-0.9.1 docutils-0.16 httplib2-0.21.0 jinja2-3.1.2 jmespath-1.0.1 networkx-2.8.7 oauth2client-4.1.3 packaging-21.3 pandas-1.5.1 pendulum-2.1.2 pulp-2.6.0 pycryptodome-3.12.0 pygments-2.13.0 pyparsing-3.0.9 python-dateutil-2.8.2 pytz-2022.5 pytzdata-2020.1 pyyaml-5.4.1 rich-12.6.0 rsa-4.7.2 s3transfer-0.6.0 skypilot-0.2.0 tabulate-0.9.0
```
After I force-killed the unattended upgrades process and removed lock files it then proceeded to
```
Setting up man-db (2.8.3-2ubuntu0.1) ...
```

----

cc @michaelzhiluo is this related to apt locks?

**Comment by Michaelvll** [comment]
This should have been fixed in #1347. Closing for now.
