### ISSUE TITLE
[spot] `sky spot logs` for non-existing job should fail immediately

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#1342]
As observed by @concretevitamin, tailing the log for a non-existing spot job will generate confusing logs. We may want to fail the tailing immediately instead.
https://github.com/skypilot-org/skypilot/pull/1329#pullrequestreview-1162063122

**Comment by concretevitamin** [comment]
Should keep open. Today's main branch:
```
» sky spot logs 99999
⠼ Waiting for controller process to be RUNNING  (status: None). It may take a
few minutes.
```

**Comment by Michaelvll** [comment]
This should stay open until we confirm this is not an issue.
