### ISSUE TITLE
Support more AWS regions for better spot availability

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#1344]
From user

> It seems that Sky only tries a few regions like us-east-1, us-east-2, us-west-1, us-west-2 (from looking at https://github.com/skypilot-org/skypilot/blob/05d42185d6376cb6061b84f12068d39aa8693c95/sky/clouds/aws.py#L116), when there are other regions potentially with spot instance availability. Is this true & if so why not more regions?

> Would be great to have this option since it might provide more spot instance availability for me

**Comment by Michaelvll** [comment]
Related to #589.
