### ISSUE TITLE
[Tests] Add autodown to smoke tests?

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#1349]
Sometimes I run smoke tests and check back a few hours later to see if all passed. During this time, its possible some tests failed and left the VM running. 

Should we add an auto-down to all smoke test clusters? We could set the autodown interval to 1-2hr to give enough time for the developer ssh if required.

**Comment by Michaelvll** [comment]
We now terminate the clusters launched by tests by default. This issue should be not relevant now.
