### ISSUE TITLE
[Feature Request] Support advanced AWS feature

### ISSUE THREAD

**Issue by zhuohan123** [skypilot-org/skypilot#1354]
Current skypilot does not support advanced aws options like specifying security groups and placement groups, which is supported by ray autoscaler and boto3. These options are critical to our experiments. For example, the placement group can make sure the instances have high inter-connection speed.

cc @Michaelvll

**Comment by romilbhardwaj** [comment]
Related feature request: #1255

**Comment by Michaelvll** [comment]
@zhuohan123 has volunteered to support this. Please feel free to submit a PR. : )
In the `resources` field in the YAML file, we can have an option called something like `additional_options`:
```
resources:
  accelerators: V100:4
  additional_options:
    placement_group: <name>
    security_group: <name>
```

To implement this, you may want to add another field to `sky.Resources` and the `from_yaml_config` method in it. To pass down the option to our ray up yaml, you can modify the function `sky.backends.backend_utils.write_cluster_confg` https://github.com/skypilot-org/skypilot/blob/a613b43a9f60848b8202486c3d52f4c147308fbc/sky/backends/backend_utils.py#L759

and also modify the template file in `sky.templates.aws-ray.yaml.j2`. It would be great if you would like to add the `additional_options` for the other clouds as well.

**Comment by Michaelvll** [comment]
This is also required by another user for setting up VPC. Increasing the priority.

**Comment by AlexvZyl** [comment]
Commenting to show interest in this closed issue.

**Comment by Michaelvll** [comment]
Thank you for pinning on this issue @AlexvZyl! Could you elaborate more on what specific feature you would like to have for AWS?

**Comment by AlexvZyl** [comment]
I would like to be able to specify the AWS security group that SkyPilot uses.

The reason: We are using terraform to build our infrastructure.  When SkyPilot creates its own additional security group outside of terraform we cannot destroy and recreate resrouces, since this dangling security group depends on them.

**Comment by Michaelvll** [comment]
> I would like to be able to specify the AWS security group that SkyPilot uses.
> 
> The reason: We are using terraform to build our infrastructure. When SkyPilot creates its own additional security group outside of terraform we cannot destroy and recreate resrouces, since this dangling security group depends on them.

Thanks for specifying the request @AlexvZyl! The security group feature was supported, but accidentally removed in a recent update. We just added it back with #3133.
After it is merged, you should be able to specify the following in the `~/.sky/config.yaml`:
```yaml
aws:
  security_group_name: your-security-group-name
```

Would that work for your case?

**Comment by AlexvZyl** [comment]
Awesome, thanks!  That will definitely work.

Just a small side-note, SkyPilot is held in a very high regard at my company.  Good work!
