### ISSUE TITLE
Way to run setup code again but skip the skypilot runtime provisioning?

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#1360]
User asked:

> is there a way to run setup code again but skip the skypilot runtime provisioning (so similar to exec but allow running some common setup before run so that there’d be an implicit barrier)?

A proposal from @Michaelvll: `sky launch --no-provision -c cluster-name task.yaml`

**Comment by michaelzhiluo** [comment]
Missing the context here, why do we need to provision again after `sky launch` is run the first time? We would just need to load the `ResourceHandle`?

**Comment by Michaelvll** [comment]
The main thing we want to do the `preparing the Skypilot runtime` again, to make sure the remote SkyPilot is the same as the local one, i.e. uploading the wheel again and installing it.
Previously, it was also for making sure the ray cluster is correctly running on the cluster, if not restart the ray cluster, but now we can use `backend_utils.refresh_cluster_status` to ensure that.
