### ISSUE TITLE
Specify multiple allowed accelerators

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#1361]
User asked:

> Is there a way to specify multiple allowed accelerators? For my specific case, the number of gpus per node can be held fixed but allow the type of gpu to vary e.g. between V100 / V100-32GB / A100

Proposal:
```
accelerators: [V100:1, V100:4, A100:8]
```
with the semantics of “use any of them, whichever is cheapest / available first”?

**Comment by michaelzhiluo** [comment]
This seems very connected to `sky bench` and the idea of Sky racing. Tagging @WoosukKwon

**Comment by concretevitamin** [comment]
Another use requested this: they wanted to request e.g., [A10, A10G, A100]. This user mentioned _perhaps_ the list should represent a search order (i.e., preference).

WIP: #1389 

Related:
- #2238 
- #1912

**Comment by concretevitamin** [comment]
@dongreenberg Would love your inputs here as you mentioned Runhouse had to workaround this A10/A10G problem. How did you solve it? Would you like SkyPilot to use an ordered list semantics or an unordered semantics?

**Comment by ErwannMillon** [comment]
Yeah, also had to do some hacky stuff to workaround this, you can see my fork of skypilot, but basically just overriding the resources passed to the provision call in the cloud VM ray backend.

**Comment by Michaelvll** [comment]
This issue has been fixed by #2498. Please feel free to try it out https://skypilot.readthedocs.io/en/latest/examples/auto-failover.html#multiple-candidate-gpus. Closing this issue now.
