### ISSUE TITLE
Easy way to deploy using containers

### ISSUE THREAD

**Issue by Kadle11** [skypilot-org/skypilot#1386]
Hi!

I am interested in understanding how SkyPilot works and want to become comfortable using it on a local machine before using it on GCP/AWS. Is there an easy way to run Tasks locally using containers or something similar?

Thanks.

**Comment by romilbhardwaj** [comment]
Thanks for raising this issue @Kadle11! We're actively working on building a `local` mode for SkyPilot which would allow you to emulate a cluster in a container and submit tasks to it using the regular `sky` CLI. We'll get back to you on this very soon.

**Comment by romilbhardwaj** [comment]
This is now supported through our k8s support: https://skypilot.readthedocs.io/en/latest/reference/kubernetes/kubernetes-setup.html#kubernetes-setup-kind

Leaving ticket open as a note to add docs on specifically this job-to-be-done, especially in quickstart/installation.

**Comment by Michaelvll** [comment]
This issue seems resolved. Closing it now.
