### ISSUE TITLE
[Setup] ssh agent forward not work with `--detach-setup`

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#1402]
Since `--detach-setup` adds the setup script to the job, the ssh agent forwarding will not work during the setup. It will cause inconsistent behavior between normal setup and `--detach-setup`, e.g. fail to clone private github repo for `--detach-setup`

**Comment by concretevitamin** [comment]
Ran into this when debugging an example. Initially I did not set the `--detach-setup / -s` flag and everything works; after setting it, was surprised to see an error.
