### ISSUE TITLE
[docs] some questiones about the launch skypilot

### ISSUE THREAD

**Issue by lambda7xx** [skypilot-org/skypilot#1409]
I setup my azure account. And I try to "bash tests/run_smoke_tests.sh test_minimal". And there is some error. So, if I want to contribute to this project, the first thing I do is to have aws/gcp/azure account? And these accounts should have some server? BTW, I don't see the local test about the skypilot project.

**Comment by concretevitamin** [comment]
Hi @lambda7xx, what's the error you saw for Azure? Can you paste a stacktrace?

Local tests are here: https://github.com/skypilot-org/skypilot/tree/master/tests

We definitely do not need every developer to have all cloud accounts. For small PRs, perhaps local unit tests can cover the functionality added/changed. Otherwise the dev team can help with running the smoke tests.

**Comment by lambda7xx** [comment]
the stacktrace is below 
`
(skylab) saemal@az-eus-v100-32gb-5-worker-vnhhyp:/data/v-xxshi/skypilot$ bash tests/run_smoke_tests.sh test_minimal
bringing up nodes...
[minimal] Test started. Log: less /tmp/minimal-m7zq7s2j.log
[minimal] Failed.
[minimal] Reason: sky launch -y -c test-minimal-722fa80a-12 --image-id skypilot:gpu-ubuntu-1804 examples/minimal.yaml
[minimal] Log: less /tmp/minimal-m7zq7s2j.log
[minimal] 
F
============================================================================================ FAILURES =============================================================================================
__________________________________________________________________________________________ test_minimal ___________________________________________________________________________________________
```
[gw0] linux -- Python 3.8.10 /workspace/skylab/bin/python
tests/test_smoke.py:146: in test_minimal
    run_one_test(test)
tests/test_smoke.py:116: in run_one_test
    raise Exception(f'test failed: less {log_file.name}')
E   Exception: test failed: less /tmp/minimal-m7zq7s2j.log
===================================================================================== short test summary info =====================================================================================
FAILED tests/test_smoke.py::test_minimal - Exception: test failed: less /tmp/minimal-m7zq7s2j.log
1 failed, 56 warnings in 3.62s
(skylab) saemal@az-eus-v100-32gb-

(skylab) saemal@az-eus-v100-32gb-5-worker-vnhhyp:/data/v-xxshi/skypilot$ cat /tmp/minimal-m7zq7s2j.log
+ sky launch -y -c test-minimal-722fa80a-12 --image-id skypilot:gpu-ubuntu-1804 examples/minimal.yaml
Task from YAML spec: examples/minimal.yaml
ValueError: image_id is only supported for AWS and GCP, please explicitly specify the cloud.
Failed.
Reason: sky launch -y -c test-minimal-722fa80a-12 --image-id skypilot:gpu-ubuntu-1804 examples/minimal.yaml
Log: less /tmp/minimal-m7zq7s2j.log

```
`

**Comment by lambda7xx** [comment]
The local test I mean is that I can run the test on my own machine without the cloud account. But I see some code that it seems that I have to test the code on the cloud. Besides, the cloud account must have money if I want to run the test code?  I am in China now and I do not have ways to put my money into the aws/gcp/azure cloud account.

**Comment by lambda7xx** [comment]
> Hi @lambda7xx, what's the error you saw for Azure? Can you paste a stacktrace?
> 
> Local tests are here: https://github.com/skypilot-org/skypilot/tree/master/tests
> 
> We definitely do not need every developer to have all cloud accounts. For small PRs, perhaps local unit tests can cover the functionality added/changed. Otherwise the dev team can help with running the smoke tests.

thanks for your help

**Comment by Michaelvll** [comment]
Thanks for the question @lambda7xx! Before going to the tests, you could probably first follow the instructions in our document to try to launch an instance on azure first. You can try `sky launch --cloud azure`.
https://skypilot.readthedocs.io/en/latest/getting-started/quickstart.html

**Comment by Michaelvll** [comment]
Closing this issue for now as it is staled. Please feel free to file a new one, if any problem still exists.
