### ISSUE TITLE
Always use autostop by default

### ISSUE THREAD

**Issue by vwxyzjn** [skypilot-org/skypilot#1435]
Hi, this is an amazing piece of software. I was wondering if there is any way to always run the cluster the `autostop` mode using the configuration from the yaml file? I don't want to always do `--idle-minutes-to-autostop --down` when launching the cluster...

Alternatively autostop can probably be used as a sensible default — we should always autostop because if we forget it we could end up with a large bill.

**Comment by concretevitamin** [comment]
@vwxyzjn This is great feedback, thanks!

Which options do you like (open for voting):

1. Change `sky launch` to always use `--idle-minutes-to-autostop`. With, say, 10 minutes.
2. Introduce a config file (e.g., .skypilot_config under $PWD or ~/) where users can define defaults for various CLI commands
3. Introduce these options to the YAML spec (this may not be ideal as it's designed to be a job spec, not how the cluster should be managed)

**Comment by vwxyzjn** [comment]
Thanks for the prompt reply. Option 1 makes sense to me as a sensible default.

**Comment by romilbhardwaj** [comment]
I think we need both 1 and 2. It'll be good to have a sensible default (e.g., 10 min) but we should also expose knobs for users to change the default (e.g., through a config file).

**Comment by csaroff** [comment]
Can this get reopened?

My autostop config gets blown away every time I run `sky launch <config.yaml> -c <autostop-enabled-cluster>`.
IMO, this mostly defeats the purpose since I have to remember to run autostop every time I run `sky launch`.

With respect to (3), I'm also not sure I understand the hesitation. The `resources` spec that specifies cpu and memory goes in the job yaml, even though it's configuration for the cluster itself. Why is autostop different?

**Comment by concretevitamin** [comment]
Thanks for the feedback @csaroff. Reopening this.

Sounds like you ran into that issue when the old cluster was autostopped (i.e., in STOPPED state), and a new `sky launch` command is run without autostop settings. Is that right?  If so, wdyt about having SkyPilot automatically restore the autostop setting on any restart (`launch` or `start`), essentially making it a cluster-wide permanent setting until explicit cancellation?

**Comment by csaroff** [comment]
Thinking about it more, maybe not? What flag would you specify on launch of you didn't want to autostop the cluster?

My preference would still be to manage this through a config file somehow though.
