### ISSUE TITLE
[Spot] Use real time price for the spot VMs

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#1437]
From our user:
> Seems that fetching spot prices from cached catalog rather than live data might have costed us more last week (I’m not 100% sure, but a lot of instances were launched in us-east-2). Curious what’s the timeline to utilize live spot prices? Also if the command line tool can display live prices it’d be helpful.

**Comment by concretevitamin** [comment]
+1, the price-fetching overheads may be ok especially if we do this for spot jobs for now.

Previous investigation on timing:

~1.2s to get spot prices for an instance type within a region

> %timeit !aws --region=us-east-2 ec2 describe-spot-price-history --instance-types p3.16xlarge --start-time=$(date +%s) --product-descriptions="Linux/UNIX" --query 'SpotPriceHistory[*].{az:AvailabilityZone, price:SpotPrice}'


~1.07s for on-demand prices

> aws pricing get-products --service-code AmazonEC2 --filters "Type=TERM_MATCH,Field=instanceType,Value=p3.8xlarge" "Type=TERM_MATCH,Field=capacitystatus,Value=Used"  "Type=TERM_MATCH,Field=tenancy,Value=Shared" "Type=TERM_MATCH,Field=location,Value=US East (N. Virginia)" "Type=TERM_MATCH,Field=operatingSystem,Value=Linux" | jq -rc '.PriceList[]' | jq -r '[  .product.attributes.location, .terms.OnDemand[].priceDimensions[].pricePerUnit.USD, .terms.OnDemand[].priceDimensions[].description] | @csv'

**Comment by romilbhardwaj** [comment]
Plus we could cache the prices - a few seconds of delay every hour or so might not be bad

**Comment by Michaelvll** [comment]
Yes, I am leaning toward having the price cached periodically (maybe a github action proposed by @WoosukKwon) in our centralized catalog service. Reason:
1. Although getting the price information for one region takes only 1.2s, it could take longer (sequentially) or resource-hungry (in parallel) to fetch the price from all the regions.
1. With the centralized service we can easier fix issues with the automated price fetching tool and do better error checking of the results.
2. It is general, as the user does not need a daemon to keep track of the price, which is useful for the normal `sky launch`.

**Comment by WoosukKwon** [comment]
I agree with @Michaelvll 

One technical challenge I can see is that our GCP catalog fetcher (and sometimes even AWS and Azure feathers) is buggy. So I think we should make the Github workflow only update the AWS catalog periodically, and keep manually updating the Azure and GCP catalogs. As Azure on-demand instance prices and GCP prices do not change a lot over time, it would be ok to have long update cycles.
