### ISSUE TITLE
[Docs] Cloud IAM access requirements for SkyPilot

### ISSUE THREAD

**Issue by infwinston** [skypilot-org/skypilot#1443]
When assigning people to our shared cloud account, I was wondering what's the minimal IAM access needed for SkyPilot to work instead of granting a full access owner. This can be relevant for people in industry who may not have full access to their shared corp account.
We probably want to investigate the access requirements in each cloud provider and document it in FAQ or even quick-start.

**Comment by Michaelvll** [comment]
After discussing offline, @infwinston and I found the following role list for the user is sufficient to launch the VM on GCP when the `ray-autoscaler` account is already setup.
```
roles/browser
roles/compute.admin
roles/iam.serviceAccountUser
roles/serviceusage.serviceUsageConsumer
roles/storage.admin
```
To set up the `ray-autoscaler` account, we need the `serviceAccount.setIAMPolicy` (can be done by the admin) to grant the following roles to the account:
```
roles/compute.admin
roles/iam.roleViewer
roles/iam.serviceAccountUser
roles/storage.objectAdmin
roles/tpu.admin
```
