### ISSUE TITLE
[spot] Interaction between `sky start [--force]` and spot controller's autostop

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#1447]
User reported that:

>Is the spot controller autostopping actually working? When checking sky status, the comment says will be autostopped if idle for 10min  but the AUTOSTOP column shows nothing.

---

After digging into potential issues, we aren't sure why this happened. The below *could* be one reason:

We should either 
- disallow `sky start [--force]` on a (stopped) spot controller (which resets its autostop setting to 0); or
- ensure  `sky start [--force]` on a (stopped) spot controller properly restores its autostop setting

cc @Michaelvll

**Comment by concretevitamin** [comment]
We should probably do the second option, to support cases like: a controller gets auto-stopped -> user wants to run `sky spot logs X`. Relatedly - this will print:

https://github.com/skypilot-org/skypilot/blob/master/sky/core.py#L709-L712

which asks users to manually run `sky start` with an updated `-i` number of minutes.

**Comment by Michaelvll** [comment]
Good catch! I have experienced this before as well. It makes sense to support the second option by automatically set the autostop when starting the spot controller.
