### ISSUE TITLE
Investigate making unmanaged spot instances (auto-)stoppable & resumable

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#1448]
A user request:

> How feasible would it be to make spot instances auto-stoppable & resumable (for interactive dev usage on cheaper instances)

**Comment by concretevitamin** [comment]
The user bumped this. More details:

- User's current workaround is to use SkyPilot to launch an unmanaged spot node (`sky launch --use-spot`) for cheaper interactive dev
- However, "I need to be very careful when using this since none of my work on the local disk will be persisted and the machine can be terminated at any time."

----

My previous investigations, limited to AWS EC2, one node:

- Approach 1: use AWS "persistent spot request"
  - **Blocker** (seemingly): if preempted, EC2 will auto-relaunch the node, which is not desirable for a few reasons:
    - The new spot node, if successfully relaunched (a big if), would have no SkyPilot runtime or user data (e.g., workdir; mounted buckets)
    - Arguably we want the node to be stopped
   
- Approach 2: we manage EBS: record IDs, reattach, etc.
  - A more complex solution; didn't investigate fully
  - This may solve the above problems and also help with the "resizing a VM" request, e.g., #1620 

-----

Seeking community feedback: if this is useful to you too, please comment :)

**Comment by Michaelvll** [comment]
This is still relevant. We should keep this open

**Comment by Michaelvll** [comment]
Stopping spot for GCP has been supported in #2877, we should look into AWS as well.
