### ISSUE TITLE
Multi-node launching when out-of-quotas will fail over without hinting the reason

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#1450]
User reported:

> I was getting consistent failovers even when launching on-demand instances (g4dn.12xlarge; spot instances launched fine). Curious if the timeout of waiting for worker provisioning might be set to be too short?

> I 11-26 17:42:45 cloud_vm_ray_backend.py:1249] Launching on AWS us-west-2 (us-west-2d,us-west-2b,us-west-2a,us-west-2c)
I 11-26 17:44:21 log_utils.py:45] Head node is up.
I 11-26 17:45:57 cloud_vm_ray_backend.py:1356] Successfully provisioned or found existing head VM. Waiting for workers.
E 11-26 17:47:34 backend_utils.py:992] Timed out: waited for more than 90 seconds for new workers to be provisioned, but no progress.
E 11-26 17:47:34 cloud_vm_ray_backend.py:1118] *** Failed provisioning the cluster. ***
E 11-26 17:47:34 cloud_vm_ray_backend.py:1120] *** Terminating the failed cluster. ***
I 11-26 17:48:00 cloud_vm_ray_backend.py:1249] Launching on AWS us-east-2 (us-east-2c,us-east-2b,us-east-2a)
I 11-26 17:49:20 log_utils.py:45] Head node is up.
I 11-26 17:50:40 cloud_vm_ray_backend.py:1356] Successfully provisioned or found existing head VM. Waiting for workers.
E 11-26 17:52:19 backend_utils.py:992] Timed out: waited for more than 90 seconds for new workers to be provisioned, but no progress.
E 11-26 17:52:19 cloud_vm_ray_backend.py:1118] *** Failed provisioning the cluster. ***
E 11-26 17:52:19 cloud_vm_ray_backend.py:1120] *** Terminating the failed cluster. ***
I 11-26 17:52:46 cloud_vm_ray_backend.py:1249] Launching on AWS us-east-1 (us-east-1f,us-east-1e,us-east-1d,us-east-1c,us-east-1b,us-east-1a)
I 11-26 17:54:11 log_utils.py:45] Head node is up.

Later it was reported that this is due to low vCPU limits:
> It seems that the error was actually caused by my vCPU limit not sufficient to launch additional worker nodes. But the timeout error was kind of obscure.

----

Some things to fix

- [ ] Consider detecting the failures are due to quotas, then print a better message  (currently there isn't a way according to https://github.com/skypilot-org/skypilot/issues/1260#issuecomment-1280284189)
- [ ] If we can't easily detect, print quota as a possible reason anyway

**Comment by Michaelvll** [comment]
This should be mitigated by #1702

**Comment by Michaelvll** [comment]
This should be fixed for clouds adopted new provisioner API: AWS, GCP, Kubernetes, RunPod.
