### ISSUE TITLE
[UX] Find the closest region to my laptop

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#1466]
From our user:
> for sky interactive instances, it could be nice for sky to offer a feature that’s kind of like “find me the closest region to my current laptop that has availability for a certain instance type” rather than having to manually locate this.

As mentioned by the user, it would be very convenient for the user who travels around the globe.

**Comment by concretevitamin** [comment]
When asked about latency differences:

> there’s very obvious difference. I use vscode remote container for development and latency difference is very noticeable.
