### ISSUE TITLE
[Spot/UX] Need a way to only show the RUNNING spot jobs

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#1482]
Request from our user:
> Is there a way to clear jobs that are finished (either "SUCCEEDED" or "FAILED")?

**Comment by infwinston** [comment]
From the discussion, seems like one option is to only show the `RUNNING` jobs by default. We may also want to add some hint message like
```
Note: Only RUNNING jobs are displayed, run sky spot queue --all to show the entire history
```

**Comment by concretevitamin** [comment]
Two other possibilities:
- `sky queue` already provides `-s, --skip-finished  Show only pending/running jobs' information` so we may provide this too for `sky spot queue`. (IIRC, the former was added for the same reason.)
- (longer term) We could provide a UI running in browser that may make displaying various info much easier.

**Comment by concretevitamin** [comment]
> * `sky queue` already provides `-s, --skip-finished  Show only pending/running jobs' information` so we may provide this too for `sky spot queue`. (IIRC, the former was added for the same reason.)

User replied to this: "yeah I think -s would work"

**Comment by concretevitamin** [comment]
A related request from another user:

> seems like `sky spot queue -r` keeps showing the failed and cancelled jobs (unlike `sky status -r`). Is that intended? Could they be hidden by default unless providing some `-v` verbosifying flag or something?

**Comment by concretevitamin** [comment]
@mraheja can we adjust #1572 from implementing option 1 to option 2, above? The first user originally making this request also preferred option 1:

> yeah defaulting to only running would be preferable for me
