### ISSUE TITLE
[Test] spot smoke test failures due to controller INIT state

### ISSUE THREAD

**Issue by infwinston** [skypilot-org/skypilot#1484]
I've been encountering many smoke tests failures recently but not because bugs in the code. Many are related to failures of getting the latest spot status due to controller state to be `INIT`. This is likely due to other ongoing `spot launch` which modified the controller state.

```
Fetching managed spot job statuses...
D 12-02 00:23:55 backend_utils.py:1732] Refreshing status: Failed get the lock for cluster 'sky-spot-controller-4da3f903'. Using the cached status.
Spot controller sky-spot-controller-4da3f903 is INIT.
Please wait for the controller to be ready.
....
Failed
``` 

I think we should treat this as a smoke test bug? or is it just me having this issue?
To fix it we may need to make `spot queue` more robust.

**Comment by infwinston** [comment]
Ah okay I think another issue I hit is I'm testing with a much smaller spot controller (2 CPUs). When all the spot smoke test submitted, some of them will be pending, which triggered failures in smoke tests.
It's not obvious how many spot tasks will be run concurrently to users. we may want to add some warning messages.

**Comment by Michaelvll** [comment]
This has been mitigated by adding the waiting in `sky spot queue` and `sky spot cancel` in the smoke tests. It should be ok to close now.
