### ISSUE TITLE
[Storage] Workdir sync to S3 is too slow (not respecting `.gitignore`; syncing a giant `.git` dir)

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#1485]
User reported workdir sync to s3 (used by managed spot, `sky spot launch`) is too slow:
- not respecting .gitignore
- syncing a giant .git dir

This caused the user to use GitHub cloning/pushing as an alternative and abandon using the workdir feature.

---

Quotes:
> Is there a way to ignore the .git folder itself when syncing code via workdir? Reason is that it’s too large. Actually I suspect the main slowness is not size, but that there are many files in .git. ... Would it make sense to upload a zipped file instead of syncing file-by-file?

> It also seems that the sync to s3 is not respecting .gitignore. for now I think I will have to bypass the workdir feature and sync code some other way since it’s too slow to upload to s3 for me

> (network bandwidth is not the issue; it’s the number of files needed to sync, & aws s3 sync is much less efficient than rsync)

We suggested using mounted storage and user said: 
> I think I’ll just git clone for now

**Comment by romilbhardwaj** [comment]
Sky storage does not respect `.gitignore` currently. This is not desired behavior. 

The underlying tools (`aws s3 sync` and `gsutil rsync`) don't [natively](https://github.com/aws/aws-cli/issues/3520) [support](https://stackoverflow.com/questions/22703210/how-to-do-gsutil-cp-r-while-ignoring-files-like-git-gitignore) using `.gitignore` files. We'll likely have to parse the .gitignore file and convert them into `--exclude` and `-x` flags.

**Comment by romilbhardwaj** [comment]
This is partially alleviated with #1494 - which excludes `.git` directory. However, we should look into how/if we can support `.gitignore` files when uploading to sky storage. Leaving the issue open.

**Comment by landscapepainter** [comment]
This is a duplicate issue of #1898 and will be resolved with #1939
