### ISSUE TITLE
[Spot] Make non-terminal spot job status more clear when the table is from the cache

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#1486]
It can be confusing to see the job in non-terminal status when the `sky spot queue` returns the cached table. From our user:
> Also the user experience of
```
Spot controller sky-spot-controller-39f73709 is STOPPED.
To view the latest job table: sky spot queue --refresh

Cached job status table [last updated: 20 hrs ago]:
```
> is a bit confusing, especially when I have many historical spot jobs in the queue. It’s not always immediately clear whether it’s displaying historical status or latest and I have to explicitly look for this earlier small blob of text.
Maybe make it appear to the bottom of the content rather than to the top (or both) would help..

We can replace the non-terminal spot job status with `NEED REFRESH` to avoid confusion.

**Comment by infwinston** [comment]
Thinking would it be better if we sync all the states to S3 bucket?
So even if the controller is stopped we can still get the up-to-date job status table. And the response time will be a lot faster?

**Comment by Michaelvll** [comment]
That is a good point. We can save the cache file to s3 bucket when the spot controller is going to auto-stop.

**Comment by Michaelvll** [comment]
We have now removed the spot queue cache. This issue is not relevant any more. Closing
