### ISSUE TITLE
[Installation] Can't install SkyPilot on Mac M1

### ISSUE THREAD

**Issue by infwinston** [skypilot-org/skypilot#1491]
A user in slack channel reported some installation error on Mac M1. Can someone with Mac M1 see if it's reproducible? @WoosukKwon 

> Installation error for apple silicon:
Having an issue to get sky work on macos m1, with installing pycryptodome.
Looks like there is no support for M1 pycryptodome.
Anyone here had same issue or know the fix?

**Comment by gmittal** [comment]
`pip install skypilot` worked in a fresh conda environment with python3.9 on my M1.

**Comment by concretevitamin** [comment]
Works on my M1.

Closing for now, let's see if there are new details.
