### ISSUE TITLE
[Failover] The stopped cluster will be removed from the cluster table if failed to restart

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#1496]
There is a leakage of the STOPPED cluster if the user tries to `sky start` the cluster and failed due to no resources.

Reproducible snippets:
1. Run the following commands
```
sky launch -c test-ap --cloud --region ap-east-1 -y
sky stop test-ap
```
2. Remove the ap-east-1 region from the `aws/vms.csv`
3. `sky start test-ap`, the restart fails as expected, but the cluster is removed from the table as well. which causes the leakage of the stopped resources.

Reason: https://github.com/skypilot-org/skypilot/blob/655267b005a22173750dacd588d2249397bec060/sky/backends/cloud_vm_ray_backend.py#L1922-L1923

**Comment by concretevitamin** [comment]
Nice repro! Does this help solve #627 too?

**Comment by Michaelvll** [comment]
> Does this help solve https://github.com/skypilot-org/skypilot/issues/627 too?

I don't think the two problems are correlated, as changing the catalog will only modify the ray YAML generated by us but not the availability of the resources. We did know that changing the list of AZs in the ray YAML would cause a new instance to be launched.
