### ISSUE TITLE
[Onprem] `check_network_connection` will error for internal networks 

### ISSUE THREAD

**Issue by michaelzhiluo** [skypilot-org/skypilot#1529]
For VPCs/internal networks, accessing the `TEST_IP` to check for internet connectivity will error out here: https://github.com/skypilot-org/skypilot/blob/master/sky/backends/backend_utils.py#L1405:L1415

We should log and warn the user instead of raising an error.

**Comment by Michaelvll** [comment]
> We should log and warn the user instead of raising an error.

I don't think we should change the behavior to log and warn, as that will cause hanging problem and the spot controller relies on the network check. Could we only bypass the network check for on-prem case in the following place?
https://github.com/skypilot-org/skypilot/blob/e9b378e63296e0a545bc83e6f54e05e4a0afd765/sky/backends/backend_utils.py#L1187

@concretevitamin Can this be a potential issue with private VPC in #1512?

**Comment by concretevitamin** [comment]
> @concretevitamin Can this be a potential issue with private VPC in #1512?

Nope. Its intended use is for private VPCs that have outbound Internet access.

**Comment by michaelzhiluo** [comment]
@Michaelvll Correct me if I'm wrong, the reason why `check_network_connection` was added was b/c of CalVisistor and one couldn't ssh into the cluster. Wouldn't this also be the case for Sky onprem? (ssh into my local Slurm cluster)
