### ISSUE TITLE
[Core] `sky status` takes 10(s) to complete

### ISSUE THREAD

**Issue by michaelzhiluo** [skypilot-org/skypilot#1534]
When I run `sky status` on laptop (without refresh), `sky status` will hang for ten seconds and then output the logs:
```
(ray) michaelluo@MacBook-Pro-7 skypilot % time sky status
Clusters
NAME                         LAUNCHED     RESOURCES            STATUS  AUTOSTOP  COMMAND                       
test-back-compat-michaelluo  57 mins ago  1x AWS(m6i.2xlarge)  UP      -         sky launch -d -c test-bac...  
onprem-cluster-c8c3e7        1 hr ago     1x AWS(m6i.2xlarge)  UP      -         examples/local/launch_clo...  
hello                        1 day ago    2x AWS(m6i.2xlarge)  UP      -         sky launch -c hello --num...  

Local clusters:
NAME              USER  HEAD_IP       RESOURCES    COMMAND                        
asdf              test  54.90.178.58  [(no GPUs)]  sky launch -c asdf -- echo...  
my-local-cluster  -     -             -            -
sky status  12.48s user 2.80s system 66% cpu 22.943 total
```

**Comment by Michaelvll** [comment]
Does the problem still occur after you run `sky status -r` with the latest master? @iojw recently behavior of the IP cache in the `ResourceHandle`, so that we need a `sky status -r` to update the IP cached in the cluster table.

**Comment by michaelzhiluo** [comment]
Yes, it does indeed look like `sky status -r` fixes it on my end. Do others also observe that the same fix works for them too?

**Comment by Michaelvll** [comment]
> Yes, it does indeed look like `sky status -r` fixes it on my end. Do others also observe that the same fix works for them too?

Thanks for confirming it @michaelzhiluo ! Yes, that is as expected, and `sky status -r` fixed the issue for the users facing the problem as well. Closing this issue for now. Please feel free to reopen it if the problem happens again. : )
