### ISSUE TITLE
[Feature Request] Port forward for `sky launch`

### ISSUE THREAD

**Issue by michaelzhiluo** [skypilot-org/skypilot#1546]
This might be an important feature needed to enable model serving. Reasons being,
1) There is no documentation on what ports are "open" for `sky launch`'ed VMs.
2) User might need a very specific port.
3) Reach feature parity with `sky cpu/gpu/tpunode` which as `--port-forward`

**Comment by romilbhardwaj** [comment]
Thanks for creating the issue @michaelzhiluo! I'll post this as a comment in #1255 so we can track all related requests in one issue.
