### ISSUE TITLE
[Onprem] Job launching failed with NotImplementedError in clouds/cloud.py

### ISSUE THREAD

**Issue by qzweng** [skypilot-org/skypilot#1580]
Hi, thanks for the great project!

I tried to deploy an on-prem sky cluster, used the current master([aa7bab7](https://github.com/skypilot-org/skypilot/commit/aa7bab7)) plus [fix_local_check](https://github.com/skypilot-org/skypilot/compare/fix_local_check), and succeeded in the cluster setup where both `ray status` and `sky status` works (no GPU shown https://github.com/skypilot-org/skypilot/issues/1423).

However, it raises a NotImplementedError in [#L83 cloud.py](https://github.com/skypilot-org/skypilot/blob/master/sky/clouds/cloud.py#L83) when I submit a job with `sky launch -c cluster -- ''`.

Have I chosen the wrong branch for on-prem deployment? Could you suggest a branch where we can get familiar with `sky` in a local cluster or homelab? Thank you!

**Comment by michaelzhiluo** [comment]
Hi @qzweng, thanks for submitting this Git issue. We just merged https://github.com/skypilot-org/skypilot/pull/1582, which addresses the bug you found 🐛 .  

Feel free to use the current master + `fix_local_check`. (`fix_local_check` will be merged within this week) and Sky onprem should work out for you!
