### ISSUE TITLE
[UX] Add timeout to (Y/n) prompts

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#1581]
I find myself running `sky launch` and alt-tabbing to do other stuff while it initializes. Sometimes I forget the `-y` flag and come back some time later only to find it's waiting for my input `Launching a new cluster 'myclus'. Proceed? [Y/n]: `.

Can we put a timeout to select the default Y if there is no input from the user (say, 30s?)

**Comment by Manishpandey11** [comment]
Hi,
I want to work on this issue. Can you please assign it to me

**Comment by romilbhardwaj** [comment]
Hi @Manishpandey11 - please feel free to submit a PR. Key things we would need are
1. A configurable time delay on (Y/n) prompts
2. A countdown shown to the user showing the time before it automatically proceeds

**Comment by romilbhardwaj** [comment]
Hi @Manishpandey11 - after some discussion, we have decided to not support this for now. Removing assignments and closing this issue for now.
