### ISSUE TITLE
Does sky workdir sync implicitly skip "data" directory?

### ISSUE THREAD

**Issue by franklsf95** [skypilot-org/skypilot#1599]
It seems `sky launch` or `sky exec` does not sync the `data` subdirectory in my workdir. Renaming it to `data1` caused it to sync. Is this expected? If so, can you prompt the user when this happens?

**Comment by infwinston** [comment]
workdir syncing excludes files/dirs in `.gitignore`. Any chance that `data` is listed in your `.gitignore`?

**Comment by Michaelvll** [comment]
Closing the issue for now as the solution is proposed. Please feel free to re-open it if that does not solve the issue.
