### ISSUE TITLE
Syncing .git is really slow - What is the best practice?

### ISSUE THREAD

**Issue by franklsf95** [skypilot-org/skypilot#1600]
Syncing up my workdir to the cloud machine is super slow on the first time (>15min). Most of the time is spent rsyncing .git, which includes a huge amount of tiny files. But I recall this is still preferred over `git clone` my repository on the cloud VM, because this allows `sky exec` to easily sync up my changes.

What's the best practice here? Is there any downside if we skip syncing the `.git` directory? (Might also be worthwhile to prompt the user if the cwd has, say, >10000 files, and thus may take long to sync)

**Comment by infwinston** [comment]
You may list `.git/` in your `.gitignore` which would be respected by `sky exec` to not upload those files and dirs.

**Comment by Michaelvll** [comment]
Closing this issue for now, as the solution is proposed. Please feel free to re-open it if that does not solve the problem.
