### ISSUE TITLE
[Feature Request] can sky logs only print the last part of the logs?

### ISSUE THREAD

**Issue by infwinston** [skypilot-org/skypilot#1606]
User asked: Can `sky logs` support outputting only the last few lines? like `tail -n`. Their program can generate hundreds of thousands of lines of output and they are only interested in the very last part.

**Comment by Michaelvll** [comment]
`sky logs <cluster-name> <job-id> | less` or `sky logs <cluster-name> <job-id> | tail -n 100` should work. Maybe we can add them to the docs.

**Comment by Michaelvll** [comment]
Similar to tail and docker logs, we may want to add `-n` option to the sky logs CLI. The main reason is that when the user logs are very long, and the job is still running, the sky logs will take a long time to reach the latest line.
