### ISSUE TITLE
Upgrade default CPU instance types

### ISSUE THREAD

**Issue by WoosukKwon** [skypilot-org/skypilot#1612]
Currently, the SkyPilot's default instance types for the three clouds are:

| Cloud | Instance Type  | vCPUs | Memory (GiB) | Price ($/hr) |
|-------|----------------|-------|--------------|--------------|
| AWS   | m6i.2xlarge    | 8     | 32           | 0.38         |
| Azure | Standard_D8_v4 | 8     | 32           | 0.38         |
| GCP   | n1-highmem-8   | 8     | 52           | 0.47         |

Why don't we upgrade the default instances as follows?

| Cloud | Instance Type  | vCPUs | Memory (GiB) | Price ($/hr) |
|-------|----------------|-------|--------------|--------------|
| AWS   | m6i.2xlarge    | 8     | 32           | 0.38         |
| Azure | Standard_D8_v5 | 8     | 32           | 0.38         |
| GCP   | n2-standard-8  | 8     | 32           | 0.39         |

That is, 
* (Azure) Upgrade Dv4 to Dv5 
* (GCP) Upgrade N1 to N2
* (GCP) Change highmem to standard

**Comment by Michaelvll** [comment]
Great findings! Upgrading those makes sense to me. For the GCP, here are several things we may need to be careful with:
1. The GPUs can only be attached to `n1` family, which means if we use `n2` for the CPU instance, we will have to switch to `n1` (some inconsistency but might be ok).
2. We may be careful that `n1-standard` only have `30GB` memory

**Comment by WoosukKwon** [comment]
Thanks!

> 1. The GPUs can only be attached to n1 family, which means if we use n2 for the CPU instance, we will have to switch to n1 (some inconsistency but might be ok).

Good point. I feel it's ok.

> 2. We need to be careful that n1-standard-8 only has 30GB memory

I think this is fine if we switch to N2, as n2-standard-8 has 32GB memory. And perhaps this change will help reduce the cost for those who will run spot controllers in GCP.
