### ISSUE TITLE
[catalog] Automatically update Azure catalog

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#1628]
Similar as AWS, we may want to set the GCP/Azure catalog to be automatically downloading from the catalog repo, so that any updates can be reflected in the user's local catalog. (https://github.com/skypilot-org/skypilot-catalog/pull/12#issuecomment-1401357683)

**Comment by concretevitamin** [comment]
We should do this. +Lambda too.

**Comment by Michaelvll** [comment]
This has been fixed for GCP, but we still need it for Azure

**Comment by Michaelvll** [comment]
A user requested the auto update for Azure catalog.
We should figure out what the minimal permissions required for fetching Azure catalog for the instruction listed here: https://skypilot.readthedocs.io/en/latest/reference/faq.html#advanced-how-to-make-skypilot-use-all-global-regions, and add the github CI in https://github.com/skypilot-org/skypilot-catalog.
