### ISSUE TITLE
[Core] More robust backward compatibility when upgrading versions

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#1660]
From @dongreenberg:

> I’ve gotten in the habit that any time I need to upgrade skypilot I totally uninstall and delete my ~/.sky directory. For some reason I’ve always had trouble if I don’t - exceptions that raise because of some malformed data or API expecting different input or something. I’m not sure if you guys do this too but I found it to be necessary for every upgrade I’ve done so far 

This is related to pickling/unpickling failing when we change an object definition. We could use a less strict serialization, but that comes at the cost of code complexity (which might be ok).

**Comment by concretevitamin** [comment]
Related to #1605 - replacing pickle with another serde in all/most places.

**Comment by romilbhardwaj** [comment]
Ah then this is a duplicate - closing for now and moving user comments to #1605.
