### ISSUE TITLE
[CPU] `sky launch --cpus 2 -c existing-cluster` fails

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#1672]
It seems we block the `sky launch` with the CPUs specified on an existing cluster. That is inconsistent with other options, such as `--instance-type`. Is it intended @WoosukKwon?

**Comment by WoosukKwon** [comment]
Yes, I intentionally banned such a case  because `--cpus` does not work as a "scheduling constraint" (unlike `--gpus` and --nodes`). I tried to avoid ambiguity despite the inconsistency. Would you like to change this behavior?
