### ISSUE TITLE
Support auto selecting instance types via `memory` filter

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#1673]
User requested:

> I saw that Sky recently added support for specifying cpu resource constraints. Would it be possible to add memory resource constraints too? The use case is that I’m using dev instance to do some data analysis that requires a certain amount of memory to be available.

The user manually selected `r6i.metal` w/ 1TB memory, 128 vCPUs. The user did not see that `x2gd.metal` (Graviton) with 1TB mem, 64 vCPUs would be much cheaper. On this suggestion the user +1'd the auto selection by memory. (NOTE: we don't currently support it but will soon; but the point is there's complexity involved in selecting the best feasible instance type.) 

The user confirmed that the main motivation is not have to worry about learning which instance type to pick.

cc @WoosukKwon

**Comment by Michaelvll** [comment]
This is also requested by the LLM example, as the example requires to use larger memory instances, e.g. `n1-highmem-32` on GCP has the similar amount of RAM as `n1-standard-64` but 2x cheaper.
