### ISSUE TITLE
[UX] Container support for task

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#1681]
We have received multiple requests from our users for the native container support in the task yaml, so that they don't need to manually run the `docker pull` and `docker run` in the `setup` and `run` sections separately.

**Comment by Michaelvll** [comment]
A blocker for one of our potential user.

**Comment by iojw** [comment]
Does this mean they would like the `run` commands to be executed within the docker container as well?

**Comment by Michaelvll** [comment]
Yes, I suppose both setup and run sections will be run in the container, if that is posible.
