### ISSUE TITLE
[Core] `sky stop/start/down` cluster on a different GCP project

### ISSUE THREAD

**Issue by michaelzhiluo** [skypilot-org/skypilot#1689]
We have recently switched to a new GCP project. When downing or stopping a cluster that was on the old GCP project, the error shows: 
```
'wow' (GCP) is owned by account 'michael.luo@berkeley.edu\n [project_id=[REDACTED_OLD]]', but the activated account is 'michael.luo@berkeley.edu\n [project_id=[REDACTED_NEW]]'.
``` 

Should Skypilot be aware/agnostic of what project each cluster is in for GCP?

**Comment by Michaelvll** [comment]
This is intended because we cannot teardown a cluster that is in another project without the correct credentials. The user should do `gcloud init` again to switch to the credential, otherwise, there can be a resource leakage.

**Comment by concretevitamin** [comment]
Closing due to working as intended.
