### ISSUE TITLE
[CLI] Add `-n` option for `sky logs` 

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#1711]
Similar to `tail` and `docker logs`, we may want to add `-n` option to the `sky logs` CLI. The main reason is that when the user logs are very long and the job is still running, the `sky logs` will take a long time to reach the latest line.

**Comment by infwinston** [comment]
Related to this https://github.com/skypilot-org/skypilot/issues/1606?

**Comment by Michaelvll** [comment]
Good catch! Closing this for duplication.
