### ISSUE TITLE
GCP permissions: make `sky check` check permissions and fail early

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#1755]
We've heard recurring reports that several permission errors showed up during `sky launch` -> `setup_gcp_authentication` ->
* `setCommonInstanceMetadata?alt=json returned "Required 'iam.serviceAccounts.actAs' permission for <project>`
* `Required 'compute.projects.get' permission for <project>`
* ...add more...

We should make `sky check` check a growing list of minimum permissions and fail early.

**Comment by Michaelvll** [comment]
This seems to be a weird issue, as the user's account (owner of the project) does have permission. The problem was solved by `rm -r ~/.config/gcloud ~/.sky` and re-configure the credentials.

**Comment by infwinston** [comment]
Could it be possible that the user logged in to another GCP account which doesn't have access to the project? Did the user try `gcloud init`?
