### ISSUE TITLE
[TPU] Disable TPU node for TPU v4

### ISSUE THREAD

**Issue by infwinston** [skypilot-org/skypilot#1759]
TPU-v4 arch doesn't support TPU node ([ref](https://cloud.google.com/tpu/docs/v4-users-guide))
```
For Cloud TPU v4, only the TPU VM architecture is supported, so all TPUs referenced in this document use the TPU VM architecture.
```
We should disable it during resource checking.

**Comment by Michaelvll** [comment]
Another issue, we need to avoid the dependency on the `n1-highmem-8` when launching TPU pods. Currently, even if the user request for tpu v4 pod, we will still look for the that instance in the catalog, but not actually use it, which will cause a problem for `us-central2-b` as it only has TPUv4 in it (we temporarily solve it by adding the n1-highmem manually in the catalog for that region.
