### ISSUE TITLE
Make `show-gpus` show `DEVICE_MEMORY` 

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#1764]
When playing with an example where I was figuring out what types of GPUs would fit my model, I wanted to quickly look up a GPU's device memory. Currently `show-gpus` shows `HOST_MEMORY`, and it'd be great to show `DEVICE_MEMORY` as well. It should be about surfacing this info from the catalog CSVs.

**Comment by concretevitamin** [comment]
Still need to add DEVICE_MEMORY info to other clouds.

**Comment by infwinston** [comment]
@jc9123 is interested in looking into this issue!
