### ISSUE TITLE
Revamp SSH config implementation to fix issues like duplicates, overwriting, orphans

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#1765]
We've seen duplicates, overwriting, orphans, and issues like that in `~/.ssh/config` (e.g., #1763). @Michaelvll and I discussed some potential fixes and enhancements to revamp our SSH config impl:

- [ ] Attempt to fix ssh config problem by always using `Include` even for single-node clusters
  - may have some back compat issues to worry about

**Comment by concretevitamin** [comment]
We should do this.

**Comment by Vaibhav2001** [comment]
I just put out a PR (https://github.com/skypilot-org/skypilot/pull/2706) for this issue. Please have a look

**Comment by concretevitamin** [comment]
Should’ve been fixed by @Vaibhav2001 in #2706.
