### ISSUE TITLE
Consider making `sky spot logs` automatically restart the controller

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#1766]
From user, who was trying to run `sky spot logs --controller 2 >> my.log`:
> btw, I’m realizing that if i run sky spot logs --controller 2 while the spot controller is not UP then it just doesn’t print out anything (instead of re-starting the spot controller for me). This is inconvenient if instead of trying to see the logs I’m using this in a script, like trying to save the logs to a file, that will then silently not do anything. Would it make sense that any sky spot command automatically re-starts the spot controller if it’s not UP?

**Comment by Michaelvll** [comment]
This should be discussed, as the restating of the spot controller can cost non-negligible time, and ctrl-c during the period will cause the spot controller in INIT mode which may cause more confusion.

**Comment by concretevitamin** [comment]
We should at least fix  this part:

> I’m realizing that if i run sky spot logs --controller 2 while the spot controller is not UP then it just doesn’t print out anything

#1918.
