### ISSUE TITLE
Syncing user cluster state across multiple work machines

### ISSUE THREAD

**Issue by gmittal** [skypilot-org/skypilot#177]
(low priority) based on personal experience.

If a user moves laptops/machines/etc., there is no way for their state to transfer with them (sky status is now empty on the new machine) since we use a local sqlite db.

**Comment by tonxxd** [comment]
Related to https://github.com/skypilot-org/skypilot/issues/1138
Would be interesting to evaluate the option for an external SQL database instead of the local SQLite

**Comment by tonxxd** [comment]
Hi, any update on this?

**Comment by concretevitamin** [comment]
Hey @tonxxd, we haven't had the resources to look into this. The workaround remains sharing `~/.sky` and `~/.ssh` (technically, just `config`, `sky-key`, `sky-key.pub`) across machines.

**Comment by romilbhardwaj** [comment]
Just noting that if you have different $HOME paths on the machines (e.g., if you have different usernames), you may need to update the IdentityFile path in `~/.ssh/config` after you copy it to your destination machine. 

Here's a simple one-liner to do so :

```
OLDUSER='/Users/romilb' NEWUSER='/Users/newuser' sed -i '' "s|IdentityFile $OLDUSER/.ssh/sky-key|IdentityFile $NEWUSER/.ssh/sky-key|g" $NEWUSER/.ssh/config
```
