### ISSUE TITLE
Confusion on task/cluster name

### ISSUE THREAD

**Issue by infwinston** [skypilot-org/skypilot#1778]
In our YAML, the `name` refers to the task name rather than the cluster name, which causes some confusion to the user.
As we are mixing the concept of task/cluster into a single YAML, we might want to add documentation to explain the difference between task/cluster. cc @WoosukKwon

**Comment by concretevitamin** [comment]
@michaelzhiluo ran into this confusion as well. He initially specified the task name only, and was surprised to not see them in `sky status`.
