### ISSUE TITLE
Python interface for getting cluster metadata (e.g., IP)

### ISSUE THREAD

**Issue by infwinston** [skypilot-org/skypilot#1779]
User asked whether there's any python interface to get existing clusters' IPs.
Current workaround is 
```
sky.status("my-cluster")[0].status["handle"].__dict__["stable_internal_external_ips"][0][1] 
```
We may want to expose a cleaner interface for users and document this.

**Comment by romilbhardwaj** [comment]
I have run into this before when setting up [VMs for sky camp](https://github.com/romilbhardwaj/skycamp-infra/blob/main/get_ssh_creds.py#L18-L41). I did this:

```
def get_cluster(name):
    clusters = sky.global_user_state.get_clusters()
    for cluster in clusters:
        if cluster['name'] == name:
            return cluster
    raise Exception(f'Cluster {name} not found')

cluster_name='myclus'
print(f'Getting SkyPilot cluster handle...')
handle = get_cluster(cluster_name)['handle']

print(f'Getting IPs for cluster {cluster_name}...')
ip_list = backend_utils.get_node_ips(handle.cluster_yaml,
                                     handle.launched_nodes, handle)
```

Maybe there's a cleaner way to expose this..

**Comment by cblmemo** [comment]
With #2210 this seems very important now. I'm thinking maybe we could store it inside `ResourceHandle`/`Resources` and print it in `sky status -a`?

**Comment by cblmemo** [comment]
BTW, another workaround I adopted is `grep -A1 "<cluster-name>" ~/.ssh/config | grep "HostName" | awk '{print $2}'`
