### ISSUE TITLE
AWS SSO: Make expired-then-renewed SSO identity work

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#1794]
From a user report:

* Use an SSO identity to create a cluster
* After a while, presumably SSO expired and relogged in
* The same cluster now encountered ClusterOwnerIdentityMismatchError
* The IDs look like
  * A<....>6JC6:myname@co.com
  * A<....>OMMU:myname@co.com

The above is a hypothesis of what happened.

**Comment by Michaelvll** [comment]
A TODO item: save the arn of the userid to make it easier to debug.

**Comment by Michaelvll** [comment]
Based on the discussion with the user, the identity change happens when the user run their own terraform script that controls the user permission, and may re-create the users. It is not related the SSO expiration and renew. Closing this for now, as the blocker has been solved by #1808
