### ISSUE TITLE
Plans to add Coreweave

### ISSUE THREAD

**Issue by lminer** [skypilot-org/skypilot#1822]
Do you have any plans to add Coreweave at some point in time? Their A100 rates aren't especially cheap, but still half the price of the major cloud providers, and V100s are pretty affordable. Might be a nice fallback...

**Comment by concretevitamin** [comment]
We'd love to! If the community has bandwidth to look into it, the recent [Lambda Cloud PR](https://github.com/skypilot-org/skypilot/pull/1557) is a good starting point.

If you're looking for cheaper GPUs, is using Lambda through SkyPilot an option?

**Comment by concretevitamin** [comment]
I'd encourage you to give it another try since SkyPilot helps find availability by: (1) automatically looping through all regions, in cheapest price order; (2) providing a `--retry-until-up` flag to automatically retry for users.

**Comment by hemildesai** [comment]
I am happy to help with this. One interesting caveat about Coreweave is that its Kubernetes native i.e. even its virtual servers run on top of Kubernetes (ref: https://docs.coreweave.com/virtual-servers/getting-started). Given this, there are two ways to go about this:
- Use Python K8s client to launch virtual servers on Coreweave and use the CloudVMRayBackend as used by the other clouds
- Implement a K8s native backend and make the Coreweave provider use the K8s backend.

Any thoughts?

**Comment by romilbhardwaj** [comment]
@hemildesai - that's great! Would love to see coreweave support. 

We have k8s support coming soon, which is similar in approach to your first bullet point - https://github.com/skypilot-org/skypilot/pull/2096

Please feel free to base your code off the `k8s_cloud` branch. There's still a lot of work to be done there, and we'll be happy to have any help. 

It'll be great to chat - if it's not too much trouble, can you join our [slack](http://slack.skypilot.co/)?

**Comment by hemildesai** [comment]
@romilbhardwaj Thanks for the prompt reply. Happy to use the k8s branch as base and build on top of it. I've joined the SkyPilot slack and I'll send you a message.
