### ISSUE TITLE
[AWS SSO] New UserId with every sky call

### ISSUE THREAD

**Issue by amitysa** [skypilot-org/skypilot#1840]
After I've logged into AWS with SSO, I can see a UserId  in the format `AXXXXXXXXXXXXXX:botocore-session-<TIMESTAMP>` when I get the identity with `aws sts get-caller-identity`

However, sky commands seem to create a new AWS session with every call. This leads to errors like `'sky-abcd' (AWS) is owned by account 'AXXXXXXXXXXXXXX:botocore-session-TIMESTAMP1', but the activated account is 'AXXXXXXXXXXXXXX:botocore-session-TIMESTAMP2'`.

Any idea on how to resolve this?

**Comment by concretevitamin** [comment]
Hey @amitysa - @Michaelvll has a recent commit in the main branch https://github.com/skypilot-org/skypilot/commit/c7d6d1d501864323324944ba2773bc7581007a51 that should've fixed this.

Would you mind installing from source and see if this fixes your issue?
```bash
pip install git+https://github.com/skypilot-org/skypilot.git
```

**Comment by amitysa** [comment]
Thanks @concretevitamin Installing from source fixes this with a warning (I assume because of the fallback account ID) 👍

**Comment by concretevitamin** [comment]
Glad it works. Let us know if you think that warning should be removed.
