### ISSUE TITLE
Custom Containers

### ISSUE THREAD

**Issue by jonathanasdf** [skypilot-org/skypilot#1847]
Is it possible to run with custom docker container images?

**Comment by romilbhardwaj** [comment]
Hi @jonathanasdf - it is possible to run custom docker images as SkyPilot tasks. You can pull/build the image in `setup`, and use `docker run` in the `run` section. 

Here's a minimal example to pull an image and run it as a task:

```
setup: |
  docker pull hello-world

run: |
  docker run hello-world
```

Here's another [example](https://github.com/skypilot-org/skypilot/blob/master/examples/docker/echo_app.yaml), which builds the image locally before running it. Hope this helps!
