### ISSUE TITLE
Make network check more reliable (1.1.1.1 could've been occupied)

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#1849]
User reported that after #1800, their `status -r` failed due to their network setup occupying 1.1.1.1 (Cloudflare) for some reason. They could ping 8.8.8.8 (in the US).

```
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='1.1.1.1', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))
```

Our choices:
- Get rid of this network check from the critical path of `status -r`
- If the above is not feasible, perhaps do both IP checks w/ fallback.

**Comment by ewzeng** [comment]
That's weird. I'm confused how they were able to `sky launch` successfully since getting the node ips requires this network check.

**Comment by concretevitamin** [comment]
It may be that
- launch things prior to upgrading past #1800 
- upgrade past
- run `status -r`

**Comment by ewzeng** [comment]
Oh okay, that makes sense.

**Comment by ewzeng** [comment]
Do we just want `status -r` to get around this check, or do we want `sky launch` and the others to also work?
