### ISSUE TITLE
UX: when launching, print currently in-effect config.yaml

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#1860]
Got tripped up because my config.yaml has private VPC/jump server setting that I forgot about. The launch didn't go through, timing out only after 10+ minutes.

**Comment by Michaelvll** [comment]
Also, can we do a pre-check to see if the `proxycommand` is correct, i.e. if the jump server can be connected, before we start launching the cluster?

**Comment by concretevitamin** [comment]
One problem is `ssh_proxy_command` itself is not necessarily a well-formed SSH command:
```
ssh_proxy_command: ssh -W %h:%p -i ~/.ssh/sky-key -o StrictHostKeyChecking=no ec2-user@1.2.3.4
```
Directly running the above will lead to
```
Bad stdio forwarding specification '%h:%p'
```
We could try to match `<usr>@<ip>`, but in general users may pass in something like `./my_proxy.sh`. I think we can add some printing of currently in-use VPC/SSH settings first, and defer the best-effort jump server ping for later?
