### ISSUE TITLE
[Docs] Docs on container support

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#1863]
SkyPilot supports running containerized workloads, but our docs don't make this clear. Talking points to include:
* How to run containers in SkyPilot
* How to build/pull before running container
* How to write outputs to Storage
* More

**Comment by Michaelvll** [comment]
Although there is a workaround to run containerized workloads in SkyPilot. There is still an issue with canceling the workloads. For example, if the workload was started with `docker run`, our `sky cancel` tries to kill the job by killing the monitor process and all its children processes (in normal cases, the user programs will be run as processes under that monitor process). However, for the `docker run`, the process can be moved to under the main docker process (all the docker container will be run there), which will cause the workload to fail to be killed by our current `sky cancel`.

@cblmemo is now looking at the native docker support in SkyPilot, i.e. run everything, including our ray cluster, in the container. : )

**Comment by romilbhardwaj** [comment]
Closed by #2082.
