### ISSUE TITLE
[R2] `sky check` does not list R2

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#1878]
`sky check` does not check if R2 is setup.  Additionally, [Installation docs](https://skypilot.readthedocs.io/en/latest/getting-started/installation.html) indicates cloudflare R2 as cloud that will be reported by `sky check`. We should add R2 in `sky check`.

**Comment by Michaelvll** [comment]
Related to #1943

**Comment by landscapepainter** [comment]
resolved #1886
