### ISSUE TITLE
Hardcodes to x86_64 miniconda binaries when AWS c7g ARM images are selected

### ISSUE THREAD

**Issue by nth10sd** [skypilot-org/skypilot#1884]
https://github.com/skypilot-org/skypilot/blob/979111d116cd6a01f3c12122ee67203fcde1a5e8/sky/templates/aws-ray.yml.j2#L144

`Miniconda3-latest-Linux-x86_64.sh` should probably be `Miniconda3-latest-Linux-aarch64.sh` for ARM images.

**Comment by concretevitamin** [comment]
cc @WoosukKwon
