### ISSUE TITLE
An older ray version (2.0.1) that does not have a Linux aarch64 wheel should probably be updated (2.2.0+)

### ISSUE THREAD

**Issue by nth10sd** [skypilot-org/skypilot#1885]
https://github.com/skypilot-org/skypilot/blob/979111d116cd6a01f3c12122ee67203fcde1a5e8/sky/skylet/constants.py#L5

is hardcoded to ray 2.0.1. However, the `aarch64` wheels for ray are only available for Linux `aarch64` from 2.2.0 onwards, see:

https://pypi.org/project/ray/2.1.0/#files
https://pypi.org/project/ray/2.2.0/#files

The following reference should probably be updated as well:

https://github.com/skypilot-org/skypilot/blob/1f7a5cd46dadc838889fcada412757e73530a22d/docs/source/reference/local/setup.rst

**Comment by romilbhardwaj** [comment]
Hi @nth10sd, welcome to the SkyPilot community!

#1734 implements support for Ray 2.3.0. Are you trying to use ARM instances with skypilot? We'd love to hear your use case and accelerate merging #1734 if required.

**Comment by nth10sd** [comment]
Hi @romilbhardwaj ! Thank you for the welcome.

Oh, interesting, I need to take a look at the code branch for #1734.

Yes, I am exploring SkyPilot as an alternative to the now-archived/deprecated [laniakea](https://github.com/MozillaSecurity/laniakea) project, and ARM64 instances are more economical than Intel/AMD ones, at least on AWS EC2 as a start.

It's just to spawn an instance with some simple scripts in userdata as a start, via the CLI, nothing special about my use case (and nothing ML-related).

> accelerate merging #1734 if required.

This will be very much appreciated! FWIW, I was able to spin up (and shut down) an ARM64 instance with SkyPilot 0.2.5, just that the autorun userdata stuff wasn't yet working.
