### ISSUE TITLE
Can we provide a parameter to override default Instance roles and IAMs

### ISSUE THREAD

**Issue by nischintu** [skypilot-org/skypilot#1896]
In  sky/skylet/providers/aws/config.py, the default IAM and INSTANCE roles are set to "ray-autoscaler-v1" or "skypilot-v1". Sometimes in corporate managed AWS infra, the IAMs and INSTANCE roles are limited. It will be great if we can override the default strings using user provided names in the config.yaml file.

**Comment by concretevitamin** [comment]
@nischintu Thanks for raising this. Is supporting bring-your-own-roles a blocker for your org? We'd love to accept a PR for this. As you mentioned it could be reading from `~/.sky/config.yaml` in some basic syntax:
```
aws:
  # already supported fields: vpc_name, ssh_proxy_command, use_internal_ips
  role: ...
```
