### ISSUE TITLE
[Storage] sky storage ls fails to sync with externally deleted storage

### ISSUE THREAD

**Issue by landscapepainter** [skypilot-org/skypilot#1904]
When a storage gets created through `sky`, it appears in the storage list when `sky storage ls` is ran. However, `sky storage ls` will show the externally deleted storage as well. It is necessary to sync with the externally deleted object before showing the storage list.

**Comment by romilbhardwaj** [comment]
Duplicate of #1313?

**Comment by landscapepainter** [comment]
closing due

**Comment by landscapepainter** [comment]
Closing as the issue is duplicate of #1313
