### ISSUE TITLE
[Feature Request] Upload Github credentials for Skypilot

### ISSUE THREAD

**Issue by michaelzhiluo** [skypilot-org/skypilot#1911]
An important usecase in Skypilot is to `git clone` a private repo. This is difficult to do so in Sky YAML file because you will have to specify the access keys. If Skypilot can automatically filemount or send over Github credentials, this would make developing over a private codebase much easier.

**Comment by Michaelvll** [comment]
This should still be relevant for people using private github repo. @infwinston mentioned about this recently as well.
