### ISSUE TITLE
How often do releases happen? (Should I install from Github?)

### ISSUE THREAD

**Issue by Taytay** [skypilot-org/skypilot#1920]
I saw that the readme mentioned some new features committed in April, but the most recent Github and PyPi release was in March. 

Is it recommended to `pip installing` from Github source as a rule, or is that basically like installing "nightly"/"canary"?

**Comment by concretevitamin** [comment]
Hey @Taytay: We have not established the cadence for releases yet, which we hope to do in the near future. 

In the meantime, if there's any functionality in the main branch you need, then yes, we do recommend installing from source and treating it as a nightly. We try to have rigorous testing for all pull requests to have some insurance on bug-freeness.
