### ISSUE TITLE
Can't create S3 storage

### ISSUE THREAD

**Issue by Taytay** [skypilot-org/skypilot#1921]
I'm using SSO to log into an account that has poweruser permissions. I've confirmed I can create an S3 bucket in the console with said user. However, I get an "AccessDenied" error when running `sky spot launch --gpus "A100:8" -n fine-tune-pythia70 fine_tune.yaml`

Note that other launch actions do work.

```
I 05-01 23:44:52 execution.py:707] Translating file_mounts with local source paths to SkyPilot Storage...
I 05-01 23:44:52 execution.py:733] Workdir '..' will be synced to cloud storage 'skypilot-workdir-taytay-a65474ba'.
I 05-01 23:44:52 execution.py:805] Uploading sources to cloud storage. See: sky storage ls
E 05-01 23:44:53 storage.py:704] Could not create StoreType.S3 store with name skypilot-workdir-taytay-a65474ba.
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the CreateBucket operation: Access Denied

The above exception was the direct cause of the following exception:

sky.exceptions.StorageBucketCreateError: Attempted to create a bucket skypilot-workdir-taytay-a65474ba but failed.

During handling of the above exception, another exception occurred:

ValueError: Storage skypilot-workdir-taytay-a65474ba not found.
```

**Comment by Taytay** [comment]
It does indeed. I wonder if it's trying to create this bucket in a region I don't have access to or something odd?
Is it possible to see the full log of what sky is doing with AWS boto? is there a verbose mode?

**Comment by concretevitamin** [comment]
The exception is raised from: 

https://github.com/skypilot-org/skypilot/blob/1be6d227a8e8b35de89a96589ef779acaad2fae9/sky/data/storage.py#L1176-L1201

The `{'LocationConstraint': region}` stuff there looks suspect. Would you mind trying to step through that function and see what's up?

**Comment by Taytay** [comment]
Turns out that I had some extra Control Tower settings that were preventing this account from provisioning resources outside of us-east-1. For some reason it wanted to provision the s3 bucket in us-east-2: `Created S3 bucket skypilot-workdir-taytay-c2e36f18 in us-east-2`

Now that I got rid of the Control Tower limitation, it works
