### ISSUE TITLE
Can I specify a new instance type when restarting a cluster?

### ISSUE THREAD

**Issue by Taytay** [skypilot-org/skypilot#1928]
I am trying to run `sky start my_cluster_name`, but unfortunately, there aren't enough resources in my target region.

`botocore.exceptions.ClientError: An error occurred (InsufficientInstanceCapacity) when calling the StartInstances operation (reached max retries: 5): Insufficient capacity.`

But the main reason I want to re-launch this is to get access to the  data on the instance EBS drive. So I really don't care what instance type it uses. Is it possible to specify a new set of resources when running `sky start` or some other hacky way to do it?

**Comment by Taytay** [comment]
Update on this: I just changed it via the AWS console and it worked fine.

**Comment by Michaelvll** [comment]
Thanks for the question @Taytay! Currently, we don't support changing the instance type for an existing cluster. It seems the problem could be solved if SkyPilot could provide a way to reuse the EBS to launch another cluster. We will try to look into it. : )

**Comment by concretevitamin** [comment]
Previous instance type changes / resize discussion: #137

> But the main reason I want to re-launch this is to get access to the data on the instance EBS drive. So I really don't care what instance type it uses. Is it possible to specify a new set of resources when running sky start or some other hacky way to do it?

This seems a good new reason for this feature :)

**Comment by Michaelvll** [comment]
We now support cloning a cluster to another instance type with `sky launch --clone-disk-from <existing-cluster> --instance-type <new-instance-type> -c new-cluster-name`.
The requested feature can be achieved with the command above. Please let us know if that works for you @Taytay : )
