### ISSUE TITLE
[Windows] os.devnull with os.path.expanduser will return '', and Windows does not accept TextIOWrapper for socket

### ISSUE THREAD

**Issue by aria1th** [skypilot-org/skypilot#1950]
os.path.expanduser behavior in linux and windows is different. 

expanduser is used in [command_runner](https://github.com/skypilot-org/skypilot/blob/2d899a95965c1fb3c4a3605645075b8390632809/sky/utils/command_runner.py#L193) and log_lib.

This can be simply solved by fallback
```py
        if log_dir == '':
            log_dir = str(pathlib.Path.home())
```

But another problem arrives , windows does not accept TextIOWrapper usage in place of sockets.

https://github.com/skypilot-org/skypilot/blob/master/sky/skylet/log_lib.py#L45

Here we defined TextIOWrapper for out io.

But Windows will throw WinError10038, because selector only accepts sockets.

...Still this can be solved by just giving up listening to socket (or we have to set up virtual socket that actually listens it)

```py
    if sys.platform != 'win32':
        sel.register(out_io, selectors.EVENT_READ)
```

and same for error io.

**Comment by concretevitamin** [comment]
@aria1th thanks for reporting this! If the suggested fixes now make SkyPilot work on Windows, would you like to submit a PR?

**Comment by aria1th** [comment]
Sure!
