### ISSUE TITLE
Sky launch failed due to worker launching time exceeds the timeout (_NODES_LAUNCHING_PROGRESS_TIMEOUT)

### ISSUE THREAD

**Issue by HysunHe** [skypilot-org/skypilot#1961]
The timeout mechanism is mainly to limit the retry times when a cluster cannot be launched due to e.g. quota capacity. However, the launch time may be varied largely from instance shapes with different configurations, the launch time might be from dozens of seconds to serveral minutes.

We can specify a general value which can satisfy **most** of provisioning cases and have the **acceptable** retry times when worker launch failed. However, it is hard to let the timeout value meet all the provisioning cases at the same time with small retry times. 

For example the following case:

Launch and 2 nodes cluster for HPC computing (Bare Metal machine with A100 * 8):

1. head ready,  go launching worker node (last_nodes_so_far=1)
2. Reset start time, as new (worker) is launched
3. nodes_so_far(2) = ready head (1) + pending worker (1)  (ready worker=0)
4. last_nodes_so_far = nodes_so_far (last_nodes_so_far=nodes_so_far=2, pending worker=1, ready worker=0)
5. wait 10 seconds  (time.sleep(10))
6. nodes_so_far=2, last_nodes_so_far=2, pending worker=1, ready_worker=0, continue wait 10 seconds...
7. save as above step, continue wait ...
8. Wait time reaches the timeout value, but ready_worker=0, pending worker=1 (worker is still in waiting-for-ssh or setting-up)
9. ready_head (1) + ready_workers (0) <> num_nodes AND timeout exceeds, so call the worker_status.stop() ... return False
10. Launch failed.

So far the timeout value is not configurable. So recommend we can have it user configurable.

**Comment by concretevitamin** [comment]
One possible improvement:

Once we know N nodes have definitely been launched (e.g., after waiting-for-ssh) and are undergoing setup, we can relax the timeout to be less aggressive. E.g., use 5-10 minutes as timeout there. The initial progress timeout could stay smaller to not increase failover time.

**Comment by HysunHe** [comment]
Nodes can be UP mostly within 3 minutes. However, the setup process can be up to 16~17 minutes (so far per my experience) before SSH-able.
