### ISSUE TITLE
[Tests] Tests for `show-gpus`

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#1976]
Since `show-gpus` is a important user facing feature now, we need to add test cases to verify functionality when making changes to it. We could start by expanding the coverage in `test_list_accelerators.py` to invoke `sky show-gpus`.

**Comment by Saikrishna-Achalla** [comment]
I'll take this up!

**Comment by romilbhardwaj** [comment]
Closed by #1985
