### ISSUE TITLE
Bug when user have R2 enabled and using AWS SSO together

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#1979]
While debugging https://github.com/skypilot-org/skypilot/pull/1963 we discovered the following bug that only triggers for (R2-enabled, AWS SSO) user*:

- I have R2 enabled
- I have AWS SSO enabled for a `sky launch`:
```
AWS_PROFILE=my-sso sky launch -t t3.large -i0 -c sso -y --down --num-nodes=2
```
- As expected, `AWS.get_credential_file_mounts()` returns empty list — i.e., don’t upload `~/.aws/credentials`.
- However, in https://github.com/skypilot-org/skypilot/blob/master/sky/check.py#L81-L88, when R2 is detected to be enabled `cloudflare.get_credential_file_mounts()` includes the above file into the file_mounts.
- This means the whole credentials file — with regular EC2 and R2 profiles — are uploaded to my head node.
- The head node then fails to launch the worker node, because it’s supposed to use an IAM assumed role, but with the presence of the credentials file it got confused.

Fixes I can think of
- Change `cloudflare.get_credential_file_mounts()` so that it copies out the r2 profile and put it in a tmp file; upload that tmp file to remote’s `~/.aws/credentials`
  - But this needs to be tested; it is possible when the head node is launching workers it could still pick up the r2 profile
- Can R2 pick up its credentials from another file path?
- better ideas

[*] To be precise, user can trigger this not just for AWS SSO, but also any other credential method that points to a different identity than the one encoded in `~/.aws/credentials`. For example, `AWS_ACCESS_KEY_ID=my-account-2-id AWS_SECRET_ACCESS_KEY=my-account-2-key sky launch ...`.

cc @landscapepainter @romilbhardwaj

**Comment by landscapepainter** [comment]
Will look into it!

**Comment by romilbhardwaj** [comment]
WIP in #1980

**Comment by romilbhardwaj** [comment]
WIP in #1980
