### ISSUE TITLE
yaml.scanner.ScannerError - When running Quickstart example

### ISSUE THREAD

**Issue by luispoehl** [skypilot-org/skypilot#1981]
Hello all,
i receive the following error when trying the quickstart example w\ Python3.9.
Whereby, I performed the following steps

1. pip install skypilot[aws]
2. aws configure
3. sky check (-> AWS enabled)
4. create test_dir/test_config.yaml (with content below)
5. sky launch -c mycluster ./test_dir/test_config.yaml
6. Error arises
Can anyone give me a hint why the generated yaml.tmp file is corrupt? 
Thanks in advance,
Luis

**ERROR:**
yaml.scanner.ScannerError: while scanning a double-quoted scalar
  in "C:\Users\user\.sky\generated\mycluster.yml.tmp", line 60, column 25
expected escape sequence of 8 hexdecimal numbers, but found 's'
  in "C:\Users\user\.sky\generated\mycluster.yml.tmp", line 60, column 30

**CONTENT YAML:**
resources:
  cloud: aws
  instance_type: t3.nano
  region: eu-central-1
workdir: .
setup: echo "Running setup."
run: echo "Hello, Luis!"

**Comment by concretevitamin** [comment]
Hi @luispoehl! Are you using WSL or is this Windows?

**Comment by burkovae** [comment]
Hi, thanks for the fast reply. I'm exploring skypilo with @luispoehl and afaik sky is running from windows in this case.

**Comment by romilbhardwaj** [comment]
Hi @burkovae and @luispoehl - thanks for the report! We also ran into the same issue when trying to address other issues for Windows (see [PR](https://github.com/skypilot-org/skypilot/pull/1955#issuecomment-1553783525)).

While we work on fixing it, is it possible to use WSL? For Windows users, our recommended and tested way of using SkyPilot is through WSL.

**Comment by burkovae** [comment]
We also tried WSL. `skypilot` initialized the EC2 instantce. But we could not connect it via SSH (it timed out for some reason). But that I think is worth another issue. Atm I'm finding out what exactly the problem is.

**Comment by Michaelvll** [comment]
Just tried to reproduce this in #3071. Please feel free to reopen this issue if the problem still exists.
