### ISSUE TITLE
[Examples] Multi-node training with Deepspeed

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#1984]
[DeepSpeed](https://www.deepspeed.ai/getting-started/#resource-configuration-multi-node) uses MPI-style hostfiles to specify nodes to be used for multi-node training. We should add an example showing how such a hostfile can be constructed in SkyPilot and used to run DeepSpeed jobs. Raised from user discussions on Slack.

**Comment by romilbhardwaj** [comment]
BTW since all SkyPilot nodes have the local ~/.ssh/sky-key  added to `authorized_keys`, deepspeed jobs can upload it as the default key (id_rsa) and then directly ssh. We can also generate a hostfile for deepspeed like so:

```
file_mounts:
  ~/.ssh/id_rsa: ~/.ssh/sky-key

run: |
  if [ "${SKYPILOT_NODE_RANK}" == "0" ]; then
      # Run only on head node
      python3 -c "import os;n_gpus=os.environ['SKYPILOT_NUM_GPUS_PER_NODE'];print('\n'.join([f'{ip} slots={n_gpus}' for ip in os.environ['SKYPILOT_NODE_IPS'].split(' ')]))" > ~/hostfile
  fi
```

This creates a hostfile like:
```
10.128.0.55 slots=4
10.128.0.54 slots=4
```

**Comment by concretevitamin** [comment]
Another user has requested this:
> Is it possible to run DeepSpeed with skypilot for distributed training? Something similar to this: https://github.com/GoogleCloudPlatform/llm-pipeline-examples

DeepSpeed is very popular and we should add an example soon.
