### ISSUE TITLE
GCP multi-node launching failure

### ISSUE THREAD

**Issue by infwinston** [skypilot-org/skypilot#1986]
Our user reported failure when launching 16 nodes on GCP. We are able to reproduce with
` sky launch --cloud gcp --num-nodes 16 --cpus 2+ --down`

From @Michaelvll:

> it seems the problem happens because the healthy nodes are not updated immediately when a worker is ready, but updated in bulk. I am guessing it is because the lock here causing the node list not during provisioning https://github.com/skypilot-org/skypilot/blob/f733415c8f192cc4fedea0ea5bfd2d878d19d0b8/sky/skylet/providers/gcp/node_provider.py#L119

Temporarily increase timeout seems to be helpful but further investigation is needed.

**Comment by romilbhardwaj** [comment]
Related/possibly duplicate - #1260

**Comment by romilbhardwaj** [comment]
Duplicated in #1260 and will likely be fixed by the new provisioner. Closing.
