### ISSUE TITLE
[Storage] Make `sky storage delete` parallel

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#1990]
Currently `sky storage delete` sequentially deletes storage objects, which can take a long time if there are many storage objects:

https://github.com/skypilot-org/skypilot/blob/f4d29ba3d15124cd44115e9ce5508542d53be206/sky/cli.py#L3223-L3224

We should see if this can be run in parallel.

**Comment by Iamhero337** [comment]
Hey, Can you guide me a little What do I have to do here?

**Comment by romilbhardwaj** [comment]
Closed by #2058.
