### ISSUE TITLE
Sky check doesn't work with AWS SSO

### ISSUE THREAD

**Issue by LeiLikun** [skypilot-org/skypilot#1997]
Hey I got my credentials from AWS SSO and stored in `~/.aws/credentials`. However, `sky check` still shows `AWS credentials are not set. Run the following commands`. I tried both `0.2.5` and `0.3.0`. Please help, thanks!

**Comment by concretevitamin** [comment]
Hi @LeiLikun: the error was raised from here:

https://github.com/skypilot-org/skypilot/blob/releases/0.3.0/sky/clouds/aws.py#L570-L574

Could you try this command in the terminal?
```
aws sts get-caller-identity
```
