### ISSUE TITLE
no such file or directory: ~/.sky/.sky-complete.zsh

### ISSUE THREAD

**Issue by kyteague** [skypilot-org/skypilot#2012]
I get this error in my shell after running `sky --install-shell-completion auto`

I confirmed the file does not exist.

I tried deleting ~/.sky and reinstalling and the problem persists.

skypilot version 0.3.0

**Comment by romilbhardwaj** [comment]
Thanks for the report! Could you share the stacktrace of the error message, preferably after running `export SKYPILOT_DEBUG=1`? It would also be helpful to share the details of your os and shell:

```
# Get the os details
uname -a

# Get the shell
ps -p $$
```

**Comment by kyteague** [comment]
```
➜  ~ uname -a
Darwin Kyles-MacBook-Air.local 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:44 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T8103 arm64
➜  ~ ps -p $$
  PID TTY           TIME CMD
94370 ttys002    0:00.31 -zsh
```

The error is from sourcing my .zshrc file, not from sky pilot. There's no error from `sky --install-shell-completion auto`
The hook is successfully added but the shell completion file doesn't exist.
