### ISSUE TITLE
[SCP] Fine-grained failure reasons in the`sky check` for SCP

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#2015]
Current output if `~/.scp/scp_credential`  does not exist:
```
  SCP: disabled
    Reason: Failed to access SCP with credentials. To configure credentials, see: https://cloud.samsungsds.com/openapiguide
    Generate API key and add the following line to ~/.scp/scp_credential:
      access_key = [YOUR API ACCESS KEY]
      secret_key = [YOUR API SECRET KEY]
      project_id = [YOUR PROJECT ID]
```

If I don't have a `~/.scp/scp_credential` file,  the `Reason` message on sky check should be descriptive and tell me exactly that file does not exist. Similarly, if the credentials are incorrect, we should re-word this to say credentials are invalid.

We should catch each exception here separately and print out nice reasons on how to fix:
https://github.com/skypilot-org/skypilot/blob/d022512aa3879476b4d7050c90cb8dbba914679e/sky/clouds/scp.py#L285-L293

The [R2 check implementation](https://github.com/skypilot-org/skypilot/blob/d022512aa3879476b4d7050c90cb8dbba914679e/sky/adaptors/cloudflare.py#L165-L196) may be a good reference.

**Comment by ksasi** [comment]
We see similar output even for Lambda

```
Lambda: disabled
    Reason: Failed to access Lambda Cloud with credentials. To configure credentials, go to:
      https://cloud.lambdalabs.com/api-keys
    to generate API key and add the line
      api_key = [YOUR API KEY]
    to ~/.lambda_cloud/lambda_keys
```
