### ISSUE TITLE
[Spot/Auth] Public key should not be uploaded to the remote VM 

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#2025]
Currently, we upload the ssh public key to the VM launched by SkyPilot for several clouds (Azure, Lambda, IBM, OCI, SCP): 
https://github.com/skypilot-org/skypilot/blob/8c497ed9b4f5bf871c613a54fc265febb2ae6354/sky/authentication.py#L306
https://github.com/skypilot-org/skypilot/blob/8c497ed9b4f5bf871c613a54fc265febb2ae6354/sky/authentication.py#L330
https://github.com/skypilot-org/skypilot/blob/8c497ed9b4f5bf871c613a54fc265febb2ae6354/sky/authentication.py#L388
https://github.com/skypilot-org/skypilot/blob/8c497ed9b4f5bf871c613a54fc265febb2ae6354/sky/authentication.py#L400

This will cause problem to the spot controller, as when the spot controller launch a new VM, a new ssh private key will be generated under `~/.ssh/sky-key`, while the public key is the one uploaded from the user's laptop `~/.ssh/sky-key.pub` which mismatch the generated one, causing the spot controller fail to log into the spot VM.

**Comment by Michaelvll** [comment]
To reproduce, change the cloud for the spot controller to Azure and run `pytest tests/test_smoke.py --managed-spot`

**Comment by concretevitamin** [comment]
Ran into this problem too. Is it possible/a good idea to let the spot controller use the local machine's pub/private sky-key pair?

**Comment by Michaelvll** [comment]
#2119 should fix this issue
