### ISSUE TITLE
[Storage]Misleading storage information displayed with sky storage ls with identical storage names in different clouds

### ISSUE THREAD

**Issue by landscapepainter** [skypilot-org/skypilot#2030]
Currently, when storages from different cloud providers, say `gcp` and `cloudflare r2`, are created with identical storage names, some information in `state.db` are overwritten due to the following script ran in `global_user_state.py/add_or_update_storage()`. 

```
   _DB.cursor.execute('INSERT OR REPLACE INTO storage VALUES (?, ?, ?, ?, ?)',
                       (storage_name, storage_launched_at, handle, last_use,
                        storage_status.value))
```

And this results into misleading information from what `sky storage ls` displays and perhaps other bugs in the future. Say there's a sky managed storage called `train-data` from `gcs`, if we create another sky managed storage called `train-data` from `r2`, the data related to the `train-data` from `gcs` in `storage` table from `state.db` will be replaced. And this is due to having `storage_name` set as the `PRIMARY KEY`.

Consider the following scenario:
```
sky storage ls 

NAME                              CREATED      STORE   COMMAND                                                                         STATUS         
train-data                     36 mins ago   GCS   sky launch test.yaml --cloud gcp -y                                        READY          

sky launch another_test.yaml --cloud gcp -y # creates a storage called train-data from R2
sky storage ls 

NAME                              CREATED      STORE   COMMAND                                                                         STATUS         
train-data                      2 mins ago  GCS, R2  sky launch another_test.yaml --cloud gcp -y                      READY 
```         

Need to figure out a way to separate storages from different clouds with identical `storage_name` in `state.db` to fix this issue.

**Comment by romilbhardwaj** [comment]
Closed by #2063.
