### ISSUE TITLE
ClusterOwnerIdentityMismatchError for the same user

### ISSUE THREAD

**Issue by tokestermw** [skypilot-org/skypilot#2032]
Hi, I recently got a `ClusterOwnerIdentityMismatchError` but for the same user. This was using the most recent `main` branch as of last Wednesday.

The full error is (this happens when I tried to do `sky down CLUSTER_ID`):

```
sky.exceptions.ClusterOwnerIdentityMismatchError: 'CLUSTER_ID' (GCP) is owned by account '["EMAIL\\n [project_id=PROJECT_ID]"]', but the activated account is 'EMAIL\n [project_id=PROJECT_ID]'.
```

Note the extra `\` after the email.

I don't exactly remember how I hit this, but I think I initially logged into GCP and ran a job. Then I logged in again, and I wasn't able to access the clusters again.

But I was able to fix by downgrading `skypilot` to 0.3.0 for now.

**Comment by Michaelvll** [comment]
Thanks @tokestermw! Just made an attempt to fix the issue in #2033. 

It is quite weird that the last `activated account` is not a list. @tokestermw Do you mind check again the error message to see if that was actually not a list or a typo when copy pasting?
