### ISSUE TITLE
[Question] Strong Minimal Cloud Permissions with GCP

### ISSUE THREAD

**Issue by bilelomrani1** [skypilot-org/skypilot#2086]
Hi, according to [the documentation](https://skypilot.readthedocs.io/en/latest/cloud-setup/cloud-permissions.html#gcp) the following roles must be granted to each account using SkyPilot:
```
roles/browser
roles/compute.admin
roles/iam.serviceAccountAdmin
roles/iam.serviceAccountUser
roles/serviceusage.serviceUsageConsumer
roles/storage.admin
```

Some of these roles are quiet strong (most notably `iam.serviceAccountAdmin`), I'm curious about the rationale behind these requirements. My issue with it is the following: our GCP project is shared between multiple developers, each developer is granted a fine-grained permission set depending on what is needed. We want to assess if it's possible for all developers to use SkyPilot without granting excessive additional permissions.

Initially I thought that `roles/iam.serviceAccountAdmin` was only needed once, to create the SkyPilot service account, and that users can all start and use VMs using this existing service account. However it appears that `roles/iam.serviceAccountAdmin` is also needed when using `sky down`. Is it really necessary? If so, what is the recommended usage of SkyPilot for shared projects like ours? According to [the GCP documentation](https://cloud.google.com/iam/docs/understanding-roles?hl=fr#service-accounts-roles), the role `roles/iam.serviceAccountAdmin` bundles the following autorisations:
```
iam.serviceAccounts.create
iam.serviceAccounts.delete
iam.serviceAccounts.disable
iam.serviceAccounts.enable
iam.serviceAccounts.get
iam.serviceAccounts.getIamPolicy
iam.serviceAccounts.list
iam.serviceAccounts.setIamPolicy
iam.serviceAccounts.undelete
iam.serviceAccounts.update
resourcemanager.projects.get
resourcemanager.projects.list
```

Could you clarify which specific permissions are required for regular users to use SkyPilot?

Thank you very much. We're excited to integrate SkyPilot into our workflow!

**Comment by concretevitamin** [comment]
Thanks @bilelomrani1 - this is great feedback we're excited to work with your use cases. The short answer is: this list of GCP roles is not minimal. 

cc @infwinston @Michaelvll who have looked into this.
