### ISSUE TITLE
[Core] Fail to restart a STOPPED cluster if no capacity

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#2088]
The user reported that a development cluster with GPU is in STOPPED status, but when they tried to restart the cluster, it fails to restart due to the GPU being out-of-capacity on the cloud.

We should provide a functionality that helps user to migrate an existing STOPPED cluster to another region or even cloud to mitigate the resource unavailability problem.

**Comment by concretevitamin** [comment]
Related to #2050?

**Comment by Michaelvll** [comment]
Ahh, yes. Closing due to duplication.
