### ISSUE TITLE
[Core] Resource leakage for sky down if a multi-node cluster is partially stopped

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#2089]
If a multi-node cluster is partially stopped (during autostop or manually stop the worker node), i.e. the cluster is in INIT state, our `backend.teardown` function will fail to terminate the stopped nodes, as we are using `ray down` to terminate the cluster, and ray ignores the stopped nodes.
Related code path: https://github.com/skypilot-org/skypilot/blob/b9626015fd4cd01ab29d4354ba38c5ff17884e3d/sky/backends/cloud_vm_ray_backend.py#L3367-L3369

To reproduce:
1. `sky launch -c min --cloud gcp --num-nodes 2 --cpus 2`
2. Manually stop the worker node.
3. `sky down min`

After that, the head node will be terminated, but the worker node is still in STOPPED state.

One possible solution is to only use our own cloud cli-based termination (should be careful: may need to kill the head node first to avoid ray autoscaler restarting some of the worker nodes, causing leakage).

**Comment by Michaelvll** [comment]
Related to this, after #2087 is merged, we should be able to move the terminate commands to the cloud class as well, making the `backend.teardown` function cleaner.

**Comment by HysunHe** [comment]
![image](https://github.com/skypilot-org/skypilot/assets/7868068/221c0a3f-9703-4027-b468-a6e0a7369a1b)

Looks that I found this and did like this for OCI, but did not dig into other clouds.

**Comment by HysunHe** [comment]
@Michaelvll

**Comment by HysunHe** [comment]
@Michaelvll Do we need to include the INIT status here?:

 elif (terminate and 
       (prev_cluster_status IN ( global_user_state.ClusterStatus.STOPPED, **global_user_state.ClusterStatus.INIT** )
