### ISSUE TITLE
[spot dashboard/UI] Page failed to display in the first few seconds after opening

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#2123]
User feedback
> Small UX feedback: when I run sky spot dashboard, very often the page that opens first shows some error, and after a few seconds it automatically refreshes and loads. Slightly confusing user experience.

I noticed that too and not sure what's wrong.

**Comment by MaoZiming** [comment]
This seems to be an issue of ssh_command needing some time to launch before the site is ready for webbrowser.open
A naive solution might be to add a time.sleep() in between.

**Comment by concretevitamin** [comment]
@MaoZiming makes sense. Do you have time to put in a quick fix? Thanks.
