### ISSUE TITLE
[Core & Storage] Task will be initialized twice, causing data initial upload/sync up twice

### ISSUE THREAD

**Issue by HysunHe** [skypilot-org/skypilot#2128]
When launch a task, I noticed that the task will be initialized twice, which causes the same dataset uploading to the cloud storage executed twice. This is huge time cost & waste when dataset is large. Detail logs as below (I added some msg with ######... prefixed):

(sky) hysunhe@HYHE-PF1ZGYCQ:~/projects/skypilot/oci-sky$ sky launch -c test023 store3.yaml
Task from YAML spec: store3.yaml
**############################# [task init] cpu-task1**
D 06-24 22:45:06 storage.py:457] Detected existing storage object, loading Storage: skybucket18
D 06-24 22:45:06 utils.py:13] 2023-06-24 22:45:06 Enter <function oci_query_helper.find_compartment at 0x7f3a2010cd30>, (<class 'sky.skylet.providers.oci.query_helper.oci_query_helper'>, 'us-sanjose-1'), {}
D 06-24 22:45:08 utils.py:17] 2023-06-24 22:45:06 Exit <function oci_query_helper.find_compartment at 0x7f3a2010cd30>
I 06-24 22:45:10 storage.py:496] Verifying bucket and uploading from source for storage skybucket18
########################## upload()
**############################### batch rsync**: ['/home/hysunhe/python/dev/mylog', '/home/hysunhe/rust/dev/modsample']
I 06-24 22:45:22 storage.py:719] Storage type StoreType.OCI already exists.
############################# [task] {'/datasets-storage-copy': <sky.data.storage.Storage object at 0x7f3a1f9736a0>}
**############################# [task init] cpu-task1**
D 06-24 22:45:22 storage.py:457] Detected existing storage object, loading Storage: skybucket18
D 06-24 22:45:22 utils.py:13] 2023-06-24 22:45:22 Enter <function oci_query_helper.find_compartment at 0x7f3a2010cd30>, (<class 'sky.skylet.providers.oci.query_helper.oci_query_helper'>, 'us-sanjose-1'), {}
D 06-24 22:45:23 utils.py:17] 2023-06-24 22:45:22 Exit <function oci_query_helper.find_compartment at 0x7f3a2010cd30>
I 06-24 22:45:25 storage.py:496] Verifying bucket and uploading from source for storage skybucket18
########################## upload()
**############################### batch rsync**: ['/home/hysunhe/python/dev/mylog', '/home/hysunhe/rust/dev/modsample']
I 06-24 22:45:49 storage.py:719] Storage type StoreType.OCI already exists.
############################# [task init] skypilot-dummy-sink
D 06-24 22:45:49 optimizer.py:245] #### cpu-task1 ####

**Comment by romilbhardwaj** [comment]
cc @landscapepainter - would you like to take a look at this?

**Comment by concretevitamin** [comment]
@HysunHe We just merged a fix to master. Could you try if this still happens?

**Comment by HysunHe** [comment]
> sky launch -c test023 store3.yaml

@concretevitamin Yes, that's well fixed the issue!

**Comment by HysunHe** [comment]
Thanks for the fix. @landscapepainter
