### ISSUE TITLE
[Example] Vicuna training example fails due to the upstream library update

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#2152]
The upstream FastChat repo updated the `scripts` folder, removing the script for uploading checkpoints, which will cause our Vicuna training example fail. https://github.com/skypilot-org/skypilot/blob/438f81599fd1728e5b8df6df7ca72e804bd6e1fd/llm/vicuna/train.yaml#L66

We need to fix this and make our example self-contained.

**Comment by infwinston** [comment]
I'll push a temp fix (moving the uploading script into our repo) soon. longer term fix (e.g., try catch loading ckpt needs some more thoughts)

**Comment by Michaelvll** [comment]
Fixed by #2173. Closing this issue for now.
