### ISSUE TITLE
[Example] Flan-T5 finetuning example

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#2161]
It would be great to have a Flan-T5 fine-tuning example in our [llm](llm) folder.

**Comment by rishabbala** [comment]
Hi, I can take up this issue if it's available. Can you point me to an example of how it should be written?

**Comment by Michaelvll** [comment]
Thanks for your interest @rishabbala! Please feel free to check the existing [vicuna](https://github.com/skypilot-org/skypilot/tree/master/llm/vicuna) example.
