### ISSUE TITLE
[llm] vLLM: Easy, Fast, and Cheap LLM Serving with PagedAttention cannot find gradio endpoint after stop and start again

### ISSUE THREAD

**Issue by lingjiekong** [skypilot-org/skypilot#2164]
Following this [example](https://github.com/skypilot-org/skypilot/tree/master/llm/vllm) to launch a vllm on aws ec2.
```
sky launch -c vllm-serve -s serve.yaml --gpus A100:1 --env MODEL_NAME=decapoda-research/llama-13b-hf
```

At the end of it, it expose a gradio and localhost endpoint like below with no issue.
```
(task, pid=24770) INFO 07-01 07:05:41 llm_engine.py:132] # GPU blocks: 2435, # CPU blocks: 1310
(task, pid=24770) INFO:     Started server process [30049]/983M [00:05<00:00, 209MB/s]
(task, pid=24770) INFO:     Waiting for application startup.83M [00:05<00:00, 212MB/s]
(task, pid=24770) INFO:     Application startup complete.
(task, pid=24770) INFO:     Uvicorn running on http://localhost:8000 (Press CTRL+C to quit)
(task, pid=24770) Starting gradio server...
(task, pid=24770) Running on local URL:  http://localhost:8001
(task, pid=24770) Running on public URL: ......
(task, pid=24770) 
(task, pid=24770) This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
```

I stopped the running cluster through below command with no issue.
```
sky stop vllm-serve
```

However, when I restart the cluster through below commands.
```
sky start vllm-serve
```
or 
```
sky launch -c vllm-serve
```

I cannot get the gradio endpoint anymore besides.
```
Restarting 1 cluster: vllm-serve. Proceed? [Y/n]: y
I 07-01 00:51:36 cloud_vm_ray_backend.py:1347] To view detailed progress: tail -n100 -f /Users/lingjiekong/sky_logs/sky-2023-07-01-00-51-36-629375/provision.log
I 07-01 00:51:38 cloud_vm_ray_backend.py:1177] Cluster 'vllm-serve' (status: STOPPED) was previously launched in AWS us-west-2. Relaunching in that region.
I 07-01 00:51:38 cloud_vm_ray_backend.py:1700] Launching on AWS us-west-2 (us-west-2a)
I 07-01 00:53:02 cloud_vm_ray_backend.py:1513] Successfully provisioned or found existing VM.
Cluster vllm-serve started.
```

Based on the [documents](https://skypilot.readthedocs.io/en/latest/reference/cli.html#sky-exec), it says that "Execute a task or a command on a cluster (skip setup).". If so, I believe the `run` section in serve.yaml should be re-run to launch the vllm and expose gradio endpoint. 

Therefore, do I miss anything?

**Comment by Michaelvll** [comment]
Thanks for your question @lingjiekong! It seems our document may need to be more clear, but when you try to restart the cluster and have the job running again, you need to provide the yaml to the launch command as well., i.e., `sky launch -c vllm-serve serve.yaml` (this will reuse the existing cluster). Otherwise, the command will only restart the machine without running anything.

Just a note, if your cluster is already in UP state, you can also run `sky exec vllm-serve serve.yaml` which will submit the run section to the cluster as the job, without re-check the setup making the process a bit faster.

**Comment by lingjiekong** [comment]
First time, I use
```
sky launch -c vllm-serve -s serve.yaml --gpus V100:4 --env MODEL_NAME=decapoda-research/llama-13b-hf --cloud aws --region us-west-2
```
Second time, I used without overwrite the gpus through args to the serve.yaml.
```
sky launch -c vllm-serve serve.yaml
```

This cause the inconstant between the new launch as well as previous stopped instance config and cause a new instance to be launch...
