### ISSUE TITLE
[core] Get rid of signal handling

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#2182]
We currently use signal handling in our backend to kill the child processes immediately after keyboard interrupt is sent and print the hints. However, this will cause `sky.launch` not able to be run in a non-main thread. This is a bug encountered by a user, and we should look into it.

https://github.com/skypilot-org/skypilot/blob/ac9ba6a3e4ad475d68304a1f5789041f3110636f/sky/backends/cloud_vm_ray_backend.py#L3257-L3258

**Comment by concretevitamin** [comment]
Just ran into this too when trying out #2235.

**Comment by concretevitamin** [comment]
A user reported they sometimes ran into this during sky.launch(), with the two detach flags set to True.
