### ISSUE TITLE
Issue while using cheaper spot instance controller

### ISSUE THREAD

**Issue by nskde99** [skypilot-org/skypilot#2191]
How can I use a cheaper spot instance controller? This [link](https://skypilot.readthedocs.io/en/latest/examples/spot-jobs.html#customizing-spot-controller-resources) from the documentation isn't working.

**Comment by concretevitamin** [comment]
Hi @nskde99! Could you share what SkyPilot version you're using, and the `spot` dict added to your `~/.sky/config.yaml`?

By the way, on common issue we've seen is if you already have a controller in your status table, the config won't take effect. The old controller needs to be down'd first.

**Comment by concretevitamin** [comment]
Wanted to confirm the following:
- Do you already have an old controller in `sky status`? 
  - If so, need to `sky down` it first, then the next `spot launch` would pick up the new config.
- Were there any logs shown when the spot controller was first launched?

**Comment by nskde99** [comment]
There is no old controller in `sky status`. I make it down first and then go for starting a new one.
 
Following are the logs when I run the command:
![Screenshot from 2023-07-11 10-48-11](https://github.com/skypilot-org/skypilot/assets/98540698/2e2343d8-e4d8-487d-8933-7d038d8af023)

**Comment by Michaelvll** [comment]
Ahh, thanks for the question! It seems you are using the v0.3.1 of SkyPilot. The customizable resource for the spot controller is only included in the version later than 0.3.2 or the master branch.

**Comment by nskde99** [comment]
Thanks a lot!!! v0.3.2 worked.
