### ISSUE TITLE
[Docker] CI/CD for docker images

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#2193]
Our docker images are built and pushed manually currently. We need to add CI/CD using github actions for building and pushing docker images, both for nightly releases (`skypilot:latest`) and releases (`skypilot:0.3.2`).

**Comment by PratikKumar125** [comment]
So certainly, if I am thinking it right, then I just need to add a ".github/workflows" yaml file with all the required configurations?
And also could you please provide some more clarity about these nightly and normal releases?

**Comment by romilbhardwaj** [comment]
That's right @PratikKumar125 - a simple github action should suffice. I wonder if we can use this action from the marketplace: https://github.com/marketplace/actions/build-and-push-docker-images

Nightly docker image builds are run every 24 hours on the master branch. This is to provide bleeding edge changes to users who want them.

Regular releases are run once when a new release is created (`releases/*` branch). For example, any commit to `releases/0.3.2` should trigger a build and push of `skypilot:0.3.2` docker image.
