### ISSUE TITLE
outdated ray version

### ISSUE THREAD

**Issue by HansvanHespen** [skypilot-org/skypilot#2197]
Dear, the most recent ray version is 3.0, your setup file demands for a ray version not higher than 2.4.

Even ray 3.0 is not adapted for windows 11/python 3.11 yet, but I at least I can make that wheelfile installable for python .

Is it possible to update you setupfile for the most recent version of ray? Now, I cannot install skypilot for this reason. And thus not runhouse, and thus not langchain and gpt-2 of HuggingFace.

Thank you.

High regards, 

Hans

**Comment by concretevitamin** [comment]
Hi @HansvanHespen, Ray's latest release is 2.5.1; perhaps you installed from their master branch (or nightly) which would show `3.0.0.dev0`? 

To unblock you installing Ray/SkyPilot, is it possible to try installing in a fresh `conda` environment?

**Comment by HansvanHespen** [comment]
You're right, I used the nightly wheel for windows. Ray does not provide a wheel for windows 11, but that does not seem to be a real problem. Where it gives a problem, is that the present ray version does not install for python 3.11. Hence, when I want to install pip install skypilot, it stops on the fact that it can't find ray. Which is not exactly true, but it can't find ray for python 3.11. 

I can circumvent that by installing the wheel manually, and changing the name of the wheel into python 3.11. Then it installs nevertheless. 

When I then try to install skypilot from the code via python setup.py install, so that I can change the setup requirement and take out the maximum version limit of 2.4.0 for ray, skypilot installs, and finds ray now, but it gives a dependency problem of the _raylet.pyd in the skylet lambda_cloud provider. The _raylet.pyd file is present, but maybe not one of the dependencies. That, I cannot see. And probably, this will be the first of many problems to come. if I could get past this one.

File "C:\Users\Hans\AppData\Roaming\Python\Python311\site-packages\skypilot\sky\skylet\providers\lambda_cloud\node_provider.py", line 8, in <module>
    from ray.autoscaler.tags import (
  File "C:\Users\Hans\AppData\Roaming\Python\Python311\site-packages\ray\__init__.py", line 92, in <module>
    _configure_system()
  File "C:\Users\Hans\AppData\Roaming\Python\Python311\site-packages\ray\__init__.py", line 89, in _configure_system
    CDLL(so_path, ctypes.RTLD_GLOBAL)
  File "C:\Program Files\Python311\Lib\ctypes\__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: Could not find module 'C:\Users\Hans\AppData\Roaming\Python\Python311\site-packages\ray\_raylet.pyd' (or one of its dependencies). Try using the full path with constructor syntax.


I tried also "pip install ." on the local setup.py, but then I get "sky is not defined" error. Did everything in the setup.py and cli.py file, but couldn't find where the sky would not be defined. And sky itself is installed properly.

So, it looks like with my lack of knowledge of skypilot and ray, I will not be able to get through to it.

In resume, ray 2.5.1 does not allow python 3.11, skypilot is ray 2.51 compatible either as it seems, therefore, I cannot run runhouse, and not langchain, and not my application.

I don't see how a fresh conda environment would help in all this? Then again, I don't know conda very well. Maybe you could explain? I'm always eager to learn.

High regards,

Hans

**Comment by concretevitamin** [comment]
Thanks @HansvanHespen. Is it possible to try 
```
conda create -n sky python=3.8 -y
conda activate sky
pip install skypilot
```
Namely, using a conda environment with a lower python version (3.8 is well-tested).

**Comment by HansvanHespen** [comment]
Thank you. This works.

**Comment by concretevitamin** [comment]
Great to know @HansvanHespen!
