### ISSUE TITLE
Pin / tighter dependency versions

### ISSUE THREAD

**Issue by Hongbo-Miao** [skypilot-org/skypilot#2204]
I am trying to install SkyPilot through Poetry.
However, due to SkyPilot uses loose dependency versions. Poetry spent 12 hours resolving dependencies and still cannot install SkyPilot successfully.

Here is a potential solution: https://github.com/orgs/python-poetry/discussions/8165#discussioncomment-6387378
It would be great to use pin / tighter dependency versions.
It also helps this library has less chance to break.

Thanks! ☺️

**Comment by Michaelvll** [comment]
Thanks, @Hongbo-Miao! This is an excellent request. Could you help us add the lower bound for some of the dependencies? The reason we don't pin the version for them is that we would like to reduce the possibility of our SkyPilot to conflict with the user's existing python environment, but adding lower bounds for some of the dependencies should be good. ; )

**Comment by Hongbo-Miao** [comment]
Thanks @Michaelvll I may not have time for this. If I have time, I will! 😃

**Comment by Michaelvll** [comment]
Trying to solve this problem, it seems working with the following modification in the `setup.py` in SkyPilot after solving the dependencies for 30 mins with `poetry lock --no-update`.

```
aws_dependencies = [
    # NOTE: this installs CLI V1. To use AWS SSO (e.g., `aws sso login`), users
    # should instead use CLI V2 which is not pip-installable. See
    # https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html.
    'awscli>=1.29',
    'botocore>=1.31',
    'boto3>=1.28',
    # 'Crypto' module used in authentication.py for AWS.
    'pycryptodome==3.12.0',
]
```

The following is the `pyproject.toml` I used.
```
[tool.poetry]
name = "foo"
version = "1.0.0"
authors = ["ZW"]
description = ""

[tool.poetry.dependencies]
python = "3.10.x"

[tool.poetry.group.dev.dependencies]
sky = {path = "../sky-experiment-dev", extras = ["aws"]}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

**Comment by Hongbo-Miao** [comment]
Thanks @Michaelvll ! Nice found! BTW, also, switching from setup.py to Poetry will make life much easier ☺️
