### ISSUE TITLE
Forcely terminate the spot controller

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#2211]
Make the `sky down <spot-controller>` respect the `-p` in `sky down`. A user encountered a problem that the spot controller's disk is full, and the state of the spot controller stuck in `INIT` state. When they tries to terminate the cluster with `sky down`, it fails due to our controller status check.

Currently, the workaround is to ask the user to `python -c "import sky; sky.down('controller-name')"`, but we should have a way to down the cluster in CLI as well.

**Comment by kalanchoej** [comment]
Thanks for this workaround @Michaelvll
