### ISSUE TITLE
[Azure] Should fail early when the disk size does not match the image

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#2219]
`sky launch -r --cloud azure --disk-size 50` will keep retrying forever, although the underlying error shows that:
```
(Conflict) {
          "error": {
            "code": "OperationNotAllowed",
            "message": "The specified disk size 50 GB is smaller than the size of the corresponding disk in the VM image: 150 GB. This is not allowed. Please choose equal or greater size or do not specify an explicit size.",
            "target": "osDisk.diskSizeGB"
          }
        }
        Code: Conflict
        Message: {
          "error": {
            "code": "OperationNotAllowed",
            "message": "The specified disk size 50 GB is smaller than the size of the corresponding disk in the VM image: 150 GB. This is not allowed. Please choose equal or greater size or do not specify an explicit size.",
            "target": "osDisk.diskSizeGB"
          }
        }
```

We should fail early for this case.

**Comment by Vaibhav2001** [comment]
Running this command now seems to work by provisioning for a VM with any arbitrary specified disk size. I tried disk sizes of 50, 40 and 43. I don't know which commit fixed this, however it seems to be working now. Maybe this issue can be closed now? @Michaelvll

**Comment by Michaelvll** [comment]
> Running this command is now provisioning for a VM with any arbitrary specified disk size. I tried disk sizes of 50, 40 and 43. I checked it on the online console and the VM has the corresponding disk size. I don't know which commit fixed this, however it seems to be working now. Maybe this issue can be closed now? @Michaelvll

Thanks for trying it out @Vaibhav2001! Could you have try to use a image that is larger than the disk size you specified?
