### ISSUE TITLE
[Spot/UX] Querying the regions a job will try on

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#2225]
A user requested that they wants to check the what regions a launched spot job will be try on (failover through).

**Comment by concretevitamin** [comment]
If we offer a “describe” call, maybe it can return a zone history too. (Some questions: does it include provision history? Or zones where the job actually started running? Likely we need both?)

**Comment by landscapepainter** [comment]
I'll be taking on this issue and seemingly related #1651, and I was wondering if I could get some clarifications.
1. Is it correct that we want to run `sky spot describe` to get history of attempted zone name/zone IDs(#1651) and which region(perhaps zoneID?) it will fail on next(this issue) for each spot job ID?
2. From #1651 , I think @Michaelvll is specifying some implementation details for this, but what is 'Add cloud/zone information in the environment variable' for?
