### ISSUE TITLE
Resources: make `clouds` take a list of clouds

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#2238]
User requested a way to say something like: `clouds: [gcp, lambda]`. Not a preference, more like a set.

Related: 
- #1912

**Comment by concretevitamin** [comment]
Will be fixed by #2498.

**Comment by concretevitamin** [comment]
@MaoZiming Actually, in #2498 do we allow this convenient syntax `cloud: [aws, gcp]`? Or would users need `ordered:` / python API etc.?

**Comment by Michaelvll** [comment]
Currently, it requires the user to specify `ordered:` or `any_of:`. Reason: the semantic for having multiple ordered list will be quite confusing, e.g.:
```
resources:
  cloud: [aws, gcp]
  accelerators: [T4, A100]
```
It is unclear if we should go through the candidates for `cloud` first or `accelerators` first. (BFS or DFS)

That said, a future way to resolve this is to only allow a single ordered list in all the fields, and allowing the other fields to be specified as either a single candidate or a set of candidates:

```
resources:
  cloud: {aws, gcp}
  accelerators: [T4, A100]
```
```
resources:
  cloud: [aws, gcp]
  accelerators: {T4, A100}
```

Both of the above task yaml should be valid.
