### ISSUE TITLE
[k8s] Kind clusters fail to pull images in some environments

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#2246]
User ran `sky local up` on a lab machine and tried submitting a task. Task did not launch - `kubectl describe pods` showed:

![image](https://github.com/skypilot-org/skypilot/assets/4416605/0cd63ccb-639d-45f1-8605-3fbcafa371c4)

```
Failed to pull image "us-central1-docker.pkg.dev/skypilot-375900/skypilotk8s/skypilot:latest"; rpc error: code = Unknown desc
failed to pull and unpack image "us-central1-docker.pkg. dev/skypilot-375900/skypilotk8s/skypilot:latest": failed to resolve reference "us-central1-docker. kg. dev/skypilot-375900/ skypilotk8s/skypilot: latest"; failed to do request: Head "https: //us-central1-docker.pkg.dev/v2/skypilot-375900/skypilotk8s/skypilot/manifests/latest": dial tcp: lookup us-central1-docker.pkg.dev: i/o timeout
```

We tried with an image from dockerhub, but still failed. Finally, we did a workaround by disabling image pull and manually loading image into the kind cluster. 

Might be related to: https://github.com/kubernetes-sigs/kind/issues/1974. Needs more investigation.

**Comment by kevin85421** [comment]
Here's a data point: I haven't observed this issue in my environment.

```sh
kind create cluster --image=kindest/node:v1.23.0
kubectl run skypilot-pod --image=us-central1-docker.pkg.dev/skypilot-375900/skypilotk8s/skypilot:latest --command -- /bin/sh -c "while true; do sleep 86400; done"

# My environment
kind version
# kind v0.14.0 go1.18.2 linux/amd64
kubectl version --short=true
# Client Version: v1.23.8
# Server Version: v1.23.0
```

**Comment by romilbhardwaj** [comment]
Awesome, thanks for the report @kevin85421! We also haven't observed this issue since. I'll let this issue be open for a bit more before closing it.
