### ISSUE TITLE
CLI: `show-gpus` doesn't treat GPU name as case-insensitive like `launch --gpus`

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#2264]
```
» sky show-gpus h100
» sky show-gpus v100
```
doesn't work but the capitalized version does. This is inconsistent with `sky launch --gpus`.

**Comment by n10dollar** [comment]
Hi @concretevitamin, this is my first pull request so hopefully, I got a few of the conventions right.
