### ISSUE TITLE
[Storage] Implement storage info. into cluster's metadata to enhance storage/cluster interaction

### ISSUE THREAD

**Issue by landscapepainter** [skypilot-org/skypilot#2278]
Some of storage and cluster interaction can benefit by adding storage info. into cluster table's metadata columne in state.db.

1. `sky stop` and `sky start` issue on clusters with mounted/C_SYNC directories https://github.com/skypilot-org/skypilot/issues/1203
2. Conditionally run checks for terminating `csync` processes https://github.com/skypilot-org/skypilot/pull/2190

**Comment by romilbhardwaj** [comment]
Closed with #2322.
