### ISSUE TITLE
setup.py: change pyyaml requirement to >= 6?

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#2285]
That said, the dependency issue may occur for folks who already have newer version of `kubernetes` installed. As suggested in review comment, can you also try `pyyaml >=6.0.1`?

_Originally posted by @romilbhardwaj in https://github.com/skypilot-org/skypilot/pull/2283#pullrequestreview-1541455609_

Pinning `pyyaml<=5.3.1` was a temp fix. We should test pinning it to be >= 6 or the like
- https://github.com/aws/aws-cli/issues/8036#issuecomment-1640932993
- https://github.com/yaml/pyyaml/issues/728
- https://github.com/skypilot-org/skypilot/pull/2283#discussion_r1270856983

**Comment by jmif** [comment]
Running into this with https://github.com/mosaicml/composer, would be great to support 6.0+.  Is upgrading + running tests sufficient or is there more testing work required?  May be able to help here.

**Comment by concretevitamin** [comment]
We'd love your help to test 6.0+ @jmif! Please see here: https://github.com/skypilot-org/skypilot/blob/master/CONTRIBUTING.md#testing

**Comment by romilbhardwaj** [comment]
We now use `pyyaml > 3.13, != 5.4.*` as the constraint. Closing.
