### ISSUE TITLE
[Feature Request] Support passing env variables via a .env file

### ISSUE THREAD

**Issue by fozziethebeat** [skypilot-org/skypilot#2295]
When launching or starting a new job, env variables currently need to be embedded in the config file or passed in through multiple `--env` arguments.  In some setups, its more convenient to have multiple env variables in a `.env` file.  Much like Docker's support, it'd be nice to be able to do 

```sh
sky launch -c some-cluster --env-file .env my-job.yaml
```

Instead of having to write all the env variables each time.

This is probably fairly simple with support for reading values from the file using `python-dotenv`

**Comment by Michaelvll** [comment]
Thanks for the great request @fozziethebeat! We got a similar request in #2151 as well. We will increase the priority for this. : )

**Comment by fozziethebeat** [comment]
Ah yeah that's fairly similar.  When I use workdir, copying over the env file works well.  But sometimes I want to skip workdir since my workdir can be a mess.

**Comment by Michaelvll** [comment]
Good point! We are happy to support it. Would you like to contribute a PR? It would be very appreciated. : )

**Comment by fozziethebeat** [comment]
Yeah, i'll give it a shot!

**Comment by fozziethebeat** [comment]
Notes to self for where to implement the change:
  - `spot_launch`
  - `benchmark_launch`
  - `launch`
  - `exec`

In all cases we have to check the contents of an `env-file` argument and override them with `env` values if they conflict (`--env` has more precedence).  I'm pretty sure this is what Docker does so might as well be consistent with that.
