### ISSUE TITLE
[k8s] Cluster leak if current kube context changes and `sky status -r` is called

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#2300]
If the user switches their `~/.kube/config`, the existing cluster on the original k8s will be leaked if `sky status -r` is called?

That might be fixed by implementing the `get_current_user_identity` in the future, so that the cluster will be marked with the current kubernetes cluster, and will not be operated when it does not match.

_Originally posted by @Michaelvll in https://github.com/skypilot-org/skypilot/pull/2096#discussion_r1272724053_

**Comment by romilbhardwaj** [comment]
Related issue - switching to a different context and running `sky down` on a existing kubernetes cluster succeeds. It should raise an error saying pod doesn't exist in the cluster, and the user can override it using --purge if they require.

**Comment by landscapepainter** [comment]
I'll take this one.

**Comment by landscapepainter** [comment]
This will be resolved with #2522
