### ISSUE TITLE
Syncing sometimes incorrectly skips syncing

### ISSUE THREAD

**Issue by bilelomrani1** [skypilot-org/skypilot#2303]
I sometimes end up in situations where my working directory does not get properly synced when using `sky launch` or `sky exec`, I don't have a reproducible example yet but I'm under the impression that this happens when I switch between different git branches, and when launching a job with files that have an older timestamp than what is located on the remote machine. I have not fully confirmed this yet, but I guess it is worth sharing with you, as you may have more clues as to what is happening. 

Looking at the [`rsync` documentation](https://linux.die.net/man/1/rsync), I realize that by default `rsync` looks at the timestamps when deciding to sync a given file or not. This is unexpected and can lead to confusion when switching between different branches with different versions of the same file. Is my understanding correct? Perhaps we should look at the checksum of the files instead?

**Comment by landscapepainter** [comment]
Hi @bilelomrani1, thanks for sharing this issue. I think this is a great observation we should look into. `rsync` indeed skips to sync if the timestamp of the file in the source is older than the one in destination given the file-size is same. Does this sound like your case?

Using checksum sounds like a great idea. As running checksum can decrease the performance for syncing, I think it would be nice to have an additional option for `sky launch` and `sky exec` to use checksum for `rsync` on top of checking modtime/file-size by default. What do you think?

**Comment by bilelomrani1** [comment]
To give a bit of context: I use SkyPilot to launch automated tests on GPU. When I switch branches I need to be sure that the code that gets executed is exactly the code I expected. It could be an additional flag if it breaks an existing feature, but I think that being explicit about this behavior is important, as I was surprised when I figured that the code that got executed is not the code of the current working directory. Being able to always sync based on checksum is a nice addition.

**Comment by concretevitamin** [comment]
@bilelomrani1 Thanks for the report! I was trying to come up with a repro and failed. However, the attempt revealed that git branch switching seems to update a file's modification time, even without content change:

```
mkdir workdir-test
cd workdir-test
git init .

# main branch
echo 0 > myfile
git add myfile
git commit ...
cat myfile  # 0
stat -f %m myfile  # 1690424976; Mac command

# new branch
git checkout -b new-version
echo 1 > myfile
git add -u
git commit ...
cat myfile  # 1
stat -f %m myfile  # 1690425011; Mac command
```
So at this point two branches have been created:
- main: content "0", mtime 1690424976
- new-version: content "1", mtime 1690425011

Now without doing content changes, simply switch branches causes the mtime of the file to change:
```
git checkout -  # to main
stat -f %m myfile  # 1690425096

git checkout -  # to new-version
stat -f %m myfile  # 1690425127

git checkout -  # to new-version
stat -f %m myfile  # 1690425134
```

I then verified that with a simple SkyPilot YAML each git branch switching indeed re-sync the file -- which is expected due to the above mtime changes:
```
» cat test.yaml
workdir: .

run: |
  set -x
  cat myfile
  # stat -f %m myfile  # works on mac only
  stat -c %Y myfile
```

We may need to have a repro to look into this more.

**Comment by landscapepainter** [comment]
@bilelomrani1 Let me spend some time on reproducing the error as well. Will get back shortly.

**Comment by landscapepainter** [comment]
Was also able to reproduce what @concretevitamin produced. When switching branches, it does update the mod time of the files that has different version from the previous branch.

Was able to confirm how mod time of a file changes by running `stat -c "%y %n" *` before switching branch and after switching.

```
>> stat -c "%y %n" *
2023-07-28 03:28:06.434199494 +0000 authentication.py # in branch a
>> git checkout b
>> stat -c "%y %n" *
2023-07-28 03:28:26.883778929 +0000 authentication.py # in branch b
>> git checkout a
>> stat -c "%y %n" *
2023-07-28 03:28:43.950025423 +0000 authentication.py # in branch a
```

For Skypilot, `rsync` would fail to sync the file from src to dst when the file in each src and dst have the same mod time and file size. If they have different mod time, it would still sync even with identical file size. Hope this info helps to figure out what may have been causing the issue for your automated test @bilelomrani1

**Comment by bilelomrani1** [comment]
I see thank you very much for this insight, I will have to investigate further, as I don't really understand when does this happen. I'm closing and if I'am able to create a reproducible example I'll submit an new issue.
