### ISSUE TITLE
[UX] `sky cancel` should terminate the latest job

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#2316]
Similar as our `sky logs <cluster-name>`, `sky cancel <cluster-name>` should ask the user if they want to cancel the latest running job <job-id>, instead of erroring out. This should improve the convenience of the CLI.

This has been asked by a user before as well.

**Comment by concretevitamin** [comment]
See two modes that people have asked for:

https://github.com/skypilot-org/skypilot/issues/1877#issuecomment-1640692318
