### ISSUE TITLE
[Feature Request] Resizing a Cluster

### ISSUE THREAD

**Issue by michaelzhiluo** [skypilot-org/skypilot#2331]
A nice feature that would allow users to save costs would be to able to resize the cluster w.r.t instance-type. (e..g if I have a 48 CPU cluster and want to reduce it to a 4 CPU cluster)

I encountered this when trying to reduce my cloud spending budget for a long term development machine that was consuming a lot of costs (not using Ray job feature, so autostop would not work here).

**Comment by Michaelvll** [comment]
@michaelzhiluo does the `--clone-from-disk` argument work for your case? https://skypilot.readthedocs.io/en/latest/reference/cli.html#sky-launch

**Comment by michaelzhiluo** [comment]
I'll try it out; this is a nice killer feature!
