### ISSUE TITLE
Cannot install due to grpcio

### ISSUE THREAD

**Issue by QLutz** [skypilot-org/skypilot#2335]
I am trying to install the latest version of SkyPilot (0.3.3) on an M1 Mac with Python 3.9 with `pip install Skypilot` and this fails because the pinned version of grpcio (1.49.1) cannot be installed correctly. Installing the latest version of grpcio (1.56.2) works fine however.

<details>
Collecting skypilot
  Using cached skypilot-0.3.3-py3-none-any.whl (610 kB)
Collecting rich
  Using cached rich-13.5.1-py3-none-any.whl (239 kB)
Requirement already satisfied: pycryptodome==3.12.0 in ./venv_arm/lib/python3.9/site-packages (from skypilot) (3.12.0)
Requirement already satisfied: filelock>=3.6.0 in ./venv_arm/lib/python3.9/site-packages (from skypilot) (3.12.2)
Requirement already satisfied: PrettyTable>=2.0.0 in ./venv_arm/lib/python3.9/site-packages (from skypilot) (3.8.0)
Requirement already satisfied: wheel in ./venv_arm/lib/python3.9/site-packages (from skypilot) (0.38.4)
Collecting jsonschema
  Using cached jsonschema-4.18.4-py3-none-any.whl (80 kB)
Requirement already satisfied: colorama<0.4.5 in ./venv_arm/lib/python3.9/site-packages (from skypilot) (0.4.4)
Collecting pandas
  Using cached pandas-2.0.3-cp39-cp39-macosx_11_0_arm64.whl (10.9 MB)
Requirement already satisfied: networkx in ./venv_arm/lib/python3.9/site-packages (from skypilot) (3.1)
Collecting ray[default]<=2.4.0,>=2.2.0
  Using cached ray-2.4.0-cp39-cp39-macosx_11_0_arm64.whl (57.6 MB)
Collecting pendulum
  Using cached pendulum-2.1.2-cp39-cp39-macosx_13_0_arm64.whl
Requirement already satisfied: jinja2>=3.0 in ./venv_arm/lib/python3.9/site-packages (from skypilot) (3.1.2)
Requirement already satisfied: protobuf!=3.19.5,>=3.15.3 in ./venv_arm/lib/python3.9/site-packages (from skypilot) (3.20.3)
Requirement already satisfied: psutil in ./venv_arm/lib/python3.9/site-packages (from skypilot) (5.9.5)
Collecting awscli
  Using cached awscli-1.29.16-py3-none-any.whl (4.2 MB)
Requirement already satisfied: click<=8.0.4,>=7.0 in ./venv_arm/lib/python3.9/site-packages (from skypilot) (8.0.4)
Requirement already satisfied: pydantic<2.0 in ./venv_arm/lib/python3.9/site-packages (from skypilot) (1.10.12)
Collecting grpcio!=1.48.0,<=1.49.1,>=1.32.0
  Using cached grpcio-1.49.1.tar.gz (22.1 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting oauth2client
  Using cached oauth2client-4.1.3-py2.py3-none-any.whl (98 kB)
Requirement already satisfied: packaging in ./venv_arm/lib/python3.9/site-packages (from skypilot) (23.1)
Requirement already satisfied: pulp in ./venv_arm/lib/python3.9/site-packages (from skypilot) (2.7.0)
Collecting boto3
  Using cached boto3-1.28.16-py3-none-any.whl (135 kB)
Requirement already satisfied: pyyaml<=5.3.1 in ./venv_arm/lib/python3.9/site-packages (from skypilot) (5.3.1)
Requirement already satisfied: tabulate in ./venv_arm/lib/python3.9/site-packages (from skypilot) (0.9.0)
Collecting cryptography
  Using cached cryptography-41.0.2-cp37-abi3-macosx_10_12_universal2.whl (5.3 MB)
Requirement already satisfied: six>=1.5.2 in ./venv_arm/lib/python3.9/site-packages (from grpcio!=1.48.0,<=1.49.1,>=1.32.0->skypilot) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./venv_arm/lib/python3.9/site-packages (from jinja2>=3.0->skypilot) (2.1.3)
Requirement already satisfied: wcwidth in ./venv_arm/lib/python3.9/site-packages (from PrettyTable>=2.0.0->skypilot) (0.2.6)
Requirement already satisfied: typing-extensions>=4.2.0 in ./venv_arm/lib/python3.9/site-packages (from pydantic<2.0->skypilot) (4.7.1)
Requirement already satisfied: frozenlist in ./venv_arm/lib/python3.9/site-packages (from ray[default]<=2.4.0,>=2.2.0->skypilot) (1.4.0)
Requirement already satisfied: virtualenv<20.21.1,>=20.0.24 in ./venv_arm/lib/python3.9/site-packages (from ray[default]<=2.4.0,>=2.2.0->skypilot) (20.21.0)
Requirement already satisfied: requests in ./venv_arm/lib/python3.9/site-packages (from ray[default]<=2.4.0,>=2.2.0->skypilot) (2.31.0)
Requirement already satisfied: numpy>=1.19.3 in ./venv_arm/lib/python3.9/site-packages (from ray[default]<=2.4.0,>=2.2.0->skypilot) (1.25.1)
Requirement already satisfied: attrs in ./venv_arm/lib/python3.9/site-packages (from ray[default]<=2.4.0,>=2.2.0->skypilot) (23.1.0)
Collecting aiosignal
  Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in ./venv_arm/lib/python3.9/site-packages (from ray[default]<=2.4.0,>=2.2.0->skypilot) (1.0.5)
Requirement already satisfied: py-spy>=0.2.0 in ./venv_arm/lib/python3.9/site-packages (from ray[default]<=2.4.0,>=2.2.0->skypilot) (0.3.14)
Requirement already satisfied: prometheus-client>=0.7.1 in ./venv_arm/lib/python3.9/site-packages (from ray[default]<=2.4.0,>=2.2.0->skypilot) (0.17.1)
Collecting aiohttp>=3.7
  Using cached aiohttp-3.8.5-cp39-cp39-macosx_11_0_arm64.whl (345 kB)
Requirement already satisfied: smart-open in ./venv_arm/lib/python3.9/site-packages (from ray[default]<=2.4.0,>=2.2.0->skypilot) (6.3.0)
Collecting gpustat>=1.0.0
  Using cached gpustat-1.1-py3-none-any.whl
Collecting aiohttp-cors
  Using cached aiohttp_cors-0.7.0-py3-none-any.whl (27 kB)
Collecting opencensus
  Using cached opencensus-0.11.2-py2.py3-none-any.whl (128 kB)
Requirement already satisfied: colorful in ./venv_arm/lib/python3.9/site-packages (from ray[default]<=2.4.0,>=2.2.0->skypilot) (0.5.5)
Requirement already satisfied: rsa<4.8,>=3.1.2 in ./venv_arm/lib/python3.9/site-packages (from awscli->skypilot) (4.7.2)
Requirement already satisfied: docutils<0.17,>=0.10 in ./venv_arm/lib/python3.9/site-packages (from awscli->skypilot) (0.16)
Collecting botocore==1.31.16
  Using cached botocore-1.31.16-py3-none-any.whl (11.1 MB)
Collecting s3transfer<0.7.0,>=0.6.0
  Using cached s3transfer-0.6.1-py3-none-any.whl (79 kB)
Requirement already satisfied: urllib3<1.27,>=1.25.4 in ./venv_arm/lib/python3.9/site-packages (from botocore==1.31.16->awscli->skypilot) (1.26.16)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in ./venv_arm/lib/python3.9/site-packages (from botocore==1.31.16->awscli->skypilot) (1.0.1)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in ./venv_arm/lib/python3.9/site-packages (from botocore==1.31.16->awscli->skypilot) (2.8.2)
Collecting cffi>=1.12
  Using cached cffi-1.15.1-cp39-cp39-macosx_11_0_arm64.whl (174 kB)
Collecting jsonschema-specifications>=2023.03.6
  Using cached jsonschema_specifications-2023.7.1-py3-none-any.whl (17 kB)
Requirement already satisfied: rpds-py>=0.7.1 in ./venv_arm/lib/python3.9/site-packages (from jsonschema->skypilot) (0.9.2)
Requirement already satisfied: referencing>=0.28.4 in ./venv_arm/lib/python3.9/site-packages (from jsonschema->skypilot) (0.30.0)
Requirement already satisfied: pyasn1>=0.1.7 in ./venv_arm/lib/python3.9/site-packages (from oauth2client->skypilot) (0.5.0)
Requirement already satisfied: httplib2>=0.9.1 in ./venv_arm/lib/python3.9/site-packages (from oauth2client->skypilot) (0.22.0)
Requirement already satisfied: pyasn1-modules>=0.0.5 in ./venv_arm/lib/python3.9/site-packages (from oauth2client->skypilot) (0.3.0)
Requirement already satisfied: tzdata>=2022.1 in ./venv_arm/lib/python3.9/site-packages (from pandas->skypilot) (2023.3)
Requirement already satisfied: pytz>=2020.1 in ./venv_arm/lib/python3.9/site-packages (from pandas->skypilot) (2023.3)
Requirement already satisfied: pytzdata>=2020.1 in ./venv_arm/lib/python3.9/site-packages (from pendulum->skypilot) (2020.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in ./venv_arm/lib/python3.9/site-packages (from rich->skypilot) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in ./venv_arm/lib/python3.9/site-packages (from rich->skypilot) (2.15.1)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in ./venv_arm/lib/python3.9/site-packages (from aiohttp>=3.7->ray[default]<=2.4.0,>=2.2.0->skypilot) (4.0.2)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in ./venv_arm/lib/python3.9/site-packages (from aiohttp>=3.7->ray[default]<=2.4.0,>=2.2.0->skypilot) (3.2.0)
Requirement already satisfied: yarl<2.0,>=1.0 in ./venv_arm/lib/python3.9/site-packages (from aiohttp>=3.7->ray[default]<=2.4.0,>=2.2.0->skypilot) (1.9.2)
Requirement already satisfied: multidict<7.0,>=4.5 in ./venv_arm/lib/python3.9/site-packages (from aiohttp>=3.7->ray[default]<=2.4.0,>=2.2.0->skypilot) (6.0.4)
Requirement already satisfied: pycparser in ./venv_arm/lib/python3.9/site-packages (from cffi>=1.12->cryptography->skypilot) (2.21)
Collecting blessed>=1.17.1
  Using cached blessed-1.20.0-py2.py3-none-any.whl (58 kB)
Requirement already satisfied: nvidia-ml-py>=11.450.129 in ./venv_arm/lib/python3.9/site-packages (from gpustat>=1.0.0->ray[default]<=2.4.0,>=2.2.0->skypilot) (12.535.77)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in ./venv_arm/lib/python3.9/site-packages (from httplib2>=0.9.1->oauth2client->skypilot) (3.1.1)
Requirement already satisfied: mdurl~=0.1 in ./venv_arm/lib/python3.9/site-packages (from markdown-it-py>=2.2.0->rich->skypilot) (0.1.2)
Requirement already satisfied: distlib<1,>=0.3.6 in ./venv_arm/lib/python3.9/site-packages (from virtualenv<20.21.1,>=20.0.24->ray[default]<=2.4.0,>=2.2.0->skypilot) (0.3.7)
Requirement already satisfied: platformdirs<4,>=2.4 in ./venv_arm/lib/python3.9/site-packages (from virtualenv<20.21.1,>=20.0.24->ray[default]<=2.4.0,>=2.2.0->skypilot) (3.10.0)
Collecting google-api-core<3.0.0,>=1.0.0
  Using cached google_api_core-2.11.1-py3-none-any.whl (120 kB)
Requirement already satisfied: opencensus-context>=0.1.3 in ./venv_arm/lib/python3.9/site-packages (from opencensus->ray[default]<=2.4.0,>=2.2.0->skypilot) (0.1.3)
Requirement already satisfied: certifi>=2017.4.17 in ./venv_arm/lib/python3.9/site-packages (from requests->ray[default]<=2.4.0,>=2.2.0->skypilot) (2023.7.22)
Requirement already satisfied: idna<4,>=2.5 in ./venv_arm/lib/python3.9/site-packages (from requests->ray[default]<=2.4.0,>=2.2.0->skypilot) (3.4)
Requirement already satisfied: google-auth<3.0.dev0,>=2.14.1 in ./venv_arm/lib/python3.9/site-packages (from google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]<=2.4.0,>=2.2.0->skypilot) (2.22.0)
Collecting googleapis-common-protos<2.0.dev0,>=1.56.2
  Using cached googleapis_common_protos-1.60.0-py2.py3-none-any.whl (227 kB)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in ./venv_arm/lib/python3.9/site-packages (from google-auth<3.0.dev0,>=2.14.1->google-api-core<3.0.0,>=1.0.0->opencensus->ray[default]<=2.4.0,>=2.2.0->skypilot) (5.3.1)
Building wheels for collected packages: grpcio
  Building wheel for grpcio (setup.py): started
  Building wheel for grpcio (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [1042407 lines of output]
      ASM Builds for BoringSSL currently not supported on: macosx-12.3-arm64

[TRUNCATED]

      Cython.Compiler.Errors.CompileError: src/python/grpcio/grpc/_cython/cygrpc.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Rolling back uninstall of grpcio
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> grpcio

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

<details/>

**Comment by Michaelvll** [comment]
> Thanks for the report and sharing the workaround @QLutz!
> 
> The requirement [here in setup.py](https://github.com/skypilot-org/skypilot/blob/master/sky/setup_files/setup.py#L103) was adopted from Ray 2.4.x. Now Ray 2.6.1 has removed the upper bound of grpcio ([ref](https://github.com/ray-project/ray/blob/ray-2.6.1/python/setup.py#L320-L321)). We should get to it soon.
> 
> (Related to #2297? cc @Michaelvll)

Just tried `1.56.2` with the ray 2.6.1, and it seems not working well for fetching the IP address of the VM. We need to investigate more for this.

**Comment by dcroley** [comment]
Given the last comment, what is the work around for installing Skypilot on an M1 Mac?

**Comment by concretevitamin** [comment]
@dcroley Are you also using Python 3.9? Have you tried something like `pip uninstall grpcio; conda install grpcio=1.56.2 -c conda-forge`? Adapted from [Ray docs](https://docs.ray.io/en/releases-2.4.0/ray-overview/installation.html#m1-mac-apple-silicon-support).

**Comment by dcroley** [comment]
Solved my problem by downgrading from python 3.11 to 3.10.

**Comment by Michaelvll** [comment]
> Solved my problem by downgrading from python 3.11 to 3.10.

Thanks for posting your solution @dcroley! Yes, we currently do not officially support python 3.11 as there is some issue with our underlying dependency on `ray`. : )
