### ISSUE TITLE
[K8s] Install SSH server in setup phase instead of image

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#2351]
Currently we install and configure OpenSSH in the our default image:

https://github.com/skypilot-org/skypilot/blob/ca2a092a1cc26d26fb49f94a11cfe5f369df0f25/Dockerfile_k8s#L13-L18

We should consider doing this after provisioning when the container is running (or in `postStart`) to enable users to bring custom images (which may not have openssh installed or configured correctly).

**Comment by romilbhardwaj** [comment]
Related to #2599.

**Comment by Michaelvll** [comment]
This should be fixed in #3019
