### ISSUE TITLE
Running a local cluster (on-prem) requires a cloud service to be setup

### ISSUE THREAD

**Issue by valeriu-balaban** [skypilot-org/skypilot#2361]
First, many thanks for this tool. Extremely useful.

I followed the [instructions](https://skypilot.readthedocs.io/en/latest/reference/local/index.html) to set up a local cluster on a new machine. No issues have been encountered up to running `sky launch -c my-local-cluster ''` which returns `Cloud access is not set up. Run: sky check`. 

Running `sky check` lists that all cloud services are disabled.

Additional info:
- `sky status` returns:
    ```
    Clusters
    No existing clusters.
    
    Local clusters:
    NAME              USER  HEAD_IP  RESOURCES  COMMAND  
    my-local-cluster  -     -        -          -        
    
    Managed spot jobs
    No in progress jobs. (See: sky spot -h)
    ```
- At the moment, I'm using the same system user both as an admin for deploying the cluster and as a user for submitting jobs.

**Comment by romilbhardwaj** [comment]
Hi @valeriu-balaban, thanks for your interest in running SkyPilot tasks on an on-prem cluster!

This is a [known issue](https://github.com/skypilot-org/skypilot/issues/1528) for our our [ray-based onprem mode](https://skypilot.readthedocs.io/en/latest/reference/local/index.html), which has been deprecated. If you'd still like to use it, you may need to enable at least one public account.

-------------

If you're interested in running SkyPilot on your onprem resources, we would recommend taking a look at our new and experimental Kubernetes support. It will allow you to run SkyPilot tasks on your onprem Kubernetes cluster. Going forward, this will be how SkyPilot will be run on on-prem resources.

You can find documentation on it [here](https://github.com/skypilot-org/skypilot/pull/2324/files).

To try it out:

* **If you have an existing Kubernetes cluster**: simply place your kubeconfig file at ~/.kube/config and open ports 30000-32767 on your k8s nodes. Then run sky check.
* **If you don't have a Kubernetes cluster** and want to try it out on your laptop first: Install [docker](https://docs.docker.com/engine/install/) and [kind](https://kind.sigs.k8s.io/docs/user/quick-start/#installation) on your laptop, and run `sky local up`.

After this, you should be able to see Kubernetes as a cloud in the list of clouds shown by SkyPilot when you run `sky launch`.

Note that this feature is under active development. Notably, GPUs and multi-node tasks are not currently supported, but we're [working on it.](https://github.com/skypilot-org/skypilot/pull/2328) Let me know if you run into any issues!

**Comment by valeriu-balaban** [comment]
Thanks a lot for the clarification. Will monitor the Kubernetes-based implementation of the local cluster.
