### ISSUE TITLE
feature request: Get (and use) the public IP in the YAML

### ISSUE THREAD

**Issue by gaocegege** [skypilot-org/skypilot#2368]
We wanna know the IP of the started server. Maybe skypilot could provide an environment var `SKYPILOT_VM_IP` in the `run` section or something else to support it.

**Comment by Michaelvll** [comment]
Thanks for requesting the feature @gaocegege! 

We currently provide the internal IPs in the env var `SKYPILOT_NODE_IPS` for the node the script is currently running on. 

https://github.com/skypilot-org/skypilot/blob/4915d682be1053a5af9a48879dfc32d886809ecb/sky/backends/cloud_vm_ray_backend.py#L500

The `job_ip_list_str` is set in the following code:

https://github.com/skypilot-org/skypilot/blob/4915d682be1053a5af9a48879dfc32d886809ecb/sky/backends/cloud_vm_ray_backend.py#L428-L431

To make the public IP available to the program, we can pass the external IP list from `handle.external_ips()` to the function here as well and create a new env var `SKYPILOT_NODE_EXTERNAL_IPS` above:

https://github.com/skypilot-org/skypilot/blob/4915d682be1053a5af9a48879dfc32d886809ecb/sky/backends/cloud_vm_ray_backend.py#L4250-L4262


We would love to support the feature, but feel free to submit a PR if you are interested. : )
