### ISSUE TITLE
sky check fails to properly check Azure credentials

### ISSUE THREAD

**Issue by dcroley** [skypilot-org/skypilot#2376]
'az account list' definitely shows I am logged in and lists subscription_id I expect. I've made sure to do the 'az account set -s <subid>' command, but 'sky check' still does not recognize that Azure credentials are in place, saying "Reason: Azure credential is not set.".  I do see that homebrew is not fully up to date with azure-cli releases, having only 2.50.0 instead of the latest 2.51.0, which causes 'az upgrade' to fail. Not sure if that is related.

**Comment by Michaelvll** [comment]
Hi @dcroley, thanks for filing the issue! I just submitted a PR to show a detailed error message in `sky check` for the failed Azure credential check. Hopefully, that will help us debug once it is merged.

**Comment by dcroley** [comment]
So I pulled the latest from github and installed from source, and now "sky check" is showing Azure as enabled. Perhaps my problem was some diff between the 0.3.3 release I pulled via "pip install" or some other recent change, but all good now.

**Comment by Michaelvll** [comment]
Nice! Thanks for confirming @dcroley! Great to hear that it works for you now.
I am closing this issue. : )
