### ISSUE TITLE
[Storage] AWS mountpoint for S3 buckets

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#2383]
AWS announced an official tool to mount S3 buckets - [mountpoint](https://github.com/awslabs/mountpoint-s3/tree/main). See [blog](https://aws.amazon.com/blogs/aws/mountpoint-for-amazon-s3-generally-available-and-ready-for-production-workloads/).

Key things to note for SkyPilot:

* Promises high performance (100 Gb/second)
* [Semantics](https://github.com/awslabs/mountpoint-s3/blob/main/doc/SEMANTICS.md) - supports basic file operations, and can read files up to 5 TB in size. It can list and read existing files, and it can create new ones. It cannot modify existing files, rename them or delete directories, and it does not support symbolic links or file locking. Effectively, good for reading all files and writing new files. 
* [Consistency](https://github.com/awslabs/mountpoint-s3/blob/main/doc/SEMANTICS.md#consistency-and-concurrency) - read-after-write consistency for new object creation and writes of existing objects, just like goofys.

Worth more investigation to see if the performance can help #1862.

**Comment by landscapepainter** [comment]
This is quite exciting. I'll benchmark this to compare with `goofys` and `aws s3 sync`.
