### ISSUE TITLE
[Onprem] NoCloudAccessError get raised when setting up a local cluster

### ISSUE THREAD

**Issue by msalhab96** [skypilot-org/skypilot#2385]
I'm building a cluster locally on google cloud VMs by following the steps in the documentation, but when trying to launch the cluster using ```sky launch -c my-local-cluster -- '' ``` getting the error below 

```
sky.exceptions.NoCloudAccessError: Cloud access is not set up. Run: sky check

During handling of the above exception, another exception occurred:

TypeError: sequence item 1: expected str instance, NoCloudAccessError found
```

I'm using the latest version on PyPi which is 0.3.3, Ubuntu 20.04

**Comment by romilbhardwaj** [comment]
Hi @msalhab96, thanks for your interest in running SkyPilot tasks on an on-prem cluster!

This is a [known issue](https://github.com/skypilot-org/skypilot/issues/1528) for our our [ray-based onprem mode](https://skypilot.readthedocs.io/en/latest/reference/local/index.html), which has been deprecated. If you'd still like to use it, you may need to enable at least one public cloud account then run `sky check`.

-------------

If you're interested in running SkyPilot on your onprem resources, we would recommend taking a look at our new and experimental Kubernetes support. It will allow you to run SkyPilot tasks on your onprem Kubernetes cluster. Going forward, this will be how SkyPilot will be run on on-prem resources.

You can find documentation on it [here](https://github.com/skypilot-org/skypilot/pull/2324/files).

To try it out:

* **If you have an existing Kubernetes cluster**: simply place your kubeconfig file at ~/.kube/config and open ports 30000-32767 on your k8s nodes. Then run sky check.
* **If you have access to Google Cloud Kubernetes Engine (GKE)** - Create a standard GKE cluster and open ports 30000-32767 on the VMs in your nodepool. See detailed instructions [here](https://github.com/skypilot-org/skypilot/blob/207aab8cba7d168cb666d7980ecfe3111d00ed13/docs/source/reference/kubernetes/kubernetes-setup.rst#deploying-on-gke).
* **If you don't have a Kubernetes cluster** and want to try it out on your laptop first: Install [docker](https://docs.docker.com/engine/install/) and [kind](https://kind.sigs.k8s.io/docs/user/quick-start/#installation) on your laptop, and run `sky local up`.

After this, you should be able to see Kubernetes as a cloud in the list of clouds shown by SkyPilot when you run `sky launch`.

Note that this feature is under active development. Notably, GPUs and multi-node tasks are not currently supported, but we're [working on it.](https://github.com/skypilot-org/skypilot/pull/2328) Let me know if you run into any issues!
