### ISSUE TITLE
Feature Request: attaching persistent disks / EBS volumes

### ISSUE THREAD

**Issue by michalwols** [skypilot-org/skypilot#2387]
It would be nice if there was to configure persistent disk mounts.

For computer vision datasets reading from an object store is too slow and requires packing image in sequence files like tfrecords or tar files (webdataset). It would be much easier and more performant if we could just attached a named volume with the data downloaded ahead of time.

**Comment by concretevitamin** [comment]
One question here is when attaching an EBS/PD, the task is tied to the disk's region. This means less freedom to save costs or bump GPU availability. Is that acceptable?

**Comment by yuval-airis** [comment]
@concretevitamin - We are also starting to try Skypilot would be happy with that feature.
Regarding the region, yes, that would be acceptable for us. (Not speaking for @michalwols)

**Comment by liorsagi69** [comment]
I would like to add a request too.

Also to @michalwols - I have a similar issue as you. Did you find an alterntive solution in the meantime?

**Comment by concretevitamin** [comment]
Circling back @michalwols @yuval-airis @liorsagi69 -- do you expect to attach an EBS to a 1-node cluster only, or to every node in an n-node cluster (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volumes-multi.html)?

**Comment by yuval-airis** [comment]
In my case, it'd be to every node in an n-node cluster.

**Comment by jackyk02** [comment]
When launching a TPU VM with `sky launch tpu_vm.yaml -c mycluster --cloud gcp --disk-size 300`, the resulting VM is still initialized with a disk size of 100 GB (default size). According to the [documentation](https://cloud.google.com/tpu/docs/setup-persistent-disk), users have to add a persistent disk to expand their local disk capacity as the boot disk of TPU VMs is not resizable. The problem emphasizes the potential necessity for the disk attachment feature.
