### ISSUE TITLE
[Kubernetes] `sky down` doesn't work correctly (for k8s) when current kubeconfig context is different

### ISSUE THREAD

**Issue by hemildesai** [skypilot-org/skypilot#2397]
If I run `sky down -a` and my `kubectl` current context is not the k8s cluster where the pods were created, it will teardown the skypilot cluster but the pods will still be running.

One can reproduce it using

1. Create a skypilot job in your current k8s cluster
2. Change your current context (eg. `kubectl config use-context kind-temp`)
3. Run `sky down -a`
4. Switch back to kind-skypilot and see the pods running.

**Comment by romilbhardwaj** [comment]
Thanks for reporting this @hemildesai! This is important to fix. We probably need to implement `get_current_user_identity` for Kubernetes, using a hash of the current kubecontext (cluster, user, namespace) as the identity:

https://github.com/skypilot-org/skypilot/blob/dd2fc07cabf48829acf64121cadf6978fdf5d7be/sky/clouds/cloud.py#L327-L337

**Comment by hemildesai** [comment]
Sounds good, I can work on fixing this.

**Comment by romilbhardwaj** [comment]
Closed with #2522.
