### ISSUE TITLE
[k8s_cloud_beta1] sky launch hangs for a same cluster name created in kind.

### ISSUE THREAD

**Issue by aviweit** [skypilot-org/skypilot#2413]
Launching a task against a same cluster that was provisioned into a former kind instance - hangs.

Please find below the steps to recreate:

1. `sky local up` to spin up `kind` skypilot cluster
2. launch a task (`sky launch -c test ../tasks/hi.yaml`) so that a ray cluster is created in the `kind` cluster
3. `sky local down`
4. `sky local up`
5. launch a task (`sky launch -c test ../tasks/hi.yaml`) will hang

It seems that the former cluster yaml for `test` (under `~/.sky/generated`) is being used which includes the `CommandProxy`  that holds the former NodePort port.

As a workaround, I invoke `sky local down` and then `rm -Rf ~/.sky`

**Comment by romilbhardwaj** [comment]
Thanks for the report @aviweit! I can confirm that I can replicate this. `sky status -r` does not help either, it changes:
```
(base) ➜  ~ sky status -r
Clusters
Refreshing status for 2 clusters ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--D 08-17 20:52:40 backend_utils.py:2043] Refreshing status: Failed to use `ray` to get IPs from cluster 'test'.
NAME  LAUNCHED     RESOURCES                 STATUS   AUTOSTOP  COMMAND
test  1 min ago    1x Kubernetes(2CPU--2GB)  INIT     -         sky launch -c test -- echo...
```

However, `sky down` removes the entry successfully and allows relaunching. 

@aviweit would you like to contribute a fix for this?

**Comment by romilbhardwaj** [comment]
@aviweit - curiously I'm no longer able to replicate the bug on master (dd2fc07cabf48829acf64121cadf6978fdf5d7be). Here's what I'm trying:
1. `sky local up`
2. `sky launch -c test -- echo hi`  - this succeeds
3. `sky local down`
4. `sky local up`
5. `sky launch -c test -- echo hi`  - this again succeeds and creates a new test pod on the kubernetes cluster. According to this issue this step should fail.

Here are my [logs](https://gist.github.com/romilbhardwaj/6b20d3dc535642f3f5dcfe268387466b). Am I missing something?

**Comment by aviweit** [comment]
@romilbhardwaj , this issue might be more related to SSH Jump pod/service; where the stale NodePort port is being used (it is inside command_proxy in the stale cluster yaml).
SSH Jump pod is not in master but in k8s_cloud_beta1 branch.
