### ISSUE TITLE
[Examples] Add remote development example

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#2421]
SkyPilot can be used to host remote dev environments which can be accessed via the browser like [github codespaces](https://github.com/features/codespaces) and [coder](https://coder.com/) [(open source)](https://github.com/coder/code-server). It would be good to have an example YAML for that.

**Comment by tchaton** [comment]
Hey @romilbhardwaj Have you tried https://lightning.ai ?

**Comment by romilbhardwaj** [comment]
Hey @tchaton - lightning.ai looks cool! Would love to try - do you have an open-source offering that runs in my cloud account(s)?

**Comment by raykoaza** [comment]
Can we do opensource version of lightning.ai? and add it to this project?

**Comment by romilbhardwaj** [comment]
I think coder/vscode remote development guide would be a great start. The [Tabby](https://github.com/skypilot-org/skypilot/tree/master/llm/tabby) example guide could be a nice template to work off of.

**Comment by Michaelvll** [comment]
We have added the guide here: https://skypilot.readthedocs.io/en/latest/examples/interactive-development.html

Closing this issue now.
