### ISSUE TITLE
Sky exec doesn't use multi-CPU?

### ISSUE THREAD

**Issue by infwinston** [skypilot-org/skypilot#243]
I submitted my job by `sky exec` but looks like it's only using 1 CPU-core for my matrix computation by PyTorch Sparse.
This is different from directly running the same run commend on the server which uses all CPU-core (10x performance difference in this case).
Is it an expected behavior?

**Comment by infwinston** [comment]
Related issue: https://github.com/skypilot-org/skypilot/issues/1944
I think we should at least document this somewhere before we close it.

**Comment by Michaelvll** [comment]
A workaround for this is to only show CPU instead of `CPU:0.5` for now.
