### ISSUE TITLE
[k8s] Add `sky show-gpus --cloud kubernetes` to show the list of available GPUs

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#2431]
Currently there's no easy way in SkyPilot for users to know which GPUs are available on their Kubernetes cluster. We instead rely on them running `kubectl describe nodes` to manually find GPUs available on their cluster.

We should implement `sky show-gpus --cloud kubernetes` which uses a variant of `kubernetes_utils.get_gpu_label_key_value` to get the list of GPUs available on the cluster and show that to the user.

**Comment by romilbhardwaj** [comment]
Bumping, this is a critical part of the user journey.

**Comment by hemildesai** [comment]
I'm happy to work on this.

**Comment by romilbhardwaj** [comment]
Closed with #2638.
