### ISSUE TITLE
[k8s] CUDA envvars don't work in ssh

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#2453]
CUDA-specific environment variables are dynamically set by the nvidia kubernetes operator and the node's kubelet when a command in a pod or `kubectl exec -it ...` is run. This allows the user to access the GPU in their python programs and through `nvidia-smi`.

Currently, these environment variables are currently not set when we run `ssh mycluster`. As a result, the GPU is unavailable when the user ssh's into the cluster for debugging.

This is related to #2287 and should be closed by #2435.

**Comment by BhAem** [comment]
Is this problem solved?
