### ISSUE TITLE
GCP K80 launch stuck in setup commands

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#2455]
test_job_queue is stuck when running on GCP
```
...
Setting up openssh-sftp-server (1:7.9p1-10+deb10u3) ...
Setting up openssh-server (1:7.9p1-10+deb10u3) ...
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
```
this is during the setup commands.

Repro
```
sky launch --gpus K80 --use-spot --cloud gcp
```

**Comment by romilbhardwaj** [comment]
A data point - this test passed for me a few hours ago

**Comment by Michaelvll** [comment]
@MaoZiming met the same issue recently.

One way is that we directly deprecate K80 support, considering Azure is removing their K80 family.

**Comment by Michaelvll** [comment]
This works normally on the master branch. : )
