### ISSUE TITLE
Smoke tests needed for gitignore in workdir, file_mounts and storage

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#2457]
Can we file an issue for adding smoke test for gitignore in workdir, file_mounts and storage?

_Originally posted by @Michaelvll in https://github.com/skypilot-org/skypilot/issues/2454#issuecomment-1692135219_
            
-----

Can convert this into a smoke test: https://github.com/skypilot-org/skypilot/pull/652

**Comment by romilbhardwaj** [comment]
We have some coverage for gitignore in workdir in `using_file_mounts.yaml`:
https://github.com/skypilot-org/skypilot/blob/39d850a43ff579ead457b1c3150e9d023685bcba/examples/using_file_mounts.yaml#L123-L125

And more extensive coverage for storage in `test_smoke.py::TestStorageWithCredentials`
https://github.com/skypilot-org/skypilot/blob/39d850a43ff579ead457b1c3150e9d023685bcba/tests/test_smoke.py#L3337-L3348

If necessary, we can add more coverage in `using_file_mounts` and `test_xxx_storage_mounts`.
