### ISSUE TITLE
[GCP] ssh profile exceeds 32 KB

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#2475]
A user using os-login on GCP experienced the following issue:
```
(test, pid=4305) I 08-27 23:04:50 authentication.py:192] OS Login is enabled for GCP project <project-id>. Running additional authentication steps.
(test, pid=4305) ERROR: (gcloud.compute.os-login.ssh-keys.add) INVALID_ARGUMENT: Login profile size exceeds 32 KiB. Delete profile values to make additional space.
(test, pid=4305) W 08-27 23:04:52 common_utils.py:350] Caught Command 'gcloud compute os-login ssh-keys add --key-file=/<user>/.ssh/sky-key.pub' returned non-zero exit status 1.. Retrying.
```

It is because multiple spot controllers have been started and deleted, i.e., multiple ssh key pairs are uploaded to the project, causing too many ssh key in the project. The problem is solved by manually deleting some of the keys with `gcloud compute os-login ssh-key remove --key='<key>'`.

We should automatically deal with this: either make the os-login to use the same logic for setting up ssh key (instead of `gcloud compute os-login ssh-key add` as we did in the following (https://github.com/skypilot-org/skypilot/blob/469a62d9ac20043f6d267edcf04f5928dae65034/sky/authentication.py#L244-L249), or we should do some LRU.

**Comment by abatilo** [comment]
What about adding a TTL for added ssh keys?

https://cloud.google.com/sdk/gcloud/reference/compute/os-login/ssh-keys/add#--ttl

**Comment by Michaelvll** [comment]
> What about adding a TTL for added ssh keys?
> 
> https://cloud.google.com/sdk/gcloud/reference/compute/os-login/ssh-keys/add#--ttl

Thanks for the suggestion @abatilo! One problem with the TTL is that this will make a cluster launched a long time ago unable to access. It might be better to remove those keys not in used.

**Comment by abatilo** [comment]
@Michaelvll Actually, if every command consistently sets a `--ttl`, then as long as you're accessing things through `gcloud`, the key timestamp will get updated and if you use a `gcloud` command with `--ttl` set and the key has already expired, the key will be added with an updated timestamp automatically.
