### ISSUE TITLE
Encrypted EBS Volumes

### ISSUE THREAD

**Issue by TRT-BradleyB** [skypilot-org/skypilot#2483]
Hello!

`create_instances: node_provider.py:515` (aws) is failing for me currently, as my organisation's SCP requires EBS storage to be encrypted. Is this an option with SkyPilot currently? I cannot find anything related to this in the documentation.

Thanks!

Bradley

**Comment by Michaelvll** [comment]
> Happy to contribute if I could get a devs take if this is remotely possible. It looks like you guys use Ray, is it a Ray limitation?

Sorry for the delay @TRT-BradleyB. We will really appreciate your contribution. : )
We currently switched to non-ray provisioner implementation. The creation of the instances use the configuration specified in the lines below. All the configurations inherit from the boto3 API, and will be directly passed to the API: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2/service-resource/create_instances.html

https://github.com/skypilot-org/skypilot/blob/ef8839acfd8de1b0cdd511c9f279f974e8c7c2de/sky/templates/aws-ray.yml.j2#L70-L128


If there is an argument that controls the encryption, we should be able to pass it into the creation process. For the interface, we can probably have a config in our `~/.sky/config.yaml` to specify that the EBS should be encrypted, and pass the arguments in the code.
```yaml
aws:
    ebs_crypted: true
```

**Comment by concretevitamin** [comment]
@fozziethebeat bumped this.

**Comment by fozziethebeat** [comment]
According to the request syntax for creating an instance there's a `Encrypted': True|False` line.  So i think skypilot/sky/templates/aws-ray.yml.j2 can be updated with an extension to the `Ebs` stanza with something like `Encrypted: {{disk_encrypted}}`

**Comment by fozziethebeat** [comment]
From a configuration standpoint, it might be easier to make an option that's similar to `disk_size` in the resources stanza.  I at least haven't setup a `.sky/config.yaml` and it might be a hassle to get multiple users to do that right.  But setting it in a task config seems much more regular practice.
