### ISSUE TITLE
[Feature Request] Can SkyPilot create subnets automatically?

### ISSUE THREAD

**Issue by franklsf95** [skypilot-org/skypilot#2484]
I got this while launching an instance in a new region:

```
I 08-29 18:22:11 cloud_vm_ray_backend.py:1704] Launching on AWS us-east-1 (us-east-1a,us-east-1b,us-east-1d,us-east-1f)
W 08-29 18:22:51 cloud_vm_ray_backend.py:836] Got error(s) in all zones of us-east-1:
W 08-29 18:22:51 cloud_vm_ray_backend.py:841]   RuntimeError: SKYPILOT_ERROR_NO_NODES_LAUNCHED: No usable subnets found for node type ray.head.default, try manually creating an instance in your specified region to populate the list of subnets and trying this again. Note that the subnet must map public IPs on instance launch unless you set `use_internal_ips: true` in the `provider` config.
W 08-29 18:22:51 cloud_vm_ray_backend.py:1984] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in us-east-1. Try changing resource requirements or use another region.
```

Is it a deliberate choice that SkyPilot chooses not to create a subnet for me? Could you help me understand the rationale?

**Comment by Michaelvll** [comment]
We will create `skypilot-vpc` for GCP if there is no VPC satisfying the required region. We can probably do someting similar for AWS as well.

For more context, why is the subnets not exist in your AWS account? It seems AWS should create a default VPC with subnets on every availability zone for every region. @franklsf95

**Comment by franklsf95** [comment]
I think this probably doesn't apply to regular users. My project was created by Jon and maybe there was some special handling there.
