### ISSUE TITLE
[k8s] Share SSH jump pod across users

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#2499]
For nodeport networking mode, we currently create one jump pod per user. Ideally want to share the same jump pod across users to minimize the number of open ports required and/or resource consumption. 

Potential solutions include assuming a common namespace is accessible to all users, and creating/running the jumppod in this shared namespace. Need to validate this design choice with users first.

**Comment by Michaelvll** [comment]
Duplicated with #2598. Closing this for now.
