### ISSUE TITLE
UX: `sky launch` refreshing many catalogs is slow

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#2501]
`sky launch` seems to refresh many catalog files sequentially, and every 7 hours. This makes the UX much less snappy than before. We need to optimize and/or rethink this update strategy.

**Comment by romilbhardwaj** [comment]
+1, and it's particularly annoying on slower connections/connections where raw.github is blocked (#2349).

**Comment by concretevitamin** [comment]
A new refresh just took ~15 sec. A next run took ~4 sec before the optimizer table is printed out.
