### ISSUE TITLE
Failed to run quickstart using AWS

### ISSUE THREAD

**Issue by stin7** [skypilot-org/skypilot#2509]
I have AWS setup. When I run the [Quickstart](https://skypilot.readthedocs.io/en/latest/getting-started/quickstart.html) tutorial I get these errors. I have tried with both conda and docker per the installation instructions. I'm on MacOS 13.4 M1.

(Note: the logs were long so I only kept what I thought was relevant, I can share more if needed. Note also I redacted the IP address.)

```
...
Defaulting to user installation because normal site-packages is not writeable
...
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fa7cc899220>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pip/
ERROR: Could not find a version that satisfies the requirement pip (from versions: none)
ERROR: No matching distribution found for pip
bash: type: python: not found
bash: type: pip: not found
WARNING: There was an error checking the latest version of pip.
...
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fe4d74e5300>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/ray/
ERROR: Could not find a version that satisfies the requirement ray[default]==2.4.0 (from versions: none)
ERROR: No matching distribution found for ray[default]==2.4.0
WARNING: There was an error checking the latest version of pip.
WARNING: There was an error checking the latest version of pip.
WARNING: Skipping skypilot as it is not installed.
Processing ./.sky/wheels/84ade8c64eb77480aef81955938246d1/skypilot-1.0.0.dev0-py3-none-any.whl
...

WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fa2ceae7220>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pendulum/
ERROR: Could not find a version that satisfies the requirement pendulum (from skypilot[aws]) (from versions: none)
ERROR: No matching distribution found for pendulum
WARNING: There was an error checking the latest version of pip.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'sky'
...

2023-09-04 03:39:28,123 INFO log_timer.py:25 -- NodeUpdater: i-0e8dbb4cae001ec6f: Setup commands failed [LogTimer=338358ms]
2023-09-04 03:39:28,126 INFO log_timer.py:25 -- NodeUpdater: i-0e8dbb4cae001ec6f: Applied config c90cd576e20ec0e5c173b84a63668518d8d6a77b  [LogTimer=434145ms]
2023-09-04 03:39:29,923 INFO log_timer.py:25 -- AWSNodeProvider: Set tag ray-node-status=update-failed on ['i-0e8dbb4cae001ec6f']  [LogTimer=787ms]
2023-09-04 03:39:29,928 ERR updater.py:158 -- New status: update-failed
2023-09-04 03:39:29,929 ERR updater.py:160 -- !!!
2023-09-04 03:39:29,930 VERR updater.py:168 -- {'message': 'SSH command failed.'}
2023-09-04 03:39:29,931 ERR updater.py:170 -- SSH command failed.
2023-09-04 03:39:29,932 ERR updater.py:172 -- !!!

I 09-04 03:39:30 cloud_vm_ray_backend.py:815] ====== stderr ======
Dropping the empty legacy field head_node. head_nodeis not supported for ray>=2.0.0. It is recommended to removehead_node from the cluster config.
Dropping the empty legacy field worker_nodes. worker_nodesis not supported for ray>=2.0.0. It is recommended to removeworker_nodes from the cluster config.
ssh: connect to host <IP_ADDR> port 22: Connection timed out
ssh: connect to host <IP_ADDR> port 22: Connection timed out
ssh: connect to host <IP_ADDR> port 22: Connection timed out
ssh: connect to host <IP_ADDR> port 22: Connection timed out
ssh: connect to host <IP_ADDR> port 22: Connection timed out
ssh: connect to host <IP_ADDR> port 22: Connection refused
Warning: Permanently added '<IP_ADDR>' (ECDSA) to the list of known hosts.
Shared connection to <IP_ADDR> closed.
Shared connection to <IP_ADDR> closed.
Shared connection to <IP_ADDR> closed.
Shared connection to <IP_ADDR> closed.
Shared connection to <IP_ADDR> closed.
2023-09-04 03:39:30,155 PANIC commands.py:819 -- Failed to setup head node.
Traceback (most recent call last):
  File "/tmp/skypilot_ray_up_yzmuokj1.py", line 76, in <module>
    sdk.create_or_update_cluster('/root/.sky/generated/mycluster.yml', **{'no_restart': True})
  File "/opt/conda/lib/python3.9/site-packages/ray/autoscaler/sdk/sdk.py", line 38, in create_or_update_cluster
    return commands.create_or_update_cluster(
  File "/opt/conda/lib/python3.9/site-packages/ray/autoscaler/_private/commands.py", line 282, in create_or_update_cluster
    get_or_create_head_node(
  File "/opt/conda/lib/python3.9/site-packages/ray/autoscaler/_private/commands.py", line 819, in get_or_create_head_node
    cli_logger.abort("Failed to setup head node.")
  File "/opt/conda/lib/python3.9/site-packages/ray/autoscaler/_private/cli_logger.py", line 614, in abort
    raise exc_cls(msg)
click.exceptions.ClickException: Failed to setup head node.


Clusters
NAME       LAUNCHED    RESOURCES                        STATUS  AUTOSTOP  COMMAND                       
mycluster  7 mins ago  1x AWS(p3.2xlarge, {'V100': 1})  INIT    -         sky launch -c mycluster h...  

RuntimeError: Errors occurred during provision; check logs above.
```

Any tips on how to debug? Looks like it failed to install sky and that caused a ModuleNotFound error, but I have no idea how to fix

**Comment by stin7** [comment]
Just tried with lambda and it worked, so it looks like it's an AWS issue.

**Comment by concretevitamin** [comment]
Hi @stin7: what’s the SkyPilot version you are using? Can check 
```
sky -v
```

**Comment by stin7** [comment]
skypilot, version 1.0.0-dev0

**Comment by stin7** [comment]
running `pip install "skypilot[all]"=0.3.3` worked.

Note that before I was just running "pip install skypilot" so the default pip is pulling that dev version...

**Comment by stin7** [comment]
I'll leave open in case someone wants to fix the docs or the root issue. For me the issue is solved with specifying the version

thanks!

**Comment by Michaelvll** [comment]
Thanks for the information! The `1.0.0-dev0` should be installed from your local clone of SkyPilot, could you check which commit version are you on?

**Comment by stin7** [comment]
I checked out master. But it's worth noting I also had this issue when I:
- used the docker instance per installation instructions
- created a new conda env in a totally different directory (also per installation instructions

So I think 'pip install skypilot' is pulling the wrong branch

**Comment by concretevitamin** [comment]
Can this be because you've run `pip install -e ...` before, and then some multiple versions of `sky` exist?

Just tried this in a fresh container:
```console
docker run -it --platform linux/amd64 --name sky --rm -v "$HOME/.config/gcloud:/root/.config/gcloud:rw" continuumio/miniconda3

# Inside
pip install skypilot
```
and 0.3.3 gets printed.

**Comment by stin7** [comment]
After looking some more I don't think it's about the version, I think it's about aws.

`sky -v` shows 0.3.3

This config using lambda works fine, and prints "Hello Skypilot" successfully:

``` yaml
resources:
  cloud: lambda
  accelerators: A10:1

# Working directory (optional) containing the project codebase.
# Its contents are synced to ~/sky_workdir/ on the cluster.
workdir: .

# Typical use: pip install -r requirements.txt
# Invoked under the workdir (i.e., can use its files).
setup: |
  echo "Running setup."
  pip3 install torch

# Typical use: make use of resources, such as running training.
# Invoked under the workdir (i.e., can use its files).
run: |
  echo "Hello, SkyPilot!"
  conda env list
  python cuda.py
```

However switching the cloud to aws (and a machine type I have quota on) does not work.

``` yaml
resources:
  cloud: aws
  accelerators: V100:1

# Working directory (optional) containing the project codebase.
# Its contents are synced to ~/sky_workdir/ on the cluster.
workdir: .

# Typical use: pip install -r requirements.txt
# Invoked under the workdir (i.e., can use its files).
setup: |
  echo "Running setup."
  pip3 install torch

# Typical use: make use of resources, such as running training.
# Invoked under the workdir (i.e., can use its files).
run: |
  echo "Hello, SkyPilot!"
  conda env list
  python cuda.py
```

Logs:
``` text
2023-09-07 20:46:09,935 INFO log_timer.py:25 -- NodeUpdater: i-06cbc4b9ae099634a: Setup commands failed [LogTimer=337893ms]
2023-09-07 20:46:09,936 INFO log_timer.py:25 -- NodeUpdater: i-06cbc4b9ae099634a: Applied config 0b51cfe04bc9529b266939eb193ebc16a5787864  [LogTimer=431519ms]
2023-09-07 20:46:11,514 INFO log_timer.py:25 -- AWSNodeProvider: Set tag ray-node-status=update-failed on ['i-06cbc4b9ae099634a']  [LogTimer=572ms]
2023-09-07 20:46:11,515 ERR updater.py:158 -- New status: update-failed
2023-09-07 20:46:11,515 ERR updater.py:160 -- !!!
2023-09-07 20:46:11,515 VERR updater.py:168 -- {'message': 'SSH command failed.'}
2023-09-07 20:46:11,515 ERR updater.py:170 -- SSH command failed.
2023-09-07 20:46:11,515 ERR updater.py:172 -- !!!

I 09-07 20:46:11 cloud_vm_ray_backend.py:816] ====== stderr ======
Dropping the empty legacy field head_node. head_nodeis not supported for ray>=2.0.0. It is recommended to removehead_node from the cluster config.
Dropping the empty legacy field worker_nodes. worker_nodesis not supported for ray>=2.0.0. It is recommended to removeworker_nodes from the cluster config.
ssh: connect to host 52.3.230.134 port 22: Operation timed out
ssh: connect to host 52.3.230.134 port 22: Operation timed out
ssh: connect to host 52.3.230.134 port 22: Operation timed out
ssh: connect to host 52.3.230.134 port 22: Operation timed out
ssh: connect to host 52.3.230.134 port 22: Operation timed out
ssh: connect to host 52.3.230.134 port 22: Connection refused
Warning: Permanently added '52.3.230.134' (ED25519) to the list of known hosts.
Shared connection to 52.3.230.134 closed.
Shared connection to 52.3.230.134 closed.
Shared connection to 52.3.230.134 closed.
Shared connection to 52.3.230.134 closed.
Shared connection to 52.3.230.134 closed.
2023-09-07 20:46:11,668 PANIC commands.py:819 -- Failed to setup head node.
Traceback (most recent call last):
  File "/var/folders/nk/9hj3dg_s43762868zwq624lc0000gn/T/skypilot_ray_up_f30_eyip.py", line 76, in <module>
    sdk.create_or_update_cluster('/Users/stin/.sky/generated/mycluster.yml', **{'no_restart': True})
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ray/autoscaler/sdk/sdk.py", line 38, in create_or_update_cluster
    return commands.create_or_update_cluster(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ray/autoscaler/_private/commands.py", line 282, in create_or_update_cluster
    get_or_create_head_node(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ray/autoscaler/_private/commands.py", line 819, in get_or_create_head_node
    cli_logger.abort("Failed to setup head node.")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ray/autoscaler/_private/cli_logger.py", line 614, in abort
    raise exc_cls(msg)
click.exceptions.ClickException: Failed to setup head node.

Clusters
NAME       LAUNCHED    RESOURCES                        STATUS  AUTOSTOP  COMMAND                       
mycluster  7 mins ago  1x AWS(p3.2xlarge, {'V100': 1})  INIT    -         sky launch -c mycluster h...  

RuntimeError: Errors occurred during provision; check logs above.
```

**Comment by Michaelvll** [comment]
Thanks for the detailed errros @stin7! It seems to be a problem with the wheel building for skypilot in your first log. 
```
ERROR: Could not find a version that satisfies the requirement pendulum (from skypilot[aws]) (from versions: none)
ERROR: No matching distribution found for pendulum
WARNING: There was an error checking the latest version of pip.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'sky'
```

Do you see the same error in your second log?


Could you have a try with the following command to use the nightly build of skypilot? We have fixed a bunch of wheel/ssh key related issues in recent fixes (0.3.3 is about 2 months old).

```
pip uninstall skypilot
pip install -U "skypilot-nightly[aws]"
```

**Comment by Michaelvll** [comment]
This is issue should have been solved in our latest master. : )

**Comment by HongLouyemeng** [comment]
> This is issue should have been solved in our latest master. : )

Hi，I get the same error, unable to execute skypilot's quickstart in AWS
**skypilot, version 1.0.0-dev0**
<img width="464" alt="image" src="https://github.com/skypilot-org/skypilot/assets/48181529/0b510322-92d0-43fb-8852-cc7c48b238f4">
<img width="708" alt="image" src="https://github.com/skypilot-org/skypilot/assets/48181529/11c09892-39f0-4525-a5c6-a9da48787fcf">

**Comment by HongLouyemeng** [comment]
**I have increased the limit for the corresponding instance, [All G and VT Spot Instance Requests](https://us-east-2.console.aws.amazon.com/servicequotas/home/services/ec2/quotas/L-3819A6DF), and request GPU:T4, error Found no quota for g4dn.xlarge on-demand instances in region us-east-2 in AWS**

**Comment by concretevitamin** [comment]
> **I have increased the limit for the corresponding instance, [All G and VT Spot Instance Requests](https://us-east-2.console.aws.amazon.com/servicequotas/home/services/ec2/quotas/L-3819A6DF), and request GPU:T4, error Found no quota for g4dn.xlarge on-demand instances in region us-east-2 in AWS**

Hi @HongLouyemeng -- did the quota request go to _spot_ or _on-demand_ instances?

**Comment by HongLouyemeng** [comment]
> > **I have increased the limit for the corresponding instance, [All G and VT Spot Instance Requests](https://us-east-2.console.aws.amazon.com/servicequotas/home/services/ec2/quotas/L-3819A6DF), and request GPU:T4, error Found no quota for g4dn.xlarge on-demand instances in region us-east-2 in AWS**
> 
> Hi @HongLouyemeng -- did the quota request go to _spot_ or _on-demand_ instances?
sure,It is available in the aws ec2 spot console.
<img width="803" alt="image" src="https://github.com/skypilot-org/skypilot/assets/48181529/c9e27cc5-00c0-4c11-bd2f-bdca41ae87ad">
<img width="1027" alt="image" src="https://github.com/skypilot-org/skypilot/assets/48181529/8e847b54-b120-41cc-ac3f-008b1804315e">
<img width="1365" alt="image" src="https://github.com/skypilot-org/skypilot/assets/48181529/26f20475-cd10-46ab-a8b5-0c78244a2e49">

**Comment by concretevitamin** [comment]
According to `Found no quota for g4dn.xlarge on-demand instances in region us-east-2 in AWS`, it seems like the `sky launch` command requested an on-demand rather than spot instance. Could you confirm that, and/or retry with:
```
sky launch --use-spot --gpus T4
```
?

**Comment by HongLouyemeng** [comment]
> According to `Found no quota for g4dn.xlarge on-demand instances in region us-east-2 in AWS`, it seems like the `sky launch` command requested an on-demand rather than spot instance. Could you confirm that, and/or retry with:
> 
> ```
> sky launch --use-spot --gpus T4
> ```
> 
> ?
Hi, thanks for you help, It works, but get  capacity  error
<img width="1037" alt="image" src="https://github.com/skypilot-org/skypilot/assets/48181529/4be41bdb-be76-4014-bcd1-adac1f177ba0">
**Multiple AWS instances satisfy T4:1. The cheapest AWS(g4dn.xlarge[Spot], {'T4': 1}) is considered among:
I 02-23 17:47:03 optimizer.py:925] ['g4dn.xlarge', 'g4dn.2xlarge', 'g4dn.4xlarge', 'g4dn.8xlarge', 'g4dn.16xlarge'].
I 02-23 17:47:03 optimizer.py:925] 
I 02-23 17:47:03 optimizer.py:931] To list more details, run 'sky show-gpus T4'.
I 02-23 17:47:04 cloud_vm_ray_backend.py:1373] To view detailed progress: tail -n100 -f /root/sky_logs/sky-2024-02-23-17-46-16-137640/provision.log
I 02-23 17:47:05 provisioner.py:76] Launching on AWS us-east-2 (us-east-2a)
⠏ Launching
⠙ Launching
W 02-23 17:47:42 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient g4dn.xlarge capacity in the Availability Zone you requested (us-east-2a). Our system will be working on provisioning additional capacity. You can currently get g4dn.xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-2b, us-east-2c.
⠙ Launching
W 02-23 17:47:43 cloud_vm_ray_backend.py:2036] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in us-east-2a. Try changing resource requirements or use another zone.
W 02-23 17:47:43 cloud_vm_ray_backend.py:2045] 
W 02-23 17:47:43 cloud_vm_ray_backend.py:2045] Provision failed for 1x AWS(g4dn.xlarge[Spot], {'T4': 1}) in us-east-2a. Trying other locations (if any).**
