### ISSUE TITLE
UX: image 'xxx' not found error should print to-fix and cloud command used to query

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#2519]
See https://github.com/run-house/runhouse/issues/100. An error like `ValueError: Image 'pytorch-latest-cpu' not found in GCP.` is not informative enough to help users debug. Let's print something like a to-fix and cloud command used to query.

(Thanks @steve-marmalade for raising this!)

**Comment by concretevitamin** [comment]
`Image 'docker:xxxx' not found ...` too.

**Comment by steve-marmalade** [comment]
In case it helps, here are the steps I took to get the image_id:

1. Choose an image family [from the table in the docs](https://cloud.google.com/deep-learning-vm/docs/images#deciding)

2. Run:
```
export IMAGE_FAMILY="pytorch-latest-cpu"

gcloud compute images list \
    --project deeplearning-platform-release \
    --format="value(NAME)" \
    --filter="family=${IMAGE_FAMILY}" \
| xargs -I {} echo "projects/deeplearning-platform-release/global/images/{}" \
| less
```
