### ISSUE TITLE
Cluster gets stuck in INIT state when pulling docker image fails

### ISSUE THREAD

**Issue by aido-ai** [skypilot-org/skypilot#2523]
I'm running into an issue when launching a local Kubernetes cluster for the skypilot project where the cluster gets stuck in an INIT state if the docker image pull fails. (skypilot commit: 7d59ff9b4c2306c85ef61aa8026a0f2a24b8608c)

Specifically, when the image us-central1-docker.pkg.dev/skypilot-375900/skypilotk8s/skypilot:latest is unable to be pulled due to network restrictions. This leaves the cluster in an initializing state.

Attempts to stop or terminate the cluster fail with the error:
```
Terminating cluster sky-0e1c...failed.
Reason: builtins.RuntimeError: Cluster 'sky-0e1c-xxx' is locked by /home/xxxx/.sky/.sky-0e1c-xxx.lock. Check to see if it is still being launched..
```
It seems the INIT state can only be resolved by waiting for the cluster launch to time out.

Is there a way to gracefully handle or recover from a failed docker image pull during cluster initialization? Being stuck in this state blocks re-use of the cluster name as well.

Let me know if any other details would be helpful!

**Comment by romilbhardwaj** [comment]
Thanks for the report @aido-ai. We should add additional checks to fail early if image pull fails.

To help us fix this, can you share the output of `kubectl describe pods` when the provisioning is stuck? Is the error shown `ImagePullBackOff`?

Also, looks like you might be trying to run `sky down` when `sky launch` is still running. If you want to terminate earlier, ctrl + c the `sky launch` process and after that you should be able to run `sky down` successfully.

**Comment by aido-ai** [comment]
> Thanks for the report @aido-ai. We should add additional checks to fail early if image pull fails.
> 
> To help us fix this, can you share the output of `kubectl describe pods` when the provisioning is stuck? Is the error shown `ImagePullBackOff`?
> 
> Also, looks like you might be trying to run `sky down` when `sky launch` is still running. If you want to terminate earlier, ctrl + c the `sky launch` process and after that you should be able to run `sky down` successfully.

-- k describe POD
```bash
Events:
  Type     Reason   Age                   From     Message
  ----     ------   ----                  ----     -------
  Warning  Failed   50m (x347 over 34h)   kubelet  Failed to pull image "us-central1-docker.pkg.dev/skypilot-375900/skypilotk8s/skypilot:latest": rpc error: code = Unknown desc = Error response from daemon: Get "https://us-central1-docker.pkg.dev/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Normal   BackOff  44s (x8646 over 34h)  kubelet  Back-off pulling image "us-central1-docker.pkg.dev/skypilot-375900/skypilotk8s/skypilot:latest"
```

**Comment by landscapepainter** [comment]
@aido-ai Thanks for reporting this issue. I'm currently trying to reproduce this issue. Do you mind sharing (1) what network restriction you have and (2) what linux distribution you are using? Also, it'd be great if you can share what `k describe POD` outputs immediately after it gets stuck with `sky launch` so other `Events` related to the pod appears as well(`Events` get's removed after 60min by default)

**Comment by aido-ai** [comment]
> 

1. In China, the default *.pkg.dev , which is hosted by google, can not access directly .
2. Linux 6.2.0-32-generic #32~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 18 10:40:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```bash
Normal   Scheduled  84s                default-scheduler  Successfully assigned default/sky-3002-ericjiang-c99c-ray-head to minikube
  Warning  Failed     67s                kubelet            Failed to pull image "us-central1-docker.pkg.dev/skypilot-375900/skypilotk8s/skypilot:latest": rpc error: code = Unknown desc = Error response from daemon: Get "https://us-central1-docker.pkg.dev/v2/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  Failed     39s (x2 over 67s)  kubelet            Error: ErrImagePull
  Warning  Failed     39s                kubelet            Failed to pull image "us-central1-docker.pkg.dev/skypilot-375900/skypilotk8s/skypilot:latest": rpc error: code = Unknown desc = Error response from daemon: Get "https://us-central1-docker.pkg.dev/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Normal   BackOff    25s (x2 over 67s)  kubelet            Back-off pulling image "us-central1-docker.pkg.dev/skypilot-375900/skypilotk8s/skypilot:latest"
  Warning  Failed     25s (x2 over 67s)  kubelet            Error: ImagePullBackOff
  Normal   Pulling    12s (x3 over 82s)  kubelet            Pulling image "us-central1-docker.pkg.dev/skypilot-375900/skypilotk8s/skypilot:latest"
```

**Comment by landscapepainter** [comment]
@aido-ai Awesome. Thanks for update! Also, to answer your question on

> Is there a way to gracefully handle or recover from a failed docker image pull during cluster initialization? Being stuck in this state blocks re-use of the cluster name as well.

you can run `rm /home/xxxx/.sky/.sky-0e1c-xxx.lock` and then run `sky down sky-0e1c-xxx -y`. This will clear off the lock and remove the name from the local db allowing you to reuse the name.
