### ISSUE TITLE
Docker permission issues about Lambda's vm image

### ISSUE THREAD

**Issue by aido-ai** [skypilot-org/skypilot#2525]
When I use Lambda's virtual machine (VM) and run Docker inside the VM, I encountered permission issues, which should be caused by incorrect permission settings of the corresponding skypilot image.

-----
resources:
  cloud: lambda
  accelerators: A10:1 
-----
(base) ubuntu@132-145-172-130:~$ docker pull xxxx
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json": dial unix /var/run/docker.sock: connect: permission denied

**Comment by Michaelvll** [comment]
Thanks for reporting the issue @aido-ai! Will it work if you call `docker` with `sudo docker`? It appears in some cloud images, it does not have the created user correctly setup with the docker permission.
