### ISSUE TITLE
[Provisioner] Adopt the new stopping/termination APIs for clouds

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#2532]
Please refer to #2121 #2199 #2248 
- [ ] `Lambda`
- [ ] `Azure` #2286
- [ ] `Oracle`
- [ ] `IBM`
- [ ] `SCP`

**Comment by landscapepainter** [comment]
I'll take support for `Lambda` to start off.

**Comment by Michaelvll** [comment]
We should look into how to make the following issue work with the latest termination API:
https://github.com/skypilot-org/skypilot/issues/1448#issuecomment-1751892763

**Comment by Michaelvll** [comment]
This should stay open.
