### ISSUE TITLE
[GCP] Enable time sync for GCP clusters

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#2539]
After having a GCP cluster UP for months, the system time has been shifted by 6 mins, which causes the awscli calls fail. We should enable automatic time sync for the system, such as:
```
sudo systemctl start ntp
sudo systemctl enable ntp
```

**Comment by Michaelvll** [comment]
This is critical for long running controllers such as spot and serve.

**Comment by iojw** [comment]
@Michaelvll Which awscli calls are failing because of the time shift?

**Comment by Michaelvll** [comment]
> @Michaelvll Which awscli calls are failing because of the time shift?

Most of the clis should fail due to permission issue. For example, `aws ec2 describe-instances` will raise credential error, while the credential is corrected set.

**Comment by iojw** [comment]
> > @Michaelvll Which awscli calls are failing because of the time shift?
> 
> Most of the clis should fail due to permission issue. For example, `aws ec2 describe-instances` will raise credential error, while the credential is corrected set.

This would be an issue for all clouds right? Not just GCP.

**Comment by Michaelvll** [comment]
Yes, we currently only observe the shift for GCP VM. Not sure if it is because GCP VM is the only VM without automatic time sync.

**Comment by iojw** [comment]
Hmm, that strange because GCP does have automatic time sync: https://cloud.google.com/compute/docs/instances/configure-ntp.

I also booted a quick VM instance on GCP and verified that it's set up properly:
```
(base) gcpuser@ray-sky-5f25-isaac-a64f-head-5d93cb14-compute:~$ chronyc sources
MS Name/IP address         Stratum Poll Reach LastRx Last sample
===============================================================================
^* metadata.google.internal      2   6    77    29  +1304ns[ -208us] +/-  210us
```

**Comment by Michaelvll** [comment]
Interesting, it happened on my cluster launched a while ago, and it seems we were using the image id: `skypilot:cpu-debian-10`, instead of the latest one.

Would you like to have a try with `sky launch --cloud gcp --image-id skypilot:cpu-debian-10` to see if the clock sync is correctly started?

**Comment by iojw** [comment]
Yep, just booted an instance with that `image-id`, and verified that clock sync is correct started using [chrony](https://chrony-project.org/). I wonder if this is caused by some issue with the chrony instance on these clusters.

```
> sky launch --cloud gcp --image-id skypilot:cpu-debian-10
...
> gcpuser@ray-sky-46a1-isaac-a64f-head-f69f29ce-compute:~$ chronyc sources
210 Number of sources = 1
MS Name/IP address         Stratum Poll Reach LastRx Last sample
===============================================================================
^* metadata.google.internal      2   6    77     6    -23us[ -315us] +/-  204us
```
