### ISSUE TITLE
Make existing node into an cluster

### ISSUE THREAD

**Issue by wisechat-eng** [skypilot-org/skypilot#2542]
I have started a few existing nodes in GCP, and I want to make it into cluster so I can use SkyPilot to control. However not sure what is the best way to configure the existing nodes.

**Comment by romilbhardwaj** [comment]
Hi @wisechat-eng - we currently do not support using SkyPilot to manage externally created VMs in GCP. Can you share a bit more about your use case and why you want to manage existing nodes instead of creating new ones with SkyPilot?

**Comment by wisechat-eng** [comment]
Hi, we have a lot of code and environment already set up in the existing node. I want to migrate to have skypilot to manage the note using cluster. Instead of create a new one, I'm wondering if I can just reuse the old one, but have skypilot to connect it as a cluster

**Comment by Michaelvll** [comment]
Hey @wisechat-eng, one quick way to get around this is to clone your original node. You create a [machine image](https://cloud.google.com/compute/docs/machine-images/create-machine-images#create-image-from-instance) for your existing node. And launch a skypilot cluster with that machine image by:
```
sky launch --cloud gcp --image-id projects/<your-project-id>/global/machineImages/<your-machine-image-name> --instance-type <instance-type-of-your-original-instance> -c <cluster-name>
```

With the command above, you will clone a node from your previous node, and all the code / environment will be preserved in the new cluster managed by skypilot, and you can then safely delete your old node.

**Comment by wisechat-eng** [comment]
make sense, thanks Michael. Another use case is that, me and my collegue may want to use SkyPilot to control the same node. Somehow if it is created from my side, he will not see it as a cluster

**Comment by concretevitamin** [comment]
@wisechat-eng To understand more, what's the reason that you desire to share a cluster? Is it due to cost/quota reasons (where launching a new node is not ideal), or is it for collaboration/debugging?

**Comment by bastienjalbert** [comment]
@concretevitamin I'm not wisechat, but honestly both use cases are to consider.

An other use case could be having a Databricks cluster with already provisioned GPU and want to use it with Skypilot cluster capabilities instead of create standalone VMs to achieve tasks. Skypilot would run as agent on target runtime and usable from local command line this way.

**Comment by asaiacai** [comment]
@concretevitamin I'm working with a couple of startups that are working with bare metal machines and they would like to be able to use it through the SkyPilot interface. Right now they either launch using slurm or by logging into each node separately, but slurm is quite bloated for this use case and is annoying to maintain, so something that only requires existing SSH access to create launch the Skypilot runtime would be really attractive I think.

**Comment by romilbhardwaj** [comment]
@asaiacai - that's interesting. If the bare metal machines are self-owned/long-term rentals, have you considered deploying Kubernetes on them and then using SkyPilot + Kubernetes support? Kubernetes' extensive support for devops and observability tooling keeps the ops teams happy, while SkyPilot can support ML engineers who do not need to deal with Kubernetes APIs.

**Comment by Michaelvll** [comment]
Re-open this issue. Related to #3926
