### ISSUE TITLE
How long does benchmarking takes ?

### ISSUE THREAD

**Issue by Hubert-Bonisseur** [skypilot-org/skypilot#2557]
I am currently running a benchmark on a task.
It has been running for close to an hour.

How long does the benchmark take ? Considering many tasks are launched in parallel, the costs add up very quickly. 
Therefore it should be possible to provide a maximum duration or number of steps before stopping the benchmark.

I haven't seen anything related to that in the documentation.

**Comment by concretevitamin** [comment]
@Hubert-Bonisseur SkyBench would run for however long the task is specified to run. This means the user should explicitly set a small number of steps/iterations in the `run` commands.
