### ISSUE TITLE
[storage] Add confirmation prompt to 'sky storage delete' command

### ISSUE THREAD

**Issue by landscapepainter** [skypilot-org/skypilot#2635]
When executing commands like `sky stop` or `sky down` on a cluster, the user is prompted for confirmation before proceeding. For consistency and safety, we should implement a similar confirmation prompt for the `sky storage delete` command, as it currently deletes storage immediately without any confirmation.

Additionally, to provide flexibility, a `--yes` option should be added. This would allow users to bypass the confirmation prompt when they're certain about their actions.

**Comment by aseriesof-tubes** [comment]
I'd like to be assigned this issue!
