### ISSUE TITLE
Custom images: changing auth.ssh_user in aws-ray.yml.j2 doesn't work

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#2674]
Repro: Deep Learning AMI GPU PyTorch 2.0.1 
```
sky launch --image-id ami-034608daa45aee403 --cloud aws --region us-east-1
```

Changed the j2 template to
```
...
auth:
  ssh_user: ec2-user
...
```

Provision log shows this change is in effect, but the launch still fails:
```
...
D 10-06 14:00:12 provisioner.py:257] Waiting for SSH to 44.200.224.223. Try: ssh -T -i '~/.ssh/sky-key' ec2-user@44.200.224.223 -o StrictHostKeyChecking=no -o ConnectTimeout=10s -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 uptime
E 10-06 14:00:12 provisioner.py:491] *** Failed setting up cluster. ***
D 10-06 14:00:12 provisioner.py:492] Stacktrace:
D 10-06 14:00:12 provisioner.py:492] Traceback (most recent call last):
D 10-06 14:00:12 provisioner.py:492] RuntimeError: Failed to SSH to 44.200.224.223 after timeout 600s.
```

**Comment by Michaelvll** [comment]
This is unexpected, we use the cloud-init to setup the username and the ssh key, which should not have this issue, as long as the image has `cloud-init` installed. We need to investigate it.

**Comment by concretevitamin** [comment]
Running `sky launch --image-id ami-034608daa45aee403 --cloud aws --region us-east-1` again on master, without changing the .j2 template, works now. Able to log in as `ubuntu` without additional setup.
