### ISSUE TITLE
Deploy mistral on cloudflare

### ISSUE THREAD

**Issue by mihalt** [skypilot-org/skypilot#2677]
I am trying to deploy by [this ](https://docs.mistral.ai/cloud-deployment/skypilot/#skypilot-configuration) config

And get an error (you can see above in the screen, that I have successfull access to Cloudflare by `sky check` command)
![изображение](https://github.com/skypilot-org/skypilot/assets/30621622/c41f980e-2188-4ef5-bb79-f1a0f5aa6cf1)

When I am trying to use something like
```
resources:
  cloud: cloudflare
```

I get an error like
```
>>> sky launch -c mistral-7b mistral-7b-v0.1.yaml
Task from YAML spec: mistral-7b-v0.1.yaml
ValueError: Invalid resources YAML: 'cloud' is not one of ['aws', 'azure', 'gcp', 'ibm', 'kubernetes', 'lambda', 'oci', 'scp']. Check problematic field(s): $.cloud
```

**Comment by romilbhardwaj** [comment]
Hi @mihalt - on cloudflare, SkyPilot currently only supports reading and writing data from R2 object store. Running tasks on cloudflare is not supported. 

Are you trying to use [cloudflare workers](https://developers.cloudflare.com/workers/)? Or is there some other compute platform offered on cloudflare that you want to use?

**Comment by mihalt** [comment]
> Hi @mihalt - on cloudflare, SkyPilot currently only supports reading and writing data from R2 object store. Running tasks on cloudflare is not supported.
> 
> Are you trying to use [cloudflare workers](https://developers.cloudflare.com/workers/)? Or is there some other compute platform offered on cloudflare that you want to use?

I am using just https://developers.cloudflare.com/r2/ with connection of SkyPilot now, as I understand. I created workers, but they were not connected with Mistral yet. Do you have any suggenstions how to use workers for my task?

**Comment by romilbhardwaj** [comment]
Hi @mihalt, we don't support Cloudflare Workers on SkyPilot right now. To launch Mistral, you will need access to one of our supported clouds - AWS, Azure, GCP, IBM Cloud, Lambda Cloud, Oracle Cloud or Samsung Cloud.

For cloudflare, we only support accessing data stored on R2 buckets (see [Sky Storage](https://skypilot.readthedocs.io/en/latest/reference/storage.html)), but I believe that is not required for launching Mistral inference server in the YAML you linked. Please let me know if I'm missing something.

**Comment by romilbhardwaj** [comment]
Closing this issue, but please feel free to reopen if you have any questions.
