### ISSUE TITLE
Add support for AWS Trainium and Inferentia

### ISSUE THREAD

**Issue by mmcclean-aws** [skypilot-org/skypilot#2686]
AWS has their own purpose built silicon offerings AWS Trainium and Inferentia. They both are supported on Ray too. Can we please have them added to Skypilot ?

**Comment by concretevitamin** [comment]
Hello @mmcclean-aws: Inferentia is already supported!
```console
sky launch --gpus Inferentia            
# or
sky launch -t inf2.xlarge 
```

Trainium not yet, but it should be reasonably straightforward to add it. A related guide here: https://github.com/skypilot-org/skypilot/pull/2343 (cc @infwinston).

**Comment by romilbhardwaj** [comment]
Just to add - for inferentia you can follow the guide [here](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/setup/neuron-setup/pytorch/neuron/ubuntu/torch-neuron-ubuntu20.html#setup-torch-neuron-u20) to setup dependencies (`aws-neuronx-tools` and `aws-neuronx-dkms`).

**Comment by spillai** [comment]
FYI One alternative to installing the dependencies is to spin up a pre-baked AMI: 

```yaml
resources:
  cloud: aws
  instance_type: inf2.xlarge
  image_id: ami-09c62125a680f0ead
```

We've tested this internally for Inf2 deployments.

**Comment by mmcclean-aws** [comment]
Great there is support for Inferentia

How can we add support for Trainium ? I tried to look in the source code but couldn't see how to do this

**Comment by mmcclean-aws** [comment]
Raised a PR to add support for AWS Trainium #2690
