### ISSUE TITLE
Managing clusters from different SkyPilot instances

### ISSUE THREAD

**Issue by anttttti** [skypilot-org/skypilot#2698]
Currently, if the computer running SkyPilot fails for some reason, control of the clusters is lost, and these have to be shut down manually from each cloud.

Would it be possible to add support for managing the same clusters from different SkyPilot instances? 

A simple way to do this would be syncing these files somehow:
~/.ssh/config
~/.ssh/sky-key
~/.ssh/sky-key.pub
~/.sky/generated/
~/.sky/benchmark.db
~/.sky/jobs.db
~/.sky/spot_jobs.db

**Comment by romilbhardwaj** [comment]
Hi @anttttti - we can look into this. Can you tell us a bit more about:

1. Where you would like this data to be backed up?
2. Where are you expecting the "different SkyPilot instances" to be running? Are they on the same machine or elsewhere? 

A common workaround used by many users is to use dropbox/google drive to continuously backup their `~/.sky/` directory.

**Comment by anttttti** [comment]
> 1. Where you would like this data to be backed up?
For the use case I have in mind, just having the data somewhere would be good. 

> 2. Where are you expecting the "different SkyPilot instances" to be running? Are they on the same machine or elsewhere?
For my use case, another machine with SkyPilot needs to pick up the clusters, so control to those isn't lost if the first one goes down.

> A common workaround used by many users is to use dropbox/google drive to continuously backup their `~/.sky/` directory.
If there's a common workaround, there should be a feature. Just copying ~/.sky/ wont do, as you also need some of ~/.ssh/ ? And from there just copying ~/.ssh/config could leak user details? So some sort of command to serialize/deserialize the state of SkyPilot to disk could be a good start.
