### ISSUE TITLE
Absence of govcloud regions

### ISSUE THREAD

**Issue by samyoed** [skypilot-org/skypilot#2699]
Hey! was wondering if there was any particular reason that the govcloud regions were left out in the regions list, thanks!

**Comment by concretevitamin** [comment]
Mostly due to the dev team having no access to govcloud to develop this :) We'd love community contributions for it. 

Under the hood, SkyPilot is using EC2 SDK to create/manage instances, so adding this support should be about some plumbing of the "partition" concept? See, e.g., https://github.com/skypilot-org/skypilot/blob/master/sky/provision/aws/instance.py#L139

**Comment by samyoed** [comment]
Will definitely be looking into it, thanks!

**Comment by samyoed** [comment]
So I was thinking it might've been as simple as adding the regions to fetch_aws.py but then when I try running a sample config, it gives me 

No resource satisfying <Cloud>({'T4': 1}) on AWS.
sky.exceptions.ResourcesUnavailableError: Catalog does not contain any instances satisfying the request:
Task(run='conda activate vllm\...')
  resources: <Cloud>({'T4': 1}).
 
So I'm assuming the regions also need to be added somewhere else as well? The regions are available under ~/.sky/catalogs but also when I try "sky show-gpus --region us-gov-west-1 --cloud aws" it gives me 

ValueError: Invalid region 'us-gov-west-1'
List of supported aws regions: ''

**Comment by Michaelvll** [comment]
@samyoed, thanks for trying to add it. To make the modification to `fetch_aws.py`, you will need to run it to get `vms.csv` catalog file and SkyPilot will read from that catalog file for the information. To do so, you can go to the folder where catalogs are stored and run the script:
```bash
cd ~/.sky/catalogs/v5
python -m sky.clouds.service_catalog.data_fetchers.fetch_aws
```

After the `vms.csv` is generated, SkyPilot should be able to find the new region. : )
