### ISSUE TITLE
[Docs] Minimal permission for using EKS/GKE with SkyPilot

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#2702]
It would be nice to provide minimal permission for accessing EKS/GKE clusters in our document in the following https://skypilot.readthedocs.io/en/latest/cloud-setup/cloud-permissions/gcp.html

**Comment by Michaelvll** [comment]
cc'ing @romilbhardwaj

**Comment by Michaelvll** [comment]
It seems `Kubernetes Engine Developer` role is needed for the user account to access the kubernetes cluster with kubectl.

**Comment by romilbhardwaj** [comment]
This should now be covered with https://github.com/skypilot-org/skypilot/pull/3632?
