### ISSUE TITLE
[Provisioner] Fail to update cloud credential on remote VM

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#2714]
The following comment failed to be solved: https://github.com/skypilot-org/skypilot/pull/1702#discussion_r1314337801

To reproduce:
1. `sky launch -c test --cloud aws` 
2. Switch the `gcloud` account
3. `sky launch -c test --cloud aws`, log into the VM and check the gcloud account.

**Comment by concretevitamin** [comment]
It seems this bug means the following dev workflow is broken on master?
```
sky launch -c dbg --cloud aws

# modify some local sky code, e.g., add logging / assert 
# then:
sky launch -c dbg --cloud aws
```
Its provision.log shows that we failed to upgrade due to a `cp` error, which was due to internal file mounts being skipped:
```
...

I 10-17 22:12:42 instance_setup.py:78] --------------------Start: internal_file_mounts --------------------
D 10-17 22:12:42 metadata_utils.py:62] Need to run stage internal_file_mounts on instance i-074b6103a2103bfe6: False
I 10-17 22:12:42 instance_setup.py:82] --------------------End:   internal_file_mounts --------------------
...
I 10-17 22:12:42 instance_setup.py:78] --------------------Start: setup_runtime_on_cluster --------------------
D 10-17 22:12:42 metadata_utils.py:62] Need to run stage setup_runtime_on_cluster on instance i-074b6103a2103bfe6: True
cp: cannot stat '/home/ubuntu/.sky/.runtime_files/0dad3458-e5ad-4d4a-8672-239dec34f69d': No such file or directory
/opt/conda/bin/conda
skypilot                  1.0.0.dev0
...
I 10-17 22:12:47 instance_setup.py:78] --------------------Start: start_skylet_on_head_node --------------------
I 10-17 22:12:47 instance_setup.py:324] Running command on head node: python3 -m sky.skylet.attempt_skylet
ubuntu     25650  0.0  0.3 114020 61856 ?        S    05:05   0:00 python3 -m sky.skylet.skylet
Skylet is running with the latest version.
I 10-17 22:12:48 instance_setup.py:82] --------------------End:   start_skylet_on_head_node --------------------

**Comment by Michaelvll** [comment]
> It seems this bug means the following dev workflow is broken on master?
> 
> ```
> sky launch -c dbg --cloud aws
> 
> # modify some local sky code, e.g., add logging / assert 
> # then:
> sky launch -c dbg --cloud aws
> ```
> 
> Its provision.log shows that we failed to upgrade due to a `cp` error, which was due to internal file mounts being skipped:
> 
> ```
> ...
> 
> I 10-17 22:12:42 instance_setup.py:78] --------------------Start: internal_file_mounts --------------------
> D 10-17 22:12:42 metadata_utils.py:62] Need to run stage internal_file_mounts on instance i-074b6103a2103bfe6: False
> I 10-17 22:12:42 instance_setup.py:82] --------------------End:   internal_file_mounts --------------------
> ...
> I 10-17 22:12:42 instance_setup.py:78] --------------------Start: setup_runtime_on_cluster --------------------
> D 10-17 22:12:42 metadata_utils.py:62] Need to run stage setup_runtime_on_cluster on instance i-074b6103a2103bfe6: True
> cp: cannot stat '/home/ubuntu/.sky/.runtime_files/0dad3458-e5ad-4d4a-8672-239dec34f69d': No such file or directory
> /opt/conda/bin/conda
> skypilot                  1.0.0.dev0
> ...
> I 10-17 22:12:47 instance_setup.py:78] --------------------Start: start_skylet_on_head_node --------------------
> I 10-17 22:12:47 instance_setup.py:324] Running command on head node: python3 -m sky.skylet.attempt_skylet
> ubuntu     25650  0.0  0.3 114020 61856 ?        S    05:05   0:00 python3 -m sky.skylet.skylet
> Skylet is running with the latest version.
> I 10-17 22:12:48 instance_setup.py:82] --------------------End:   start_skylet_on_head_node --------------------
> ```

This should be fine as the wheel_hash will be updated if the sky code is updated, and the internal file mounts will be executed. The problem will only affect the credentials.
