### ISSUE TITLE
[GCP/Spot] Skypilot GCP user credentials expire on controller with SSO

### ISSUE THREAD

**Issue by kuza55** [skypilot-org/skypilot#2738]
Hi,

I have been trying to use skypilot's spot scheduling.

I have run into issues where the controller becomes unresponsive and the ~/.sky/skylet.log file is filled with this error:

```google.auth.exceptions.RefreshError: Reauthentication is needed. Please run `gcloud auth application-default login` to reauthenticate.```

My understanding of the issue is that user credentials and access tokens derived from them expire in relatively short time windows, though I am poking at my setup to see if I am doing something weird: https://stackoverflow.com/questions/69229759/longer-lasting-user-credentials-with-gcloud-auth-prevent-expiration

I have seen suggestions to create service accounts and interact with gcp using a service account, which will likely address this issue, but that feels at least like a documentation bug.

Alternatively using the service account that skypilot creates seems like it would make sense to me.

 - Alex

**Comment by ethansiegl** [comment]
I've also run into this issue but could not resolve

**Comment by kuza55** [comment]
I think only service accounts are supported and the docs try to say this but are a little unclear: https://skypilot.readthedocs.io/en/latest/cloud-setup/cloud-auth.html#gcp

**Comment by concretevitamin** [comment]
Confirmed that with the above,
```
sky spot launch --cloud gcp --cpus 2+ sleep 1000
```
started both a new controller (given that no controller exists in `sky status`) and the spot cluster under the service account. 

To check that, you could click on either the controller VM or the spot cluster VM -> OBSERVABILITY -> LOGS, and check that the logs display the service account (see below right):

<img width="1238" alt="Screen Shot 2023-10-31 at 12 49 09" src="https://github.com/skypilot-org/skypilot/assets/592670/226771af-91e3-4af2-9bd9-a91b4eea598c">
