### ISSUE TITLE
Add axolotl training example

### ISSUE THREAD

**Issue by casper-hansen** [skypilot-org/skypilot#2744]
Axolotl is one of the most popular open-source pertaining and fine-tuning packages that make use of the Huggingface ecosystem.

Speed ups achieved in axolotl:
- Implements sample packing (can be up to 10x faster)
- Implements flash attention
- Implements fused RMSNorm that speeds training 15-20
- Memory efficiency with bitsandbytes 8-bit optimizer

Ease of use:
- Specify a config, start training
- Implements LoRA and QLoRA
- Implements DeepSpeed and FSDP
- Easy monitoring with `wandb`
- Built-in prompt templates
- Pulls and pushes datasets and models from and to Huggingface

https://github.com/OpenAccess-AI-Collective/axolotl

**Comment by concretevitamin** [comment]
This would be great to have. Some users are already using axolotl:

https://github.com/skypilot-org/skypilot/issues/2671#issuecomment-1750776618

https://github.com/skypilot-org/skypilot/issues/2689#issuecomment-1783365365

**Comment by manishiitg** [comment]
```
# jupyter.yaml

name: axolotl

resources:
  accelerators: A100:1
  cloud: gcp
  use_spot: True

file_mounts:
  /sky-notebook:
    source: gs://sky-notebook
    mode: MOUNT

workdir: mistral

setup: |
  docker pull winglian/axolotl:main-py3.10-cu118-2.0.1
  pip install autoawq peft

  

run: |
  docker run --gpus all \
    -v /home/gcpuser/sky_workdir:/sky_workdir \
    -v /root/.cache:/root/.cache \
    winglian/axolotl:main-latest \
    huggingface-cli login --token XXX

  docker run --gpus all \
    -v /home/gcpuser/sky_workdir:/sky_workdir \
    -v /root/.cache:/root/.cache \
    winglian/axolotl:main-latest \
                accelerate launch -m axolotl.cli.train /sky_workdir/hi-qlora.yaml

  
  
  
  


  


```


this would work

**Comment by concretevitamin** [comment]
Awesome @manishiitg !! Would you like to open a PR and push it to [`llm/axolotl`](https://github.com/skypilot-org/skypilot/tree/master/llm)?

**Comment by manishiitg** [comment]
sure will git it a try

**Comment by concretevitamin** [comment]
@casper-hansen This has been added by @manishiitg. Closing this.
