### ISSUE TITLE
Skypilot spot controller is overprovisioned on GCP

### ISSUE THREAD

**Issue by kuza55** [skypilot-org/skypilot#2746]
Hi,

It seems like the spot controller on GCP is overprovisioned, to the extent that GCP showed this warning for me in the console:

```Instance "ray-sky-spot-controller-1b337b63-1b33-head-a191fea6-compute" is underutilized. You can save an estimated $111 per month by switching to the machine type: n2-custom```

**Comment by concretevitamin** [comment]
Hi @kuza55 -- the default spot controller has 8 vCPUs, same as the default spec chosen by `sky launch`. Whether it's over- or under-provisioned depends on the number of concurrent spot jobs you'd like to run.

To switch to a lower-cost spot controller, you could tear down the current one first, then follow: https://skypilot.readthedocs.io/en/latest/examples/spot-jobs.html#customizing-spot-controller-resources

**Comment by csaroff** [comment]
What does the spot controller actually do? I'm confused why it can't always be some really tiny machine.

**Comment by concretevitamin** [comment]
> What does the spot controller actually do? I'm confused why it can't always be some really tiny machine.

The controller runs processes to monitor the entire lifecycle of spot jobs/clusters. Ray is used to launch clusters in some cases and to run these processes, and unfortunately Ray can take up a lot of memory (say 1GB) per such launch process. We’re continuously looking to optimize this resource usage (contributions welcome!).
