### ISSUE TITLE
[Azure] Update default image to support newer cuda versions

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#2751]
The current image used for Azure has an old version of nvidia drivers:
```
(base) azureuser@ray-dbg-2ea4-head-5f89-adf20:~$ nvidia-smi
Thu Nov  2 21:54:46 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.29.05    Driver Version: 495.29.05    CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
```

This version of nvidia drivers does not support CUDA 11.8. This is problematic for many reasons, including the latest pytorch supporting only [CUDA 11.8+](https://pytorch.org/get-started/locally/).

In contrast, AWS and GCP run 5xx.yy nvidia drivers, which support newer cuda versions.

**Comment by Michaelvll** [comment]
This is being fixed by #2468
