### ISSUE TITLE
sky logs and sky queue should be accessible on stopped instances

### ISSUE THREAD

**Issue by csaroff** [skypilot-org/skypilot#2766]
When running `sky logs` on a stopped instance, I receive the following message:

```
$ sky logs sky-bench-hydra-3eps-tk2-1
sky.exceptions.ClusterNotUpError: Tailing logs: skipped for cluster 'sky-bench-hydra-3eps-tk2-1' (status: STOPPED). It is only allowed for UP clusters.
```

Is it possible to have each cluster stream its logs to a cloud storage bucket and have `sky logs` reference that instead? It's a bit tedious(and potentially expensive) to restart clusters just to pull down the logs after a job completes.

**Comment by romilbhardwaj** [comment]
Thanks for raising this @csaroff. This is not yet supported, but we can look into adding this. Related ask for spot jobs - #800.

Meanwhile, a workaround could be to manually copy over the sky logs directory (`~/sky_logs`) at the end of your task. Something like this in your YAML:

```
run: |
  echo hi
  aws s3 sync ~/sky_logs ...
```

**Comment by manishiitg** [comment]
this would be a useful feature, it we can automatically sync logs to cloud storage.

**Comment by concretevitamin** [comment]
@csaroff @manishiitg Any preferences for these options?
- Weights and Biases (free up to some quota)
- Cloud logging solutions (Datadog; native logging services ([example](https://github.com/skypilot-org/skypilot/issues/800#issuecomment-1603709961)); ..)
- Object storage (S3, GC3, ..)
- ..

**Comment by manishiitg** [comment]
Simple cloud storage would work for me

**Comment by csaroff** [comment]
I'd be happy with a gcs integration(though not opposed to elasticsearch or gcp logging). I think the main point is being able to pull those logs seamlessly with `sky logs` regardless of where they're stored
