### ISSUE TITLE
`sky bench -i` only sets autostop once all clusters come online

### ISSUE THREAD

**Issue by csaroff** [skypilot-org/skypilot#2768]
Launch:
```
$ sky bench launch -i 1 test_boot_plus_files.yaml -b test-boot-plus-files
```

5 minutes in:
```
(venv) (base) csaroff in ~/code/bioticsai/ultrasound_classifier on prod ● ● λ sky status --refresh
Clusters
NAME                              LAUNCHED     RESOURCES                           STATUS   AUTOSTOP  COMMAND                       
sky-bench-test-boot-plus-files-0  2 mins ago   1x GCP(n2-standard-2)               UP       -         sky launch /var/folders/z...  
sky-bench-test-boot-plus-files-1  5 mins ago   1x GCP(n1-standard-2, {'T4': 1})    INIT     -         sky launch /var/folders/z...
```

A couple minute later(Forgot to run --refresh so maybe they both have autostop enabled now?):
```bash
(venv) (base) csaroff in ~/code/bioticsai/ultrasound_classifier on prod ● ● λ sky status                               
Clusters
NAME                              LAUNCHED     RESOURCES                           STATUS   AUTOSTOP  COMMAND                       
sky-bench-test-boot-plus-files-1  2 mins ago   1x GCP(n1-standard-2, {'T4': 1})    UP       -         sky launch /var/folders/z...  
sky-bench-test-boot-plus-files-0  5 mins ago   1x GCP(n2-standard-2)               UP       1m        sky launch /var/folders/z...
```

After the run finished:
```
(venv) (base) csaroff in ~/code/bioticsai/ultrasound_classifier on prod ● ● λ sky status --refresh
Clusters
NAME                              LAUNCHED     RESOURCES                           STATUS   AUTOSTOP  COMMAND                       
sky-bench-test-boot-plus-files-1  8 mins ago   1x GCP(n1-standard-2, {'T4': 1})    STOPPED  1m        sky launch /var/folders/z...  
sky-bench-test-boot-plus-files-0  12 mins ago  1x GCP(n2-standard-2)               STOPPED  1m        sky launch /var/folders/z...
```

So eventually everything gets auto-stopped, but if for some reason one of the clusters in your run is taking forever to start(ex. skypilot is searching 20 different gcp regions for an A100:8 instance), the clusters that have completed will just run-up your cloud costs even though they aren't doing anything. It also seems to imply that if I lose internet connectivity somehow while the benchmark is starting, skypilot will never stop those clusters that have already started.

**Comment by concretevitamin** [comment]
To clarify, 

- Each individual candidate cluster has its own process running `sky launch -i<your setting> ..`, so even if there's a straggler candidate, the rest of the candidates will proceed to run first + apply the autostop setting.
- The autostop logic is run on the remote clusters. So it's safe to close your laptop as soon as all clusters/jobs are launched (laptop doesn't have to stay up till they finish).

Do you see any places in docs where the above info should be added?

**Comment by csaroff** [comment]
@concretevitamin I apologize, I think I must have been confused by the information coming from `sky cost-report` that erroneously showed the instances stopping at the same times.

I am confused why `sky status` reports autostop not being enabled in my first `sky status --refresh` example thought.

**Comment by concretevitamin** [comment]
No prob. During `sky launch`, "setting autostop" is a step that runs after the cluster has been provisioned (transitioned from INIT to UP) and before the actual job starts running. So I'm guessing in
```
(venv) (base) csaroff in ~/code/bioticsai/ultrasound_classifier on prod ● ● λ sky status --refresh
Clusters
NAME                              LAUNCHED     RESOURCES                           STATUS   AUTOSTOP  COMMAND                       
sky-bench-test-boot-plus-files-0  2 mins ago   1x GCP(n2-standard-2)               UP       -         sky launch /var/folders/z...  
sky-bench-test-boot-plus-files-1  5 mins ago   1x GCP(n1-standard-2, {'T4': 1})    INIT     -         sky launch /var/folders/z...
```
this command was run 
- right after candidate 0 transitioned to UP (but before autostop setting took place)
- during candidate 1's provisioning

**Comment by csaroff** [comment]
Got it! Okay, this is just an idea and probably not a high priority at all, but for additional safety, when you initially provision the cluster, would it make sense to add a "max run duration" of an hour or something in case the sky process that would normally setup autostop is killed or something?
