### ISSUE TITLE
[Storage] Investigate using rclone sync to replace gsutil rsync

### ISSUE THREAD

**Issue by landscapepainter** [skypilot-org/skypilot#2771]
According to some user report, `rclone sync` is an order of magnitude faster than `gsutil rsync`, which SkyPilot uses to upload from local node to cloud storage and to download from cloud storage to local node.

The user reported a case of fetching millions of images and json files worth of ~500GB from the storage to the node:

> Yeah, in my case, it was a dataset with millions of images and json files. The full dataset was ~500GB. Not sure the average file size.

With some loose benchmark on 4 categories below, it turns out that using rclone sync is much faster than gsutil rsync in a case there's huge number of small files being fetched from cloud storage(GS) to node(GCP).

1. uploading 6 of 10GB files from local node(GCP) to cloud storage(GS)
2. uploading 1000 of 1MB files from local node(GCP) to cloud storage(GS)
3. downloading 6 of 10GB files from cloud storage(GS) to local node(GCP)
4. downloading 1000 of 1MB files from cloud storage(GS) to local node(GCP)

![image](https://github.com/skypilot-org/skypilot/assets/34902420/81ecb34c-c775-46de-a500-614dab229326)

We should investigate if rclone sync has all the features we need to run smoothly with SkyPilot, and replace `gsutil rsync` with `rclone sync` if feasible.

**Update**: Added a new benchmark of `gsutil -m copy -r`, and used a larger amount of data using 10000 of 1MB files as opposed to the previous benchmark above which has 1000 of 1MB files.

![image](https://github.com/skypilot-org/skypilot/assets/34902420/177c054c-9f1f-40df-a3c7-065a8b09eb58)

**Comment by landscapepainter** [comment]
We also want to investigate syncing `workdir` with `rclone sync` for managed spot jobs as well as files under `workdir` will be uploaded to cloud storage first and then fetched to the spot VM with first start or recovering from preemption

**Comment by dtran24** [comment]
Hey, happy to pick this up! Some thoughts so far:
- Seems like the `upload` method will be a good place to start looking at making changes 
https://github.com/skypilot-org/skypilot/blob/76c5af9cc24663528d5e5f57253f252a9aa4d8bf/sky/data/storage.py#L1541-L1553
- While I haven't done any manual tests yet, from a cursory reading docs and community posts of `gsutil rsync` and `rclone sync`, seems like `rclone` can replace `gsutil rsync`. Some community posts: 
    - https://github.com/rclone/rclone/issues/1275
    - https://www.reddit.com/r/rclone/comments/vzto6g/can_rclone_replace_rsync/

Please let me know if I'm on the right track, or if there's anything else I should know before diving more into the solution.

**Comment by landscapepainter** [comment]
Welcome to Skypilot @dtran24! 

`upload` method is a great place to start. After, you can take a look into `_execute_file_mounts` with `cloud_stores.py/make_sync_dir_command` and `make_sync_file_command` for fetching files/dirs from GCS to remote VM.

One thing to note is that IBM COS uses `rclone` as well, so we have an abstraction for rclone, `data_utils.Rclone`, that can be utilized.

**Comment by sqr00t** [comment]
Heya! I wonder if it's worth to add exploring [s5cmd](https://github.com/peak/s5cmd). For AWS, there's some [benchmarking results](https://joshua-robinson.medium.com/s5cmd-for-high-performance-object-storage-7071352cc09d) to take with a grain of salt. Maybe an adaptor over this would allow a more unified API across clouds with better performance?

**Comment by landscapepainter** [comment]
Hey @sqr00t, thanks for sharing the benchmark results and suggestion. We actually do have a [PR for adding s5cmd with crt client](https://github.com/skypilot-org/skypilot/pull/2291)! Are you an active user of `s5cmd` outside of Skypilot? Was wondering if you encountered any edge cases while using it :)

**Comment by aseriesof-tubes** [comment]
Hi, I'm interested on working on this! If nobody's working on it, could I give it a shot?

**Comment by landscapepainter** [comment]
Hey @aseriesof-tubes thanks for taking on this issue. It's a very important issue to enhance user experience. I just assigned you to the problem.
