### ISSUE TITLE
[Cost Report] Storing instance price in the history

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#2780]
`sky cost-report` queries the curent catalog for the price of the instances launched before. This is unstable when the catalog is updated. We should instead saving the instance price in the history table as well.

Reference: https://github.com/skypilot-org/skypilot/blob/31aa76c968e6c9ca8c21ac25051f002383c1baee/sky/core.py#L151

**Comment by concretevitamin** [comment]
Specific error users met when running `cost-report`
```
..
sky/clouds/service_catalog/common.py", line 257, in get_hourly_cost_impl
    raise ValueError(f'Instance type {instance_type!r} not found '
ValueError: Instance type 'g3.8xlarge' not found in zone 'us-east-1b'.
```
This is likely because 
```
commit 976563a8b9cc0d8c40b991dacd1c6b1e2de205d7
Author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
Date:   Wed Feb 22 07:14:53 2023 +0000

    [Bot] Update AWS catalog v5 (scheduled at Wed Feb 22 07:14:53 UTC 2023)

 catalogs/v5/aws/vms.csv | 28341 +++++++++++++++++++++-------------------------
 1 file changed, 12887 insertions(+), 15454 deletions(-)
```
in the catalog repo removed 2 zones for this instance type.
