### ISSUE TITLE
Does skypilot support to inferece Llama2-70B in multiple GPU nodes?

### ISSUE THREAD

**Issue by JustinZou1** [skypilot-org/skypilot#2782]
Does skypilot support to inferece Llama2-70B in multiple GPU nodes? for example, does  skypilot support to inference LLama2-70B in multiple A10 vms? Thanks.

**Comment by cblmemo** [comment]
Hi @JustinZou1 ! If you are asking to replicate multiple 70B models to handle more requests, you could probably try SkyServe (#2458) which will be merged to master within 1-2 days. It is a serving layer built on top of SkyPilot which allows easy replication of models. If you are asking about model parallelism, you could refer to [this link](https://github.com/skypilot-org/skypilot/blob/master/llm/llama-2/README.md) and there is an example CLI to serving a single 70B model (5. Optional: Serve the 70B Llama-2 model) ;)

**Comment by JustinZou1** [comment]
@cblmemo Thanks for you advice for this. I refer to inference llama2-70B model via multiple nodes.

**Comment by Michaelvll** [comment]
This can be added to our AI gallery.
