### ISSUE TITLE
Skypilot copies `.aws/credentials`

### ISSUE THREAD

**Issue by Wirg** [skypilot-org/skypilot#2820]
Hi!

We've started using skypilot recently. Thanks for the great tool. :)

We noticed that when we have a `.aws/credentials` files locally on our machine, Skypilot seems to copy it to the remote.
At the same time, the remote also receive permissions from the `skypilot-v1` role.
We end up having situations where some commands fails because of using `.aws/credentials` instead of the `skypilot-v1` role.

Is this an expected behavior?
Is there a way to change this behavior? Do I want to do it?
Why is this the current design? It seems counterintuitive to me but I feel I am missing something?

**Comment by concretevitamin** [comment]
Thanks for the report @Wirg. We should definitely fix it. For your local machine, are you using any AWS profile (`AWS_PROFILE=xxx`)? What's the credential type you expect to use for local machine and subsequently any SkyPilot launched instances?

**Comment by Wirg** [comment]
Hi @concretevitamin 

On my local machine, I am using either access token for the moment, but I am going to switch to a custom SSOs in a few months.
I am setting AWS_PROFILE to select a specific one locally. On the server, I am expecting to have enough permission on the ec2 based on the ec2 role.

**Comment by concretevitamin** [comment]
Thanks @Wirg, we'll investigate how to properly solve this. cc @Michaelvll too.

What were the failures for situations where some commands fail?

One possible workaround to try in the meantime: In the beginning of `run` commands, remove `~/.aws/credentials` so that the VM only has the role. You could confirm that by `ssh mycluster` and then running `aws configure list`, which should not show `shared-credentials-file` anymore.

**Comment by Wirg** [comment]
Hi @concretevitamin ,

Thanks for the workaround, I think it's what we are doing right now.
Copying the .aws seems to work in most case (unless the EC2 has some permissions the user don't have in this profile which was our case). 
On the other hand, I find it weird to both set a role and override it by pushing the .aws of the user. This also might be a security risk.

**Comment by concretevitamin** [comment]
Indeed. The main reason for uploading the credentials is to allow a non-AWS controller (spot or serve) to launch AWS clusters.  That said, it should be feasible to avoid uploading cloud X's credential file when launching a cluster on cloud X. That may involve some changes in our backend. Stay tuned.
