### ISSUE TITLE
Consider allowing `sky stop` on GCP spot clusters

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#2837]
Not allowing `sky stop` on spot clusters was a decision made a long time ago, and it was modeled after AWS behavior. AWS would throw an error like this
```
You can't stop the Spot Instance 'i-xxx' because it is associated with a one-time Spot Instance request. You can only stop Spot Instances associated with persistent Spot Instance requests.
```
On GCP, however, they do [allow](https://cloud.google.com/compute/docs/instances/preemptible#preemption-process) the disks to be preserved:
```
You can access and recover data from any persistent disks that are attached to the instance, but those disks still incur storage charges until you delete them.
```

A user raised the above and ranked it as "nice to have".

**Comment by concretevitamin** [comment]
Another user raised this.

**Comment by wwa132** [comment]
Just for reference
Why does `sky stop` not work on GCP spot instances? - https://skypilot-org.snowshoe.dev/qr9B2LBpZZ7

**Comment by concretevitamin** [comment]
@wwa132 It's supported in #2877 and available on nightly now: `pip install -U skypilot-nightly` should give you the ability to do so.
