### ISSUE TITLE
[k8s] Show currently available GPUs on Kubernetes cluster

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#2839]
User requested - in addition to showing list of supported GPUs, they would like to see realtime utilization for GPUs so they can know how many GPUs they can launch. Kubernetes dashboard is nice, but doesn't show live GPU usage.

**Comment by gmittal** [comment]
following

**Comment by michaelzhiluo** [comment]
Potentially misunderstanding this here - does the user mean like 5/8 gpus are used on the cluster (where 5 gpus are occupied by other pods)?

In this case, it can be done by dynamically fetching `node.status.allocatable_capacity` in `kubectl get nodes` for the `nvidia.com/gpu` field.

**Comment by romilbhardwaj** [comment]
Bumping this up
