### ISSUE TITLE
Configure Exponential Backoff for `--retry-until-up`

### ISSUE THREAD

**Issue by michaelzhiluo** [skypilot-org/skypilot#2843]
I have a workload that is not migratable on GCP us-central-1. Hence, I keep `sky start XYZ -y --retry-until-up` to  provision the resources. However, the exponential backoff is too long and I would like to have more frequent polling.

This also reflect other systems, where the backoff is tunable by users.

**Comment by Michaelvll** [comment]
Thanks for raising the issue! This should be fixed by #2805. Please feel free to try the master branch. Closing this issue now. Please feel free to reopen the issue if the problem still occurs for you @michaelzhiluo
