### ISSUE TITLE
[k8s] change the container images for k8s

### ISSUE THREAD

**Issue by fourfireM** [skypilot-org/skypilot#2846]
When I use sky launch to create a cluster, I only configured k8s. it calls the us-central1-docker.pkg.dev/skypilot-375900/skypilotk8s/skypilot:latest by default to get image files to create it, now I want to change this default image source to my own, how can I change it, I can't find out which script or file sky launch called to import this address.

**Comment by romilbhardwaj** [comment]
Thanks for raising this @fourfireM. This is tracked in #2599, and we have an open PR #2729 which should add this feature soon. This will allow you to specify image like so:
```
resources:
  image_id: docker:yourrepo/yourimage:latest
```

Will this work for your use-case? 

Also, just so we know we're building the right thing - is your custom image debian based?
