### ISSUE TITLE
Will you plan to add free tier support? 

### ISSUE THREAD

**Issue by mihalt** [skypilot-org/skypilot#2848]
It would be nice if your service count not just cheapest servers but which has free tiers too. Count its limits and give the best option to deploy. And ideally if will be any statistics how long this model will able to work with this free tiers dedications.

**Comment by concretevitamin** [comment]
Hey @mihalt, could you elaborate on the problem & what you'd like to see?

Currently users can manually use a free-tier instance. E.g., for AWS EC2 free-tier:
```
» sky launch -t t3.micro
```

**Comment by mihalt** [comment]
> Hey @mihalt, could you elaborate on the problem & what you'd like to see?
> 
> Currently users can manually use a free-tier instance. E.g., for AWS EC2 free-tier:
> 
> ```
> » sky launch -t t3.micro
> ```

It doesn't automatically recommend me what free tiers and in what clouds can be appropriate for me hardware requirements

**Comment by mihalt** [comment]
would be nice to see in next versions! :-)
