### ISSUE TITLE
[Core/Spot] Support trying multiple regions in parallel 

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#2849]
A user complains that the `sky spot launch` can take more than 10 minutes to find an available resources across different regions. It is worth investigating to see if we can launch the cluster on multiple regions in parallel, and only keep one working region to run the job.

**Comment by michaelzhiluo** [comment]
IMO should be a feature for all of Skypilot, not only Spot.

Parallel provisioning reduces the need to failover, i.e. provisioning time = min(time to provision in region1, region 2, ...).
An additional thought - this reduces the need to track spot availability across regions/clouds, assuming that the aggregate availability across all clouds is 99+%. Tracking spot availability would then instead bring the value of reducing the # of parallel workers in provisioning (i.e. I only parallel provision on the regions which most likely has the spot instance)
