### ISSUE TITLE
`show-gpus`: have an option to show all regions' pricing for an accelerator 

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#2863]
User mentioned
> is there a way to use sky command line tool to see which regions have a certain instance type available? possible to use sky show-gpus to see the per-region price of the same instance type? ... I wanted to get a cross-region overview of the pricing. My workaround right now is to go to each vendor's websites

Default behavior is not satisfying this since we show the cheapest region by default.

To implement
- `sky show-gpus T4:8 --all-regions` (show all regions across clouds that (fuzzy?) match the accelerator)
- (maybe) `sky show-gpus -t <general instance type> --all-regions`

**Comment by Michaelvll** [comment]
This has been fixed in #2892 and #2933. Closing.
