### ISSUE TITLE
Cannot run example from documentation: Mistral on Azure with SkyPilot

### ISSUE THREAD

**Issue by richard-mueller** [skypilot-org/skypilot#2865]
Hi, I tried the example from the official Mistral documentation (https://docs.mistral.ai/self-deployment/skypilot), but deploying to Azure instead of AWS. SkyPilot runs without error and gives me an IP address with

```
IP=$(sky status --ip cluster-name)
```

Unfortunately, that IP address is not reachable (neither curl nor ping). I don't seem to be the only one with this issue, see https://discord.com/channels/1144547040454508606/1184797878762356826/1184797878762356826 

Any idea on how to proceed?

**Comment by cblmemo** [comment]
Hi @richard-mueller ! Thanks for reaching out. What is your SkyPilot version? Could you share your output for `sky -v`? #2649 fixed a bug on the open port feature for Azure, and it is not included in our latest release. If you are not using the nightly build, you can try the following:

```bash
pip install skypilot-nightly
```

If the above doesn't resolve your problem, could you share your YAML so that we could try to reproduce your error?

**Comment by richard-mueller** [comment]
Hi, thanks for the quick response! My SkyPilot version is `version 1.0.0.dev20231213`; that should already be a nightly build. 

Please find my YAML below:
```
resources:
  cloud: azure
  accelerators: A10:1
  ports:
    - 8000

run: |
  docker run --gpus all -p 8000:8000 ghcr.io/mistralai/mistral-src/vllm:latest \
                   --host 0.0.0.0 \
                   --model mistralai/Mistral-7B-Instruct-v0.2 \
                   --tensor-parallel-size 1
```

**Comment by cblmemo** [comment]
Sorry for the delay -  We merged another fix (#2891) to the master branch. Could you retry with the latest master

**Comment by richard-mueller** [comment]
Hi, thanks for the update! I did a retry, but unfortunately I get the same error
```Failed to connect to IP port 8000 after 24 ms: Couldn't connect to server```

Here's what I did:

1. Updated SkyPilot to latest nightly build `version 1.0.0.dev20231223`
2. Launched SkyPilot with above YAML `sky launch -c cluster-name mistral.yaml --region westeurope`
3. Got IP address `IP=$(sky status --ip cluster-name)`
4. Tried to curl the Mistral LLM
   ```
   curl http://$IP:8000/v1/completions \
  -H "Content-Type: application/json" \
  -d '{
      "model": "mistralai/Mistral-7B-Instruct-v0.2",
      "prompt": "My favourite condiment is",
      "max_tokens": 25
  }'
   ```

**Comment by Michaelvll** [comment]
I got the following error when trying out the yaml above:
```
docker: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create": dial unix /var/run/docker.sock: connect: permission denied.
```

**Comment by Michaelvll** [comment]
After adding `sudo` before the `docker run` in the run section, it seems working correctly. Could you help retry this? @richard-mueller  : )

**Comment by cblmemo** [comment]
> Thanks for the replies!
> 
> I updated to the latest SkyPilot version `skypilot-nightly-1.0.0.dev20240223` and added `sudo` before `docker run` in the above yaml.
> 
> However, I still get the same error `Failed to connect to <IP address> port 8000 after 21 ms: Couldn't connect to server`

Hi @richard-mueller ! Could you double-check the cloud console to see if there are related firewall rules in the NSG? Also, could you share the commit hash you are on (by running `sky -c`) and the whole YAML file you are using?
