### ISSUE TITLE
Attach an existing cloud instance with Skypilot

### ISSUE THREAD

**Issue by michaelzhiluo** [skypilot-org/skypilot#2872]
I have a long running 1-year-old instance that **used** to be created Skypilot. However, after a long time, this instance is not attached anymore, so I just manually start and stop the machine on GCP console when needed.

It'd be really nice feature to  re-attach an existing instance with Skypilot; that way, I would be able to `sky start/stop` without any hassle.

**Comment by Michaelvll** [comment]
Related to #2542

**Comment by michaelzhiluo** [comment]
Nice to see that others want this feature too. This is also a lot of value provided for people with un-migratable workloads (or too lazy to build the skypilot yaml to make their workloads migratable)
