### ISSUE TITLE
`sky launch --ports` not open on GCP

### ISSUE THREAD

**Issue by michaelzhiluo** [skypilot-org/skypilot#2873]
**Reproducibility**

```
sky launch -c my-sky --cloud gcp --ports 50051 --cpus 4

telnet [my-sky-public-IP] 50051
```

Port is also closed also using https://www.yougetsignal.com/tools/open-ports/ to test.

The port rule does exist; however, the port is not open.
<img width="1301" alt="Screenshot 2023-12-15 at 6 50 59 PM" src="https://github.com/skypilot-org/skypilot/assets/20640975/10b0b9b5-eadd-4def-ab94-6cb59b2690fe">

**Comment by Michaelvll** [comment]
Do you have any service running on that port? Also, could you please share the version of SkyPilot you are using and the detail information page of the VM you created?

**Comment by michaelzhiluo** [comment]
There is an API service running on that port. The Skypilot is the most recent master branch. 

The VM command is very similar to the one above. VM  details below:
<img width="829" alt="Screenshot 2023-12-15 at 6 56 47 PM" src="https://github.com/skypilot-org/skypilot/assets/20640975/d1f34aee-91d8-4c76-81b5-1ea56d61917a">

**Comment by Michaelvll** [comment]
Could you check if there is any network tags set with your VM like the following? 
![image](https://github.com/skypilot-org/skypilot/assets/6753189/504f8b9a-1935-45e6-b4c1-21d71d3e23f7)

**Comment by michaelzhiluo** [comment]
Yes seems to have identical network tags. 

<img width="882" alt="Screenshot 2023-12-15 at 7 11 42 PM" src="https://github.com/skypilot-org/skypilot/assets/20640975/1e98dc24-924e-4013-a257-5cbb5571eb85">

..and the firewall rule that Skypilot made has the right tag. I went through all the firewall rules in `skypilot-vpc` and find nothing blocking port 50051.

<img width="478" alt="Screenshot 2023-12-15 at 7 12 36 PM" src="https://github.com/skypilot-org/skypilot/assets/20640975/523f3685-6137-4db7-8fa6-fc1a069f1bdc">

**Comment by Michaelvll** [comment]
Hmm, this is weird. Would you like to try to start another service on the port to see if it is the issue with the application itself, e.g. `jupyter notebook --ip 0.0.0.0 --port 50051`?

**Comment by michaelzhiluo** [comment]
Yes it does work with `ssh -L localhost:50051:localhost:50051 skyflow`. Application should be good.

However, the ports still seems closed with `curl -X GET .....[IP_ADDRESS]:50051/...`

<img width="1637" alt="Screenshot 2023-12-15 at 7 18 15 PM" src="https://github.com/skypilot-org/skypilot/assets/20640975/91e42843-94da-4eaa-9719-2ffe5f4cf1b9">

**Comment by Michaelvll** [comment]
Hmm, this is weird. I just tried to run this on my end and it seems the jupyter notebook works well:
![image](https://github.com/skypilot-org/skypilot/assets/6753189/86946751-5e0f-447c-807a-a436e576ea64)
```bash
sky launch -c my-sky --cloud gcp --ports 50051 --cpus 4 "jupyter notebook --port 50051 --ip 0.0.0.0"
```

If there is no speciic firerules that are needed in your `skypilot-vpc`, you can try to delete your `skypilot-vpc` and `sky launch` again?

**Comment by michaelzhiluo** [comment]
Ah yes, I will probably need to create a new VPC, it is most likely the rootcause. However, a lot of my GKE clusters depend on the old skypilot-vpc. Deleting this will probably ruin the GKE cluster. Does Skypilot provide the option to specify the VPC that it will create?

**Comment by Michaelvll** [comment]
Yes, you can specify vpc_name in the `~/.sky/config.yaml`:
```
gcp:
  vpc_name: your-vpc-name
```

However, this will not automatically create firewall rules for you. You may need to follow the instructions here: https://skypilot.readthedocs.io/en/latest/cloud-setup/cloud-permissions/gcp.html#firewall-rules

**Comment by michaelzhiluo** [comment]
Very impressive that Skypilot catches this case here. Thanks @Michaelvll ! 💪
