### ISSUE TITLE
SkyServe: warn/raise on `min_replicas: 0`

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#2893]
Tried the http server example with `min_replicas: 0` and got
```
Services
NAME  UPTIME  STATUS        REPLICAS  ENDPOINT
http  -       REPLICA_INIT  0/0       172.190.62.140:30001

Service Replicas
No existing replicas.
```
At this point there's no way to curl and trigger a scale-up.

We should consider raising a ValueError / NotImplementedError about this.

cc @MaoZiming @cblmemo

**Comment by cblmemo** [comment]
Humm, did you specify `max_replicas=<some positive integer>`? If not, the default value of `max_replicas` is `min_replicas`, and no autoscaling is enabled. I think if you specify `min_replicas=0, max_replicas=1` and curl the endpoint, then it will trigger a scale-up.

**Comment by MaoZiming** [comment]
@cblmemo I think we need special handling for `min_replicas=0`, I believe currently it will take multiple curl's to trigger a scale-up when num replicas is 0. That is probably not good.

**Comment by concretevitamin** [comment]
+1. I believe I set `min_replicas: 0` and `max_replicas: 1`.

**Comment by cblmemo** [comment]
Sounds great! Lets keep `min_replicas>0` for now
