### ISSUE TITLE
Add support for skypilot YAML configuration format in jsonstore

### ISSUE THREAD

**Issue by remyleone** [skypilot-org/skypilot#2907]
Could you put a json description of the skypilot configuration format in: https://www.schemastore.org/json/ ?
That would help bring native support and completion in all editors for users of skypilot

**Comment by romilbhardwaj** [comment]
Thanks @remyleone! @Shrinandan-N is taking a look at this. We'll soon get a PR going at the [schemastore](https://github.com/SchemaStore/schemastore) repository.

**Comment by romilbhardwaj** [comment]
Can be closed with the merge of https://github.com/SchemaStore/schemastore/pull/3499 - thanks @Shrinandan-N!

**Comment by Michaelvll** [comment]
This is fantastic! Just curious, do we have a guide/instruction for how to setup the auto-completion for SkyPilot YAMLs in editors? It would be nice to add such instruction in our doc page with something similar to: https://skypilot.readthedocs.io/en/latest/getting-started/installation.html#enabling-shell-completion
