### ISSUE TITLE
[SkyServe] controller resources in service YAML

### ISSUE THREAD

**Issue by cblmemo** [skypilot-org/skypilot#2916]
According to a user's request, we should have a `controller_resources` section under `service` to override the specification in `~/.sky/config.yaml`. If both specified controller resources, what is specified in the service yaml takes precedence.

**Comment by landscapepainter** [comment]
+1 This would be really useful especially for the new HeteroGPU serving policy, #2927, which may run launch processes more that our default controller spec can handle.

**Comment by dtran24** [comment]
If both controller resources are specified, would the controller sources under `service` be a complete or partial override of the specification in `~/.sky/config.yaml`?

**Comment by cblmemo** [comment]
> If both controller resources are specified, would the controller sources under `service` be a complete or partial override of the specification in `~/.sky/config.yaml`?

IMO it should be a partial override; though we could discuss it in our coming meeting :)

**Comment by cblmemo** [comment]
After an offline discussion, we decided to defer that since this will complicate our service yaml.

**Comment by cblmemo** [comment]
Closing this as not planned.
