### ISSUE TITLE
sky show-gpus throws gcloud error

### ISSUE THREAD

**Issue by Vaibhav2001** [skypilot-org/skypilot#2926]
With the current state of the master (https://github.com/skypilot-org/skypilot/commit/394ec4ad8f30e61213d6a706502d3fe2df4c1f93) . If someone does not have gcloud installed, when `sky show-gpus` is run this error is thrown

```
RuntimeError: Failed to run "gcloud version".
**** STDOUT ****

**** STDERR ****
/bin/sh: gcloud: command not found
```

According to my testing, this was not an issue before (https://github.com/skypilot-org/skypilot/commit/5e9ebb8873dcbb293f970c50c23d0cff598549a0)

**Comment by Michaelvll** [comment]
Thanks for raising this issue @Vaibhav2001! I just tried the following and it seems working correctly.
1. `docker run -it --rm --name skypilot-debug2 berkeleyskypilot/skypilot-debug /bin/bash`
2. `cd ./skypilot; pip install -e .; sky show-gpus`

Could you provide a reproducible script for this?

**Comment by Vaibhav2001** [comment]
> Thanks for raising this issue @Vaibhav2001! I just tried the following and it seems working correctly.
> 
> 1. `docker run -it --rm --name skypilot-debug2 berkeleyskypilot/skypilot-debug /bin/bash`
> 2. `cd ./skypilot; pip install -e .; sky show-gpus`
> 
> Could you provide a reproducible script for this?

For me when I ran `sky show-gpus` on my mac it did not work, and threw the error that I mentioned above. As soon as I installed `gcloud`, the issue went away.

**Comment by Michaelvll** [comment]
The problem has been resolved as we have refactored the provisioner of GCP and TPU.


Just tested it with `docker run -it --rm --name continuumio/miniconda3:23.3.1-0 /bin/bash` and `pip install skypilot-nightly` with version: `skypilot-nightly-1.0.0.dev20240204`.
It seems the problem has been resolved for `sky show-gpus`. Closing this issue for now. Thanks for reporting this @Vaibhav2001!
