### ISSUE TITLE
Optimize when launching dag

### ISSUE THREAD

**Issue by BhAem** [skypilot-org/skypilot#2928]
The code snippet states:
`assert len(dag) == 1, f'We support 1 task for now. {dag}'`

So in my understanding, if there is a dag like "train >> infer" mentioned in the paper, it cannot be directly passed as an input to sky.launch(dag). In other words, Skypilot does not perform overall dag optimization when launching the dag.

I would like to ask if the correct usage of Skypilot is to first use `sky.optimize(dag)` to obtain the optimized resources and then use `sky.launch(train).set_resources(resouce_from_optimization)` and `sky.exec(infer).set_resources(resouce_from_optimization)` sequentially?

**Comment by Michaelvll** [comment]
Thank you for the request @BhAem! Dag is not supported in production right now for SkyPilot as it requires the user client that calls SkyPilot to be alive throughout the whole lifecycle of the whole dag. If you would like to try out the pipeline support, please check the PR #1982, where we add the pipeline support for managed spot jobs as we have an always-on controller for spot jobs. 

Just a note that we have a doc being added for the spot pipeline #2936 : )
