### ISSUE TITLE
FR pls. support runpod.io

### ISSUE THREAD

**Issue by chymian** [skypilot-org/skypilot#2929]
runpod.io has a very competitive prices and support People to rent out their GPUs

**Comment by concretevitamin** [comment]
Runpod support is in progress: #2360 #2829

**Comment by Michaelvll** [comment]
The runpod support has just been merged in master. Please feel free to try it out.

**Comment by Michaelvll** [comment]
Closing this issue as runpod has been supported. Please feel free to file another issue, if you met any issue with the runpod support : )
