### ISSUE TITLE
[k8s] Can not running the train

### ISSUE THREAD

**Issue by fourfireM** [skypilot-org/skypilot#2952]
I'm trying to do distributed training with multiple machines and cards within a cluster after enabling a multi-node cluster using k8s, however my training will always stop before starting the training loop without reporting an error or any further indication, what could be the cause of this situation? I currently suspect too few cpu calls, what needs to be done to fix this? I set the export OMP_NUM_THREADS environment variable as per some of the tips below the question nothing seems to change.

**Comment by romilbhardwaj** [comment]
Hi @fourfireM - thanks for the report. To help debug:

1. What is the failure mode? Do you see any error or are you unable to ssh/connect to the cluster anymore?
2. What's the output of `kubctl get pods`? If some pods show as failed, can you paste the output of `kubectl describe pod <pod-name>`?
3. Can you share provisioning (path to this file is printed during beginning of provisioning under "To view detailed progress:") and job logs, if any?
4. To help replication, can you share your task YAML here?
5. Is this a cloud Kubernetes cluster (GKE/EKS) or an onprem deployment?

**Comment by fourfireM** [comment]
I don't see any error messages displayed, and I can always connect to my cluster via ssh, and I believe there should be no configuration issues, as I have no problem running my training program on a separate node.

Also using `kubctl get pods` is normal showing the following:
NAME                              READY   STATUS    RESTARTS   AGE
mycluster-d8f4-ray-head           1/1     Running   0          14h
mycluster-d8f4-ray-worker-pkwkl   1/1     Running   0          14h
sky-ssh-jump-d8f42d5f             1/1     Running   0          4d16h

and my provision log is in attatch:
[provisioning.log](https://github.com/skypilot-org/skypilot/files/13867839/provisioning.log)

and my yaml is like this:
[test.txt](https://github.com/skypilot-org/skypilot/files/13867864/test.txt)

and it is a On-Prem Kubernetes Deployment

In fact, normally speaking, when I run my training script after loading the model, it starts training, and some of the outputs under normal circumstances are as follows:
(Works fine for both single node and local multi-machine training )
```
[01/08 17:01:22 d2.checkpoint.c2_model_loading]: The checkpoint state_dict contains keys that are not used by the model:
    (head, rank=0, pid=2701)   stem.fc.{bias, weight}
[01/08 17:22:51 d2.engine.train_loop]: Starting training from iteration 0
then here is the training information .... loss....
```

but now it will stop after loading the model like 
```
[01/08 17:01:22 d2.checkpoint.c2_model_loading]: The checkpoint state_dict contains keys that are not used by the model:
    (head, rank=0, pid=2701)   stem.fc.{bias, weight}
(There's no output, but I'm monitoring the GPU and CPU resource as if it's still running.)
```
IMO, I suspect it's a cpu limit issue

However when I launch the 70cpus cluster and `export OMP_NUM_THREADS=70` in yaml, it still doesn't seem to have changed.

**Comment by romilbhardwaj** [comment]
Thanks for the details @fourfireM - I haven't come across this issue before. Can you try bumping up memory and cpu using `--memory` and `--cpus` flags to `sky launch`?

Meanwhile, I will also try reproducing it. Should I try using your YAML with code from https://github.com/PeizeSun/SparseR-CNN.git and run `sky launch task.yaml`? Or are there any other steps I should follow?

**Comment by fourfireM** [comment]
Thank you for your answer and help, I am using the code in https://github.com/PeizeSun/SparseR-CNN.git to try to run the training, the `run:` in yaml is also based on SparseR-CNN. I would appreciate if you could try the code to run.

**Comment by fourfireM** [comment]
In fact there is nothing wrong with the project code itself, it just seems to be too slow using multiple nodes, I tried to let the training run all the time and it took about 8 hours to run the first iteration of the first epoch.

Is there anything I can do to improve the multi-node training, by the way I've tried using --memory and --cpus flags to sky launch like you said.

**Comment by romilbhardwaj** [comment]
Hmm that's interesting. I've previously run multi-gpu multi-node training ([nemo example](https://github.com/skypilot-org/skypilot/blob/master/examples/nemo/nemo_gpt_train.yaml)) on GKE cluster and I recall it working fine.

@landscapepainter is investigating this now. One blind guess would be to check would be if ulimits are set too low, and if [increasing them](https://stackoverflow.com/a/54564540) helps.

**Comment by fourfireM** [comment]
Thanks for the reply, for reference this is my training output on single node：time: 0.4544

```
(worker1, rank=1, pid=1728, ip=10.42.2.30) [01/09 02:37:02 d2.utils.events]:  eta: 1 day, 10:05:09  iter: 19  total_loss: 60.7  loss_ce: 2.071  loss_giou: 2.395  loss_bbox: 8.479  loss_ce_0: 2.114  loss_giou_0: 2.014  loss_bbox_0: 4.383  loss_ce_1: 2.232 
loss_giou_1: 1.957  loss_bbox_1: 4.273  loss_ce_2: 2.185  loss_giou_2: 2.248  loss_bbox_2: 4.196  loss_ce_3: 2.286  loss_giou_3: 2.2  loss_bbox_3: 6.94  loss_ce_4: 2.15  loss_giou_4: 2.238  loss_bbox_4: 6.638  time: 0.4544  data_time: 0.3754  lr: 7.2025e-07  max_mem: 2873M
```


This is my training output on multiple nodes: time: 1386.3151

```
(head, rank=0, pid=8259) [01/09 10:46:29 d2.utils.events]:  eta: 4333 days, 21:08:17  iter: 19  total_loss: 60.84  loss_ce: 2.087  loss_giou: 2.371  loss_bbox: 8.264  loss_ce_0: 2.09  loss_giou_0: 2.044  loss_bbox_0: 4.391  loss_ce_1: 2.253  
loss_giou_1: 2.033  loss_bbox_1: 4.141  loss_ce_2: 2.209  loss_giou_2: 2.225  loss_bbox_2: 4.027  loss_ce_3: 2.306  loss_giou_3: 2.27  loss_bbox_3: 6.824  loss_ce_4: 2.081  loss_giou_4: 2.221  loss_bbox_4: 6.377  time: 1386.3151  data_time: 0.1655  lr: 7.2025e-07  max_mem: 2907
```


We can see that the training time is off by a very large factor.

In addition, I used ssh to enter the cluster head node, and then typed in `ulimit -a` and got the following output, 

```
(base) sky@mycluster-d8f4-ray-head:~$ ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 2579663
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) unlimited
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

so I hope this can serve as some kind of reference.

**Comment by landscapepainter** [comment]
@fourfireM Thanks for reporting this issue! Do you mind sharing which version of `torch` and `torchvision` is currently being used in your setting? I was trying to reproduce with the Task YAML you provided, which installs `torch` and `torchvision` with `pip install torch==2.0.0 torchvision==0.15.1 -i https://pypi.tuna.tsinghua.edu.cn/simple`. But I encountered an error running this YAML due to some torchvision `ImportError`. I'm assuming the version of pytorch and torchvision being used are different. It can be discovered by running:
```
import torch
print("PyTorch Version:", torch.__version__)
import torchvision
print("Torchvision Version:", torchvision.__version__)
```

**Comment by fourfireM** [comment]
In fact， `-i https://pypi.tuna.tsinghua.edu.cn/simple`  is the mirror source I used for the download, you could probably just remove it for the download.

For reference my version of torch and torchvision is as follows:
```
>>> import torch
>>> import torchvision
>>> print(torch.__version__)
2.0.0+cu117
>>> print(torchvision.__version__)
0.15.1+cu117
```

**Comment by landscapepainter** [comment]
@fourfireM Gotcha. Thanks! I guess the issue wasn't from different versions as I have the same installed. Then, did you happen to encounter this `ImportError` as well? Was wondering if you had a specific way to go around this error.

```
(worker1, rank=1, pid=933, ip=172.31.0.23) Traceback (most recent call last):
(worker1, rank=1, pid=933, ip=172.31.0.23)   File "/home/sky/sky_workdir/projects/SparseRCNN/train_net.py", line 29, in <module>
(worker1, rank=1, pid=933, ip=172.31.0.23)     from sparsercnn import SparseRCNNDatasetMapper, add_sparsercnn_config, SparseRCNNWithTTA
(worker1, rank=1, pid=933, ip=172.31.0.23)   File "/home/sky/sky_workdir/projects/SparseRCNN/sparsercnn/__init__.py", line 7, in <module>
(worker1, rank=1, pid=933, ip=172.31.0.23)     from .detector import SparseRCNN
(worker1, rank=1, pid=933, ip=172.31.0.23)   File "/home/sky/sky_workdir/projects/SparseRCNN/sparsercnn/detector.py", line 24, in <module>
(worker1, rank=1, pid=933, ip=172.31.0.23)     from .loss import SetCriterion, HungarianMatcher
(worker1, rank=1, pid=933, ip=172.31.0.23)   File "/home/sky/sky_workdir/projects/SparseRCNN/sparsercnn/loss.py", line 15, in <module>
(worker1, rank=1, pid=933, ip=172.31.0.23)     from .util.misc import (NestedTensor, nested_tensor_from_tensor_list,
(worker1, rank=1, pid=933, ip=172.31.0.23)   File "/home/sky/sky_workdir/projects/SparseRCNN/sparsercnn/util/misc.py", line 22, in <module>
(worker1, rank=1, pid=933, ip=172.31.0.23)     from torchvision.ops import _new_empty_tensor
(worker1, rank=1, pid=933, ip=172.31.0.23) ImportError: cannot import name '_new_empty_tensor' from 'torchvision.ops' (/home/ray/anaconda3/lib/python3.10/site-packages/torchvision/ops/__init__.py)
(head, rank=0, pid=1927) Traceback (most recent call last):
(head, rank=0, pid=1927)   File "/home/sky/sky_workdir/projects/SparseRCNN/train_net.py", line 29, in <module>
(head, rank=0, pid=1927)     from sparsercnn import SparseRCNNDatasetMapper, add_sparsercnn_config, SparseRCNNWithTTA
(head, rank=0, pid=1927)   File "/home/sky/sky_workdir/projects/SparseRCNN/sparsercnn/__init__.py", line 7, in <module>
(head, rank=0, pid=1927)     from .detector import SparseRCNN
(head, rank=0, pid=1927)   File "/home/sky/sky_workdir/projects/SparseRCNN/sparsercnn/detector.py", line 24, in <module>
(head, rank=0, pid=1927)     from .loss import SetCriterion, HungarianMatcher
(head, rank=0, pid=1927)   File "/home/sky/sky_workdir/projects/SparseRCNN/sparsercnn/loss.py", line 15, in <module>
(head, rank=0, pid=1927)     from .util.misc import (NestedTensor, nested_tensor_from_tensor_list,
(head, rank=0, pid=1927)   File "/home/sky/sky_workdir/projects/SparseRCNN/sparsercnn/util/misc.py", line 22, in <module>
(head, rank=0, pid=1927)     from torchvision.ops import _new_empty_tensor
(head, rank=0, pid=1927) ImportError: cannot import name '_new_empty_tensor' from 'torchvision.ops' (/home/ray/anaconda3/lib/python3.10/site-packages/torchvision/ops/__init__.py)
```

**Comment by landscapepainter** [comment]
@fourfireM Thanks for the confirmation! I'm still trying to reproduce your error. I have one suggestion and a question:
Suggestion: ray job scheduler uses `CUDA_VISIBLE_DEVICES` to assign jobs on those GPUs, so it's possible that more than training job is running on those GPUs if you specifiy `export CUDA_VISIBLE_DEVICES=0,1,2,3`. Do you mind trying out after removing those commands to see if there's a speed boost?

Question: While trying to reproduce your result, I'm encountering the following `AttributeError` and it seems like `torch` `2.0.0` does not have the attribute, `_sync_params_and_buffers`, for `DistributedDataParallel` anymore. What was your work around?
```
(head, rank=0, pid=2972) Traceback (most recent call last):
(head, rank=0, pid=2972)   File "/home/sky/sky_workdir/projects/SparseRCNN/train_net.py", line 153, in <module>
(head, rank=0, pid=2972)     launch(
(head, rank=0, pid=2972)   File "/home/sky/sky_workdir/detectron2/engine/launch.py", line 55, in launch
(head, rank=0, pid=2972)     mp.spawn(
(head, rank=0, pid=2972)   File "/home/ray/anaconda3/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 239, in spawn
(head, rank=0, pid=2972)     return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
(head, rank=0, pid=2972)   File "/home/ray/anaconda3/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
(head, rank=0, pid=2972)     while not context.join():
(head, rank=0, pid=2972)   File "/home/ray/anaconda3/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 160, in join
(head, rank=0, pid=2972)     raise ProcessRaisedException(msg, error_index, failed_process.pid)
(head, rank=0, pid=2972) torch.multiprocessing.spawn.ProcessRaisedException: 
(head, rank=0, pid=2972) 
(head, rank=0, pid=2972) -- Process 1 terminated with the following error:
(head, rank=0, pid=2972) Traceback (most recent call last):
(head, rank=0, pid=2972)   File "/home/ray/anaconda3/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
(head, rank=0, pid=2972)     fn(i, *args)
(head, rank=0, pid=2972)   File "/home/sky/sky_workdir/detectron2/engine/launch.py", line 94, in _distributed_worker
(head, rank=0, pid=2972)     main_func(*args)
(head, rank=0, pid=2972)   File "/home/sky/sky_workdir/projects/SparseRCNN/train_net.py", line 146, in main
(head, rank=0, pid=2972)     trainer.resume_or_load(resume=args.resume)
(head, rank=0, pid=2972)   File "/home/sky/sky_workdir/detectron2/engine/defaults.py", line 334, in resume_or_load
(head, rank=0, pid=2972)     self.model._sync_params_and_buffers()
(head, rank=0, pid=2972)   File "/home/ray/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
(head, rank=0, pid=2972)     raise AttributeError("'{}' object has no attribute '{}'".format(
(head, rank=0, pid=2972) AttributeError: 'DistributedDataParallel' object has no attribute '_sync_params_and_buffers'
```

**Comment by fourfireM** [comment]
I have encountered this problem, it is because pytorch version is too high, my way to deal with it is to comment out lines 333-335 in detectron2/engine/defaults.py, like the following, after that the code will work fine. @landscapepainter 

```python
330       if isinstance(self.model, DistributedDataParallel):
331            # broadcast loaded data/model from the first rank, because other
332            # machines may not have access to the checkpoint file
333        #    if TORCH_VERSION >= (1, 7):
334        #        self.model._sync_params_and_buffers()
335            self.start_iter = comm.all_gather(self.start_iter)[0]
336
337    def build_hooks(self):
338    #... code....
```

**Comment by fourfireM** [comment]
Did you have the same problem as me after trying to run it? I'm debugging the code internally right now, and I'm finding that the multi-node run gets stuck on the model merge weights. @landscapepainter

**Comment by landscapepainter** [comment]
@fourfireM Thanks for sharing what you discovered! I haven't made much progress yet since my last reply. I'll get back to this as soon as possible with what you provided in the previous comment. Meanwhile, if you happen to discover any other related problems, please share it with us! I absolutely appreciate your insights.
