### ISSUE TITLE
[Catalog] Inconsistency for GCP, A100:16 instance

### ISSUE THREAD

**Issue by cblmemo** [skypilot-org/skypilot#2953]
This is an issue surfaced in #2946, thanks to @Vaibhav2001 . In https://github.com/skypilot-org/skypilot/blob/a31fdd93bdfa342393a61ed603057ec5f233b2b0/sky/clouds/service_catalog/gcp_catalog.py#L69-L76

It shows an A100:16 instance in GCP should use a `a2-megagpu-16g` instance type. However, A100:16 is shown in the region `asia-northeast{1,3}` https://github.com/skypilot-org/skypilot-catalog/blob/780ced46ff71eeb7086e118d9d570781008a4f5a/catalogs/v5/gcp/vms.csv#L14493-L14496

But the instance type is not shown in the region: https://github.com/skypilot-org/skypilot-catalog/blob/780ced46ff71eeb7086e118d9d570781008a4f5a/catalogs/v5/gcp/vms.csv#L74-L80

**Comment by Michaelvll** [comment]
Just checked that it is not possible to create A100-80GB:16 or A100:16 on `asia-northeast1` (The accelerator somehow exists but the machine type: `a2-megagpu-16g` does not)

**Comment by Michaelvll** [comment]
Reopened as #3083 was reverted.
