### ISSUE TITLE
[Developer][Code Style] Align the implementation from `__setstate__`

### ISSUE THREAD

**Issue by cblmemo** [skypilot-org/skypilot#2954]
In https://github.com/skypilot-org/skypilot/blob/527eb4c4fc7fe2f3f92bf945d83b32df6c5c1080/sky/resources.py#L1265-L1353

Seems like we are mixing `state['_xxx'] = xxx` and `self._yyy = yyy`. IIUC they are semantically equivalent? Is there any reason to use both of them?

**Comment by Michaelvll** [comment]
We are using the different style, because for `self._yyy = yyy` we are handling the case where the `state` does not have the key. I don't have a strong perference for it though。

**Comment by cblmemo** [comment]
> We are using the different style, because for `self._yyy = yyy` we are handling the case where the `state` does not have the key. I don't have a strong perference for it though。

I see! Thanks for the information 🫡
