### ISSUE TITLE
skypilot + vllm example number of parallel tensors question

### ISSUE THREAD

**Issue by drawnwren** [skypilot-org/skypilot#2955]
In the skypilot + vllm example, `--tensor-parallel-size` is set to the number of gpus per node. 
```
python -u -m vllm.entrypoints.api_server \
                   --model $MODEL_NAME \
                   --tensor-parallel-size $SKYPILOT_NUM_GPUS_PER_NODE \
                   --tokenizer hf-internal-testing/llama-tokenizer 2>&1 | tee api_server.log &
```

However, I want to distribute across a cluster of machines. According to the [vllm docs](https://docs.vllm.ai/en/latest/serving/distributed_serving.html), I should use `--tensor-parallel-size` set to the number of gpus in the cluster.

```
After that, you can run inference and serving on multiple machines by launching the vLLM process on the head node by setting tensor_parallel_size to the number of GPUs to be the total number of GPUs across all machines.
```

When I do this, I get `ValueError: The number of required GPUs exceeds the total number of available GPUs in the cluster.`. 

The output of `ray list nodes` shows the correct number nodes each with 1 gpu. Do I need to start and manage a new ray cluster inside of your ray cluster?

**Comment by Michaelvll** [comment]
This is fantastic @drawnwren! Thanks for figuring this out. Would you like to submit a PR to add a new section in our vllm example's [readme](https://github.com/skypilot-org/skypilot/blob/master/llm/vllm/README.md) for running vllm on multiple nodes? This would be great for future users.

**Comment by drawnwren** [comment]
So, this ended up not working. The problem is that if vllm and skypilot use the same ray cluster:

1. skypilot schedules a task `sky_job_1`
  1. inside `sky_job_1`
  2. vllm schedules a task for the llm
  3. vllm blocks
  4. deadlock

**Comment by Michaelvll** [comment]
> So, this ended up not working. The problem is that if vllm and skypilot use the same ray cluster:
> 
> 1. skypilot schedules a task `sky_job_1`
> 2. inside `sky_job_1`
> 3. vllm schedules a task for the llm
> 4. vllm blocks
> 5. deadlock

I see! That makes sense. Thank you for the feedback!

In SkyPilot, we have made the ray cluster invisible to user program, by using non-default ports for the ray cluster used as SkyPilot's runtime. A user should be able to create a ray cluster on their own by using something like the following commands (note that `ray>=2.9` may not work due to a recent update from `ray` that makes it fail to run multiple ray cluster):

```
run: |
  head_ip=`echo "$SKYPILOT_NODE_IPS" | head -n1`
  if [ "$SKYPILOT_NODE_RANK" == "0" ]; then
    ps aux | grep ray | grep 6379 &> /dev/null || ray start --head  --disable-usage-stats --port 6379
    sleep 8
    python -u -m vllm.entrypoints.api_server \
                   --model $MODEL_NAME \
                   --tensor-parallel-size $(SKYPILOT_NUM_GPUS_PER_NODE) \
                   --tokenizer hf-internal-testing/llama-tokenizer 2>&1 | tee api_server.log &
  else
    sleep 5
    ps aux | grep ray | grep 6379 &> /dev/null || ray start --address $head_ip:6379 --disable-usage-stats
  fi
```

**Comment by drawnwren** [comment]
Ok, yep the `2.9` thing was the piece I was missing. Here's a copy of the yaml I'm using -- but idk if you want to put this in your nice repo. The only major change is using `--tensor-parallel-size=` the total number of gpus in the ray cluster. 

```
resources:
    accelerators: A10G:1
num_nodes: 4
envs:
    MODEL_NAME: "TheBloke/Xwin-LM-70B-V0.1-AWQ"
    NUM_WORKERS: 4
    NUM_GPUS: 4 # number of accelerators per worker * number of workers 
    PREFIX: "4-A10G:1"
workdir: .

file_mounts:
  /outputs:
    name: sky-outputs    # Can be existing S3 bucket or a new bucket
    store: s3
    mode: MOUNT

setup: |
    conda create -n vllm python=3.10 -y
    conda activate vllm
    sudo apt install -y nvtop net-tools
    pip install vllm jupyter gradio 

    pip install "ray<2.9.0" 
run: |
    conda activate vllm

    if [ "${SKYPILOT_NODE_RANK}" == "0" ]; then
        ps aux | grep ray | grep 6379 &> /dev/null || ray start --head  --disable-usage-stats --port 6379
        now=$(date +"%T")
        # benchmark.py calls vllm.LLM(tensor_parallel_size=$NUM_GPUS)
        python benchmark.py 2>&1 | tee "/outputs/head_${now}_log.txt"
    else
        head_ip=`echo "$SKYPILOT_NODE_IPS" | head -n1`
        ps aux | grep ray | grep 6379 &> /dev/null || ray start --address $head_ip:6379 --disable-usage-stats
    fi
 ```
