### ISSUE TITLE
Use existing resource group for creating azure VMs

### ISSUE THREAD

**Issue by madacsbotond** [skypilot-org/skypilot#2962]
I wanted to try out skypilot with Azure, but I haven't got full permission and I couldn't create new resource groups at our existing subscription. 
At the documentation I couldn't find what minimal permissions are needed (you can find AWS and GCP, but not Azure), I think skypilot should tell you that you haven't got enough permission before creating any clusters.
Are there any workarounds to use skypilot without creating new resource groups and using an already existing one? I can create any resources inside a resource group (except role/permission assignments).

**Comment by Michaelvll** [comment]
This is also related to #2910.
