### ISSUE TITLE
Sky check prompting for password

### ISSUE THREAD

**Issue by pbarker** [skypilot-org/skypilot#2973]
After a fresh installation on nightly (macOS 13.5) [gcp, aws] when I run:

```
sky check
```

I get prompted for my password:

```
Checking credentials to enable clouds for SkyPilot.
  Checking GCP...Please enter your password:
Please enter your password:
```

It's not my system password, I'm not sure whats causing this. I'm actively logged in to both aws and gcp, I reinstalled at different python versions with the same result.

**Comment by concretevitamin** [comment]
This is unexpected. Looks like it's prompted by one of the GCP commands. Here's the function that gets called: https://github.com/skypilot-org/skypilot/blob/master/sky/clouds/gcp.py#L593

Does manually running the below trigger this prompt?
- `gcloud --version`
- `gcloud auth list --filter=status:ACTIVE --format="value(account)"`
- Maybe set a breakpoint at https://github.com/skypilot-org/skypilot/blob/master/sky/clouds/gcp.py#L672

**Comment by pbarker** [comment]
```
 ~/  main !1  gcloud --version                                                                                                     255  3.10.1 py | agent-dev gcloud  21:58:27
Google Cloud SDK 443.0.0
bq 2.0.96
core 2023.08.11
gcloud-crc32c 1.0.0
gke-gcloud-auth-plugin 0.5.5
gsutil 5.25
Updates are available for some Google Cloud CLI components.  To install them,
please run:
  $ gcloud components update

 ~/  main !1  gcloud auth list --filter=status:ACTIVE --format="value(account)"                                                     ok  3.10.1 py | agent-dev gcloud  22:04:10
patrick.barker@awesome.ai


Updates are available for some Google Cloud CLI components.  To install them,
please run:
  $ gcloud components update
  ```
