### ISSUE TITLE
Feature Request OVH public cloud

### ISSUE THREAD

**Issue by k-e-r-n-e-l-p-a-n-i-c** [skypilot-org/skypilot#2974]
Please consider implementing this for compute instances provided by OVH public cloud. Although they do not provide spot instances, but the limited edition instances by OVH can be used as a drop in replacement.

**Comment by concretevitamin** [comment]
Hello @k-e-r-n-e-l-p-a-n-i-c, OVH is actually being added in #2740. Please add +1 there if it's important to your team.

**Comment by dtonda** [comment]
Would really be appreciated 👍

**Comment by TokeyChan** [comment]
I would like to bump this because it is important for my team. Any chance this can be reopened?
