### ISSUE TITLE
Feature Request: Support custom templates on runpod

### ISSUE THREAD

**Issue by 7flash** [skypilot-org/skypilot#3007]

**Comment by Michaelvll** [comment]
Thank you for filing the issue @7flash ! Would you like to elaborate a bit for the use case and example case that we can support?

**Comment by 7flash** [comment]
Trying to follow this example

https://github.com/skypilot-org/skypilot/blob/master/llm/vllm/serve-openai-api.yaml

It throws errors related to incompatible cuda drivers, as expected because default runpod image doesn't have correct dependencies

I added this line in config to spawn a machine with corrected container I found

```
  image_id: docker:alpayariyakrunpod/vllm-base:0.1.1-cuda-11.8.0-OG
```

But unfortunately the machine was still spawned with default runpod image

So I created runpod template manually

<img width="831" alt="image" src="https://github.com/skypilot-org/skypilot/assets/4569866/6396579f-8d87-4b07-a0bf-a55fbea09076">

And spawned a new instance with this template

<img width="777" alt="image" src="https://github.com/skypilot-org/skypilot/assets/4569866/ed2cdef5-8c75-44c3-b962-3b2bf939d490">

I'm not sure if it's possible to create templates with skypilot, but it's not a big deal

What's more important that's being able to specify template_id for resources, what do you think it takes to implement?

**Comment by Michaelvll** [comment]
Thank you for elaborating the use case @7flash! It may take a greater effort to support the `template_id` as we have to change the API of our `resources` section to it compatible with the template, but it seems we can definitely make it work for custom image by using the `image_id`. We probably just need to pump the argument to the cloud API call underneath (currently, it is not passed into the API call, which might be the reason why it fails to create the pod with the image).


The modification would involve the following steps:
1. pass the `image_id` in the resource config generated: https://github.com/skypilot-org/skypilot/blob/c05a0ea44f8e86b6d13852e209ec2693978e2244/sky/clouds/runpod.py#L171-L175
Reference: https://github.com/skypilot-org/skypilot/blob/c05a0ea44f8e86b6d13852e209ec2693978e2244/sky/clouds/aws.py#L406
2. Add the `image_id` in the `node_config`: https://github.com/skypilot-org/skypilot/blob/c05a0ea44f8e86b6d13852e209ec2693978e2244/sky/templates/runpod-ray.yml.j2#L21-L23
Reference: https://github.com/skypilot-org/skypilot/blob/c05a0ea44f8e86b6d13852e209ec2693978e2244/sky/templates/aws-ray.yml.j2#L72
3. Use the `image_id` during the `runpod` API call: https://github.com/skypilot-org/skypilot/blob/c05a0ea44f8e86b6d13852e209ec2693978e2244/sky/provision/runpod/instance.py#L82-L86
4. Pass the argument to the API call: https://github.com/skypilot-org/skypilot/blob/c05a0ea44f8e86b6d13852e209ec2693978e2244/sky/provision/runpod/utils.py#L105

It would be really helpful and appreciated if you could help submit a PR for this. No worries, if it does not work. We can work on that as well. : )
