### ISSUE TITLE
[k8s][UX] Suppress known host warnings on ssh

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#3008]
Our kubernetes ssh mechanism prints a bunch of warnings at each SSH command execution. User reported these can be distracting.
```
Warning: Permanently added '127.0.0.1' (ED25519) to the list of known hosts.
Warning: Permanently added '10.42.56.141' (ED25519) to the list of known hosts.
```
We should suppress these messages.

**Comment by raykoaza** [comment]
suppressing these warning, will have effect on other useful warning as well. Do you really think we should be considering doing that?
