### ISSUE TITLE
[k8s] AlreadyExists error if starting a recently downed cluster

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#3010]
From user:

> Getting this error if I sky down a k8s cluster and then immediately start a new one again
> ```
> kubernetes.client.exceptions.ApiException: (409)
> Reason: Conflict
> HTTP response headers: HTTPHeaderDict({'Audit-Id': '6ee8225c-b015-416f-b1b0-d48f862da171', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': '01cbc7dd-4f00-4163-b3f5-7d82328db5ad', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'f2ecb3db-f07d-451e-a854-de6ded0641fa', 'Date': 'Mon, 22 Jan 2024 06:50:56 GMT', 'Content-Length': '247'})
> HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"object is being deleted: pods \"k8s-test-4c1d-ray-head\" already exists","reason":"AlreadyExists","details":{"name":"k8s-test-4c1d-ray-head","kind":"pods"},"code":409}
> ```

**Comment by Michaelvll** [comment]
This should be solved by https://github.com/skypilot-org/skypilot/pull/3019/commits/686b5b33f9d2aff55d3e7342b2a188564fa7f207 ?
