### ISSUE TITLE
Swapping Accounts for Skypilot

### ISSUE THREAD

**Issue by michaelzhiluo** [skypilot-org/skypilot#3016]
Skypilot assumes that there is one account per cloud. It's be nice if there is mention in the docs on how to swap between different projects accounts IF there are multiple accounts per cloud. (i.e. separate GCP projects or AWS projects).

**Comment by Michaelvll** [comment]
Thanks for the request @michaelzhiluo! Here is a potential page that may solve your question: https://skypilot.readthedocs.io/en/latest/cloud-setup/cloud-auth.html

Could you see if this works for you?

**Comment by michaelzhiluo** [comment]
The docs can provide a potential solution but not sufficiently yet. The context swapping for the docs regards different projects on the same service account. However, swapping across service accounts can be very painful (I have one service account with projects that has access to _a lot_ of GPUs while the other service account is bounded by a budget).

The docs should include ```gcloud config set account [ACCOUNT_NAME]``` of some form.
