### ISSUE TITLE
[GCP] Fail to launch the cluster on GCP due to missing `legacy_credentials`

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#3026]
A user report the error occus during launching a GCP cluster:
```
cp -r '/home/xxx/.config/gcloud/legacy_credentials' /tmp/tmpyhwsu_df/8456a4f7-171b-4805-a0cc-4add4344e18d
```

This might relates to the update of the recent GCP credential.

gcloud version reported: 461.0.0

**Comment by concretevitamin** [comment]
Shall we make legacy_credentials optional?
