### ISSUE TITLE
Relative file mounts not working as expected

### ISSUE THREAD

**Issue by seftontycho** [skypilot-org/skypilot#3045]
I have the following project structure:
```
/project
    my_file.json
    /data
        data.yaml
        ...
    /train
        train.yaml
        ...
```

I want to use `my_file.json` for both my training runs and also for my dataset generation.
I only want to have one copy of `my_file.json`.

I have tried the following in `data.yaml`:
```
...
file_mounts:
    /my_file.json: ../my_file.json
...    
```

However I cannot find the file anywhere on the remote machine (AWS) when running with `sky launch -c cluster data.yaml` from within `project/data`.

It does work if I copy `my_file.json` to `/project/data` and set the path config to `/my_file.json: ./my_file.json`.
However this means I have to maintain two seperate copies of `my_file.json`  and any differences will break my project.
Is this a bug or am I doing it wrong?

Thanks,
Sefton

**Comment by landscapepainter** [comment]
Hi @seftontycho,
If you set
```
file_mounts:
    /my_file.json: ../my_file.json
```
`my_file.json` from your local machine will copy over the file to the root directory of your remote VM(`/my_file.json`). Basically, the syntax for what you are doing is:
```
file_mounts:
    /path/at/remote: /path/at/local
```
If you want to have a single copy to `my_file.json`, the way to go is to set a path for the file at remote machine that you are comfortable with, and refer to that path from training and dataset generation scripts. Please feel free to drop another clarifying questions if you need more assistance :)

**Comment by seftontycho** [comment]
Closing as I am an idiot and had quotes round one of the paths.
Removed them and it works.
Thanks for your help.
