### ISSUE TITLE
Unable to ssh into cluster after launch

### ISSUE THREAD

**Issue by jacobwjs** [skypilot-org/skypilot#3065]
I'm unable to ssh into the cluster, using the cluster name, immediately after launch.

e.g.
`sky launch -c dev-rag-west3 sky-jupyter.yaml` 

everything finishes fine,
```
I 02-01 16:39:03 cloud_vm_ray_backend.py:3168] Setup completed.
I 02-01 16:39:10 cloud_vm_ray_backend.py:3265] Job submitted with Job ID: 1
I 02-01 12:39:12 log_lib.py:431] Start streaming logs for job 1.
```

sky status shows the cluster is up and running, but trying to `ssh dev-rag-west3` results in,
`ssh: Could not resolve hostname dev-rag-west3: nodename nor servname provided, or not known`

If I find the public ip, and provide full path to `sky-key` I can connect,
`ssh azureuser@xx.xxx.xx.xx -i ~/.ssh/sky-key`

This is from a fresh SkyPilot nightly install

**Comment by Michaelvll** [comment]
Thanks for reporting this @jacobwjs! Could you help check if the `~/.ssh/config` has a line `Include ~/.sky/generated/ssh/*
` at the top?

**Comment by Michaelvll** [comment]
Just identified a potential issue that can causes this and we are fixing it in #3069. To unblock the case, could you try to add `Include ~/.sky/generated/ssh/*` at the top of your `~/.ssh/config` and try to ssh again?

**Comment by jacobwjs** [comment]
@Michaelvll Verified this fixes the issue. Thanks for the quick fix!
