### ISSUE TITLE
[GCP] m2 instance series not supported

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#3066]
User reported
```
»  sky launch --cloud gcp --instance-type m2-ultramem-416
ValueError: Invalid instance type 'm2-ultramem-416' for cloud GCP.
```

Low priority since it doesn't support spot.

**Comment by ighoshsubho** [comment]
I would like to work on this issue.

**Comment by concretevitamin** [comment]
Thanks @ighoshsubho; just assigned you to this issue. I'd suggest checking out
- https://github.com/skypilot-org/skypilot/blob/master/sky/clouds/service_catalog/data_fetchers/fetch_gcp.py
- https://github.com/skypilot-org/skypilot-catalog
