### ISSUE TITLE
[Clouds] Support slurm as a backend

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#3072]
Users were asking how SkyPilot should interact with slurm clusters.
We should think of how we should handle the case for slurm, i.e. whether to treat it as a job scheduler only or a way to start new clusters.

**Comment by michaelzhiluo** [comment]
A huge feature that users want in Slurm as well as Kubernetes is the ability to alloc or reserve parts of each node/creation of virtual clusters. This perfectly fits Skypilot's vision, as this is already implemented in Skypilot Kubernetes. 

Regarding job scheduler, we already have an implementation for Slurm and is under the domain of another lab project. Let's discuss further if needed.
