### ISSUE TITLE
Hi, Is there an open source program for the system's RFC?

### ISSUE THREAD

**Issue by HongLouyemeng** [skypilot-org/skypilot#3076]
Thank you for the open source, this project is really great and I'd like to dive into the workflow of it!QAQ

**Comment by concretevitamin** [comment]
Thank you for the interest @HongLouyemeng. SkyPilot doesn't have a formal RFC process. That said, if a contributor is planning to add a major component/feature,  we encourage you to draft a basic design doc and share with the community in GitHub issues and/or Slack.

**Comment by HongLouyemeng** [comment]
> Thank you for the interest @HongLouyemeng. SkyPilot doesn't have a formal RFC process. That said, if a contributor is planning to add a major component/feature, we encourage you to draft a basic design doc and share with the community in GitHub issues and/or Slack.

Thanks for the reply.I've been waiting for an email from github, but I can't join slack in my area.QAQ
