### ISSUE TITLE
[Docs] Clarify that setup for task should avoid installing other version of ray in base env

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#3082]
A user experiences an issue that job does not output anything and fails after installing `ray==2.6.3` in the setup.

**Comment by MysteryManav** [comment]
I would like to work on this issue. Would you specify what would the best place for the documentation to have this "warning" ?

**Comment by MysteryManav** [comment]
or I can just add it with the "Note" on the Installation Page in the documentation

**Comment by Michaelvll** [comment]
This has been fixed by #2801 and #3267.
