### ISSUE TITLE
Adding DNS capabilities to skypilot?

### ISSUE THREAD

**Issue by manzke** [skypilot-org/skypilot#3085]
How do you guys handle the changing IPs, if you are using spot instances? I'm using skypilot right now to serve LLMs for tests (call the instances from other services) and I don't want to change the IPs all the time a new spot instance is created.

I could also write a script which tries to update the DNS entry when starting up.

**Comment by Michaelvll** [comment]
Hi @manzke, thank you for asking!

If you would like to have a automatic recovery of spot instance and having the endpoint (IP:port) unchanged, you could try our new SkyServe feature, with which you can get a single endpoint, autoscaler and load-balancer. Please check out https://skypilot.readthedocs.io/en/latest/serving/sky-serve.html

**Comment by manzke** [comment]
@Michaelvll I'll have a look. I still think even connecting it to a DNS entry to have a named instance, would also be quite nice.
