### ISSUE TITLE
[SERVE] Add the ability to update a service in place

### ISSUE THREAD

**Issue by JGSweets** [skypilot-org/skypilot#3089]
Currently when pushing an update to a service, if there's an overlap in requirements for resources the new version does not utilize resources from the old version.

It would be ideal that it reuses resources if the following conditions are met:
1. All other conditions have not changed 
    - code
    - storage
    - etc.
2. There's an overlap in resources that the previous replica is using and the new replica requires
    - e.g. both systems utilize an instance type of X and the previous replica already has X stood up.
    - Therefore, transfer the previous resource to the new replica no longer requiring a new resource to stand up.
    - launch anything else required by the updated service as needed.

EDIT:
Example Cases:
1. Add a new allowed accelerator and keep the previous accelerators.
2. Update the min / max replicas.

These shouldn't require tearing down previous resources or spinning up new ones where it is unnecessary as this adds extra cost or may not be feasible due to service limit constraints.

**Comment by Michaelvll** [comment]
Thanks for the suggestion @JGSweets! This is a optimization we are thinking for the serve update as well! We should definitely get to it soon. Any contribution would be really appreciated as well : )

Related issues: #2956, #2992

**Comment by JGSweets** [comment]
Thanks @Michaelvll! 

Follow-up Q and likely a separate issue / request, but if we specify order can we suggest the min / max count for each resource specification? e.g. max - 2 `A10g: 4`,  max - 1 `A100: 8` etc.

**Comment by Michaelvll** [comment]
Hi @JGSweets, we added the support for reusing existing replicas, when only the `services` field is changed and no `workdir`, `file_mounts` are specified. Please check the hint in the doc: https://skypilot.readthedocs.io/en/latest/serving/update.html#rolling-update

We will further improve this reuse logic for:
1. `workdir` and `file_mounts` are specified
2. Accelerator list changes
