### ISSUE TITLE
[Docs] Add an example how to cache the models?

### ISSUE THREAD

**Issue by manzke** [skypilot-org/skypilot#3091]
While playing with skypilot and spinning up and down instances, I recognized there is no real documentation about caching. Especially when we use the examples for vllm (the ones without docker), a lot of the stuff is loaded again.
The models / weights are probably not changing, why downloading from huggingfaces, if I can have them in a bucket and don't even pay for the traffic (while I do for external).

Should be easy to use the downloaddir for vllm, map it to a bucket mapped directory and next time a new instance, it should be already there or am I missing something?

**Comment by concretevitamin** [comment]
Thanks for the feedback! Agreed it's an important part of the operations.  

Here's some docs we're adding; does it address this use case? https://github.com/skypilot-org/skypilot/pull/3073

**Comment by manzke** [comment]
Yeah already found that one and started doing it manually. ;) But I actually thought about caching the weights only in a bucket.

**Comment by concretevitamin** [comment]
I see. Have you compared `HF -> download to VM` vs. `Bucket -> download to VM`? Is the latter definitely faster?
