### ISSUE TITLE
Recovery of stopped instances doesn't work?

### ISSUE THREAD

**Issue by manzke** [skypilot-org/skypilot#3092]
When you start an instance with vllm, it works as expected.

When you stop it and later start the instance again, the server is not running anymore. Anything specific to do?

Easy to reproduce:
- start with vllm install, launch, ...
- stop instance
- start instance again

**Comment by concretevitamin** [comment]
`sky start` does not rerun any `setup` or `run` commands, which is why the vllm server isn't restarted.

You could use `sky launch -c my-stopped-cluster --no-setup my.yaml` to both restart and rerun the `run` commands.

**Comment by manzke** [comment]
thanks! would be a nice shortcut to have in the cli :D
