### ISSUE TITLE
[Clouds] OpenStack support

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#3097]
Many small clouds use [OpenStack](https://www.openstack.org/) - perhaps SkyPilot can support these clouds through a generic openstack support.

**Comment by jaehanbyun** [comment]
I’ll take a look and handle it.

**Comment by pdehaye** [comment]
Is there an update? 
This would be very interesting, for instance for Infomaniak 
https://www.infomaniak.com/fr/support/faq/2601/guide-de-demarrage-public-cloud

**Comment by Michaelvll** [comment]
Thanks for bumping on this! It would be really appreciated if you get a chance to push a PR for that : )

**Comment by neelaruban** [comment]
Any news on this PR ? i am happy to help it accelerate
