### ISSUE TITLE
Failed to Load GCP Advanced Configurations

### ISSUE THREAD

**Issue by mahmoudrasmyfathy1** [skypilot-org/skypilot#3100]
I encountered an error while setting up the advanced GCP configuration in SkyPilot. Following the [documentation](https://skypilot.readthedocs.io/en/latest/reference/config.html), I used the below configuration to use internal IPs

```
gcp:
  use_internal_ips: true
```

However, when initiating the cluster creation, the process failed with an error indicating that the use_internal_ips attribute is not recognized.

**Comment by Michaelvll** [comment]
Thanks for reporting this @mahmoudrasmyfathy1! Could you share the version of skypilot you are using with `sky --version` and `sky --commit`?
You may have to install the latest skypilot to get those features: 
```
pip uninstall skypilot
pip install -U skypilot-nightly
```

**Comment by mahmoudrasmyfathy1** [comment]
@Michaelvll , Thanks for your reply, I can confirm that the GCP advanced configuration functions correctly with **skypilot-nightly==1.0.0.dev20240206**, and in order to reproduce the issue I encountered, below are the software versions I was using:

Conda: 23.11.0
Python: 3.10.13
OS: Ubuntu 20.04.6 LTS
SkyPilot: 0.4.1
SkyPilot Commit: bfedf4593b01ea3a3edd05e8751cbcb11653078d

**Comment by Michaelvll** [comment]
Thanks for sharing the versions @mahmoudrasmyfathy1! We are recommending our users to use `skypilot-nightly` to get the latest features, but we are about to release a new stable version 0.5.0 soon, if you prefer to use the stable version. : )

**Comment by mahmoudrasmyfathy1** [comment]
ok great, thanks @Michaelvll
