### ISSUE TITLE
Error: Path Too Long for Unix Domain Socket in /tmp/skypilot_ssh_* Directory

### ISSUE THREAD

**Issue by mahmoudrasmyfathy1** [skypilot-org/skypilot#3101]
The function [_ssh_control_path ](https://github.com/skypilot-org/skypilot/blob/98e92fae44a5b6a39776095089c02a3c744a4f63/sky/utils/command_runner.py#L35) constructs paths that can exceed the maximum length limit for Unix domain sockets, leading to an error while initiating the cluster or sending jobs to the cluster. 

**Function Details:**
```
def _ssh_control_path(ssh_control_filename: Optional[str]) -> Optional[str]:
    """Returns a temporary path to be used as the ssh control path."""
    if ssh_control_filename is None:
        return None
    username = getpass.getuser()
    path = (f'/tmp/skypilot_ssh_{username}/{ssh_control_filename}')
    os.makedirs(path, exist_ok=True)
    return path
```
![image](https://github.com/skypilot-org/skypilot/assets/46302138/b6ab104b-02ce-4db9-b0ef-593f5d174f06)

**Potential Solution:** : 
A potential solution could be to truncate the ssh_control_filename or hash it to ensure the overall path length stays within the system-imposed limit for Unix domain sockets.

**Comment by Michaelvll** [comment]
That is a great catch @mahmoudrasmyfathy1 ! It seems the `%C` generates a quite long string which may not work with a long user name. Would you like to take stab on this issue?
I am thinking we can replace the `username` in the function you shown with `common_utils.get_user_hash()`, which will be a fixed length string we generated for the user.
https://github.com/skypilot-org/skypilot/blob/cf490287f140dbb271bab8fb77846c0d5da1ef45/sky/utils/command_runner.py#L35-L42

**Comment by mahmoudrasmyfathy1** [comment]
@Michaelvll I replaced the username variable with common_utils.get_user_hash(), and it's working well now.

```
def _ssh_control_path(ssh_control_filename: Optional[str]) -> Optional[str]:
    """Returns a temporary path to be used as the ssh control path."""
    if ssh_control_filename is None:
        return None
    username = getpass.getuser()
    path = (f'/tmp/skypilot_ssh_{common_utils.get_user_hash()}/{ssh_control_filename}')
    os.makedirs(path, exist_ok=True)
    return path
```

![image](https://github.com/skypilot-org/skypilot/assets/46302138/68f3fec5-468d-4cf4-9fbe-efd6e1aec365)

**Comment by Michaelvll** [comment]
> @Michaelvll I replaced the username variable with common_utils.get_user_hash(), and it's working well now.
> 
> ```
> def _ssh_control_path(ssh_control_filename: Optional[str]) -> Optional[str]:
>     """Returns a temporary path to be used as the ssh control path."""
>     if ssh_control_filename is None:
>         return None
>     username = getpass.getuser()
>     path = (f'/tmp/skypilot_ssh_{common_utils.get_user_hash()}/{ssh_control_filename}')
>     os.makedirs(path, exist_ok=True)
>     return path
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/46302138/302771661-68f3fec5-468d-4cf4-9fbe-efd6e1aec365.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNTI1NzQsIm5iZiI6MTcwNzI1MjI3NCwicGF0aCI6Ii80NjMwMjEzOC8zMDI3NzE2NjEtNjhmM2ZlYzUtNDY4ZC00Y2Y0LTlmYmUtZWZkNmUxYWVjMzY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDIwNDQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlMmU5NzNhYzdmNjQxNDY5MmVmOWE0YWE2OTFiNzM2OThiNjc5NGQ1YjAxNDAxZTFhNDgwOWQxZGI4MzAyOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CJuK4a28bUS_zkWBlBYO3PuqufTAJjhAr3v_ZwX7WSg)

Nice! Would you like to submit a pr for it?

**Comment by mahmoudrasmyfathy1** [comment]
> > @Michaelvll I replaced the username variable with common_utils.get_user_hash(), and it's working well now.
> > ```
> > def _ssh_control_path(ssh_control_filename: Optional[str]) -> Optional[str]:
> >     """Returns a temporary path to be used as the ssh control path."""
> >     if ssh_control_filename is None:
> >         return None
> >     username = getpass.getuser()
> >     path = (f'/tmp/skypilot_ssh_{common_utils.get_user_hash()}/{ssh_control_filename}')
> >     os.makedirs(path, exist_ok=True)
> >     return path
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://private-user-images.githubusercontent.com/46302138/302771661-68f3fec5-468d-4cf4-9fbe-efd6e1aec365.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNTI1NzQsIm5iZiI6MTcwNzI1MjI3NCwicGF0aCI6Ii80NjMwMjEzOC8zMDI3NzE2NjEtNjhmM2ZlYzUtNDY4ZC00Y2Y0LTlmYmUtZWZkNmUxYWVjMzY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDIwNDQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlMmU5NzNhYzdmNjQxNDY5MmVmOWE0YWE2OTFiNzM2OThiNjc5NGQ1YjAxNDAxZTFhNDgwOWQxZGI4MzAyOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CJuK4a28bUS_zkWBlBYO3PuqufTAJjhAr3v_ZwX7WSg)
> 
> Nice! Would you like to submit a pr for it?

yes I am working on that
