### ISSUE TITLE
[k8s] Auto-configure Nginx Ingress for `sky local up`

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#3112]
Nginx ingress can be useful for users using `sky local up` to expose services running on local cluster. We should look into automatically configuring and installing the nginx ingress controller in `sky local up` clusters: https://kind.sigs.k8s.io/docs/user/ingress/#ingress-nginx

**Comment by shethhriday29** [comment]
Being addressed by #3223

**Comment by shethhriday29** [comment]
@romilbhardwaj I think we can close this issue!

**Comment by romilbhardwaj** [comment]
Fixed by #3223 - thanks @shethhriday29!
