### ISSUE TITLE
Can't request multiple GPUs when deploying on Runpod

### ISSUE THREAD

**Issue by alxiang** [skypilot-org/skypilot#3146]
in `sky/provision/runpod/utils.py`, `gpu_quantity` only factors into `min_vcpu_count` and `min_memory_in_gb`, so when I have my resources like:

```
resources:
  cloud: runpod
  accelerators: A100-80GB-SXM:2
```

I only get 1 A100 in Runpod and not 2. Based on my understanding of Runpod's Python SDK, the proper way to specify the # of GPUs is the `gpu_count` parameter (see https://github.com/runpod/runpod-python/blob/9e11c994fcceba0d6c3cd35be87084a28d9426d3/runpod/api/ctl_commands.py#L119C12-L119C21).

I'm on `runpod==1.6.0`, seems like skypilot should be updated to be compatible?

**Comment by Michaelvll** [comment]
That is a great catch @alxiang! Thank you for reporting this! Would you like to submit a PR to fix this?
