### ISSUE TITLE
[GCP/Catalog] Add H100 GPUs on GCP

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#3150]
We should add the catalog for H100 GPUs on GCP.

https://cloud.google.com/blog/products/compute/introducing-a3-supercomputers-with-nvidia-h100-gpus

It seems possible to create a spot H100 GPU in our GCP project manually through the console, but it seems the SKU and the pricing table are not updated on GCP. As a first step we could try hardcode the H100 GPUs in our `fetch_gcp.py` and our catalog to make it possible to create H100 instances.

**Comment by leoitcode** [comment]
What is the possibilities to use the H100 on GCP and Skypilot?

**Comment by binarycrayon** [comment]
You can provision H100 via Preemptible instance

**Comment by leoitcode** [comment]
@binarycrayon I need to add something on Catalog? How I can set the YAML file to work with the a3-highgpu-8g instance?

**Comment by binarycrayon** [comment]
@leoitcode as the author mentioned, a3-highgpu-8g needed to be added (probably to) `fetch_gcp.py` so skypilot can link "H100:8" to the correct instance type `a3-highgpu-8g`. Just adding it to yaml may not work.

Yes you are correct, if you have quota approved you can just used it On-Demand. You can also use it as preemtible instance (cheaper)

**Comment by leo-multimodal** [comment]
@Michaelvll thank you for going through it! So, I'm receiving now the error:

`W 03-05 19:26:10 instance_utils.py:112] Got return code 'invalid' in us-central1-a: "Invalid value for field 'resource.instanceProperties.guestAccelerators[0].acceleratorType': 'nvidia-tesla-h100'. Accelerator type 'nvidia-tesla-h100' is not valid for zone 'us-central1-a'"`

`W 03-05 19:26:25 instance_utils.py:112] Got return code 'invalid' in us-central1-c: "Invalid value for field 'resource.instanceProperties.guestAccelerators[0].acceleratorType': 'nvidia-tesla-h100'. Accelerator type 'nvidia-tesla-h100' is not valid for zone 'us-central1-c'"`

**Comment by leoitcode** [comment]
Hello @Michaelvll , thanks for going through it. Now I'm receiving the error for all regions:

`W 03-05 19:26:10 instance_utils.py:112] Got return code 'invalid' in us-central1-a: "Invalid value for field 'resource.instanceProperties.guestAccelerators[0].acceleratorType': 'nvidia-tesla-h100'. Accelerator type 'nvidia-tesla-h100' is not valid for zone 'us-central1-a'"`

`W 03-05 19:26:25 instance_utils.py:112] Got return code 'invalid' in us-central1-c: "Invalid value for field 'resource.instanceProperties.guestAccelerators[0].acceleratorType': 'nvidia-tesla-h100'. Accelerator type 'nvidia-tesla-h100' is not valid for zone 'us-central1-c'"`

**Comment by Michaelvll** [comment]
> Hello @Michaelvll , thanks for checking it. Now I'm receiving the error for all regions:
> 
> `W 03-05 19:26:10 instance_utils.py:112] Got return code 'invalid' in us-central1-a: "Invalid value for field 'resource.instanceProperties.guestAccelerators[0].acceleratorType': 'nvidia-tesla-h100'. Accelerator type 'nvidia-tesla-h100' is not valid for zone 'us-central1-a'"`
> 
> `W 03-05 19:26:25 instance_utils.py:112] Got return code 'invalid' in us-central1-c: "Invalid value for field 'resource.instanceProperties.guestAccelerators[0].acceleratorType': 'nvidia-tesla-h100'. Accelerator type 'nvidia-tesla-h100' is not valid for zone 'us-central1-c'"`

Thanks for trying it out @leoitcode! It seems you are still using an older version of SkyPilot, could you update to the latest master to get the fix for H100?
```
pip uninstall skypilot skypilot-nightly
pip install git+https://github.com/skypilot-org/skypilot.git
```

**Comment by leo-multimodal** [comment]
It's working here, I was able to start the cluster with H100, I'll test the job running on it,
I really appreciated, thank you very much for the support!

**Comment by leoitcode** [comment]
@Michaelvll 
It's working here, I was able to start the cluster with H100, I'll test the job running on it,
I really appreciated, thank you very much for the support!
