### ISSUE TITLE
[Feature Request] Add CLI argument to specify custom path for `~/.sky/config.yml`

### ISSUE THREAD

**Issue by AlexvZyl** [skypilot-org/skypilot#3156]
In light of what we discussed in #1354, I would like to be able to specify a custom path for the sky config.  

The reason for this is I want to be able to store the sky config file in our repository and just reference it from there, instead of having to copy it to the current user's filesystem each time.

This would also make it easier to deploy SkyPilot to our infrastructure.

**Comment by concretevitamin** [comment]
Good point @AlexvZyl -- would using this env var work? 

https://github.com/skypilot-org/skypilot/blob/master/sky/skypilot_config.py#L67

Example usage:
```
SKYPILOT_CONFIG=/my/repo/my-org-sky-config.yaml sky launch ...
```

**Comment by AlexvZyl** [comment]
Yes, that would be perfect!
