### ISSUE TITLE
Initialization of service timeout

### ISSUE THREAD

**Issue by ScottLL** [skypilot-org/skypilot#3177]
Hello, 
I've tried the guild for [Quick tour: LLM serving](https://skypilot.readthedocs.io/en/latest/serving/sky-serve.html#:~:text=U%20skypilot%2Dnightly-,Quick%20tour%3A%20LLM%20serving,-%23), and I get the following issue:

I 02-17 17:48:55 provisioner.py:79] Launching on AWS us-east-1 (us-east-1a)
I 02-17 17:49:55 provisioner.py:454] Successfully provisioned or found existing instance.
I 02-17 17:51:06 provisioner.py:556] Successfully provisioned cluster: sky-serve-controller-99506131
I 02-17 17:51:07 cloud_vm_ray_backend.py:4469] Processing file mounts.
I 02-17 17:51:07 cloud_vm_ray_backend.py:4501] To view detailed progress: tail -n100 -f ~/sky_logs/sky-2024-02-17-17-48-52-719435/file_mounts.log
I 02-17 17:51:07 backend_utils.py:1288] Syncing (to 1 node): /var/folders/y2/rmtghvx11dsdnn88ldv2d4w00000gn/T/service-task-sky-service-2740-hb97zs5t -> ~/.sky/serve/sky_service_2740/task.yaml.tmp
I 02-17 17:51:09 cloud_vm_ray_backend.py:3209] Running setup on 1 node.
I 02-17 17:51:26 cloud_vm_ray_backend.py:3222] Setup completed.
I 02-17 17:51:33 cloud_vm_ray_backend.py:3319] Job submitted with Job ID: 1

E 02-17 17:52:35 subprocess_utils.py:82] **ValueError: Initialization of service 'sky-service-2740' timeout.**
E 02-17 17:52:35 subprocess_utils.py:82] 
RuntimeError: Failed to spin up the service. Please check the logs above for more details.

and I checked my AWS EC2 instance, the timeout error is happened before the instance initialization. any idea for how to solving this issue? 

Thank you!

**Comment by Michaelvll** [comment]
Thank you for submitting the issue @ScottLL! This should be fixed in our current master branch by #3175. You could try to clone the latest master branch and install it with `pip uninstall skypilot skypilot-nightly; pip install .[aws]` or wait a few hours so that our nightly build will include the fix, so you can use `pip install -U skypilot-nightly` to get the latest changes.

**Comment by ScottLL** [comment]
Appreciated!
