### ISSUE TITLE
[Serve][UX] Fine-grained reason for a replica failure

### ISSUE THREAD

**Issue by cblmemo** [skypilot-org/skypilot#3180]
Currently our recommendation to users is to check logs if the replica fails, but it might be easier to understand/debug if we can clearly state in the `sky status` output.

Potential solutions:
* More replica status, e.g. `RUN_FAILED`, `SETUP_FAILED`;
* Add a column to indicate failure reason in a plain text string.

**Comment by brian316** [comment]
you can run `sky serve logs <service_name> <replica_id>` to see the logs of the failing replica, but i agree that skypilot should have a status for failed build or stop creating new replicas if a max number of attempts was made

**Comment by cblmemo** [comment]
Already resolved by #3411. Closing now
