### ISSUE TITLE
CNCF TAG Runtime Discussion/Presentation

### ISSUE THREAD

**Issue by rajaskakodkar** [skypilot-org/skypilot#3204]
Hello Skypilot maintainers,

As the Tech Lead of [CNCF TAG Runtime](https://github.com/cncf/tag-runtime), I am reaching out to you to present/discuss Skypilot at one of our meetings.

It would be great to learn about the project overview and get to know what lies on your roadmap.

If you are interested, there is a slot available on 29th Feb on our [agenda](https://docs.google.com/document/d/1k7VNetgbuDNyIs_87GLQRH2W5SLgjgOhB6pDyv89MYk/edit#heading=h.qvunylimkyic). 

Please feel free to add it to the agenda or reach out to us in the [#tag-runtime](https://slack.cncf.io/) channel on the CNCF slack.

Thanks!

cc: @raravena80 @nikhita

**Comment by romilbhardwaj** [comment]
Thanks for the invite @rajaskakodkar! We'll be there and I've added SkyPilot to the agenda. How long should our presentation be, and are there any particular things you think that would be of interest to attendees?

**Comment by rajaskakodkar** [comment]
Hello @romilbhardwaj! We generally have the meeting slot for an hour. Currently you are the only one of the agenda so you can plan accordingly and leave enough time for QnA. Through his presentation we mainly look forward to knowing more about the project and its plans and if we can engage more! 

If it is of any help, you can go through past recordings here - https://www.youtube.com/watch?v=zCQ3gzEDdG4&list=PL6wYrb-bYwC_iStEfVmBpLKDBqOy23nCA

Thank you for adding yourself to the agenda!

**Comment by srust** [comment]
Hi @romilbhardwaj do you mind if we move your discusssion/presentation to MArch 7th? TAG-Runtime meets the 1st/3rd thursday of each month, which would put the next regularly scheduled meeting to March 7th. Sorry for the confusion! Does that March 7th slot work for you? If it does, I can adjust the agenda and put you into that time slot.

Thank you!

**Comment by romilbhardwaj** [comment]
Hi @srust - yes, I'm happy to do March 7. Thanks!

**Comment by srust** [comment]
thank you so much! appreciate the flexibility here. Talk to you then!

**Comment by srust** [comment]
Just posted the reminder: https://cloud-native.slack.com/archives/CPBE97SMU/p1709770139478149

March 7th, 2024 @ 8am PT

**Comment by romilbhardwaj** [comment]
Thanks @srust, looking forward to it!
