### ISSUE TITLE
[k8s] Set CUDA_VISIBLE_DEVICES to empty str when no GPUs are requested

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#3221]
Related to #2721. If a CPU only pod is launched on a GPU k8s node, GPUs will be visible inside it. We should set `CUDA_VISIBLE_DEVICES=""` or "-1" to avoid user code from using GPUs.

**Comment by Michaelvll** [comment]
IIRC, if the job is submitted with `sky exec` or `sky launch` it should have the CUDA_VISIBLE_DEVICES set. We should test it out. : )

**Comment by romilbhardwaj** [comment]
This is no longer an issue after strong GPU isolation from #3443.
