### ISSUE TITLE
[k8s] Surface logs during kubectl exec command execution on pods

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#3222]
Some of the command we execute on the pod as a part of the provisioning may fail or get stuck (e.g., due to network issues). We should print out the command logs in provision.log for easier debugging. 

https://github.com/skypilot-org/skypilot/blob/ae181e4f3ff06350e6376338b50dab03fec5b23c/sky/provision/kubernetes/instance.py#L320-L354

**Comment by shethhriday29** [comment]
Addressed by #3266

**Comment by romilbhardwaj** [comment]
Closed with #3266.
