### ISSUE TITLE
[k8s] Move socat/netcat dependency checks to `sky check` for k8s

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#3252]
From https://github.com/skypilot-org/skypilot/pull/3128#discussion_r1484898523:

> During the sky check can we check the installation of socat as well? I only got the error when I am running sky launch -c test-k8s --cloud kubernetes after my sky check shows kubernetes enabled.

**Comment by Michaelvll** [comment]
This is still relevant? @romilbhardwaj

**Comment by romilbhardwaj** [comment]
Yes, needs to be closed with #3306
