### ISSUE TITLE
not able to install azure with latest skypilot release

### ISSUE THREAD

**Issue by Kenadyi** [skypilot-org/skypilot#3253]
not able to install azure with latest skypilot release

The conflict is caused by:
    skypilot-nightly[azure] 1.0.0.dev20240228 depends on ray!=2.6.0, <=2.6.3 and >=2.2.0; extra == "azure"
    skypilot-nightly[azure] 1.0.0.dev20240228 depends on ray!=2.6.0, <=2.6.3 and >=2.2.0; extra == "azure"

**Comment by Kenadyi** [comment]
i have installed a new conda env to test this but still only azure fails

```

  Downloading skypilot_nightly-1.0.0.dev20221126-py3-none-any.whl.metadata (8.8 kB)
ERROR: Cannot install skypilot-nightly[azure]==1.0.0.dev20221126, skypilot-nightly[azure]==1.0.0.dev20230713, skypilot-nightly[azure]==1.0.0.dev20230714, skypilot-nightly[azure]==1.0.0.dev20230715, skypilot-nightly[azure]==1.0.0.dev20230716, skypilot-nightly[azure]==1.0.0.dev20230717, skypilot-nightly[azure]==1.0.0.dev20230718, skypilot-nightly[azure]==1.0.0.dev20230719, skypilot-nightly[azure]==1.0.0.dev20230720, skypilot-nightly[azure]==1.0.0.dev20230721, skypilot-nightly[azure]==1.0.0.dev20230722, skypilot-nightly[azure]==1.0.0.dev20230723, skypilot-nightly[azure]==1.0.0.dev20230724, skypilot-nightly[azure]==1.0.0.dev20230725, skypilot-nightly[azure]==1.0.0.dev20230726, skypilot-nightly[azure]==1.0.0.dev20230727, skypilot-nightly[azure]==1.0.0.dev20230728, skypilot-nightly[azure]==1.0.0.dev20230729, skypilot-nightly[azure]==1.0.0.dev20230730, skypilot-nightly[azure]==1.0.0.dev20230731, skypilot-nightly[azure]==1.0.0.dev20230801, skypilot-nightly[azure]==1.0.0.dev20230802, skypilot-nightly[azure]==1.0.0.dev20230803, skypilot-nightly[azure]==1.0.0.dev20230804, skypilot-nightly[azure]==1.0.0.dev20230805, skypilot-nightly[azure]==1.0.0.dev20230806, skypilot-nightly[azure]==1.0.0.dev20230807, skypilot-nightly[azure]==1.0.0.dev20230808, skypilot-nightly[azure]==1.0.0.dev20230809, skypilot-nightly[azure]==1.0.0.dev20230810, skypilot-nightly[azure]==1.0.0.dev20230811, skypilot-nightly[azure]==1.0.0.dev20230812, skypilot-nightly[azure]==1.0.0.dev20230813, skypilot-nightly[azure]==1.0.0.dev20230814, skypilot-nightly[azure]==1.0.0.dev20230815, skypilot-nightly[azure]==1.0.0.dev20230816, skypilot-nightly[azure]==1.0.0.dev20230817, skypilot-nightly[azure]==1.0.0.dev20230818, skypilot-nightly[azure]==1.0.0.dev20230819, skypilot-nightly[azure]==1.0.0.dev20230820, skypilot-nightly[azure]==1.0.0.dev20230821, skypilot-nightly[azure]==1.0.0.dev20230822, skypilot-nightly[azure]==1.0.0.dev20230823, skypilot-nightly[azure]==1.0.0.dev20230824, skypilot-nightly[azure]==1.0.0.dev20230825, skypilot-nightly[azure]==1.0.0.dev20230826, skypilot-nightly[azure]==1.0.0.dev20230827, skypilot-nightly[azure]==1.0.0.dev20230828, skypilot-nightly[azure]==1.0.0.dev20230829, skypilot-nightly[azure]==1.0.0.dev20230830, skypilot-nightly[azure]==1.0.0.dev20230831, skypilot-nightly[azure]==1.0.0.dev20230901, skypilot-nightly[azure]==1.0.0.dev20230902, skypilot-nightly[azure]==1.0.0.dev20230903, skypilot-nightly[azure]==1.0.0.dev20230904, skypilot-nightly[azure]==1.0.0.dev20230905, skypilot-nightly[azure]==1.0.0.dev20230906, skypilot-nightly[azure]==1.0.0.dev20230907, skypilot-nightly[azure]==1.0.0.dev20230908, skypilot-nightly[azure]==1.0.0.dev20230909, skypilot-nightly[azure]==1.0.0.dev20230910, skypilot-nightly[azure]==1.0.0.dev20230911, skypilot-nightly[azure]==1.0.0.dev20230912, skypilot-nightly[azure]==1.0.0.dev20230913, skypilot-nightly[azure]==1.0.0.dev20230914, skypilot-nightly[azure]==1.0.0.dev20230915, skypilot-nightly[azure]==1.0.0.dev20230916, skypilot-nightly[azure]==1.0.0.dev20230917, skypilot-nightly[azure]==1.0.0.dev20230918, skypilot-nightly[azure]==1.0.0.dev20230919, skypilot-nightly[azure]==1.0.0.dev20230920, skypilot-nightly[azure]==1.0.0.dev20230921, skypilot-nightly[azure]==1.0.0.dev20230922, skypilot-nightly[azure]==1.0.0.dev20230923, skypilot-nightly[azure]==1.0.0.dev20230924, skypilot-nightly[azure]==1.0.0.dev20230925, skypilot-nightly[azure]==1.0.0.dev20230926, skypilot-nightly[azure]==1.0.0.dev20230927, skypilot-nightly[azure]==1.0.0.dev20230928, skypilot-nightly[azure]==1.0.0.dev20230929, skypilot-nightly[azure]==1.0.0.dev20230930, skypilot-nightly[azure]==1.0.0.dev20231001, skypilot-nightly[azure]==1.0.0.dev20231002, skypilot-nightly[azure]==1.0.0.dev20231005, skypilot-nightly[azure]==1.0.0.dev20231006, skypilot-nightly[azure]==1.0.0.dev20231007, skypilot-nightly[azure]==1.0.0.dev20231008, skypilot-nightly[azure]==1.0.0.dev20231009, skypilot-nightly[azure]==1.0.0.dev20231010, skypilot-nightly[azure]==1.0.0.dev20231011, skypilot-nightly[azure]==1.0.0.dev20231012, skypilot-nightly[azure]==1.0.0.dev20231013, skypilot-nightly[azure]==1.0.0.dev20231014, skypilot-nightly[azure]==1.0.0.dev20231015, skypilot-nightly[azure]==1.0.0.dev20231016, skypilot-nightly[azure]==1.0.0.dev20231017, skypilot-nightly[azure]==1.0.0.dev20231018, skypilot-nightly[azure]==1.0.0.dev20231019, skypilot-nightly[azure]==1.0.0.dev20231020, skypilot-nightly[azure]==1.0.0.dev20231021, skypilot-nightly[azure]==1.0.0.dev20231022, skypilot-nightly[azure]==1.0.0.dev20231023, skypilot-nightly[azure]==1.0.0.dev20231024, skypilot-nightly[azure]==1.0.0.dev20231025, skypilot-nightly[azure]==1.0.0.dev20231026, skypilot-nightly[azure]==1.0.0.dev20231027, skypilot-nightly[azure]==1.0.0.dev20231028, skypilot-nightly[azure]==1.0.0.dev20231029, skypilot-nightly[azure]==1.0.0.dev20231030, skypilot-nightly[azure]==1.0.0.dev20231031, skypilot-nightly[azure]==1.0.0.dev20231101, skypilot-nightly[azure]==1.0.0.dev20231102, skypilot-nightly[azure]==1.0.0.dev20231103, skypilot-nightly[azure]==1.0.0.dev20231104, skypilot-nightly[azure]==1.0.0.dev20231105, skypilot-nightly[azure]==1.0.0.dev20231106, skypilot-nightly[azure]==1.0.0.dev20231107, skypilot-nightly[azure]==1.0.0.dev20231108, skypilot-nightly[azure]==1.0.0.dev20231109, skypilot-nightly[azure]==1.0.0.dev20231110, skypilot-nightly[azure]==1.0.0.dev20231111, skypilot-nightly[azure]==1.0.0.dev20231112, skypilot-nightly[azure]==1.0.0.dev20231113, skypilot-nightly[azure]==1.0.0.dev20231114, skypilot-nightly[azure]==1.0.0.dev20231115, skypilot-nightly[azure]==1.0.0.dev20231116, skypilot-nightly[azure]==1.0.0.dev20231117, skypilot-nightly[azure]==1.0.0.dev20231118, skypilot-nightly[azure]==1.0.0.dev20231119, skypilot-nightly[azure]==1.0.0.dev20231120, skypilot-nightly[azure]==1.0.0.dev20231121, skypilot-nightly[azure]==1.0.0.dev20231122, skypilot-nightly[azure]==1.0.0.dev20231123, skypilot-nightly[azure]==1.0.0.dev20231124, skypilot-nightly[azure]==1.0.0.dev20231125, skypilot-nightly[azure]==1.0.0.dev20231126, skypilot-nightly[azure]==1.0.0.dev20231127, skypilot-nightly[azure]==1.0.0.dev20231128, skypilot-nightly[azure]==1.0.0.dev20231129, skypilot-nightly[azure]==1.0.0.dev20231130, skypilot-nightly[azure]==1.0.0.dev20231201, skypilot-nightly[azure]==1.0.0.dev20231202, skypilot-nightly[azure]==1.0.0.dev20231203, skypilot-nightly[azure]==1.0.0.dev20231204, skypilot-nightly[azure]==1.0.0.dev20231205, skypilot-nightly[azure]==1.0.0.dev20231206, skypilot-nightly[azure]==1.0.0.dev20231207, skypilot-nightly[azure]==1.0.0.dev20231208, skypilot-nightly[azure]==1.0.0.dev20231209, skypilot-nightly[azure]==1.0.0.dev20231210, skypilot-nightly[azure]==1.0.0.dev20231211, skypilot-nightly[azure]==1.0.0.dev20231212, skypilot-nightly[azure]==1.0.0.dev20231213, skypilot-nightly[azure]==1.0.0.dev20231214, skypilot-nightly[azure]==1.0.0.dev20231215, skypilot-nightly[azure]==1.0.0.dev20231216, skypilot-nightly[azure]==1.0.0.dev20231217, skypilot-nightly[azure]==1.0.0.dev20231218, skypilot-nightly[azure]==1.0.0.dev20231219, skypilot-nightly[azure]==1.0.0.dev20231220, skypilot-nightly[azure]==1.0.0.dev20231221, skypilot-nightly[azure]==1.0.0.dev20231222, skypilot-nightly[azure]==1.0.0.dev20231223, skypilot-nightly[azure]==1.0.0.dev20231224, skypilot-nightly[azure]==1.0.0.dev20231225, skypilot-nightly[azure]==1.0.0.dev20231226, skypilot-nightly[azure]==1.0.0.dev20231227, skypilot-nightly[azure]==1.0.0.dev20231228, skypilot-nightly[azure]==1.0.0.dev20231229, skypilot-nightly[azure]==1.0.0.dev20231230, skypilot-nightly[azure]==1.0.0.dev20231231, skypilot-nightly[azure]==1.0.0.dev20240101, skypilot-nightly[azure]==1.0.0.dev20240102, skypilot-nightly[azure]==1.0.0.dev20240103, skypilot-nightly[azure]==1.0.0.dev20240104, skypilot-nightly[azure]==1.0.0.dev20240105, skypilot-nightly[azure]==1.0.0.dev20240106, skypilot-nightly[azure]==1.0.0.dev20240107, skypilot-nightly[azure]==1.0.0.dev20240108, skypilot-nightly[azure]==1.0.0.dev20240109, skypilot-nightly[azure]==1.0.0.dev20240110, skypilot-nightly[azure]==1.0.0.dev20240111, skypilot-nightly[azure]==1.0.0.dev20240112, skypilot-nightly[azure]==1.0.0.dev20240113, skypilot-nightly[azure]==1.0.0.dev20240114, skypilot-nightly[azure]==1.0.0.dev20240115, skypilot-nightly[azure]==1.0.0.dev20240116, skypilot-nightly[azure]==1.0.0.dev20240117, skypilot-nightly[azure]==1.0.0.dev20240118, skypilot-nightly[azure]==1.0.0.dev20240119, skypilot-nightly[azure]==1.0.0.dev20240120, skypilot-nightly[azure]==1.0.0.dev20240121, skypilot-nightly[azure]==1.0.0.dev20240122, skypilot-nightly[azure]==1.0.0.dev20240125, skypilot-nightly[azure]==1.0.0.dev20240126, skypilot-nightly[azure]==1.0.0.dev20240127, skypilot-nightly[azure]==1.0.0.dev20240128, skypilot-nightly[azure]==1.0.0.dev20240129, skypilot-nightly[azure]==1.0.0.dev20240130, skypilot-nightly[azure]==1.0.0.dev20240131, skypilot-nightly[azure]==1.0.0.dev20240201, skypilot-nightly[azure]==1.0.0.dev20240202, skypilot-nightly[azure]==1.0.0.dev20240203, skypilot-nightly[azure]==1.0.0.dev20240204, skypilot-nightly[azure]==1.0.0.dev20240205, skypilot-nightly[azure]==1.0.0.dev20240206, skypilot-nightly[azure]==1.0.0.dev20240207, skypilot-nightly[azure]==1.0.0.dev20240208, skypilot-nightly[azure]==1.0.0.dev20240209, skypilot-nightly[azure]==1.0.0.dev20240210, skypilot-nightly[azure]==1.0.0.dev20240211, skypilot-nightly[azure]==1.0.0.dev20240212, skypilot-nightly[azure]==1.0.0.dev20240213, skypilot-nightly[azure]==1.0.0.dev20240214, skypilot-nightly[azure]==1.0.0.dev20240215, skypilot-nightly[azure]==1.0.0.dev20240216, skypilot-nightly[azure]==1.0.0.dev20240217, skypilot-nightly[azure]==1.0.0.dev20240218, skypilot-nightly[azure]==1.0.0.dev20240220, skypilot-nightly[azure]==1.0.0.dev20240221, skypilot-nightly[azure]==1.0.0.dev20240222, skypilot-nightly[azure]==1.0.0.dev20240223, skypilot-nightly[azure]==1.0.0.dev20240224, skypilot-nightly[azure]==1.0.0.dev20240225, skypilot-nightly[azure]==1.0.0.dev20240226, skypilot-nightly[azure]==1.0.0.dev20240227, skypilot-nightly[azure]==1.0.0.dev20240228, skypilot-nightly[azure]==1.0.0.dev20240229 and skypilot-nightly[azure]==1.0.0.dev20240301 because these package versions have conflicting dependencies.

The conflict is caused by:

```

**Comment by Michaelvll** [comment]
> i have installed a new conda env to test this but still only azure fails
> 
> ```
> 
>   Downloading skypilot_nightly-1.0.0.dev20221126-py3-none-any.whl.metadata (8.8 kB)
> ERROR: Cannot install skypilot-nightly[azure]==1.0.0.dev20221126, skypilot-nightly[azure]==1.0.0.dev20230713, skypilot-nightly[azure]==1.0.0.dev20230714, skypilot-nightly[azure]==1.0.0.dev20230715, skypilot-nightly[azure]==1.0.0.dev20230716, skypilot-nightly[azure]==1.0.0.dev20230717, skypilot-nightly[azure]==1.0.0.dev20230718, skypilot-nightly[azure]==1.0.0.dev20230719, skypilot-nightly[azure]==1.0.0.dev20230720, skypilot-nightly[azure]==1.0.0.dev20230721, skypilot-nightly[azure]==1.0.0.dev20230722, skypilot-nightly[azure]==1.0.0.dev20230723, skypilot-nightly[azure]==1.0.0.dev20230724, skypilot-nightly[azure]==1.0.0.dev20230725, skypilot-nightly[azure]==1.0.0.dev20230726, skypilot-nightly[azure]==1.0.0.dev20230727, skypilot-nightly[azure]==1.0.0.dev20230728, skypilot-nightly[azure]==1.0.0.dev20230729, skypilot-nightly[azure]==1.0.0.dev20230730, skypilot-nightly[azure]==1.0.0.dev20230731, skypilot-nightly[azure]==1.0.0.dev20230801, skypilot-nightly[azure]==1.0.0.dev20230802, skypilot-nightly[azure]==1.0.0.dev20230803, skypilot-nightly[azure]==1.0.0.dev20230804, skypilot-nightly[azure]==1.0.0.dev20230805, skypilot-nightly[azure]==1.0.0.dev20230806, skypilot-nightly[azure]==1.0.0.dev20230807, skypilot-nightly[azure]==1.0.0.dev20230808, skypilot-nightly[azure]==1.0.0.dev20230809, skypilot-nightly[azure]==1.0.0.dev20230810, skypilot-nightly[azure]==1.0.0.dev20230811, skypilot-nightly[azure]==1.0.0.dev20230812, skypilot-nightly[azure]==1.0.0.dev20230813, skypilot-nightly[azure]==1.0.0.dev20230814, skypilot-nightly[azure]==1.0.0.dev20230815, skypilot-nightly[azure]==1.0.0.dev20230816, skypilot-nightly[azure]==1.0.0.dev20230817, skypilot-nightly[azure]==1.0.0.dev20230818, skypilot-nightly[azure]==1.0.0.dev20230819, skypilot-nightly[azure]==1.0.0.dev20230820, skypilot-nightly[azure]==1.0.0.dev20230821, skypilot-nightly[azure]==1.0.0.dev20230822, skypilot-nightly[azure]==1.0.0.dev20230823, skypilot-nightly[azure]==1.0.0.dev20230824, skypilot-nightly[azure]==1.0.0.dev20230825, skypilot-nightly[azure]==1.0.0.dev20230826, skypilot-nightly[azure]==1.0.0.dev20230827, skypilot-nightly[azure]==1.0.0.dev20230828, skypilot-nightly[azure]==1.0.0.dev20230829, skypilot-nightly[azure]==1.0.0.dev20230830, skypilot-nightly[azure]==1.0.0.dev20230831, skypilot-nightly[azure]==1.0.0.dev20230901, skypilot-nightly[azure]==1.0.0.dev20230902, skypilot-nightly[azure]==1.0.0.dev20230903, skypilot-nightly[azure]==1.0.0.dev20230904, skypilot-nightly[azure]==1.0.0.dev20230905, skypilot-nightly[azure]==1.0.0.dev20230906, skypilot-nightly[azure]==1.0.0.dev20230907, skypilot-nightly[azure]==1.0.0.dev20230908, skypilot-nightly[azure]==1.0.0.dev20230909, skypilot-nightly[azure]==1.0.0.dev20230910, skypilot-nightly[azure]==1.0.0.dev20230911, skypilot-nightly[azure]==1.0.0.dev20230912, skypilot-nightly[azure]==1.0.0.dev20230913, skypilot-nightly[azure]==1.0.0.dev20230914, skypilot-nightly[azure]==1.0.0.dev20230915, skypilot-nightly[azure]==1.0.0.dev20230916, skypilot-nightly[azure]==1.0.0.dev20230917, skypilot-nightly[azure]==1.0.0.dev20230918, skypilot-nightly[azure]==1.0.0.dev20230919, skypilot-nightly[azure]==1.0.0.dev20230920, skypilot-nightly[azure]==1.0.0.dev20230921, skypilot-nightly[azure]==1.0.0.dev20230922, skypilot-nightly[azure]==1.0.0.dev20230923, skypilot-nightly[azure]==1.0.0.dev20230924, skypilot-nightly[azure]==1.0.0.dev20230925, skypilot-nightly[azure]==1.0.0.dev20230926, skypilot-nightly[azure]==1.0.0.dev20230927, skypilot-nightly[azure]==1.0.0.dev20230928, skypilot-nightly[azure]==1.0.0.dev20230929, skypilot-nightly[azure]==1.0.0.dev20230930, skypilot-nightly[azure]==1.0.0.dev20231001, skypilot-nightly[azure]==1.0.0.dev20231002, skypilot-nightly[azure]==1.0.0.dev20231005, skypilot-nightly[azure]==1.0.0.dev20231006, skypilot-nightly[azure]==1.0.0.dev20231007, skypilot-nightly[azure]==1.0.0.dev20231008, skypilot-nightly[azure]==1.0.0.dev20231009, skypilot-nightly[azure]==1.0.0.dev20231010, skypilot-nightly[azure]==1.0.0.dev20231011, skypilot-nightly[azure]==1.0.0.dev20231012, skypilot-nightly[azure]==1.0.0.dev20231013, skypilot-nightly[azure]==1.0.0.dev20231014, skypilot-nightly[azure]==1.0.0.dev20231015, skypilot-nightly[azure]==1.0.0.dev20231016, skypilot-nightly[azure]==1.0.0.dev20231017, skypilot-nightly[azure]==1.0.0.dev20231018, skypilot-nightly[azure]==1.0.0.dev20231019, skypilot-nightly[azure]==1.0.0.dev20231020, skypilot-nightly[azure]==1.0.0.dev20231021, skypilot-nightly[azure]==1.0.0.dev20231022, skypilot-nightly[azure]==1.0.0.dev20231023, skypilot-nightly[azure]==1.0.0.dev20231024, skypilot-nightly[azure]==1.0.0.dev20231025, skypilot-nightly[azure]==1.0.0.dev20231026, skypilot-nightly[azure]==1.0.0.dev20231027, skypilot-nightly[azure]==1.0.0.dev20231028, skypilot-nightly[azure]==1.0.0.dev20231029, skypilot-nightly[azure]==1.0.0.dev20231030, skypilot-nightly[azure]==1.0.0.dev20231031, skypilot-nightly[azure]==1.0.0.dev20231101, skypilot-nightly[azure]==1.0.0.dev20231102, skypilot-nightly[azure]==1.0.0.dev20231103, skypilot-nightly[azure]==1.0.0.dev20231104, skypilot-nightly[azure]==1.0.0.dev20231105, skypilot-nightly[azure]==1.0.0.dev20231106, skypilot-nightly[azure]==1.0.0.dev20231107, skypilot-nightly[azure]==1.0.0.dev20231108, skypilot-nightly[azure]==1.0.0.dev20231109, skypilot-nightly[azure]==1.0.0.dev20231110, skypilot-nightly[azure]==1.0.0.dev20231111, skypilot-nightly[azure]==1.0.0.dev20231112, skypilot-nightly[azure]==1.0.0.dev20231113, skypilot-nightly[azure]==1.0.0.dev20231114, skypilot-nightly[azure]==1.0.0.dev20231115, skypilot-nightly[azure]==1.0.0.dev20231116, skypilot-nightly[azure]==1.0.0.dev20231117, skypilot-nightly[azure]==1.0.0.dev20231118, skypilot-nightly[azure]==1.0.0.dev20231119, skypilot-nightly[azure]==1.0.0.dev20231120, skypilot-nightly[azure]==1.0.0.dev20231121, skypilot-nightly[azure]==1.0.0.dev20231122, skypilot-nightly[azure]==1.0.0.dev20231123, skypilot-nightly[azure]==1.0.0.dev20231124, skypilot-nightly[azure]==1.0.0.dev20231125, skypilot-nightly[azure]==1.0.0.dev20231126, skypilot-nightly[azure]==1.0.0.dev20231127, skypilot-nightly[azure]==1.0.0.dev20231128, skypilot-nightly[azure]==1.0.0.dev20231129, skypilot-nightly[azure]==1.0.0.dev20231130, skypilot-nightly[azure]==1.0.0.dev20231201, skypilot-nightly[azure]==1.0.0.dev20231202, skypilot-nightly[azure]==1.0.0.dev20231203, skypilot-nightly[azure]==1.0.0.dev20231204, skypilot-nightly[azure]==1.0.0.dev20231205, skypilot-nightly[azure]==1.0.0.dev20231206, skypilot-nightly[azure]==1.0.0.dev20231207, skypilot-nightly[azure]==1.0.0.dev20231208, skypilot-nightly[azure]==1.0.0.dev20231209, skypilot-nightly[azure]==1.0.0.dev20231210, skypilot-nightly[azure]==1.0.0.dev20231211, skypilot-nightly[azure]==1.0.0.dev20231212, skypilot-nightly[azure]==1.0.0.dev20231213, skypilot-nightly[azure]==1.0.0.dev20231214, skypilot-nightly[azure]==1.0.0.dev20231215, skypilot-nightly[azure]==1.0.0.dev20231216, skypilot-nightly[azure]==1.0.0.dev20231217, skypilot-nightly[azure]==1.0.0.dev20231218, skypilot-nightly[azure]==1.0.0.dev20231219, skypilot-nightly[azure]==1.0.0.dev20231220, skypilot-nightly[azure]==1.0.0.dev20231221, skypilot-nightly[azure]==1.0.0.dev20231222, skypilot-nightly[azure]==1.0.0.dev20231223, skypilot-nightly[azure]==1.0.0.dev20231224, skypilot-nightly[azure]==1.0.0.dev20231225, skypilot-nightly[azure]==1.0.0.dev20231226, skypilot-nightly[azure]==1.0.0.dev20231227, skypilot-nightly[azure]==1.0.0.dev20231228, skypilot-nightly[azure]==1.0.0.dev20231229, skypilot-nightly[azure]==1.0.0.dev20231230, skypilot-nightly[azure]==1.0.0.dev20231231, skypilot-nightly[azure]==1.0.0.dev20240101, skypilot-nightly[azure]==1.0.0.dev20240102, skypilot-nightly[azure]==1.0.0.dev20240103, skypilot-nightly[azure]==1.0.0.dev20240104, skypilot-nightly[azure]==1.0.0.dev20240105, skypilot-nightly[azure]==1.0.0.dev20240106, skypilot-nightly[azure]==1.0.0.dev20240107, skypilot-nightly[azure]==1.0.0.dev20240108, skypilot-nightly[azure]==1.0.0.dev20240109, skypilot-nightly[azure]==1.0.0.dev20240110, skypilot-nightly[azure]==1.0.0.dev20240111, skypilot-nightly[azure]==1.0.0.dev20240112, skypilot-nightly[azure]==1.0.0.dev20240113, skypilot-nightly[azure]==1.0.0.dev20240114, skypilot-nightly[azure]==1.0.0.dev20240115, skypilot-nightly[azure]==1.0.0.dev20240116, skypilot-nightly[azure]==1.0.0.dev20240117, skypilot-nightly[azure]==1.0.0.dev20240118, skypilot-nightly[azure]==1.0.0.dev20240119, skypilot-nightly[azure]==1.0.0.dev20240120, skypilot-nightly[azure]==1.0.0.dev20240121, skypilot-nightly[azure]==1.0.0.dev20240122, skypilot-nightly[azure]==1.0.0.dev20240125, skypilot-nightly[azure]==1.0.0.dev20240126, skypilot-nightly[azure]==1.0.0.dev20240127, skypilot-nightly[azure]==1.0.0.dev20240128, skypilot-nightly[azure]==1.0.0.dev20240129, skypilot-nightly[azure]==1.0.0.dev20240130, skypilot-nightly[azure]==1.0.0.dev20240131, skypilot-nightly[azure]==1.0.0.dev20240201, skypilot-nightly[azure]==1.0.0.dev20240202, skypilot-nightly[azure]==1.0.0.dev20240203, skypilot-nightly[azure]==1.0.0.dev20240204, skypilot-nightly[azure]==1.0.0.dev20240205, skypilot-nightly[azure]==1.0.0.dev20240206, skypilot-nightly[azure]==1.0.0.dev20240207, skypilot-nightly[azure]==1.0.0.dev20240208, skypilot-nightly[azure]==1.0.0.dev20240209, skypilot-nightly[azure]==1.0.0.dev20240210, skypilot-nightly[azure]==1.0.0.dev20240211, skypilot-nightly[azure]==1.0.0.dev20240212, skypilot-nightly[azure]==1.0.0.dev20240213, skypilot-nightly[azure]==1.0.0.dev20240214, skypilot-nightly[azure]==1.0.0.dev20240215, skypilot-nightly[azure]==1.0.0.dev20240216, skypilot-nightly[azure]==1.0.0.dev20240217, skypilot-nightly[azure]==1.0.0.dev20240218, skypilot-nightly[azure]==1.0.0.dev20240220, skypilot-nightly[azure]==1.0.0.dev20240221, skypilot-nightly[azure]==1.0.0.dev20240222, skypilot-nightly[azure]==1.0.0.dev20240223, skypilot-nightly[azure]==1.0.0.dev20240224, skypilot-nightly[azure]==1.0.0.dev20240225, skypilot-nightly[azure]==1.0.0.dev20240226, skypilot-nightly[azure]==1.0.0.dev20240227, skypilot-nightly[azure]==1.0.0.dev20240228, skypilot-nightly[azure]==1.0.0.dev20240229 and skypilot-nightly[azure]==1.0.0.dev20240301 because these package versions have conflicting dependencies.
> 
> The conflict is caused by:
> ```

Sorry for the delay @Kenadyi! Do we have the complete log for which pacakge is causing the confliction? It seems the log you shown above is not complete. 

Could you share the `out.log` with the following command `pip install skypilot-nightly[azure] > out.log`?

Also, just to confirm, which python version are you using in your conda environments?

**Comment by Kenadyi** [comment]
[out.log](https://github.com/skypilot-org/skypilot/files/14509496/out.log)
@Michaelvll 
Uploaded out.log

**Comment by Michaelvll** [comment]
Ahh, it seems you are using python 3.12, which is not supported by many of our dependencies. Could you try to use `python 3.10` in the conda env?

**Comment by Michaelvll** [comment]
Hi @Kenadyi, just a kind bump for this. Does switch python version to 3.10 work for you? : )

**Comment by Kenadyi** [comment]
@Michaelvll ,
Yes it did work thank you
