### ISSUE TITLE
[Catalog] AWS K80 image removed, causing any K80 launch to fail

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#3273]
Repro: `sky launch --gpus K80 --cloud aws`
```
..
I 03-04 14:18:59 cloud_vm_ray_backend.py:1457] No image found in catalog for region us-east-2. Try setting a valid image_id.
```

It’s due to skypilot:k80-* images in the catalog https://github.com/skypilot-org/skypilot-catalog/blob/master/catalogs/v5/aws/images.csv being empty. Removed in this catalog auto update: 

https://github.com/skypilot-org/skypilot-catalog/commit/55fc35372730363b16169525f0c8ff9f44f84fe1

**Comment by Michaelvll** [comment]
We should probably start removing our k80 support across multiple clouds considering the deprecation of the gpu on those clouds.
