### ISSUE TITLE
[Storage] Error out when no access to the bucket during storage mounting

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#3282]
We should error out when storage mounting fails on the remote VM. The following case reproduce the error:
1. Having an AWS SSO setup
2. Launch a VM on fluidstack with a private s3 bucket mounted
Since the SSO setup will not upload the credential to the remote VM, the mounting of the s3 bucket will fail silently due to the access issue. We should fail directly for that to make the issue more easy to identify.

**Comment by romilbhardwaj** [comment]
Related - #1895

**Comment by shethhriday29** [comment]
Addressed by #3400
