### ISSUE TITLE
Subdirectories are excluded in a way distinct from regular .gitignore rules

### ISSUE THREAD

**Issue by fozziethebeat** [skypilot-org/skypilot#3298]
I have a git repository with a project structure like

```
src/project/data/....
```

In my `.gitignore` we have an exclusion like

```
data/*
```

To make sure any top level data directories aren't included.

However SkyPilot when copying my local directory happens to exclude new some files like

```
src/project/data/__init__.py
```

When I updated my gitignore with

```
/data/*
```

Everything worked perfectly.

I was hoping that SkyPilot would follow the same rules for gitignore as git but it seems there's subtle differences.

**Comment by fozziethebeat** [comment]
Here's an example repository that showcases this more comprehensively: https://github.com/fozziethebeat/skypilot-bug/tree/broken-branch

**Comment by concretevitamin** [comment]
Thanks @fozziethebeat!

It appears the reason is: SkyPilot builds up an rsync command that looks like 
```
rsync -Pavz --filter='dir-merge,- .gitignore' -e "ssh -i ~/.ssh/sky-key -o StrictHostKeyChecking=no ..."  <local src> ubuntu@<ip>:'~/sky_workdir'
```

**Comment by fozziethebeat** [comment]
I fixed it with updating my gitignore to have `/data/*` instead of `data/*`.  That's goo enough for now but a less surprising fix would be nice.
