### ISSUE TITLE
Issues with Sky Cluster when launched from GCP VM

### ISSUE THREAD

**Issue by subhamde8247** [skypilot-org/skypilot#3309]
Hi, I am running LLM inferences using SkyPilot and vLLM. The code works well when I run from my local. But now I need to get things running from GCP VM. The VM has a Service Account attached to it with all required permission set as per [here](https://skypilot.readthedocs.io/en/latest/cloud-setup/cloud-permissions/gcp.html#medium-permissions).  And I am seeing 2 issues:

1. Spot Controller fails to create the inference cluster. 
2. I tried `sky launch` (without the controller), but the created cluster cannot access any GCP resources like SecretManager, bucket etc due to permission issues. 

Not sure, if this is related to this [comment](https://github.com/skypilot-org/skypilot/pull/1539#issuecomment-1360385983) , but would appreciate any help. cc @Michaelvll

**Comment by Michaelvll** [comment]
Hi @subhamde8247, thanks for filing the issue! Could you try to run `gcloud auth list`, ` gcloud config get project` and `gsutil ls` on the cluster you launched to see if those match the corresponding configs you expected?

**Comment by subhamde8247** [comment]
Thanks a lot for giving the above direction @Michaelvll . Running those commands revealed the issue - I assumed sky nodes were using the same service account that we used for launching the VM, but turns out they were using skypilot-v1 service account(created automatically) that needed more permission.
