### ISSUE TITLE
[k8s] Profile & optimize `sky launch` a new K8s cluster

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#3315]
`sky launch --clouds kubernetes -y` on an existing on-prem K8s cluster is a bit slow. Ideally it should be as fast as launching a pod / running a local command. We should knock out any low hanging fruits.

**Comment by romilbhardwaj** [comment]
One low hanging fruit here to shave off 1-2s for each ssh connection would be to find a more robust fix for concurrent SSH connections. 

We currently have a random sleep for 1-2s to avoid an issue with `kubectl port-foward` failing on concurrent calls. 

https://github.com/skypilot-org/skypilot/blob/823999af850ee93138f45d01abba6c54a93d3c1e/sky/templates/kubernetes-port-forward-proxy-command.sh.j2#L52-L55

See more [investigation here](https://github.com/skypilot-org/skypilot/issues/2628#issuecomment-1741569523).

**Comment by Michaelvll** [comment]
#3157 is a prototype for fixing this issue, which reduces the time for `launch` new cluster and `launch` existing clusters by 2x and `exec` on existing cluster by 3x.


We can separate the optimization to multiple separate PRs:
1. #3394: lazy import and avoid rsync for exec
2. TBD: avoid source bashrc for internal remote command execution
3. #3157: kubernetes command runner
