### ISSUE TITLE
[tests] Allow custom ~/.sky/config.yaml for tests

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#3376]
Our tests use whatever `~/.sky/config.yaml` is configured on the developer's machine. 

We need a mechanism in `test_smoke.py` to temporarily override the the config in `~/.sky/config.yaml` instead specify the config within the test.

E.g., this will be useful for specifying specific cloud for the SkyServe controller. Similarly, it will allow us to robustly test different port modes (LoadBalancer vs Ingress).

We can probably do this via `ENV_VAR_SKYPILOT_CONFIG`, but we should provide a convenience method to do so.

Current workaround is to have tester to manually modify their config.yaml for the specific tests which require this.

**Comment by concretevitamin** [comment]
Would this help?:

https://github.com/skypilot-org/skypilot/blob/49fd20880ec6ebfa8fc6e4c9ed9ff9f70384a215/sky/skypilot_config.py#L67
