### ISSUE TITLE
RunPod skypilot does not allow stopping instances

### ISSUE THREAD

**Issue by ashah03** [skypilot-org/skypilot#3378]
Wondering if this is a bug or not -- I do not have the option to stop instances on RunPod that are created with skypilot (either with `sky stop` or on the RunPod dashboard.)

**Comment by Michaelvll** [comment]
Stopping a VM is probably not supported by RunPod cloud itself. We have to disable it for that cloud for now until they have the feature. :)

**Comment by ashah03** [comment]
In my experience, stopping VMs is supported on RunPod if I created the instances with the dashboard! Just not for instances created with skypilot.

**Comment by Programmerino** [comment]
Actually, it appears like stopping these does work if you use the API:
```
curl --request POST \
  --header 'content-type: application/json' \
  --url 'https://api.runpod.io/graphql?api_key=KEY' \
  --data '{"query": "mutation { podStop(input: {podId: \"idhere\"}) { id desiredStatus } }"}'
```

**Comment by hongbo-miao** [comment]
Got same issue, it would be great to support stop Runpod cluster, thanks!

```sh
➜  sky stop experiment-cluster
Stopping 1 cluster: experiment-cluster. Proceed? [Y/n]: 
Stopping cluster 'experiment-cluster'... skipped.
  Stopping is currently not supported for runpod.
  To terminate the cluster instead, run: sky down experiment-cluster
Stopping 1 cluster ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--

➜ sky down experiment-cluster
Terminating 1 cluster: experiment-cluster. Proceed? [Y/n]: 
Terminating cluster experiment-cluster...done.
Terminating 1 cluster ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
```
