### ISSUE TITLE
Spot instances not supported for runpod

### ISSUE THREAD

**Issue by ascillitoe** [skypilot-org/skypilot#3382]
Setting `use_spot: True` for `cloud: runpod` results in `ResourcesUnavailableError` for all resource requests, even when spot instances are available via runpod.io.

**Comment by ashah03** [comment]
https://github.com/skypilot-org/skypilot/blob/428414014059e5fec510eba1255e3d9432e24819/sky/clouds/runpod.py#L29

Looks like they haven't implemented it yet (since RunPod CLI doesn't have spot implemented either)

**Comment by BitPhinix** [comment]
Seems like they support it now: https://docs.runpod.io/sdks/graphql/manage-pods#create-spot-pod
