### ISSUE TITLE
[GCP] Add support for the Dynamic Workload Scheduler (GCE)

### ISSUE THREAD

**Issue by colinjc** [skypilot-org/skypilot#3414]
GCP recently made the dynamic workload scheduler feature available in public preview. This system works by letting you submit a request to get N number of GPU VMs and puts you in a queue to get them, only provisioning once all are ready. This increases the ability of users to get rare GPUs without needing reservations. It also decreases costs compared to grabbing 1 vm at a time until all are available. 

It would be useful if when SkyPilot was provisioning GPU instances on GCE it created them through this system instead of standard node provisioning APIs.

Announcement - https://cloud.google.com/blog/products/compute/introducing-dynamic-workload-scheduler
GCE API - https://cloud.google.com/compute/docs/instance-groups/about-resize-requests-mig

**Comment by asaiacai** [comment]
I'd like to take this if possible. I'm trying to figure out where skypilot would fit in with Kueue currently :)

**Comment by romilbhardwaj** [comment]
Closed with #3574.
