### ISSUE TITLE
[APIs] Failed to call v1/embeddings API

### ISSUE THREAD

**Issue by Biga-incorta** [skypilot-org/skypilot#3444]
curl http://url/v1/embeddings \
>   -H "Content-Type: application/json" \
>   -X POST \
>   -d '{
>     "input": "The food was delicious and the waiter...",
>     "model": "snowflake-arctic-embed",
>     "encoding_format": "float"
>   }'

Response
**404 page not found(base)**

Server logs 
(task, pid=3867) [GIN] 2024/04/17 - 11:26:47 | 404 |      13.496µs |    | POST     "/v1/embedding"
(task, pid=3867) [GIN] 2024/04/17 - 11:37:37 | 404 |      13.799µs |    | POST     "/v1/embeddings"
(task, pid=3867) [GIN] 2024/04/17 - 11:38:33 | 404 |      16.143µs |    | POST     "/v1/embeddings"
(task, pid=3867) [GIN] 2024/04/17 - 11:40:15 | 404 |      14.818µs |    | POST     "/v1/embeddings"

**Comment by romilbhardwaj** [comment]
Hi @Biga-incorta - can you provide steps to reproduce this error? What's the YAML you're running and which cloud are you on?

Also, what version/commit are you on (`sky -v` and `sky -c`)/

**Comment by Biga-incorta** [comment]
YAML content
```
envs:
  MODEL_NAME: llama2  # mistral, phi, other ollama supported models
  OLLAMA_HOST: 0.0.0.0:8888  # Host and port for Ollama to listen on

resources:
  cpus: 4+
  memory: 8+  # 8 GB+ for 7B models, 16 GB+ for 13B models, 32 GB+ for 33B models
  # accelerators: L4:1  # No GPUs necessary for Ollama, but you can use them to run inference faster
  ports: 8000
  use_spot: true

service:
  replicas: 2
  # An actual request for readiness probe.
  readiness_probe:
    path: /v1/chat/completions
    post_data:
      model: $MODEL_NAME
      messages:
        - role: user
          content: Hello! What is your name?
      max_tokens: 1

setup: |
  # Install Ollama
  if [ "$(uname -m)" == "aarch64" ]; then
    # For apple silicon support
    sudo curl -L https://ollama.com/download/ollama-linux-arm64 -o /usr/bin/ollama
  else
    sudo curl -L https://ollama.com/download/ollama-linux-amd64 -o /usr/bin/ollama
  fi
  sudo chmod +x /usr/bin/ollama
  
  # Start `ollama serve` and capture PID to kill it after pull is done
  ollama serve &
  OLLAMA_PID=$!
  
  # Wait for ollama to be ready
  IS_READY=false
  for i in {1..20};
    do ollama list && IS_READY=true && break;
    sleep 5;
  done
  if [ "$IS_READY" = false ]; then
      echo "Ollama was not ready after 100 seconds. Exiting."
      exit 1
  fi
  
  # Pull the model
  ollama pull $MODEL_NAME
  echo "Model $MODEL_NAME pulled successfully."
  
  # Kill `ollama serve` after pull is done
  kill $OLLAMA_PID

run: |
  # Run `ollama serve` in the foreground
  echo "Serving model $MODEL_NAME"
  ollama serve
```
`sky launch serve.yaml -c ollama`

sky -c
skypilot, commit bca709b5554858fc630695a1d867c2d84593a291

 sky -v
skypilot, version 1.0.0.dev20240403

**Comment by romilbhardwaj** [comment]
@Biga-incorta - your YAML runs ollama on port 8888 (`OLLAMA_HOST: 0.0.0.0:8888`), but exposes port 8000 on the cluster (`ports: 8000`). As a result the server may not be accessible.

Try changing `OLLAMA_HOST: 0.0.0.0:8888` to `OLLAMA_HOST: 0.0.0.0:8000` (or change the `ports`).
