### ISSUE TITLE
Feat: Specify regions for spot instances

### ISSUE THREAD

**Issue by AlexvZyl** [skypilot-org/skypilot#3471]
Hi there!

Currently you cannot specify regions when running spot instances.  This can be quite the hassle for small setups (like ours), since now we need to first enable all of the regions before wen can run the spot instances, and we do not necessarily want to do that.

Is there a specific reason why the design was implemented like this?  And if not, could specifying spot regions be added?

Thanks!

**Comment by romilbhardwaj** [comment]
Hey @AlexvZyl - specifying regions for spot instances is supported. 

For instance, you can specify the region in your YAML like:
```
resources:
  cloud: gcp
  region: us-west1
```

or through cli: `sky spot launch --cloud gcp --region us-west1`.

Is there a specific region/cloud that's not working for you?

**Comment by AlexvZyl** [comment]
My apologies - seems like I misread the docs.  You are correct.

However, I do recall being prohibited from using spot instances when specifying the region, but I cannot recall the exact scenario.  I will reopen if I run into that issue again.

Thanks!
