### ISSUE TITLE
[Core] Disk tier `best` is not the best possible disk

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#3517]
On AWS, `sky launch -c aws --cloud aws --disk-tier best` provisions a gp3 EBS with 7000 IOPS and 437MB/s throughput.

On the other hand, the "best" possible EBS (discounting io2) is io1 with 64000 IOPS and 1 GB/s throughput:
<img width="1297" alt="image" src="https://github.com/skypilot-org/skypilot/assets/4416605/8a740ac7-ef97-456a-a4aa-360f5f64bbfc">

Similar behavior may exist on other clouds, need to verify.

I understand SkyPilot is using its "high" disk tier as the "best", but that is ~9x fewer IOPS and half the throughput you can get from the "best" EBS. Using the best possible configuration is particularly important for performance of disk-heavy workloads.

**Comment by kevinmingtarja** [comment]
Fixed by https://github.com/skypilot-org/skypilot/pull/3860
