### ISSUE TITLE
[GCP] Compute Engine Metadata unavailable when using service account in a local Docker?

### ISSUE THREAD

**Issue by LucasProptexx** [skypilot-org/skypilot#3520]
Context: 
- Automate ML batch jobs via Skypilot triggered automatically by an Python application listening to some events and running out of its own Docker image, outside of any Cloud provider
- Started configuring Google Cloud as the first Cloud provider to try this with, following [the service account approach](https://skypilot.readthedocs.io/en/latest/cloud-setup/cloud-auth.html#gcp-service-account), and setting the Service Account with [medium permission](https://skypilot.readthedocs.io/en/latest/cloud-setup/cloud-auth.html#gcp-service-account)
- Run the command `gcloud auth activate-service-account --key-file=XXXX --project=YYY --quiet` before doing anything `sky` related

Problem:
- `sky check` triggers many `google.auth.compute_engine._metadata` related errors:
```bash
WARNING:google.auth.compute_engine._metadata:Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
WARNING:google.auth.compute_engine._metadata:Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
WARNING:google.auth.compute_engine._metadata:Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
WARNING:google.auth._default:Authentication failed using Compute Engine authentication due to unavailable metadata server.
WARNING:google.auth.compute_engine._metadata:Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 111] Connection refused
WARNING:google.auth.compute_engine._metadata:Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 111] Connection refused
WARNING:google.auth.compute_engine._metadata:Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 111] Connection refused
WARNING:google.auth._default:Authentication failed using Compute Engine authentication due to unavailable metadata server.
```
- `sky check` then prints out:
```bash
Checking GCP...
  GCP: disabled
    Reason: Getting project ID or user identity failed. You can debug with `gcloud auth list`. To fix this, run the following commands:
      $ gcloud init
      $ gcloud auth application-default login
    For more info: https://skypilot.readthedocs.io/en/latest/getting-started/installation.html#google-cloud-platform-gcp
    Details: [google.auth.exceptions.DefaultCredentialsError] Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
```

Troubleshooting done:
- Verified all the right permissions were given to the Service Account from which I downloaded the JSON key file used in my code (see attached)
![Screenshot 2024-05-07 at 15 27 03](https://github.com/skypilot-org/skypilot/assets/149964938/0e3c58da-d475-4df0-b118-95710f139ae1)

_Version & Commit info:_
* `sky -v`: skypilot, version 1.0.0.dev20240506
* `sky -c`: skypilot, commit 2ff95bb40067984022de5a5a530dfbfea3b0e741

**Comment by Michaelvll** [comment]
Hi @LucasProptexx , thanks for raising the issue! If you would like to authenticate with service account, it would be nice to double check if you have followed the instructions here to make all the required files available to SkyPilot: https://skypilot.readthedocs.io/en/latest/cloud-setup/cloud-auth.html#gcp-service-account

**Comment by Michaelvll** [comment]
Thanks for raising the issue @LucasProptexx! Not sure if this is the case, but we need the `GOOGLE_APPLICATION_CREDENTIALS` to be set when you are running `sky check`. Could you check if you have that env var set to the key-file you use in additional to your `gcloud auth activate-service-account` command?

Also, please feel free to join our slack channel if you would like to discuss it interactively: slack.skypilot.co
