### ISSUE TITLE
[Catalog/show-gpus] Combine RunPod's A100 and A100-SXM 

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#3540]
Another issue, it seems we have A100 and A100-SXM separated for RunPod while combined for lambda labs. We probably need to separate them for all the clouds.

_Originally posted by @Michaelvll in https://github.com/skypilot-org/skypilot/pull/3492#pullrequestreview-2026918295_

**Comment by romilbhardwaj** [comment]
Related - https://github.com/skypilot-org/skypilot-catalog/issues/64
