### ISSUE TITLE
Runpod uses extremely old base image

### ISSUE THREAD

**Issue by baxelrod** [skypilot-org/skypilot#3542]
I'm excited to use skypilot across multiple clouds, but I've noticed that it uses a really old runpod base image that has a very outdated cuda version.

https://github.com/skypilot-org/skypilot/blob/8a0a34d36bc75cd1e337e11d14e5bf8aeb4144e4/sky/provision/runpod/utils.py#L105

Would you consider a pull request to update to a more recent version or removing the version tag? Please let me know if there is anything I can do to make this happen.

They are currently on version 0.6.2. [Source](https://hub.docker.com/r/runpod/base/tags).

**Comment by concretevitamin** [comment]
I wonder if it’s sufficient to just change that image version and test everything still works? Cc @justinmerrell
