### ISSUE TITLE
[k8s] Remove SSH Jump Pod for `networking: port-forward` mode

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#3566]
In the initial design of SkyPilot on Kubernetes, we [used the SSH jump pod](https://docs.google.com/document/d/1IrrkbtkX74gx1VHlPLjB9c_CTpuE4VZiB-QCXPehzqY/edit#bookmark=id.si47syyy8qob) as a design choice to minimize the number of ports that are exposed outside of the cluster to access SkyPilot nodes running on the cluster. However, after we developed `networking: port-forward` mode (now default), this is no longer necessary since we directly `kubectl port-forward <target pod svc>` instead of going via the jump pod.

We should use this direct `kubectl port-forward` when using `networking: port-forward` and not create any SSH jump pods.

**Comment by shubhscoder** [comment]
@romilbhardwaj I am new to this project and would like to work on this issue! Thanks in advance!

**Comment by martin-liu** [comment]
This will be great!

One other issue for SSH jump pod is that when using autoscaler like Karpenter, it may evict this pod without recover in another node, because there's no deployment for the pod. This often happens when need to launch a new GPU node.

From this angle, all the pod should be controlled by a deployment to guarantee recoverability.

**Comment by romilbhardwaj** [comment]
Thanks @martin-liu - it makes sense to make the ssh jump pod controlled by a deployment. 

SkyPilot cluster pods however cannot be deployments since they are not fully stateless and cannot self-recover (i.e., they need the SkyPilot job controller to assist with recovery - re-run setup, copy file mounts, workdir etc). As a result, they are run as plain pods. The recoverability is provided by the [job controller](https://skypilot.readthedocs.io/en/latest/examples/managed-jobs.html), which detects failures and restarts pods. More [discussion on the design here](https://github.com/skypilot-org/skypilot/pull/3543#issuecomment-2125119997).

**Comment by martin-liu** [comment]
@romilbhardwaj Got it, thanks for the info!

**Comment by martin-liu** [comment]
@romilbhardwaj may I know the ETA for this?
