### ISSUE TITLE
sky launch  problem with cluster kubernetes

### ISSUE THREAD

**Issue by taigetco** [skypilot-org/skypilot#3603]
Run sky in an environment with limited network access. Download the image in advance: us-central1-docker.pkg.dev/skypilot-375900/skypilotk8s/skypilot:20240321 and import the image into the containerd directory. However, kubelet will also download it when it starts. Investigation found that it was in the file kubernetes-ssh-jump.yml.j2, which sets **imagePullPolicy: Always.** I modified it in the local environment sky directory: **sky/lib/python3.10/site-packages/sky/templates/kubernetes-ingress.yml.j2**, and set **imagePullPolicy: IfNotPresent.**
But sky launch did not take effect again, and it still downloaded. The question I want to ask is, is the place I changed correct, or can it not be changed?

**Comment by romilbhardwaj** [comment]
Hey @taigetco - changing `imagePullPolicy` in `sky/templates/kubernetes-ssh-jump.yml.j2` is all that should be required- https://github.com/skypilot-org/skypilot/blob/90f8e89014a517dcd370081d62e5655f229a3325/sky/templates/kubernetes-ssh-jump.yml.j2#L17

We will also soon be removing the SSH jump pod, so this should no longer be necessary after this PR: https://github.com/skypilot-org/skypilot/pull/3577
