### ISSUE TITLE
[UX] `sky jobs launch` should be able to take a list of yamls

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#3612]
An easy way to define a pipeline should be `sky jobs launch train.yaml eval.yaml test.yaml`.

**Comment by romilbhardwaj** [comment]
Agreed, would be nice to define a pipeline from the CLI by specifying multiple YAMLs. The `sky jobs launch train.yaml eval.yaml test.yaml` syntax might be a little confusing since it may be interpreted as "Invoke `sky jobs launch` on three jobs separately", but we can brainstorm alternatives.

**Comment by concretevitamin** [comment]
`sky jobs launch --pipeline=1.yml,2.yml` (an arg taking a comma-sep list)?
