### ISSUE TITLE
[Azure] Incorrect pricing information for H100

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#3615]
H100s on Azure are shown as $0 price, whereas its actually ~$8.8:

<img width="1011" alt="image" src="https://github.com/skypilot-org/skypilot/assets/4416605/93f28672-d58e-44db-a826-72198213d7e5">

**Comment by Michaelvll** [comment]
The issue is with the Azure API not returning the correct price:
https://github.com/skypilot-org/skypilot/blob/eedeed468626be1e831589543f90632477adfc41/sky/clouds/service_catalog/data_fetchers/fetch_azure.py#L264-L279
