### ISSUE TITLE
[Managed Jobs] Support Rsync for managed jobs

### ISSUE THREAD

**Issue by hemildesai** [skypilot-org/skypilot#3620]
Currently, managed jobs automatically translate local files and workdir to cloud bucket mounts. This means that managed jobs cannot be launched if a user does not have access to cloud storage.

I am wondering if its possible to support rsync for `workdir` and local files in managed jobs where the jobs controller will essentially act as a jump host for the rsync. So the flow would be to rsync to jobs controller first, then rsync from the jobs controller to the jobs which are launched by the controller.

Ideally, this should be bidirectional - i.e. later on, it should also be possible to rsync back any changes to the workdir from the controller to the local machine.

**Comment by romilbhardwaj** [comment]
+1 - this is important for the Kubernetes-only case where the user does not have access to any cloud object store.

**Comment by hemildesai** [comment]
@romilbhardwaj In the k8s only use case, managed jobs would also need to support the jobs controller being launched in k8s. Right now, [autostop](https://github.com/skypilot-org/skypilot/blob/master/sky/jobs/core.py#L132) is set on the jobs controller which means it will fail to launch in k8s.

**Comment by romilbhardwaj** [comment]
Running controllers on Kubernetes is supported now :) We updated the downstream code to skip autostop for Kubernetes in #3377: https://github.com/skypilot-org/skypilot/blob/7692eaaef4efe1f36a5e53d050f05991568c0226/sky/backends/cloud_vm_ray_backend.py#L2014-L2021
