### ISSUE TITLE
Add option to disable conda installation when using custom docker images

### ISSUE THREAD

**Issue by hemildesai** [skypilot-org/skypilot#3628]
When using a custom docker image as runtime environment, there should be an option to disable the CONDA_INSTALLATION_COMMANDS during setup which the user can configure.

I think setting the value to empty string [here](https://github.com/skypilot-org/skypilot/blob/1e640e11149f03109275b7629cd7865a21023bce/sky/backends/backend_utils.py#L911) when a custom image is present should suffice.

This will also help reduce the startup time.

Let me know your thoughts if this a good idea?

**Comment by Michaelvll** [comment]
Thanks for raising this @hemildesai! We were installing conda for all clusters to keep environments aligned. We can consider adding a knob in `~/.sky/config.yaml` to disable the conda installation for better speed.

In that case, setting `CONDA_INSTALLATION_COMMANDS` may not be sufficient, as we may need some checks for the default Python version on the system, and not install conda only when python=3.10 to make sure the dependency for skypilot runtime can be correctly installed.

**Comment by hemildesai** [comment]
@Michaelvll Ah ok, makes sense. I would assume it would require changes to https://github.com/skypilot-org/skypilot/blob/1e640e11149f03109275b7629cd7865a21023bce/sky/skylet/constants.py#L102 as well.

But would be nice to reuse the python environment directly inside the container.

**Comment by cblmemo** [comment]
This should be fixed by https://github.com/skypilot-org/skypilot/pull/3874. Closed now
