### ISSUE TITLE
'sky check' Command Fails on Windows Due to Missing Resource Directory

### ISSUE THREAD

**Issue by olivermolenschot** [skypilot-org/skypilot#3648]
**Description**: The `sky check` function throws an error on Windows because it cannot find the required resource directory.

**Steps to Reproduce**:
1. Install the skypilot package on a Windows machine using the following command:
   pip install "skypilot-nightly[aws]"
2. run the command sky check

**Comment by romilbhardwaj** [comment]
Hi @olivermolenschot - are you using WSL? 

Windows is not officially supported, but SkyPilot is known to work on WSL.
