### ISSUE TITLE
Nightly release is stuck on 1.0.0.dev2024053101

### ISSUE THREAD

**Issue by WesleyYue** [skypilot-org/skypilot#3650]
It looks like there were two releases for 5/31
- `1.0.0.dev2024053101`
- `1.0.0.dev20240531`

Because the additional 01 makes it a "bigger" number than the following version numbers `1.0.0.dev20240601`, the pip upgrade and @latest install behaviour is broken. `1.0.0.dev20240601` and beyond will always "upgrade" to `1.0.0.dev2024053101`

**Comment by Michaelvll** [comment]
Thanks for identifying this @WesleyYue! We just removed the 1.0.0.dev2024053101 version no PyPI. Could you try it again?

**Comment by WesleyYue** [comment]
Looks good, thanks for the quick fix!
