### ISSUE TITLE
Slack link is broken

### ISSUE THREAD

**Issue by david1542** [skypilot-org/skypilot#3653]
Seems like the Slack link in the README.md is broken.

_Version & Commit info:_
* `sky -v`: PLEASE_FILL_IN
* `sky -c`: PLEASE_FILL_IN

**Comment by concretevitamin** [comment]
@david1542 were you able to access http://slack.skypilot.co/ or https://slack.skypilot.co/ ?

**Comment by aavarghese** [comment]
Both links show:
```
This link is no longer active
To join this workspace, you’ll need to ask the person who originally invited you for a new link.
```

**Comment by concretevitamin** [comment]
@david1542 @aavarghese Thanks for flagging this. We've just updated the invite link. https://slack.skypilot.co/  should work now.
