### ISSUE TITLE
Add option to select Azure resource group

### ISSUE THREAD

**Issue by tom-papatheodore** [skypilot-org/skypilot#3659]
Hello. My group recently got access to some Azure cloud resources and I wanted to test out SkyPilot to see if it could make finding resources easier. However, the folks in my group only have access to the Azure resources through a specific resource group within our company's larger Azure account. In the SkyPilot Slack workspace, I was told that I could hardcode my resource group in here for now: https://github.com/skypilot-org/skypilot/blob/6a624b2fa3533496bbed3bf013ae608e834b807f/sky/clouds/azure.py#L374. I suspect there will be others who need this feature as well, so I wanted to submit this issue as a feature request. Please let me know if you have any questions. Thanks.

-Tom

_Version & Commit info:_
* `sky -v`: PLEASE_FILL_IN
* `sky -c`: PLEASE_FILL_IN

**Comment by romilbhardwaj** [comment]
cc @landscapepainter

**Comment by landscapepainter** [comment]
@tom-papatheodore @faizan-cognimind Thanks for waiting. The feature has been added. We now allow our users to configure resource group from `~/.sky/config.yaml` file. All the Azure instances provisioned will be created at the specified resource group you created. Please refer to the `resource_group_vm` field from [this doc](https://skypilot.readthedocs.io/en/latest/reference/config.html#spec-sky-config-yaml) for more information.

**Comment by tom-papatheodore** [comment]
Excellent! Thanks, @landscapepainter!
