### ISSUE TITLE
[Serve] Allow scaling of replicas based on response time

### ISSUE THREAD

**Issue by JGSweets** [skypilot-org/skypilot#3686]
Currently, replicas scale based on QPS. It would also be beneficial to be able to scale based on response time. This can help ensure a maximum response time when a system gets overloaded due to long running queries as opposed to the number of queries.

**Comment by WesleyYue** [comment]
More generally, it would be useful we can can plugin our own scaling logic so we can tailor it to our needs (for example, target prompt tokens per second)
