### ISSUE TITLE
[Bug] Should try provisioning instance in all availability zones before complaining that no instance available

### ISSUE THREAD

**Issue by ashutoshsaboo** [skypilot-org/skypilot#3687]
I was trying to do a `sky launch` for some model on AWS inf2 instances. When i just pass the `--region us-east-1` param without `--zone`, it just searches in one of the zones and fails when no instance in that first-searched for zone are found. Now when I run the same command with `--region us-east-1 --zone us-east-1f` it succeeds in spawning the instance. Ideally when I'm not passing `--zone` it should search in all zones one at a time, and not prematurely fail saying that instance not found. 

_Version & Commit info:_
* `sky -v`: skypilot, version 1.0.0.dev20240620
* `sky -c`: skypilot, commit 65bbcf5f45276a8584a76758536cf6c429534240

**Comment by concretevitamin** [comment]
@ashutoshsaboo Do you have the provisioning log for the former case?

I just tried
```
sky launch -t inf2.xlarge --region us-east-1 --cloud aws -i0 --down
```
and SkyPilot does (and is engineered to) look at all zones in the requested region:
```
I 06-25 07:41:30 provisioner.py:76] Launching on AWS us-east-1 (us-east-1b,us-east-1c,us-east-1d,us-east-1f)
```

**Comment by ashutoshsaboo** [comment]
I did see the second log as well. But I'm not sure if it's working as expected. @concretevitamin 

See logs below: 
```
sky launch llama3.yaml -c llama7 --env HF_TOKEN --region us-east-1 --no-use-spot --instance-type inf2.24xlarge -y

Task from YAML spec: llama3.yaml
INFO:numexpr.utils:Note: NumExpr detected 11 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
I 06-25 22:12:08 cli.py:1112] Service section will be ignored when using `sky launch`.
I 06-25 22:12:08 cli.py:1112] To spin up a service, use SkyServe CLI: sky serve up
I 06-25 22:12:08 optimizer.py:695] == Optimizer ==
I 06-25 22:12:08 optimizer.py:718] Estimated cost: $6.5 / hour
I 06-25 22:12:08 optimizer.py:718]
I 06-25 22:12:08 optimizer.py:843] Considered resources (1 node):
I 06-25 22:12:08 optimizer.py:913] --------------------------------------------------------------------------------------------
I 06-25 22:12:08 optimizer.py:913]  CLOUD   INSTANCE        vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN
I 06-25 22:12:08 optimizer.py:913] --------------------------------------------------------------------------------------------
I 06-25 22:12:08 optimizer.py:913]  AWS     inf2.24xlarge   96      384       Inferentia:6   us-east-1     6.49          ✔
I 06-25 22:12:08 optimizer.py:913] --------------------------------------------------------------------------------------------
I 06-25 22:12:08 optimizer.py:913]
Running task on cluster llama7...
I 06-25 22:12:08 cloud_vm_ray_backend.py:4420] Creating a new cluster: 'llama7' [1x AWS(inf2.24xlarge, cpus=32+, {'Inferentia': 6}, disk_tier=best, disk_size=512, ports=['8081'])].
I 06-25 22:12:08 cloud_vm_ray_backend.py:4420] Tip: to reuse an existing cluster, specify --cluster (-c). Run `sky status` to see existing clusters.
I 06-25 22:12:09 cloud_vm_ray_backend.py:1406] To view detailed progress: tail -n100 -f /Users/ashutoshsaboo/sky_logs/sky-2024-06-25-22-12-08-674000/provision.log
I 06-25 22:12:10 provisioner.py:76] Launching on AWS us-east-1 (us-east-1a,us-east-1c,us-east-1d,us-east-1f)
W 06-25 22:12:27 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient inf2.24xlarge capacity in zones with support for 'gp3' volumes. Our system will be working on provisioning additional capacity.
W 06-25 22:12:32 cloud_vm_ray_backend.py:2086] sky.exceptions.ResourcesUnavailableError: Failed to acquire resources in all zones in us-east-1. Try changing resource requirements or use another region.
W 06-25 22:12:32 cloud_vm_ray_backend.py:2095]
W 06-25 22:12:32 cloud_vm_ray_backend.py:2095] Provision failed for 1x AWS(inf2.24xlarge, cpus=32+, {'Inferentia': 6}, disk_tier=best, disk_size=512, ports=['8081']) in us-east-1. Trying other locations (if any).
Clusters
No existing clusters.

sky.exceptions.ResourcesUnavailableError: Failed to provision all possible launchable resources. Relax the task's resource requirements: 1x AWS(inf2.24xlarge, cpus=32+, {'Inferentia': 6}, disk_tier=best, disk_size=512, ports=['8081'])
To keep retrying until the cluster is up, use the `--retry-until-up` flag.
```

And around same time, this one succeeded and spawned the instance: 
```
sky launch llama3.yaml -c llama7 --env HF_TOKEN --region us-east-1 --zone us-east-1f --no-use-spot --instance-type inf2.24xlarge -y

Task from YAML spec: llama3.yaml
INFO:numexpr.utils:Note: NumExpr detected 11 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
I 06-25 22:13:45 cli.py:1112] Service section will be ignored when using `sky launch`.
I 06-25 22:13:45 cli.py:1112] To spin up a service, use SkyServe CLI: sky serve up
I 06-25 22:13:45 optimizer.py:695] == Optimizer ==
I 06-25 22:13:45 optimizer.py:718] Estimated cost: $6.5 / hour
I 06-25 22:13:45 optimizer.py:718]
I 06-25 22:13:45 optimizer.py:843] Considered resources (1 node):
I 06-25 22:13:45 optimizer.py:913] --------------------------------------------------------------------------------------------
I 06-25 22:13:45 optimizer.py:913]  CLOUD   INSTANCE        vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE   COST ($)   CHOSEN
I 06-25 22:13:45 optimizer.py:913] --------------------------------------------------------------------------------------------
I 06-25 22:13:45 optimizer.py:913]  AWS     inf2.24xlarge   96      384       Inferentia:6   us-east-1f    6.49          ✔
I 06-25 22:13:45 optimizer.py:913] --------------------------------------------------------------------------------------------
I 06-25 22:13:45 optimizer.py:913]
Running task on cluster llama7...
I 06-25 22:13:45 cloud_vm_ray_backend.py:4420] Creating a new cluster: 'llama7' [1x AWS(inf2.24xlarge, cpus=32+, {'Inferentia': 6}, disk_tier=best, disk_size=512, ports=['8081'])].
I 06-25 22:13:45 cloud_vm_ray_backend.py:4420] Tip: to reuse an existing cluster, specify --cluster (-c). Run `sky status` to see existing clusters.
I 06-25 22:13:46 cloud_vm_ray_backend.py:1406] To view detailed progress: tail -n100 -f /Users/ashutoshsaboo/sky_logs/sky-2024-06-25-22-13-45-525363/provision.log
I 06-25 22:13:47 provisioner.py:76] Launching on AWS us-east-1 (us-east-1f)
⠸ Launching - Waiting for SSH access
```

**Comment by Michaelvll** [comment]
Hi @ashutoshsaboo, this is expected, as the availability of the instance is unpredictable, and may change subject to time of your launch request.

As shown in the first log, there is `W 06-25 22:12:27 instance.py:243] create_instances: Attempt failed with An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 0): We currently do not have sufficient inf2.24xlarge capacity in zones with support for 'gp3' volumes. Our system will be working on provisioning additional capacity.` which indicates that AWS cannot allocate the resources requested at the time of `launch`.

If you would like SkyPilot to keep trying until it gets the resources, please use `sky launch --retry-until-up` : )

**Comment by ashutoshsaboo** [comment]
I know what that error means. But what also that error means is that, it can't allocate resources in the specific zone it searched for, not universally. AWS has multiple availability zones inside each region, i'm not sure if it's possible to search for an instance in "all" availability zones in a specific region with a single call, or if multiple calls would be needed to each zone inside the region. Atleast from logs (not sure about under the hood), I don't see skypilot making calls to diff availability zones in the mentioned region, it just makes a single call and fails - so not sure if it's the former case. 
I've tried that flag as well --retry-until-up. I've tried running both commands in parallel, triggered at almost the same time in separate terminal tabs, and the one with --zone always succeeds in the first attempt, while with just --region fails even with --retry-until-up. Have seen numerous cases of such failures, only then I opened this github issue ; so it's not a one off case that I encountered, but was happening on a consistent basis. Request you to check it exhaustively once - preferably with inf2 instances, if the bug is indeed there or not. @Michaelvll

**Comment by Michaelvll** [comment]
Thanks for running those tests @ashutoshsaboo! We do try all the zones within the region in the following code:
https://github.com/skypilot-org/skypilot/blob/8b81e1ed26e44ccaf19ee297c104e68363732043/sky/provision/aws/instance.py#L217-L248

Indeed your output shows only a single warning when region is specified, which means it only tries one zone. Have you tried specifying `--zone` for other zones in `us-east-1` to see if it will succeed? When SkyPilot tries to figure out the zones to try for a region, it will look for zones that have available subnets set up already, and it might be possible that the other zones do not have the subnet setup in your account.

Unfortunately, our development account cannot get quota for the instance you mentioned, but it would be highly appreciated if you could try to add some logging to the code above (e.g., printing out the filtered subnets) to help us debug. : )

**Comment by ashutoshsaboo** [comment]
I haven't tried with other zones other than us-east-1f as of now yet. Can try if needed. But what will that conclude for you, from this bug aspect atleast? I'm assuming definitely it wont succeed in all the zones and will fail in atleast one such zone (where skypilot might also be trying), which is why it's failing when querying without the --zone param. 

Where do you want me to add logging for the filtered subnets? Can it be done in my client code rather than modifying the skypilot lib with logging? @Michaelvll

**Comment by Michaelvll** [comment]
> I haven't tried with other zones other than us-east-1f as of now yet. Can try if needed. But what will that conclude for you, from this bug aspect atleast? I'm assuming definitely it wont succeed in all the zones and will fail in atleast one such zone (where skypilot might also be trying), which is why it's failing when querying without the --zone param.

This would be helpful for us to understand whether it is a bug with SkyPilot not selecting all the zones to try in the region, or it is just all the other zones does not have available subnet and `sky launch` without `--zone` is also going to the same zone as `--zoen us-east-1f`

> Where do you want me to add logging for the filtered subnets? Can it be done in my client code rather than modifying the skypilot lib with logging? @Michaelvll
> I'm also ok with installing the latest nightly build, if you want to add some logging yourself with a quick change (in a new --debug/--verbose flag or something, or maybe you can add these logs even without those flags for all since it seems useful for all), and then i can provide you with the logs if needed.

Thanks for the offerings! This logging has a similar intention as the previous test for other zones using `--zone` -- we are just trying to see if there is any issue with the zone selection when `--zone` is not specified. If we can confirm that there is only one zone with a subnet enabled, we can definitely skip this test.

Do you see the issue if you run `sky launch --retry-until-up --region` for a longer time alone without running `--zone` with it at the same time, as the latter will compete for the resources with the former? Seems if we don't have an issue with the zone selection, the behavior of only specifying `--region` and specifying `--zone` should be exactly the same in our code.
