### ISSUE TITLE
FR: Support custom S3-server

### ISSUE THREAD

**Issue by chymian** [skypilot-org/skypilot#3713]
Since skypilot supports onPrem clusters, it would also be logical & necessary to support custom/onprem S3-server.

1. there can be a significant speedup instead of pulling the data from S3-cloudservices  (AWS/GC/etc), every time a task ist started inhouse, if the S3-bucket is hosted/mirrored inhouse as well.
2. thinking EU Data-Security Laws and company policies: Data has to be keept inhouse!
3. So, it's a missing piece and without it, K8s/onPrem support is not complete and not truly onprem, when one has to store the sensitive company data on a CloudService - just do download it again into my DC.

**Comment by Michaelvll** [comment]
Related to #2687
