### ISSUE TITLE
aws labels feature rejects all proposed label keys

### ISSUE THREAD

**Issue by fozziethebeat** [skypilot-org/skypilot#3733]
When trying to launch a task using the following resources configuration, skypilot rejects the label reporting that the label key is invalid:

```
resources:
  cloud: aws
  region: us-east-1
  labels:
    "sprinto": "notprod"
```

Failure message:

```
sprinto: notprod  Invalid tag key sprinto for AWS. Key must start with any character except 'aws:' and must be 128 characters or fewer in length.
```

* `sky -v`: skypilot, version 1.0.0.dev20240702
* `sky -c` d40081aa7d53441d17ddc595c7aec04a93e1c46b

I believe the issue is the aws key regex used to validate strings.

The current check is

```
        key_regex = re.compile(r'^[^aws:][\S]{0,127}$')
```

But I believe it should be

```
       key_regx = re.compile(r'^(?!aws:)[\S]{0,127}$')
```

which would reject the `aws:` prefix and still check that the remaining portion is valid.  A small check in jupyter confirms that this different regex works

**Comment by romilbhardwaj** [comment]
Great catch! Looks like our current regex checks the first character is not "a", "w", "s", or ":", which is incorrect. As you mention, this should be a one line fix/ Would you like to submit a PR?
