### ISSUE TITLE
Duplicated Azure instances

### ISSUE THREAD

**Issue by WesleyYue** [skypilot-org/skypilot#3750]
I get the following error when specifying Standard_D2as_v5 instances. Presumably because the [Azure catalog fetching script](https://github.com/skypilot-org/skypilot/blob/d6ce1bac7a53744b427e25ee2f40e463e5b81408/sky/clouds/service_catalog/data_fetchers/fetch_azure.py) is pulling an extra instance. The (0.086,     0.0086) price should be the correct one. https://cloudprice.net/vm/Standard_D2as_v5?tier=spot

```
  File "/python/.venv/lib/python3.11/site-packages/sky/clouds/service_catalog/common.py", line 351, in get_hourly_cost_impl
    assert region is None or len(set(df[price_str])) == 1, df
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError:           InstanceType AcceleratorName  AcceleratorCount  vCPUs  MemoryGiB GpuInfo  Price  SpotPrice   Region Generation
1182  Standard_D2as_v5             NaN               NaN    2.0        8.0     NaN  0.178     0.0086  westus3      V1,V2
1183  Standard_D2as_v5             NaN               NaN    2.0        8.0     NaN  0.086     0.0086  westus3      V1,V2
```

_Version & Commit info:_
* `sky -v`: skypilot, version 1.0.0.dev20240712
* `sky -c`: skypilot, commit bce117d9ab108985baefd0866810ea291de97702

**Comment by Michaelvll** [comment]
Hi @WesleyYue, thanks for raising the issue! It seems indeed an issue with the catalog. Could you help check [sky/clouds/service_catalog/data_fetchers/fetch_azure.py](https://github.com/skypilot-org/skypilot/blob/master/sky/clouds/service_catalog/data_fetchers/fetch_azure.py) to see if there is any issue with this particular instance type? A PR would be really appreciated @WesleyYue : )

**Comment by Michaelvll** [comment]
Hi @WesleyYue, would you be able to identify the issue on this? It seems another user has encountered this issue. We would like to prioritize it a bit. We can take it over if you have not started working on it.

**Comment by WesleyYue** [comment]
Sorry I didn't get to it. I manually patched the code to bypass it but didn't fully get to the root cause in fetch_azure
