### ISSUE TITLE
[k8s] multinode torch distributed nccl timeout

### ISSUE THREAD

**Issue by asaiacai** [skypilot-org/skypilot#3788]
I tried running `examples/torch_ddp_benchmark` on kubernetes but the tasks hangs with the following error until throwing an NCCL timeout. It might be related to this [issue](https://github.com/pytorch/pytorch/issues/85300)?

```
(head, rank=0, pid=5752) 10.40.3.5
(head, rank=0, pid=5752) [W726 02:14:09.077658670 socket.cpp:697] [c10d] The IPv6 network addresses of (torch-bench-k8s-ebd1-3458-worker, 43913) cannot be retrieved (gai error: -2 - Name or service not known).
```

`task.yaml`
```
name: torch-ddp-bench

num_nodes: 2

resources:
  image_id: docker:nvcr.io/nvidia/pytorch:23.10-py3
  accelerators: H100:8 # Make sure you use 8 GPU instances
  cloud: kubernetes

file_mounts: 
  ./torch_ddp_benchmark.py: ./examples/torch_ddp_benchmark/torch_ddp_benchmark.py

setup: |
  conda activate ddp
  if [ $? -eq 0 ]; then
    echo 'conda env exists'
  else
    conda create -n ddp python=3.10 -y
    conda activate ddp
  fi
  pip install torch torchvision

run: |
  conda activate ddp
  num_nodes=`echo "$SKYPILOT_NODE_IPS" | wc -l`
  master_addr=`echo "$SKYPILOT_NODE_IPS" | head -n1`
  echo $master_addr
  torchrun \
    --nproc_per_node 8 \
    --rdzv_id=1 --rdzv_endpoint=${master_addr}:1234 \
    --rdzv_backend=c10d --nnodes $num_nodes \
    torch_ddp_benchmark.py --distributed-backend nccl
```

_Version & Commit info:_
* `sky -v`: `skypilot, version 1.0.0-dev0`
* `sky -c`: `skypilot, commit 93b319e8b90ab60d80f37e06802b876246a8e9fd`
* 1.29.6-gke.1326000

**Comment by romilbhardwaj** [comment]
I've seen something similar before on a different framework (fastchat?) where binding the server's socket to `localhost` wouldn't work on a k3s cluster, but binding explicitly to a ipv4 address `127.0.0.1` or `0.0.0.0` would work. Related to how `lo` is configured inside a pod.

Perhaps something similar is going on here? Is there some way to force master in torchrun to use ipv4 sockets?

**Comment by asaiacai** [comment]
so one workaround I found that works is to set `/etc/hosts` with these lines, which at least makes the example runnable.
```
10.76.4.7       torch-bench-9eb4-head
10.76.3.7    torch-bench-9eb4-e6b8-worker
```
My understanding as of right now is that for `torchrun` with `c10d`:
1.) all workers join at `rdzv_endpoint`
2.) each worker publicizes `hostname` to the `rdzv_endpoint`
3.) Torchrun tries to resolve [output of `hostname` to ipv4s with `getaddrinfo`](https://github.com/pytorch/pytorch/issues/85300#issuecomment-1310162834), and fails to map from `hostname` to an ipv4 socket.

So the way i see it, to make this work multinode out of the box we can either
- set `/etc/hosts` (could be done using [Host Aliases](https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/)
- configure a headless service for each pod
