### ISSUE TITLE
sky-serve-controller on azure does not have inbound ports configure correctly

### ISSUE THREAD

**Issue by petergerten** [skypilot-org/skypilot#3793]
When starting a sky-serve-controller on azure, it used to work for me out of the box with ports 30001 internet accessible. I recently started a controller that reproducible did not open this port anymore although in READY state. I checked the network security group manually on azure portal and only SSH was open. After manually adding the 30001-30020 port range, everything worked.

_Version & Commit info:_
* `sky -v`: skypilot, version 0.6.0
* `sky -c`: skypilot, commit e37a39d19a8f5b8fd7809e29c8691f65e462896a

**Comment by romilbhardwaj** [comment]
Hi @petergerten - could you try upgrading to 0.6.1? We recently made major improvements to our Azure provisioning which may address your issue. 

```
pip install -U skypilot
```

**Comment by b0b023** [comment]
@romilbhardwaj thanks! I upgraded to 0.6.1 and indeed could not reproduce the issue anymore. All good :-)

**Comment by petergerten** [comment]
@romilbhardwaj thanks! I upgraded to 0.6.1 and indeed could not reproduce the issue anymore. All good :-)
