### ISSUE TITLE
Unable to use NodePort in EKS

### ISSUE THREAD

**Issue by bpradipt** [skypilot-org/skypilot#3805]
I'm trying to use skypilot with Elastic Kubernetes Service (EKS) cluster with nodeport.  However it's never able to connect to the SSH jump pod.

I see the following error

```
D 08-01 19:30:30 provisioner.py:582] RuntimeError: Failed to SSH to 123456.gr7.us-east-2.eks.amazonaws.com after timeout  
600s, with Error: Command '['ssh', '-T', '-i', '~/.ssh/sky-key', 'sky@123456.gr7.us-east-2.eks.amazonaws.com', '-p', '22', '-o', 
'StrictHostKeyChecking=no', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10s', '-o', 'UserKnownHostsFile=/dev/null', 
'-o', 'IdentitiesOnly=yes', '-o', 'ExitOnForwardFailure=yes', '-o', 'ServerAliveInterval=5', '-o', 'ServerAliveCountMax=3', '-o', 
'ProxyCommand=ssh -tt -i /Users/test/.ssh/sky-key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o 
IdentitiesOnly=yes -W %h:%p sky@123456.gr7.us-east-2.eks.amazonaws.com -p 30981 ', 'uptime']' timed out after 10 seconds

```

Looks like skypilot is trying to SSH to the API server endpoint (edited the actual endpoint name) and not the node IP. Is this expected? 

_Version & Commit info:_
* `sky -v`: version 0.6.1
* `sky -c`: commit bc30c0b2e5c92dc00e52c6f4240b603fad4b258

**Comment by romilbhardwaj** [comment]
Hmm, that does look like a bug. We'll look into it.

Is it possible to use `portforward` (the default)? No SSH jump pods are required for `portforward`. For context, we plan to deprecate nodeport support and have all our users use `portforward`.

**Comment by bpradipt** [comment]
> Hmm, that does look like a bug. We'll look into it.
> 
> Is it possible to use `portforward` (the default)? No SSH jump pods are required for `portforward`. For context, we plan to deprecate nodeport support and have all our users use `portforward`.

Yeah it's possible to use `portforward`. 

Alternatively is it possible to disable SSH completely or it's mandatory for skypilot core functionalities? For my use case it's fine to use the ingress ports.

**Comment by romilbhardwaj** [comment]
SkyPilot on Kubernetes does not _require_ SSH - we use kubectl behind the scenes to execute remote commands and for rsync-ing files. SSH is provided largely as a convenience feature for users to access their pods easily. 

It may be possible to kill the SSH service on the pods in the `run` or `setup` sections of your task YAML if you'd like to disable it, but we haven't tested it.

**Comment by bpradipt** [comment]
This issue can be closed if nodeport is gonna be deprecated.
