### ISSUE TITLE
Param typo

### ISSUE THREAD

**Issue by camelop** [skypilot-org/skypilot#3813]
https://github.com/skypilot-org/skypilot/blob/f921f1343ee934429b6e74e8bdc874a1e9661d42/sky/provision/__init__.py#L189-L196

**Comment by Michaelvll** [comment]
Thanks for identifying this @camelop! Would you like to submit a PR for the fix?

**Comment by wizenheimer** [comment]
Hey @Michaelvll,
Familiarizing myself with skypilot's source. Pushed a fix for [this](https://github.com/skypilot-org/skypilot/pull/3924).

**Comment by Michaelvll** [comment]
Fixed by #3924. Closing this now.
