### ISSUE TITLE
[Core] Barrier synchronization in `run`

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#3839]
Some multi-node tasks require barrier synchronization (e.g., workers should wait till master is set up and ready). Would be nice if SkyPilot can provide barrier sync primitives in `run` section of the YAML.

**Comment by Michaelvll** [comment]
Related to #1762. This is important.

**Comment by romilbhardwaj** [comment]
Oh nice, looks like there's more context there. I'll reopen that and add my context there. Closing this.
