### ISSUE TITLE
[Core] Launching and job submission fails on MacOS

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#3859]
A few people experience the issue where `sky launch task.yaml` errors out with 255 and a message saying the message sending through ssh is too long. This is related to our previous optimization: #3394 with the upper bound set to 120KB #3512.

We tried to reduce the upper bound to 90KB but still fails, and it only works until we change the threshold to 0.

_Version & Commit info:_
* `sky -v`: PLEASE_FILL_IN
* `sky -c`: PLEASE_FILL_IN

**Comment by TimCJanke** [comment]
Ran into this problem today, the error message was quite confusing tbh. Downgrading to 0.6.0 worked for me.
