### ISSUE TITLE
[Core] Fail to install bash shell completion: "Installation failed with code 1"

### ISSUE THREAD

**Issue by jucor** [skypilot-org/skypilot#3885]
Trying to install bash shell completion with `sky --install-shell-completion bash`  fails with:
```
Installation failed with code 1
```
<img width="784" alt="image" src="https://github.com/user-attachments/assets/48f22006-2e9d-4da2-8825-2adbfe353bac">

_Version & Commit info:_
* `sky -v`: skypilot, version 0.6.1
* `sky -c`: skypilot, commit bc30c0b2e5c92dc00e52c6f4240b603fad4b258a
* `$BASH_VERSION`: 5
* `bash --version`: GNU bash, version 5.2.32(1)-release (aarch64-apple-darwin23.4.0) . Note: installed via homebrew.
* `uname -a`:  Darwin Juliens-MacBook-Pro.local 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000 arm64
* macOS Sonoma 14.6..1

Happy to help run any command that might help debug :)

**Comment by jucor** [comment]
Found the reason! I'm on macOS with a bash 5.2 installed via homebrew in `/opt/homebrew/bin/bash`. The system bash, in `/bin/bash`, is still version 3.2.57.  Since https://github.com/skypilot-org/skypilot/pull/2433/ skypilot checks that Bash is v5 or returns an error.
Unfortunately, https://github.com/skypilot-org/skypilot/blob/9323dc825c5f061f255f4bf484839e0698167433/sky/cli.py#L393 hard-codes a call to `/bin/bash`, hence fails.

I'll do two PRs:
- one that uses `/usr/bin/env bash` to find the shell, instead of a call to `/bin/bash`.
- one that gives an informative error message if bash is too old :)

Apologies in advance: I don't have the full testing stack set up, but since these are bash-level fixes I hope this won't matter too much for merging those upcoming PRs :)

**Comment by romilbhardwaj** [comment]
Awesome work and welcome to the SkyPilot community @jucor! Thanks for the PRs, we'll review them.

**Comment by jucor** [comment]
Thanks for the welcome and the hard work on skypilot! :) I'm currently fiddling with the formatting to please yapf and pylint in both PR. I'll get there eventually!
