### ISSUE TITLE
Spot instance support for runpod.

### ISSUE THREAD

**Issue by BitPhinix** [skypilot-org/skypilot#3927]
Re-raising the issue from https://github.com/skypilot-org/skypilot/issues/3382 as Runpod now supports creation spot instances via their API: https://docs.runpod.io/sdks/graphql/manage-pods#create-spot-pod

**Comment by kldzj** [comment]
Now that RunPod supports creating spot instances using the API, it'd be great to have SkyPilot support. :)

**Comment by Michaelvll** [comment]
This has been added in #4447. : )
