### ISSUE TITLE
Add Paperspace instance support to other GPU types

### ISSUE THREAD

**Issue by cassova** [skypilot-org/skypilot#3988]
We are unable to spin up Paperspace instances like a `P4000` or a `GPU+` or a `A4000`. 

```sh
$ sky launch -c mycluster hello_sky.yaml
Task from YAML spec: hello_sky.yaml
I 09-25 16:26:09 optimizer.py:1264] No resource satisfying Paperspace({'A4000': 1}) on Paperspace.
sky.exceptions.ResourcesUnavailableError: Catalog does not contain any instances satisfying the request:
Task(run='echo "Hello, SkyPilo...')
  resources: Paperspace({'A4000': 1}).

To fix: relax or change the resource requirements.

Hint: sky show-gpus to list available accelerators.
      sky check to check the enabled clouds.
```

The choice of instance seems to be restricted to the instances in this file: https://github.com/skypilot-org/skypilot/blob/master/sky/provision/paperspace/constants.py

_Version & Commit info:_
* `sky -v`: `skypilot, version 0.6.1`
* `sky -c`: `skypilot, commit bc30c0b2e5c92dc00e52c6f4240b603fad4b258a`

**Comment by asaiacai** [comment]
hi @cassova, i added the paperspace integration, the `A4000` and `P4000` are not part of the paperspace catalog currently but i can add it easily. thanks for bringing this up!

**Comment by cassova** [comment]
hi @asaiacai Thanks, I can see `A4000` and `P4000` available on the Paperspace UI.  (I suspect that's what you mean by catalog?). Here's a few screenshots.
<img width="813" alt="image" src="https://github.com/user-attachments/assets/2478dc26-4780-4172-88bb-5bb912b9563d">
<img width="789" alt="image" src="https://github.com/user-attachments/assets/35d9f1af-ffb3-45eb-b103-954b551db298">

**Comment by cassova** [comment]
@asaiacai Thanks for the quick work on this!  Could you please add the instances also mentioned in the screenshots?
