### ISSUE TITLE
[Docs] Incorrect Highlighting in Code Block

### ISSUE THREAD

**Issue by andylizf** [skypilot-org/skypilot#3993]
The highlighting in the YAML code block incorrectly emphasizes `cpus: 2+` instead of the intended `replicas: 3`. This misrepresentation can lead to confusion regarding which configuration is being referenced.

![image](https://github.com/user-attachments/assets/a2b783a6-652a-4ce4-b332-5d9b773470d0)

Update the highlighting to correctly emphasize `replicas: 3` to ensure accurate representation of the code.

**Comment by Michaelvll** [comment]
Thanks for raising this issue @andylizf ! Would you like to submit PR to fix this?
