### ISSUE TITLE
[Serve] Stop using deprecated `on_event()` decorator.

### ISSUE THREAD

**Issue by andylizf** [skypilot-org/skypilot#3997]
In `controller.py`, we are still using the decorator `@app.on_event('startup')` to set up our logger, which is deprecated and should no longer be used.

I suggest using [lifespan event handlers](https://fastapi.tiangolo.com/advanced/events/) instead.

**Comment by cblmemo** [comment]
Thanks for identifying the problem! Could you help submit a PR to fix this?
