### ISSUE TITLE
[Storage] Upload to storage from local path does not respect `.gitignore`

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#4015]
```
workdir: .


run: ls examples/
```

Add `examples/` in .gitignore, and run `sky jobs launch --cloud gcp echo hi --cpus 2` does not exclude examples from the uploaded files.

_Version & Commit info:_
* `sky -v`: PLEASE_FILL_IN
* `sky -c`: PLEASE_FILL_IN

**Comment by Michaelvll** [comment]
It is confirmed that when a folder/file is included in the git history, our handling with `.gitignore` will not list the folder/file in the excluded list.

One proposal is that: we can have a `.skyignore` file that allows user to explicitly specify the folders/files to exclude in the same fashion as required for `rsync --exclude` file. The behavior should be:
1. if `.skyignore` exists root folder of the source, use that file to exclude files/folders.
2. Otherwise, still use `.gitignore` as we did in our current code.

**Comment by yika-luo** [comment]
Added support for `.skyignore`: https://github.com/skypilot-org/skypilot/pull/4038
