### ISSUE TITLE
[Serve] Error handling inconsistency in service update process

### ISSUE THREAD

**Issue by andylizf** [skypilot-org/skypilot#4030]
While implementing the `terminate_replica` functionality, I discovered an inconsistency in error handling during the service update process. This issue potentially masks errors and prevents proper error propagation.

Current behavior:
1. The `/controller/update_service` endpoint in `sky/serve/controller.py` always returns a 200 status code, even when errors occur. Error information is only included in the response message.
2. The `update_service_encoded` function in `sky/serve/serve_utils.py` expects non-200 status codes for error conditions and raises a ValueError accordingly.
3. Due to this mismatch, errors occurring in the controller are not properly propagated back to the caller in `sky/serve/core.py`.

Relevant code:

1. In `sky/serve/controller.py`:
```python
@self._app.post('/controller/update_service')
async def update_service(request: fastapi.Request):
    request_data = await request.json()
    try:
        # ... (processing logic)
        return {'message': 'Success'}
    except Exception as e:  # pylint: disable=broad-except
        logger.error(f'Error in update_service: '
                     f'{common_utils.format_exception(e)}')
        return {'message': 'Error'}  # FIXME: Still returns 200 status code
```

2. In `sky/serve/serve_utils.py`:
```python
def update_service_encoded(service_name: str, version: int, mode: str) -> str:
    # ...
    resp = requests.post(
        _CONTROLLER_URL.format(CONTROLLER_PORT=controller_port) +
        '/controller/update_service',
        json={
            'version': version,
            'mode': mode,
        })
    if resp.status_code == 404:
        raise ValueError('The service is up-ed in an old version and does not '
                         'support update. Please `sky serve down` '
                         'it first and relaunch the service. ')
    elif resp.status_code != 200: # FIXME: Seems always getting into this branch
        raise ValueError(f'Failed to update service: {resp.text}')

    service_msg = resp.json()['message']
    return common_utils.encode_payload(service_msg)
```

3. In `sky/serve/core.py`:
```python
code = serve_utils.ServeCodeGen.update_service(service_name,
                                               current_version,
                                               mode=mode.value)
returncode, _, stderr = backend.run_on_head(handle, # FIXME: Where stdout is dropped!
                                            code,
                                            require_outputs=True,
                                            stream_logs=False,
                                            separate_stderr=True)
try:
    subprocess_utils.handle_returncode(returncode,
                                       code,
                                       'Failed to update services',
                                       stderr,
                                       stream_logs=True)
except exceptions.CommandError as e:
    raise RuntimeError(e.error_msg) from e
```

Steps to reproduce:
1. Initiate a service update that would cause an error in the controller.
2. Observe that the error is logged in the controller but not propagated back to the caller.

Expected behavior:
Errors occurring during the service update process should be properly propagated back to the caller, allowing for appropriate error handling and user notification.

Proposed solution:
- [ ] Modify `/controller/update_service` to use appropriate HTTP status codes (200 for success, 4xx for client errors, 500 for server errors).
- [ ] Update `update_service_encoded` to handle different status codes and raise exceptions based on the response body.
- [ ] Modify `update` in `sky/serve/core.py` to handle and display any errors returned from the update process.
- [ ] Apply this error handling pattern consistently across all similar functionalities in the system, and ensures that `stdout` always stores the payload while `stderr` stores information about exceptions raised by the callee, and all RESTful endpoints follow the status codes convention.

These changes will ensure consistent error handling and improve the reliability of the service update process.

**Comment by cblmemo** [comment]
Thanks for identifying this problem @andylizf ! The 404 code is for service launched before we add the update feature, whose controller does not have the '/controller/update_service' endpoint. Despite that, we should indeed return an non-200 code if any error happens. Could you help submit a PR to fix this?
