### ISSUE TITLE
Feature Request: Add a `force` option to `sky down` to handle services controller stuck in `SHUTTING_DOWN` state

### ISSUE THREAD

**Issue by andylizf** [skypilot-org/skypilot#4059]
There is a scenario where service replicas are stuck in the `SHUTTING_DOWN` state indefinitely. This prevents the SkyPilot controller from being terminated, as it requires all services to be fully terminated before the controller can be shut down.

This issue was observed in #4058 , where service replicas in the `SHUTTING_DOWN` state blocked the shutdown of the controller:
```shell
andyl@DESKTOP-7FP6SMO ~/skypilot (master) [1]> sky status -r(skypilot) 
Clusters
NAME                           LAUNCHED     RESOURCES                                                                  STATUS  AUTOSTOP    COMMAND                       
sky-serve-controller-6eabc0cb  24 mins ago  1x Kubernetes(4CPU--4GB, cpus=4+, disk_size=200, ports=['30001-30020']...  UP      10m (down)  /home/andyl/skypilot/sky/...  

Managed jobs
No in-progress managed jobs. (See: sky jobs -h)

Services
NAME      VERSION  UPTIME  STATUS         REPLICAS  ENDPOINT                                                                          
new-http  -        -       SHUTTING_DOWN  0/2       http://localhost:30046/skypilot/default/sky-serve-controller-6eabc0cb-6eab/30001  

Service Replicas
SERVICE_NAME  ID  VERSION  ENDPOINT  LAUNCHED     RESOURCES              STATUS         REGION      
new-http      1   1        -         21 mins ago  1x Kubernetes(vCPU=2)  SHUTTING_DOWN  in-cluster  
new-http      2   1        -         21 mins ago  1x Kubernetes(vCPU=2)  SHUTTING_DOWN  in-cluster  

* To see detailed service status: sky serve status -a
```

This causes the controller shutdown process to hang, as it continues waiting for the service to fully shut down.

I suggest introduce a `--force` option for `sky serve down`, allowing users to forcefully terminate the controller and services, even if some replicas are still in the process of shutting down. This may result in resource leaks, but it would provide a way to avoid being stuck in situations where the shutdown process hangs indefinitely.

**Comment by cblmemo** [comment]
Could you elaborate on why is the replica stucked in SHUTTING_DOWN state? Is the `sky.down` process still running? I think we should investigate the root reason why the replica status is stucked.

For this PR, does `sky serve down --replica-id 1 --purge` in #4032 satisfies your need?

**Comment by andylizf** [comment]
> Could you elaborate on why is the replica stucked in SHUTTING_DOWN state? Is the `sky.down` process still running? I think we should investigate the root reason why the replica status is stucked.
> 
> 
> 
> For this PR, does `sky serve down --replica-id 1 --purge` in #4032 satisfies your need?

IDK. I will further investigate in this rare issue later. But I do think we should provide users an option to circumvent the restriction that the controller is not scheduled to shut down if there is service running.

**Comment by cblmemo** [comment]
> > Could you elaborate on why is the replica stucked in SHUTTING_DOWN state? Is the `sky.down` process still running? I think we should investigate the root reason why the replica status is stucked.
> > For this PR, does `sky serve down --replica-id 1 --purge` in #4032 satisfies your need?
> 
> IDK. I will further investigate in this rare issue later. But I do think we should provide users an option to circumvent the restriction that the controller is not scheduled to shut down if there is service running.

I think we need to think twice before adding an API as we want to keep our API clean. Adding too many options would result in a steep learning curve. Could you elaborate on potential use case? I think in the case provided by the PR, the user could achieve it by manually `--purge` every replica, after #4032 merged.

**Comment by andylizf** [comment]
> > > Could  you  elaborate  on  why  is  the  replica  stucked  in  SHUTTING_DOWN  state?  Is  the  `sky. down`  process  still  running?  I  think  we  should  investigate  the  root  reason  why  the  replica  status  is  stucked. 
> > > For  this  PR,  does  `sky  serve  down  --replica-id  1  --purge`  in  #4032  satisfies  your  need?
> > 
> > 
> > IDK.  I  will  further  investigate  in  this  rare  issue  later.  But  I  do  think  we  should  provide  users  an  option  to  circumvent  the  restriction  that  the  controller  is  not  scheduled  to  shut  down  if  there  is  service  running.
> 
> I think we need to think twice before adding an API as we want to keep our API clean. Adding too many options would result in a steep learning curve. Could you elaborate on potential use case? I think in the case provided by this PR, the user could achieve it by manually `--purge` every replica, after #4032 merged.

Thanks to @cblmemo's insight, instead of adding a `force` terminating option, we decided to implement a timeout mechanism for terminating replicas so that users can tear down those exceed the timeout and end up in `FAILED_SHUTDOWN` status via previously mentioned `terminate_replica` introduced by #4032. Then users can further down the controller with ease. So there is no need for `force` option anymore.
