### ISSUE TITLE
[UX][Bug] Abnormal dim in the new UX

### ISSUE THREAD

**Issue by cblmemo** [skypilot-org/skypilot#4093]
When trying #3865, I observe this abnormal dim:

<img width="1027" alt="image" src="https://github.com/user-attachments/assets/e785269b-3d03-4df6-b759-dce7c7094e3e">

Maybe the `Instance is up` line does not end the dim.

**Comment by Michaelvll** [comment]
Have you pulled the latest master? See https://github.com/skypilot-org/skypilot/pull/4084

**Comment by cblmemo** [comment]
> Have you pulled the latest master? See #4084

Thanks! Just checked that merging the latest master resolved this problem. closing now
