### ISSUE TITLE
[Performance] Move validation calls out of Resource.__init__

### ISSUE THREAD

**Issue by yika-luo** [skypilot-org/skypilot#4160]
We are initiating the resource object multiple times which triggers non-trivial validation.
https://github.com/skypilot-org/skypilot/blob/master/sky/resources.py#L228-L234

_Version & Commit info:_
* `sky -v`: PLEASE_FILL_IN
* `sky -c`: PLEASE_FILL_IN

**Comment by invisiblepancake** [comment]
#![Image](https://github.com/user-attachments/assets/9b3dea8f-c101-495d-8d86-471282759bd8)
