### ISSUE TITLE
[UX] Better logging when user program OOM'ed

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#4199]
Currently, if a user program OOM'ed, our logs for the job will not include any information of the failure reason and no returncode will be shown.

We should improve the UX for this with the following steps:
1. Include necessary logs in the `sky logs`, e.g, OOM and returncode.
2. Improve the `sky queue` with additional failure reasons instead of just a `FAILED` state of the job.

_Version & Commit info:_
* `sky -v`: PLEASE_FILL_IN
* `sky -c`: PLEASE_FILL_IN

**Comment by cg505** [comment]
There should be a log that we can see in the controller logs, but it is redirected to /dev/null here:
https://github.com/skypilot-org/skypilot/blob/e8d0130b84ec88a0cd407cd214174d29335cf598/sky/backends/cloud_vm_ray_backend.py#L3281-L3283
