### ISSUE TITLE
[UI] Ads on the SkyPilot documentation page

### ISSUE THREAD

**Issue by MaoZiming** [skypilot-org/skypilot#4210]
There seems to be unrelated ads on the documentation page. 
<img width="245" alt="image" src="https://github.com/user-attachments/assets/d2597017-74d4-43bd-b7b5-39767879ab30">

**Comment by romilbhardwaj** [comment]
Unfortunately it's from readthedocs, our docs host: https://docs.readthedocs.io/en/stable/advertising/index.html

**Comment by Michaelvll** [comment]
Fixed.
