### ISSUE TITLE
cannot run `sky jobs logs -n <job_name>` on SUCCEEDED job

### ISSUE THREAD

**Issue by cg505** [skypilot-org/skypilot#4235]
```
$ sky jobs logs -n example-job-name
No running managed job found with name 'example-job-name'.
```
Verified that the job can be seen in `sky jobs queue`.
Providing the job id shows `Job <id> is already in terminal state SUCCEEDED. Logs will not be shown.`

_Version & Commit info:_
* `sky -v`: PLEASE_FILL_IN
* `sky -c`: PLEASE_FILL_IN

**Comment by Michaelvll** [comment]
This has been fixed by #4380
