### ISSUE TITLE
runpod 4090 spot not available

### ISSUE THREAD

**Issue by alita-moore** [skypilot-org/skypilot#4265]
Runpod offers 4090 spot on their website, but when I try to reserve it using skypilot it gives me an error:
```
sky launch -c mycluster hello-sky.yaml --use-spot
Task from YAML spec: hello-sky.yaml
No resource satisfying RunPod([Spot], {'RTX4090': 1}) on RunPod.
sky.exceptions.ResourcesUnavailableError: Catalog does not contain any instances satisfying the request: 1x RunPod([Spot], {'RTX4090': 1}).
To fix: relax or change the resource requirements.

Hint: sky show-gpus to list available accelerators.
      sky check to check the enabled clouds.
```

_Version & Commit info:_
* `sky -v`: 0.7.0
* `sky -c`: 3f625886bf1b13ee463a9f8e0f6741f620f7f66f

**Comment by Michaelvll** [comment]
Spot instances are not supported by RunPod yet, as they don't have spot instance support in their APIs yet. Related to #3927

**Comment by alita-moore** [comment]
oh cool, will this be added soon?

**Comment by kldzj** [comment]
@Michaelvll they do, see https://docs.runpod.io/sdks/graphql/manage-pods#create-spot-pod and https://graphql-spec.runpod.io/#mutation-podRentInterruptable

**Comment by Michaelvll** [comment]
> @Michaelvll they have support for creating spot instances, see https://docs.runpod.io/sdks/graphql/manage-pods#create-spot-pod and https://graphql-spec.runpod.io/#mutation-podRentInterruptable

@kldzj, thanks for the pointer! They have the spot instance supported in the low-level GraphQL, but not supported with python API we are using yet: https://github.com/runpod/runpod-python/issues/327

See: https://github.com/skypilot-org/skypilot/blob/294401455fca036829a342f26e1718e243bad300/sky/provision/runpod/utils.py#L145-L163

One option is to change the API we use to GraphQL with HTTP request directly. Would you like to have a try to add it? Any contribution would be super helpful. : )

**Comment by Michaelvll** [comment]
This has been added in https://github.com/skypilot-org/skypilot/pull/4447. : )
