### ISSUE TITLE
Flaky test: `test_optimizer_dryruns.py` occasionally fails

### ISSUE THREAD

**Issue by andylizf** [skypilot-org/skypilot#4308]
The test `test_infer_cloud_from_region_or_zone` in `test_optimizer_dryruns.py` occasionally fails in GitHub Actions. For example: https://github.com/skypilot-org/skypilot/actions/runs/11737074167/job/32697299221

The error message suggests a cloud inference issue:
```
ValueError: Cannot infer cloud from (region 'us-east-2', zone None). Multiple enabled clouds have region/zone of the same names: [AWS, Lambda]. To fix: explicitly specify `cloud`.
```

However, this appears to be a resource availability issue causing the test to be flaky, rather than an actual cloud inference problem. The test sometimes passes and sometimes fails, indicating a potential race condition or resource constraint in the test environment.

We should either:
1. Add retry logic for this test
2. Mock the resource availability check
3. Mark the test as flaky using [`pytest-rerunfailures`](https://github.com/pytest-dev/pytest-rerunfailures?tab=readme-ov-file#re-run-individual-failures)

**Comment by Michaelvll** [comment]
fixed in #4302
