### ISSUE TITLE
[Catalog] Lambda catalog fetcher fails due to GH200

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#4375]
```
sky/clouds/service_catalog/data_fetchers/fetch_lambda_cloud.py", line 103, in create_catalog
    'SizeInMiB': GPU_TO_MEMORY[gpu]
KeyError: 'GH200'
```
The fetcher for lambda catalog is experiencing an issue above. cc'ing @cbrownstein-lambda, do you have a chance to take a look?

_Version & Commit info:_
* `sky -v`: PLEASE_FILL_IN
* `sky -c`: PLEASE_FILL_IN

**Comment by cbrownstein-lambda** [comment]
@Michaelvll I'll look into this.
