### ISSUE TITLE
Does sky still supports local cluster mode?

### ISSUE THREAD

**Issue by wander3r** [skypilot-org/skypilot#4385]
Hello, I'm trying to set up a local cluster following https://sky-proj-sky.readthedocs-hosted.com/en/latest/reference/local/setup.html
However it errors out with `Error: No such command 'admin'` when I run `sky admin deploy sky-cluster.yaml`.
Does Sky still support local cluster mode? Or did I do something wrong? thank you!

_Version & Commit info:_
* `sky -v`: 0.7.0
* `sky -c`: 3f625886bf1b13ee463a9f8e0f6741f620f7f66f

**Comment by concretevitamin** [comment]
Local clusters are now supported via: https://skypilot.readthedocs.io/en/latest/reservations/existing-machines.html

**Comment by wander3r** [comment]
Thank you!
