### ISSUE TITLE
[k8s] Nimbus backward compatibility issues

### ISSUE THREAD

**Issue by romilbhardwaj** [skypilot-org/skypilot#4397]
Running `sky launch -c myclus` on master where `myclus` was launched before #4393 would stall indefinitely on

```
⠋ Preparing SkyPilot runtime (2/3 - dependencies)  View logs at: ~/sky_logs/sky-2024-11-22-09-10-40-883437/provision.log
```

Provision.log is stuck at:
```
I 11-22 09:10:51 common.py:292] --------------------Start: setup_runtime_on_cluster --------------------
D 11-22 09:10:51 metadata_utils.py:66] Need to run stage setup_runtime_on_cluster on instance test-2ea4-head-0: True
=== Logs for asynchronous ray and skypilot installation ===
Tail PID: 9229
tail: cannot open '/tmp/runtime-setup.log' for reading: No such file or directory
tail: no files remaining
```

Looks like we may need to add some backward compatibility.

**Comment by Michaelvll** [comment]
Proposal: we can skip the wait if `/tmp/runtime-setup.log` does not exist and do the previous setup steps.

cc'ing @cg505, we should check why our backward compatibility tests failed to catch this and improve the test case there.

**Comment by cg505** [comment]
oh - this only impacts k8s, right? Realizing that I only ran backwards compatibility tests on the default cloud which is AWS.

**Comment by cg505** [comment]
Confirmed backwards compatibility tests hang on kubernetes.

**Comment by cg505** [comment]
> Proposal: we can skip the wait if `/tmp/runtime-setup.log` does not exist and do the previous setup steps.

Is there race potential here in the non-backwards-compatible case, if we haven't created that file yet? Do we have a more reliable indicator that the cluster is "old"? E.g. pod metadata or skylet version?

**Comment by romilbhardwaj** [comment]
> Is there race potential here in the non-backwards-compatible case, if we haven't created that file yet? Do we have a more reliable indicator that the cluster is "old"? E.g. pod metadata or skylet version?

Yeah, I'm "fixing" it by creating the file at the very start to make sure the file exists. If it does not, then we can skip it (backward compatibility case)
