### ISSUE TITLE
[Storage] Support disable exclude .gitignore

### ISSUE THREAD

**Issue by cblmemo** [skypilot-org/skypilot#4416]
The file in .gitignore can be useful and one could want to sync them to cluster sometimes. Could we provide an API to suppress the ignore and sync every file to the cluster?

Current workaround: I modified this constant to a random string so it cannot read the excluded file list.

https://github.com/skypilot-org/skypilot/blob/13ce397264484a65f34d89dee609484bcf537326/sky/skylet/constants.py#L11

**Comment by Michaelvll** [comment]
If `.skyignore` exists, `.gitignore` will be ignored. Closing now
