### ISSUE TITLE
[Core] `setup` will not run if you don't have a `run` section and `--detach-setup` is specified

### ISSUE THREAD

**Issue by yika-luo** [skypilot-org/skypilot#4419]
_Version & Commit info:_
* `sky -v`: PLEASE_FILL_IN
* `sky -c`: PLEASE_FILL_IN

**Comment by Michaelvll** [comment]
To reproduce:
```
# test.yaml
setup: hostname
```

```
sky launch -c test-detach --detach-setup test.yaml
```

The setup is not executed, due to: https://github.com/skypilot-org/skypilot/blob/23f9821bd165c8d154a44c3505a18b1e28cc0f48/sky/backends/cloud_vm_ray_backend.py#L3463-L3465
