### ISSUE TITLE
[UX] Additional message from OCI even though not enabled

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#4450]
I am getting the following message while `sky launch -c test` with `pip install -e .[all]` and no OCI credentials

```
INFO:oci.circuit_breaker:Default Auth client Circuit breaker strategy enabled
```

We should get rid of this.

_Version & Commit info:_
* `sky -v`: PLEASE_FILL_IN
* `sky -c`: PLEASE_FILL_IN

**Comment by Michaelvll** [comment]
cc'ing @HysunHe @cblmemo

**Comment by cblmemo** [comment]
Yeah I can reproduce that. @HysunHe could you help take a look on what is happening here?

**Comment by cg505** [comment]
appears to be a regression in oci library 2.138.0: https://github.com/oracle/oci-python-sdk/commit/006daa099e86fdb0225f647585ae83a3c9ff9e8b#diff-eb4016c2aa5e8df81e097f881edc6df579eef91e15c9ad88ed6c98881e1ff954R30
