### ISSUE TITLE
[Core] Launching on a just launched existing cluster with `--fast` does not skip the provision

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#4460]
To reproduce: 
1. `sky launch -c test-fast --cloud aws --cpus 2 echo hi`
2. `sky launch -c test-fast --fast echo hi`: does not skip provisioning
3. `sky launch -c test-fast --fast echo hi`: skips the provisioning

_Version & Commit info:_
* `sky -v`: PLEASE_FILL_IN
* `sky -c`: PLEASE_FILL_IN

**Comment by cg505** [comment]
`provider.availability_zone` in the cluster yaml changes from initial launch (lists all zones) to second and all future launches (only lists the zone that the cluster is actually in)

I will add a mechanism to ignore some fields from the cluster yaml for the config hash calculation. Was trying to avoid that but I think its the best way to go.

**Comment by concretevitamin** [comment]
Maybe some of these are relevant? https://github.com/skypilot-org/skypilot/blob/master/sky/backends/backend_utils.py#L129-L175
