### ISSUE TITLE
Base conda environment causes dependency issues

### ISSUE THREAD

**Issue by gmittal** [skypilot-org/skypilot#515]
There was a lot of friction around installing Sky in the base conda environment due to package conflicts and creating a new conda environment without python=3.8 resulted in the env using system pip (not good!).

Actions (Zhanghao/Siyuan): 
- Version conflict issue: unclear whether pinning requests/urllib3 fixes it
  - Could it be a python2 issue?
- Suggest in docs that you can “conda create -n sky python=3.8”
- Why not provide our own image? This addresses a lot issues (slow start, incorrect configuration, incorrect python shell, conflict packages, missing dependencies)

**Comment by concretevitamin** [comment]
We've been advocating for installing sky in a new conda env, and have not received complaints for a long period of time.

Closing for now, please reopen if this shows up again.
