### ISSUE TITLE
Surface error messages or crash faster during setup

### ISSUE THREAD

**Issue by gmittal** [skypilot-org/skypilot#518]
From Kevin's onboarding: When git clone failed - “I wasn’t sure where the error happened”. 

Can we RED all stdout/stderr when something is wrong? We can also try crashing faster by setting -e for the setup and run scripts (note: this will require modifying some of our own examples which use `conda activate xyz` failures to determine whether to create a new environment).

**Comment by Michaelvll** [comment]
A proposal from @concretevitamin  for surfacing the error message:

```
sky.exceptions.CommandError: Command /bin/bash -i /tmp/sky_setup_c52qujc_ 2>&1 failed with return code 127.
Failed to setup with return code 127. Check log: xxxx to debug.

******* START Last lines of setup output ******* (red this line)
<tail -n10 setup.log>
******* END Last lines of setup output ******* (red this line)
```
