### ISSUE TITLE
Adding new file_mounts cannot be done without setup again

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#544]
When the user adds a new file_mounts, they may only want to upload a new file to the cluster, but they have to run the setup again with `sky launch`. Not sure if we can figure out a way to get rid of this, otherwise we can tell them to just use `rsync`.

**Comment by concretevitamin** [comment]
This has been recently supported: edit the file mounts, then do `sky launch --no-setup`.
