### ISSUE TITLE
Add support for TPU VMs

### ISSUE THREAD

**Issue by gmittal** [skypilot-org/skypilot#578]
Currently Sky only supports TPU nodes, but an investigation by @infwinston and myself with our JAX experiments showed that Google is pushing all support to TPU VMs (see: https://cloud.google.com/blog/products/compute/introducing-cloud-tpu-vms) for JAX/newer frameworks (even Colab is backed by TPU VMs now). It is important that we support these types of machines as JAX is not compatible with the older TPU nodes.

iirc there was a discussion about a team at Berkeley needing TPU nodes, so we should find a way to support both.

**Comment by infwinston** [comment]
Closing this issue as TPU VM is now supported.
