### ISSUE TITLE
[Feature request] Can Sky support AWS regions outside US?

### ISSUE THREAD

**Issue by infwinston** [skypilot-org/skypilot#589]
Feedback from Daniel: "only three AWS regions are supported."
We may consider support more regions to increase Sky's availability. For example, [P3 instance](https://aws.amazon.com/ec2/instance-types/p3/) is available in 14 regions including some in Asia/Europe.

**Comment by Michaelvll** [comment]
This issue no longer exists as we support global region for AWS already.
