### ISSUE TITLE
[Bug] Resource name conflict in shared Azure subscription

### ISSUE THREAD

**Issue by infwinston** [skypilot-org/skypilot#642]
@gmittal first ran
```
sky cpunode -c flax-test --cloud azure
```
After the VM is up, I ran the same command with the same cluster name again.
Then @gmittal can no longer log in to the CPU node he created.
I checked the web portal now there's only one `flax-test` VM launched by my Sky.
Looks like we need to modify the resource group name properly to avoid such conflicts.

**Comment by Michaelvll** [comment]
This issue is the same problem in #1853. Let's keep the latest one. Closing this for now. : )
