### ISSUE TITLE
Mark a storage mount as read-only, even if user has write permissions to the backing store

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#705]
User would like to put additional constraints (e.g. read-only) through the YAML.

Probably influenced by https://docs.docker.com/storage/volumes/#use-a-read-only-volume (which can mark a mount as readonly).  Also, see https://github.com/sky-proj/sky/blob/master/examples/detectron2_docker.yaml#L32 `--volume="/inputs:/inputs:ro"`.

**Comment by turian** [comment]
I agree that it would be great to have a MOUNT that the yaml says is read-only.

**Comment by concretevitamin** [comment]
@turian thanks for the feedback! To learn more, what's the use case you have in mind? Is it for training datasets that you don't want to accidentally overwrite? 

This will be very useful for us to learn about intended usage.

**Comment by turian** [comment]
"Is it for training datasets that you don't want to accidentally overwrite?"

Exactly.

**Comment by romilbhardwaj** [comment]
Thanks for the report @turian! Can you share a little more about your use-case for a read only MOUNT?

**Comment by turian** [comment]
I am pinging this thread so that stale gets removed.

**Comment by turian** [comment]
Was this ever fixed?

**Comment by romilbhardwaj** [comment]
Reopening since this is not yet fixed. Meanwhile, a workaround can be to enforce read-only on your mounted dir with `chattr +i` in the `setup` section of your YAML.

**Comment by carlthome** [comment]
Still relevant IMO.

**Comment by concretevitamin** [comment]
@carlthome would you like to share the underlying use cases? Is it to guardrail accidental writes?

**Comment by carlthome** [comment]
> [@carlthome](https://github.com/carlthome) would you like to share the underlying use cases? Is it to guardrail accidental writes?

Yes, precisely.
