### ISSUE TITLE
Storage: Goofys OOM-killed when mounting/using a big bucket

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#706]
User report:

I was trying out the s3 file system mount. With some config like:
```
file_mounts:
  /data/xxx:
    source: s3://some-giant-bucket
    mode: MOUNT
```
This worked ok initially and I was able to start a training job and run initialization of the dataloader. However half way through I’m starting to get errors like
```
OSError: [Errno 107] Transport endpoint is not connected: '/data/xxx/....json'
```
And if I check the mounted folder it’s gone (also gone in df -h). When I first started the instance it was OK though.

from syslog, looks like goofys ran out of memory lol
```
Apr  4 12:03:28 ip-172-16-29-213 kernel: [ 2497.250427] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/session-11.scope,task=goofys,pid=26769,uid=1000
Apr  4 12:03:28 ip-172-16-29-213 kernel: [ 2497.250468] Out of memory: Killed process 26769 (goofys) total-vm:9484132kB, anon-rss:9350624kB, file-rss:0kB, shmem-rss:0kB, UI
```
using a g4dn.xlarge currently.

Usage pattern
- some stats of a particular subfolder of this bucket that we’re loading data from. 
  - 1.9M total objects, total size 841GB
- Lots of small files, and at the beginning of training we have some directory listing commands that seems to make the goofys climb up in memory usage.
- there might be some concurrent operations after the directory listing steps too for data loading.
------

TODO: reproduce, investigate, mitigate?

**Comment by romilbhardwaj** [comment]
Marking as not stale. Though we haven't heard many OOM complaints from users, we should close this issue only after verifying this problem no longer exists.
