### ISSUE TITLE
Should we preserve the case-insensitive behavior for accelerator names?

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#708]
This problem is raised in https://github.com/sky-proj/sky/pull/698#pullrequestreview-931013942. The case-insensitive behavior can introduce additional complexity to our code. We can discuss about whether we should preserve that feature. (More discussions can be found in #698).

**Comment by WoosukKwon** [comment]
I think we can close this issue as it is resolved by #1075.
