### ISSUE TITLE
Support asynchronous setup and file_mounts

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#730]
Our current setup and file_mounts require the user's laptop to have an `ssh` connection with the cluster, which means the setup or file_mounts will be stopped if the user stop the laptop. When the setup takes a long time, it is easy for the user to fail the setup.

Workaround: place setup in the run section.

**Comment by concretevitamin** [comment]
@dementrock ran into this again:
> This would be a big usability improvement for me to be able to run the setup process without having to guard my laptop to be open & have good internet connection since I have kind of a long-ish setup right now (1~2 hours).
