### ISSUE TITLE
[Ray Autoscaler] `ray status`, Accelerator Placement Group

### ISSUE THREAD

**Issue by michaelzhiluo** [skypilot-org/skypilot#753]
1. Launch P3.8x with 4 V100s.
2. Submit job with 2 V100. 
3. Ray Status on the head node seems to have incorrect logging.

<img width="667" alt="Screen Shot 2022-04-21 at 6 40 59 PM" src="https://user-images.githubusercontent.com/20640975/164579887-8d4e4d19-a159-43a4-80d8-10e828088a28.png">

This could be a Ray bug.

**Comment by concretevitamin** [comment]
Can this be closed @michaelzhiluo?
