### ISSUE TITLE
UX: make `sky status` refresh correctly and by default

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#904]
From Ritwik's onborading: "it’s counter-intuitive to me `sky status` doesn’t refresh by default."

We can make it refresh correctly by talking with the cloud provider. Currently refresh simply pings - if a cluster is unreachable, it's considered STOPPED but it could have been terminated manually.

We can make it refresh by default without the need to remember typing `-r`.

**Comment by Michaelvll** [comment]
Tried to replace the current threading-based solution with multiprocessing / asyncio based solution:
1. Threading: 20.70s
2. Multiprocessing: 29.72s
3. asyncio: 24.70s

Keeping the original threading-based implementation for now.

**Comment by concretevitamin** [comment]
Another user bumped on this request (his second time bumping). This can be a big UX improvement.

> I’ve already mentioned that imo the refresh should probably be opt-out rather than opt-in, as most users probably want to know the current status of a system when they request the status
