### ISSUE TITLE
UX: remove `ray-` in cluster node names

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#905]
Mentioned by Ritwik during onboarding.  Slight confusion.  He preferred that if a cluster is named "mycluster", then it's easier to see in the console the nodes being named "mycluster-{head,...}" without prefix.

We could patch related files in Ray autoscaler.  I filed https://github.com/ray-project/ray/issues/20944 before which includes the files we need to patch -- it's unlikely the Ray team would make the naming format configurable.

**Comment by infwinston** [comment]
I think we should keep this open? It's still a bit confusing that our cluster name starts with `ray-`.

**Comment by concretevitamin** [comment]
+1. This would be solved when we have new provisioner (#1702) merged.

**Comment by Michaelvll** [comment]
This will be fixed for AWS in #1702
