### ISSUE TITLE
TPU: investigate whether on-demand TPUs get killed occasionally 

### ISSUE THREAD

**Issue by concretevitamin** [skypilot-org/skypilot#909]
A TPU user mentioned that for TPUs, even with on-demand TPU, it will be killed at any time within every 2 days, and no logs can be found for the reason. Quote: "Before deadline, I have to get up in the midnight to see if my job being killed, due to the failure of TPU. It would be good thing to look at for the spot feature."

We should first investigate this issue (e.g., low cost `sky tpunode --tpus tpu-v2-8`) and see how we can solve this problem.

**Comment by infwinston** [comment]
To reproduce, I launched five TPU VMs and ran a bert training job for over a week. So far all of them look normal. We probably need more inputs from users on this.

**Comment by infwinston** [comment]
Got report from users saying this issue is recurring:
```
... tpus got taken away within hours.
```
After some investigation, we could use `spot launch` to manage on-demand TPUs. We can discuss whether this is a good option. See https://github.com/skypilot-org/skypilot/pull/1658 for more details.
