### ISSUE TITLE
Documents for using TPU node and TPU VM

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#941]
It would be great to have a tutorial in our document for using TPU nodes and TPU VMs in our document. Currently, we only have a single line in the YAML spec, which may not be enough to show how to use it.

**Comment by WoosukKwon** [comment]
@Michaelvll @infwinston Can we close this issue as we have the doc now?

**Comment by infwinston** [comment]
Yes let's close it.
