### ISSUE TITLE
Multiple candidate resources for failover

### ISSUE THREAD

**Issue by Michaelvll** [skypilot-org/skypilot#971]
Some inference tasks can be run on multiple different resources, e.g. V100:8, V100:4, or V100:1. Based on the availability, the user wants the sky to failover from 8 to 1.

Moreover, it can also be a list of ~~candidate images~~(Supported) or a list of regions.

**Comment by Michaelvll** [comment]
This is recently requested by @dongreenberg again.

**Comment by dongreenberg** [comment]
A failover would work, but I'll clarify that I actually care more about being able to specify multiple resources for price/availability comparison. Meaning, we're writing a series of tutorials that need to run on an Ampere GPU. GCP and Azure users can use an A100, but an AWS user needs an A10G, so right now AWS users need to switch it in every tutorial. I'd like to be able to say "Launch this task on an A100 or A10G, depending on what's available." If that means first trying an A100 and then failing over to A10G that's fine, but just wanted to add that color.

**Comment by romilbhardwaj** [comment]
Just to add a note for implementation - [a way](https://dl.acm.org/doi/pdf/10.1145/3542929.3563498) of expressing soft-resource constraints is through ordinal sets (lists). I.e.,a set of soft-resource constraints $R$ can be expressed as $R$=[$r_1$, $r_2$, ..., $r_n$], where $r_i$ is the $i^{th}$ preferred resource requirement set. 

For instance, to specify @dongreenberg's requirement above, we could have 𝑅 = [{A100: 1}, {A10G: 1}].

**Comment by dongreenberg** [comment]
Love it, and perhaps if you want a non-preferential list (meaning compare all prices) you just specify with a non-ordered set? This would let you do things like compare the spot prices of various combinations of multicpu instances on one or more providers. E.g. maybe I don't care if I get 4 m5.large or 1 m5.4xlarge, I just want whichever is cheaper (and can mix in other instance types or cloud providers).

**Comment by Michaelvll** [comment]
This is still in progress. We may want to keep this open.

**Comment by concretevitamin** [comment]
Will be fixed by #2498

**Comment by concretevitamin** [comment]
Supported by #2498.
